## 0 - Imports

In [32]:
#Basic
import pandas as pd
import numpy as np
import json
import math
from IPython.display import display, Markdown
import requests

#Natural Language
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import re
import string

#Indexing/Scoring
from collections import defaultdict
from rank_bm25 import BM25Okapi

#Embeddings
from sentence_transformers import SentenceTransformer

#Machine Learning
from sklearn.metrics.pairwise import cosine_similarity

#UI
import streamlit as st

#Webscraping
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

## 1 - Data Extraction
- Load JSONs
- See what is available

Use this link https://business.yelp.com/data/resources/open-dataset/
and download the JSON .zip - once downloaded extract it into your repo with the folder within the .gitignore
and then you can run the following code!

In [52]:
#Extracting data - was going to do Phoenix however it is not in the data so we will do all of Arizona

business = pd.read_json('../data/yelp_academic_dataset_business.json', lines=True)
# filtered by Arizona
business = business[business['state'] == 'AZ']
# filter by food/restuarant string
business = business[business['categories'].str.contains('Restaurant | Food',case = False,na=False)
                    &
                    ~business['categories'].str.contains('Drugstore|Convenience|Automotive|Grocery|Store',case = False, na=False)]
#Filter by open
business = business[business['is_open']==1]
#Filter by review count greater than 5
business = business[business['review_count']>5]
business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
56,txyXRytGjwOXvS8s4sc-WA,Smoothie King,1070 E Tucson Marketplace Blvd,Tucson,AZ,85713,32.186794,-110.954765,3.0,29,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Vitamins & Supplements, Ice Cream & Frozen Yog...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-21:0', '..."
319,f82dhKNiUXsDVPMLqKYiIQ,Sher-e-Punjab,853 East Grant Rd,Tucson,AZ,85719,32.250960,-110.959158,4.0,446,1,"{'RestaurantsAttire': ''casual'', 'BusinessAcc...","Restaurants, Salad, Pakistani, Indian, Cocktai...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21..."
553,adATTqggIQX5xxLDISkFTw,Just Churros,,Tucson,AZ,85705,32.271231,-110.992075,5.0,25,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Food Trucks, Restaurants, Caterers, Event Plan...","{'Monday': '0:0-0:0', 'Friday': '15:0-21:0', '..."
954,2vAqYNN86VWXZiy2E96-TQ,Chick-fil-A,"1303 E University Blvd, Ste 149",Tucson,AZ,85719,32.232445,-110.951699,3.0,13,1,"{'RestaurantsReservations': 'False', 'GoodForK...","Event Planning & Services, Caterers, Fast Food...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
995,iNMdSi5bmvGSGeRQiUW4dw,Wendy's,3535 E. Irvington Road,Tucson,AZ,85714,32.163740,-110.916722,2.5,14,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Fast Food, Burgers, Restaurants","{'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149247,zfw03c1jP7sYkIfu1da64w,Panda Express,"9565 E. 22nd Street, SUITE 155",Tucson,AZ,85748,32.206846,-110.788470,2.0,45,1,"{'Ambience': '{'romantic': False, 'intimate': ...","Restaurants, Fast Food, Chinese","{'Monday': '10:30-21:30', 'Tuesday': '10:30-21..."
149436,NHz8uMabvQ2nXk6CddCK4w,McDonald's,3315 N Swan,Tucson,AZ,85712,32.267066,-110.893169,2.5,20,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Fast Food, Burgers, Restaurants, Coffee & Tea,...","{'Monday': '5:0-23:0', 'Tuesday': '5:0-23:0', ..."
150000,aGOXuqO6yhN66tLYI61Thg,Jack in the Box,4450 1st Ave,Tucson,AZ,85719,32.287556,-110.960460,4.5,13,1,"{'DriveThru': 'True', 'Caters': 'False', 'Bike...","Tacos, American (Traditional), Fast Food, Mexi...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150127,K_kRU8j8th6yBeLbI94pJQ,Starbucks,555 E Grant Rd,Tucson,AZ,85705,32.251672,-110.962574,3.5,9,1,"{'RestaurantsTakeOut': 'True', 'BusinessParkin...","Coffee & Tea, Food","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
150328,1jx1sfgjgVg0nM6n3p0xWA,Savaya Coffee Market,11177 N Oracle Rd,Oro Valley,AZ,85737,32.409552,-110.943073,4.5,41,1,"{'BusinessParking': '{'garage': False, 'street...","Specialty Food, Food, Coffee & Tea, Coffee Roa...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-14:0', '..."

In [53]:
#Gather IDs
ids = business['business_id'].to_list()
# Append reviews without high computational cost
reviews = []
with open('../data/yelp_academic_dataset_review.json','r', encoding = 'utf-8') as f:
    for line in f:
        review = json.loads(line)
        if review['business_id'] in ids:
            reviews.append(review)

rev_df = pd.DataFrame(reviews)
rev_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,onlgwy5qGDEzddsrnIvtWg,pYXeL0RCqus2IfhthYCOyA,W7NxQw8UYFR0HLPrI08tvw,4.0,0,0,0,Don't know what it is but If my tummy's feelin...,2012-02-01 14:21:25
1,mRnYZes0nj4sr8DsE_gWMQ,FuTJWFYm4UKqewaosss1KA,fgTOJRkc703E4XRdcr5zRA,3.0,3,0,0,I've come from Cali where boba is very common ...,2016-01-30 01:59:11
2,f7fAYGJpd4gZAoJxuJcciw,LpZfJekvMo5S61UBAmuyHw,cXAKeC-EgVChIxhS7fscmw,5.0,2,0,0,The food at Ghini's is just delicious. Everyth...,2011-05-27 15:44:29
3,b0AI6U9CCWpFKI3iPLYiow,_l0csyXqNIcb3vG-1qR8DQ,UCMSWPqzXjd7QHq7v8PJjQ,4.0,0,0,0,I really like Prep & Pastry - we have been twi...,2017-09-20 18:19:33
4,Zssrl36KBW-QMHsa8G9a_w,zcYZgNeJHpKCSBRwh6WskQ,SbdL-8NSmTWgSwdGZBa7WQ,5.0,0,0,0,Another five-star dining review! Fresco serve...,2015-02-24 04:27:38
...,...,...,...,...,...,...,...,...,...
78857,VkXr54yJMN4Qu4dRznAN8Q,4jEdEPDNAAa3aS7rYhQ60w,MK0OMY_u9unl8xSqjPLtMw,5.0,3,0,0,"ALWAYS love this place! And it's always busy, ...",2020-01-17 20:58:05
78858,JA8GCU3glb6TQRExleWjHg,Iq-9jCp219AEcbtjy-ZyNQ,tBWjMqUc0yP5lRElCfDaKg,5.0,1,0,1,"Great pizza, awesome choices of beers, pet fri...",2016-07-25 01:08:01
78859,PMgEv05rnLIJZlpGc4IHvQ,CDUkT2tD6y3gSfivf3Beyw,EhFJgjgn9Kzo_gu03DVkRg,3.0,1,0,0,Not my favorite dessert place. You don't get m...,2018-02-05 17:27:07
78860,jacDcaIWSPdZq2bDq1GD_g,Y-mwrjOx29pnJX0MCBb2Yg,9VRmMY9vGhGKGz9hiGoEUw,1.0,0,0,0,If I could leave no stars I would. I understan...,2021-11-28 14:23:39
78861,YGUyDcnAxZsUAjlK3QF99g,Qa5MBgb7Xyrr9Pg5bD4taQ,jh8j-DWqgWkbRe_a2XtKFQ,5.0,0,0,1,My secret to finding good food often starts by...,2021-11-28 22:24:05

In [54]:
#Concatenate maximum 20 reviews for each unique business_id
group_rev = (rev_df.groupby('business_id')['text'].apply(lambda x: " ".join(x[:20])).reset_index())
group_rev

                business_id                                               text
0    -1w9JMktu9oWTXwNqtZQoA  I was in Tuscan from Baltimore md . I stumbled...
1    -3-6BB10tIWNKGEF0Es2BA  We will absolutely be coming back here! The ch...
2    -7cNgs6N105MDlLjOudObg  I'm a regular here for sure. Fresh ingredients...
3    -Ah16__ceG91aXtrbkhkxQ  Yummy cakes! Always fresh and they taste great...
4    -B6fyJ8PoAMr_mH5VGaPjA  Best Bacon wrapped burritos in Town, come in e...
..                      ...                                                ...
969  zbhID412Pg3zXd_t3mswpg  Finally! A last minute BB fix before you leave...
970  zfw03c1jP7sYkIfu1da64w  First time eating at this location. The inside...
971  zgClnCzcLl1gzUeKFaJAhg  The food was good the service was slow but lat...
972  zkrEIgrkGylMek2-dUZgZg  I tried Popeyes again 3 months after the 1st r...
973  zwrgCMuZyFX46mL3piDyjg  Amazing food.... This time I had the nicoise, ...

[974 rows x 2 columns]

In [55]:
# Merge business data to get documents
docs = business.merge(group_rev, on='business_id')
# arranged corpus
docs['document'] = (
    'Name: ' + docs['name'] + '\n' +
    'Categories: ' + docs['categories'] + '\n' +
    'Ratings: ' + docs['stars'].astype(str) + '\n' +
    'Reviews: ' + docs['text'].fillna('')

)
docs['document']

0      Name: Smoothie King\nCategories: Vitamins & Su...
1      Name: Sher-e-Punjab\nCategories: Restaurants, ...
2      Name: Just Churros\nCategories: Food Trucks, R...
3      Name: Chick-fil-A\nCategories: Event Planning ...
4      Name: Wendy's\nCategories: Fast Food, Burgers,...
                             ...
969    Name: Panda Express\nCategories: Restaurants, ...
970    Name: McDonald's\nCategories: Fast Food, Burge...
971    Name: Jack in the Box\nCategories: Tacos, Amer...
972    Name: Starbucks\nCategories: Coffee & Tea, Foo...
973    Name: Savaya Coffee Market\nCategories: Specia...
Name: document, Length: 974, dtype: object

In [57]:
# Save corpus of documents (restaurant data) as .pkl - no need to run Step 1: again after this
# From now on use .pkl
docs['document'].to_pickle('../data/arizona_restuarant_corpus.pkl')
docs.to_pickle('../data/az_dict.pkl')

In [25]:
docs

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,text,document
0,txyXRytGjwOXvS8s4sc-WA,Smoothie King,1070 E Tucson Marketplace Blvd,Tucson,AZ,85713,32.186794,-110.954765,3.0,29,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Vitamins & Supplements, Ice Cream & Frozen Yog...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-21:0', '...","The smoothies here are fantastic, they never f...",Name: Smoothie King\nCategories: Vitamins & Su...
1,f82dhKNiUXsDVPMLqKYiIQ,Sher-e-Punjab,853 East Grant Rd,Tucson,AZ,85719,32.250960,-110.959158,4.0,446,1,"{'RestaurantsAttire': ''casual'', 'BusinessAcc...","Restaurants, Salad, Pakistani, Indian, Cocktai...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",One of my most favorite Indian restaurants. No...,"Name: Sher-e-Punjab\nCategories: Restaurants, ..."
2,adATTqggIQX5xxLDISkFTw,Just Churros,,Tucson,AZ,85705,32.271231,-110.992075,5.0,25,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Food Trucks, Restaurants, Caterers, Event Plan...","{'Monday': '0:0-0:0', 'Friday': '15:0-21:0', '...",Hired their food truck for a party I hosted. I...,"Name: Just Churros\nCategories: Food Trucks, R..."
3,2vAqYNN86VWXZiy2E96-TQ,Chick-fil-A,"1303 E University Blvd, Ste 149",Tucson,AZ,85719,32.232445,-110.951699,3.0,13,1,"{'RestaurantsReservations': 'False', 'GoodForK...","Event Planning & Services, Caterers, Fast Food...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ...",This is the worst Chik-fil-A I have ever been ...,Name: Chick-fil-A\nCategories: Event Planning ...
4,iNMdSi5bmvGSGeRQiUW4dw,Wendy's,3535 E. Irvington Road,Tucson,AZ,85714,32.163740,-110.916722,2.5,14,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Fast Food, Burgers, Restaurants","{'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'...",Drove by for a late dinner Sunday night and ha...,"Name: Wendy's\nCategories: Fast Food, Burgers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,zfw03c1jP7sYkIfu1da64w,Panda Express,"9565 E. 22nd Street, SUITE 155",Tucson,AZ,85748,32.206846,-110.788470,2.0,45,1,"{'Ambience': '{'romantic': False, 'intimate': ...","Restaurants, Fast Food, Chinese","{'Monday': '10:30-21:30', 'Tuesday': '10:30-21...",First time eating at this location. The inside...,"Name: Panda Express\nCategories: Restaurants, ..."
970,NHz8uMabvQ2nXk6CddCK4w,McDonald's,3315 N Swan,Tucson,AZ,85712,32.267066,-110.893169,2.5,20,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Fast Food, Burgers, Restaurants, Coffee & Tea,...","{'Monday': '5:0-23:0', 'Tuesday': '5:0-23:0', ...","To be called ""fast foods"", you would need to b...","Name: McDonald's\nCategories: Fast Food, Burge..."
971,aGOXuqO6yhN66tLYI61Thg,Jack in the Box,4450 1st Ave,Tucson,AZ,85719,32.287556,-110.960460,4.5,13,1,"{'DriveThru': 'True', 'Caters': 'False', 'Bike...","Tacos, American (Traditional), Fast Food, Mexi...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W...",Everything here was sticky and dirty. \n\nThe ...,"Name: Jack in the Box\nCategories: Tacos, Amer..."
972,K_kRU8j8th6yBeLbI94pJQ,Starbucks,555 E Grant Rd,Tucson,AZ,85705,32.251672,-110.962574,3.5,9,1,"{'RestaurantsTakeOut': 'True', 'BusinessParkin...","Coffee & Tea, Food","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ...","I love Starbucks because of their consistency,...","Name: Starbucks\nCategories: Coffee & Tea, Foo..."
973,1jx1sfgjgVg0nM6n3p0xWA,Savaya Coffee Market,11177 N Oracle Rd,Oro Valley,AZ,85737,32.409552,-110.943073,4.5,41,1,"{'BusinessParking': '{'garage': False, 'street...","Specialty Food, Food, Coffee & Tea, Coffee Roa...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-14:0', '...",I love this coffee shop. The staff is friendl...,Name: Savaya Coffee Market\nCategories: Specia...

## 2 - Preprocessing
- lowercase
- tokenization
- stemming (removed for now)
- stopword removal

In [2]:
documents = pd.read_pickle('../data/arizona_restuarant_corpus.pkl')
docs = pd.read_pickle('../data/az_dict.pkl')
documents

0      Name: Smoothie King\nCategories: Vitamins & Su...
1      Name: Sher-e-Punjab\nCategories: Restaurants, ...
2      Name: Just Churros\nCategories: Food Trucks, R...
3      Name: Chick-fil-A\nCategories: Event Planning ...
4      Name: Wendy's\nCategories: Fast Food, Burgers,...
                             ...
969    Name: Panda Express\nCategories: Restaurants, ...
970    Name: McDonald's\nCategories: Fast Food, Burge...
971    Name: Jack in the Box\nCategories: Tacos, Amer...
972    Name: Starbucks\nCategories: Coffee & Tea, Foo...
973    Name: Savaya Coffee Market\nCategories: Specia...
Name: document, Length: 974, dtype: object

In [3]:
#Preprocess - appears to work better for vocab list
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    tokens = text.lower().split() #lower case all
    tokens = [x for x in tokens if x not in stop_words and x not in string.punctuation] #no stop words or punctuations
    # tokens = [stemmer.stem(x) for x in tokens] #stemming
    return tokens

In [4]:
#Preprocess V2 - appears to work better for cleaning up queries to be meaningful
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocessv2(text):
    #lowercase text
    text = text.lower()

    # tokenize words
    tokens = re.findall(r"\b[a-z]+\b",text)

    #tokenization
    # tokens = text.split()

    #removing stop words
    tokens = [x for x in tokens if x not in stop_words]

    # lemmatize 
    tokens = [lemmatizer.lemmatize(x) for x in tokens]
    return tokens

In [5]:
# Apply to documents
tokens0 = [preprocess(doc) for doc in documents]
tokens = [preprocessv2(doc) for doc in documents]

print(f'Original: {tokens0[0][:5]} --> New: {tokens0[0][:5]}')

Original: ['name:', 'smoothie', 'king', 'categories:', 'vitamins'] --> New: ['name:', 'smoothie', 'king', 'categories:', 'vitamins']

## 3 - Indexing | Scoring (Initial Test)
- Create the Inverted Index 
- TF-IDF testing
- BM25 testing
- GOAL: Make the inverted index and just check and see how scoring works

In [6]:
# INVERTED INDEX

invert_index = defaultdict(dict)

for id, token in enumerate(tokens):
    for x in token:
        invert_index[x][id] = invert_index[x].get(id,0)+1

#example 

print(invert_index['taco'])

{8: 3, 9: 26, 12: 1, 24: 3, 32: 26, 35: 4, 36: 18, 38: 1, 40: 1, 41: 1, 43: 19, 73: 2, 76: 2, 79: 1, 83: 26, 90: 19, 96: 19, 99: 1, 105: 4, 106: 4, 110: 2, 111: 19, 112: 6, 115: 1, 116: 1, 119: 3, 120: 4, 126: 18, 127: 5, 131: 3, 141: 6, 146: 4, 151: 6, 154: 8, 158: 1, 172: 7, 179: 25, 180: 4, 181: 27, 187: 4, 189: 14, 190: 2, 191: 2, 201: 1, 218: 1, 219: 2, 224: 2, 228: 2, 229: 2, 231: 1, 234: 1, 243: 3, 248: 1, 251: 1, 263: 4, 264: 23, 266: 1, 270: 13, 272: 2, 278: 13, 284: 22, 285: 4, 287: 5, 300: 6, 305: 19, 312: 26, 320: 1, 323: 4, 326: 9, 330: 1, 345: 1, 353: 15, 361: 22, 364: 7, 365: 2, 375: 5, 383: 10, 390: 21, 392: 13, 393: 27, 402: 1, 403: 2, 407: 8, 409: 2, 421: 4, 426: 1, 430: 3, 432: 1, 435: 2, 436: 1, 445: 1, 447: 20, 451: 7, 455: 2, 460: 10, 464: 1, 472: 32, 474: 16, 475: 5, 492: 21, 495: 1, 501: 1, 509: 12, 521: 43, 522: 1, 526: 1, 530: 2, 534: 31, 535: 1, 549: 16, 552: 1, 554: 1, 556: 2, 561: 8, 567: 15, 570: 6, 571: 3, 579: 2, 591: 2, 592: 1, 595: 2, 597: 7, 628: 10, 630: 1, 633: 2, 634: 16, 641: 1, 647: 15, 651: 1, 655: 1, 660: 2, 663: 1, 668: 13, 686: 1, 688: 8, 691: 21, 699: 5, 703: 26, 704: 30, 705: 3, 709: 11, 712: 11, 715: 30, 716: 1, 719: 1, 722: 1, 728: 6, 729: 38, 730: 5, 746: 1, 747: 9, 751: 10, 752: 1, 754: 2, 760: 3, 767: 1, 770: 6, 772: 40, 775: 3, 790: 1, 799: 4, 801: 2, 803: 1, 804: 6, 811: 12, 814: 2, 820: 7, 823: 1, 824: 1, 830: 29, 831: 18, 834: 17, 835: 7, 839: 6, 840: 5, 842: 43, 847: 2, 852: 41, 859: 17, 864: 4, 870: 5, 874: 1, 880: 6, 883: 26, 887: 31, 897: 6, 902: 1, 905: 2, 906: 1, 907: 5, 909: 5, 910: 4, 911: 2, 915: 4, 918: 11, 932: 1, 933: 1, 940: 2, 950: 1, 956: 1, 957: 19, 959: 4, 961: 1, 967: 20, 971: 5}

In [7]:
# Basic TF-IDF

# N - total # docs
# df - number of docs with term
# idf - log(N/df)


N = len(tokens)

def tfidf(term):
    df = len(invert_index[term])
    return math.log(N/df)


tfidf_score = tfidf('taco')

print(tfidf_score)


#BUILD IDF DICTIONARY
idf = {}
for term in invert_index:
    df = len(invert_index[term])
    idf[term] = math.log(N/df)

#maybe add l2 normalization to make it 0-1 scale

1.5584013245041268

In [8]:
# BM25 Implementation
bm25 = BM25Okapi(tokens)

query = preprocessv2('best tacos')

scores = bm25.get_scores(query)

print('Before Ranking')
print(scores[:5])
ranked_docs = np.argsort(scores)[::-1]
print(f'\nAfter Ranking\n{ranked_docs[:5]}')


def bm25z(query):

    exp_q = preprocessv2(query)

    scores = bm25.get_scores(exp_q)

    ranked = np.argsort(scores)[-10:][::-1]

    return list(set(ranked))

Before Ranking
[2.39108109 2.66423091 2.63177683 1.54282944 1.65668543]

After Ranking
[472 715  36 859 709]

In [9]:
#TF-IDF scoring logic
N = len(tokens)

def tfidf_scoring(query):
    scores = [0] * N

    for x in query:
        if x in invert_index:
            for id,tf in invert_index[x].items():
                # scores[id]+=tf*idf[x] #basic
                scores[id] += (tf / len(tokens[id])) *idf[term] #length normalization - way more similar to BM25

    return scores

In [10]:
#Compare Scores
#TF-IDF
tf_scores = tfidf_scoring(query)

#BM25
bm25_scores = bm25.get_scores(query)

def top_results(scores,x=5):
    return np.argsort(scores)[::-1][:x] #top 5 results

tf_top = top_results(tf_scores)
bm_top = top_results(bm25_scores)

print(f'TF-IDF Top Results: ')
for rank,id in enumerate(tf_top,1):
    print(f'{rank} -> (Document: {id}) -> Score: {tf_scores[id]:.2f}')
    print('  ', tokens[id])

print('\nBM25 Top Results: ')
for rank, id in enumerate(bm_top,1):
    print(f'{rank} -> (Document: {id}) -> Score: {bm25_scores[id]:.2f}')
    print('   ', tokens[id])

TF-IDF Top Results:
1 -> (Document: 709) -> Score: 0.48
   ['name', 'taco', 'rico', 'category', 'food', 'truck', 'food', 'taco', 'restaurant', 'fast', 'food', 'mexican', 'rating', 'review', 'absolutely', 'delicious', 'best', 'mexican', 'truck', 'tucson', 'glad', 'located', 'ina', 'driving', 'south', 'sometimes', 'drag', 'waste', 'time', 'writing', 'review', 'going', 'show', 'day', 'write', 'many', 'review', 'deleted', 'well', 'sure', 'owner', 'business', 'since', 'gave', 'star', 'review', 'assume', 'yelp', 'great', 'taco', 'taco', 'truck', 'specializes', 'taco', 'ordered', 'chicken', 'carne', 'asada', 'steak', 'taco', 'came', 'sliced', 'radish', 'grilled', 'onion', 'cilantro', 'sauce', 'tried', 'pastor', 'asada', 'cabeza', 'taco', 'delicious', 'tortilla', 'excellent', 'meat', 'fresh', 'moist', 'served', 'radish', 'cucumber', 'onion', 'side', 'plus', 'traveled', 'oro', 'valley', 'say', 'worth', 'trip', 'back', 'soon', 'food', 'truck', 'actually', 'really', 'good', 'tried', 'asada', 'cabeza', 'pollo', 'pastor', 'taco', 'excellent', 'pollo', 'super', 'moist', 'cabeza', 'greasy', 'wife', 'carne', 'asada', 'connoisseur', 'liked', 'asada', 'really', 'tell', 'something', 'new', 'cali', 'probably', 'liked', 'forget', 'add', 'cheese', 'salsa', 'homemade', 'bomb', 'super', 'good', 'food', 'maybe', 'best', 'town', 'nice', 'people', 'fresh', 'clean', 'food', 'homemade', 'horchata', 'outstanding', 'hopefully', 'move', 'closer', 'town', 'would', 'time', 'first', 'time', 'taco', 'truck', 'glad', 'stopped', 'way', 'home', 'probably', 'top', 'best', 'taco', 'tucson', 'come', 'carne', 'asada', 'al', 'pastor', 'also', 'red', 'chili', 'hot', 'oil', 'sauce', 'amazing', 'lightweight', 'beware', 'hot', 'dang', 'flavorful', 'definitely', 'gonna', 'picking', 'taco', 'side', 'town', 'skimp', 'meat', 'either', 'side', 'salsa', 'place', 'legit', 'go', 'support', 'great', 'local', 'food', 'truck', 'especially', 'awesome', 'price']
2 -> (Document: 472) -> Score: 0.44
   ['name', 'taqueria', 'rosita', 'category', 'food', 'truck', 'food', 'rating', 'review', 'best', 'carne', 'asada', 'town', 'best', 'salsa', 'town', 'best', 'cabeza', 'town', 'even', 'need', 'teeth', 'chew', 'tender', 'sad', 'discontinued', 'adobada', 'also', 'best', 'town', 'rafa', 'josefina', 'always', 'cheerful', 'gracious', 'host', 'spot', 'epitome', 'elegant', 'street', 'fair', 'eating', 'close', 'year', 'find', 'better', 'taco', 'tucson', 'easily', 'one', 'best', 'taco', 'truck', 'tucson', 'eat', 'least', 'twice', 'week', 'never', 'get', 'sick', 'carne', 'asada', 'taco', 'definitely', 'par', 'aqui', 'con', 'el', 'nene', 'birria', 'cabesa', 'also', 'tasty', 'wednesday', 'taco', 'day', 'prepared', 'wait', 'awhile', 'come', 'day', 'personally', 'think', 'worth', 'spend', 'extra', 'cent', 'avoid', 'rush', 'coming', 'non', 'wednesday', 'still', 'pretty', 'cheap', 'miss', 'gem', 'awesome', 'food', 'truck', 'far', 'best', 'carne', 'asada', 'burrito', 'tucson', 'meat', 'flavorful', 'tender', 'salsa', 'good', 'back', 'favorite', 'taco', 'caramelos', 'burro', 'consistent', 'quality', 'always', 'cooked', 'wait', 'best', 'food', 'tucson', 'love', 'place', 'staff', 'friendly', 'food', 'delicious', 'eat', 'keep', 'mind', 'dirt', 'lot', 'going', 'clean', 'always', 'get', 'mine', 'go', 'since', 'work', 'close', 'accept', 'cash', 'problem', 'know', 'ahead', 'time', 'carne', 'asada', 'trimmed', 'nicely', 'price', 'portion', 'good', 'oh', 'park', 'spot', 'early', 'prep', 'open', 'lunch', 'highly', 'recommend', 'place', 'carne', 'asada', 'taco', 'best', 'food', 'truck', 'delicious', 'guacamole', 'salsa', 'perfect', 'may', 'wait', 'bit', 'hey', 'line', 'usually', 'good', 'sign', 'worth', 'wait', 'one', 'great', 'mexican', 'food', 'truck', 'gem', 'tucson', 'basic', 'menu', 'food', 'good', 'usually', 'get', 'burrito', 'taco', 'tortas', 'carmelos', 'asada', 'birria', 'cabeza', 'pollo', 'adobado', 'highly', 'reccomend', 'truck', 'looking', 'authentic', 'tucson', 'food', 'truck', 'experience', 'gang', 'work', 'really', 'love', 'taco', 'truck', 'taqueria', 'great', 'taco', 'great', 'burrito', 'cabeza', 'carne', 'asada', 'pollo', 'several', 'table', 'available', 'shade', 'tree', 'get', 'go', 'taco', 'easily', 'best', 'town', 'rosita', 'every', 'dollar', 'spend', 'towards', 'authentic', 'full', 'flavorful', 'taco', 'b', 'real', 'tucson', 'gem', 'inhale', 'taco', 'exhale', 'negativity', 'namaste', 'mi', 'amigo', 'taco', 'truck', 'lover', 'really', 'care', 'sketchy', 'place', 'look', 'try', 'heck', 'eaten', 'taco', 'stand', 'people', 'front', 'yard', 'puerto', 'penasco', 'yeah', 'bring', 'taco', 'taqueria', 'rosita', 'nothing', 'fancy', 'tent', 'truck', 'dirt', 'lot', 'kind', 'nestled', 'back', 'tree', 'bit', 'along', 'valencia', 'carne', 'asada', 'taco', 'lord', 'taco', 'bout', 'awesome', 'recent', 'visit', 'meat', 'perfection', 'gristle', 'little', 'fatty', 'piece', 'ton', 'flavor', 'actually', 'charred', 'grill', 'bit', 'give', 'flavor', 'taco', 'place', 'missing', 'watch', 'red', 'salsa', 'spicy', 'delicious', 'spicy', 'favor', 'stop', 'carne', 'asada', 'taco', 'remember', 'bring', 'cash', 'cuz', 'rosita', 'take', 'card', 'jefe', 'wow', 'delicious', 'place', 'probably', 'best', 'mexican', 'food', 'since', 'coming', 'arizona', 'carne', 'asada', 'taco', 'fresh', 'vibrant', 'tasty', 'offer', 'great', 'pico', 'de', 'gillo', 'guac', 'hot', 'sauce', 'meat', 'option', 'available', 'would', 'eat', 'anything', 'taco', 'first', 'time', 'yesterday', 'delicious', 'first', 'time', 'fell', 'taco', 'tucson', 'make', 'want', 'go', 'back', 'thank', 'best', 'taco', 'tucson', 'live', 'vail', 'happy', 'made', 'minute', 'drive', 'little', 'roach', 'coach', 'husband', 'pleased', 'offered', 'choice', 'corn', 'flour', 'tortilla', 'prefer', 'flour', 'found', 'tortilla', 'delicious', 'thin', 'seemingly', 'homemade', 'u', 'tried', 'pollo', 'asada', 'birria', 'good', 'asada', 'particularly', 'delicious', 'pico', 'great', 'enjoyed', 'sauce', 'ordered', 'go', 'order', 'bring', 'home', 'son', 'waited', 'nearly', 'finished', 'meal', 'prepare', 'extremely', 'considerate', 'would', 'convenient', 'accept', 'card', 'yes', 'keep', 'line', 'moving', 'faster', 'taco', 'cash', 'totally', 'worth', 'gentleman', 'inside', 'truck', 'kind', 'make', 'terrific', 'food', 'already', 'dreaming', 'next', 'visit', 'love', 'corn', 'tortilla', 'thin', 'soft', 'flavorful', 'packed', 'favorite', 'meat', 'fresh', 'ingredient', 'service', 'fast', 'friendly', 'fooled', 'location', 'appearance', 'lone', 'truck', 'gravel', 'lot', 'nice', 'shady', 'spacious', 'outdoor', 'eating', 'area', 'park', 'like', 'setting', 'clean', 'table', 'back', 'great', 'choice', 'tucson', 'taco', 'truck', 'experience', 'sweet', 'people', 'working', 'food', 'taste', 'great', 'feeling', 'sitting', 'foldout', 'table', 'couple', 'tree', 'cracking', 'open', 'bottle', 'coca', 'cola', 'hard', 'beat', 'best', 'bang', 'buck', 'taco', 'tucson', 'pure', 'joy', 'wished', 'open', 'longer', 'think', 'close', 'come', 'lunch', 'almost', 'daily', 'never', 'ever', 'disappointed', 'outstanding', 'street', 'taco', 'exactly', 'looking', 'street', 'truck', 'food', 'super', 'friendly', 'helpful', 'suggesting', 'topping', 'added', 'bonus', 'small', 'entertainer', 'made', 'visit', 'hand', 'one', 'best', 'taco', 'tucson', 'simple', 'taco', 'truck', 'outdoor', 'seating', 'food', 'packed', 'amazing', 'flavor', 'plus', 'price', 'right', 'tried', 'meat', 'far', 'taco', 'exception', 'chicharron', 'cooked', 'seasoned', 'perfectly', 'sure', 'try', 'caramelos', 'also', 'got', 'carne', 'asada', 'caramelos', 'divine', 'cheesy', 'cooked', 'perfection', 'outside', 'bit', 'crunchy', 'crisp', 'provided', 'u', 'pico', 'de', 'gallo', 'salsa', 'red', 'one', 'spiciest', 'add', 'great', 'kick', 'highly', 'recommend', 'place', 'thank', 'open', 'covid', 'time', 'definitely', 'back', 'recommending', 'spot', 'fellow', 'foodie', 'seriously', 'best', 'taco', 'ever', 'hearty', 'portion', 'meat', 'perfect', 'seasoning', 'price', 'great', 'plus', 'ordered', 'limonade', 'found', 'made', 'bottled', 'tucson', 'limonade', 'honestly', 'best', 'ever', 'careful', 'lot', 'sugar', 'damn', 'worth', 'new', 'go', 'spot', 'rest', 'time', 'live', 'added', 'bonus', 'nice', 'lady', 'patient', 'answered', 'question', 'also', 'sell', 'birria', 'juice', 'bigger', 'quart', 'take', 'home', 'perfect', 'hole', 'wall', 'decided', 'review', 'since', 'place', 'much', 'review', 'photo', 'delicious', 'tucson', 'finding', 'good', 'taco', 'mission', 'place', 'road', 'hotel', 'convenient', 'tried', 'asada', 'cabeza', 'divine', 'serve', 'onion', 'cilantro', 'cabbage', 'add', 'guacamole', 'salsa', 'salsa', 'bit', 'spicy', 'stay', 'away', 'good', 'opinion', 'guacamole', 'runny', 'side', 'tasty', 'well', 'also', 'give', 'option', 'pico', 'de', 'gallo', 'fresh', 'definitely', 'worth', 'try']
3 -> (Document: 715) -> Score: 0.41
   ['name', 'taco', 'de', 'cabeza', 'category', 'food', 'food', 'truck', 'restaurant', 'mexican', 'rating', 'review', 'complains', 'food', 'excellent', 'complain', 'place', 'look', 'never', 'clean', 'yard', 'look', 'ugly', 'place', 'extraordinary', 'best', 'cabeza', 'taco', 'tucson', 'hand', 'go', 'usually', 'take', 'taco', 'de', 'cabeza', 'beef', 'head', 'taco', 'bichi', 'beef', 'stew', 'w', 'onion', 'cilantro', 'coca', 'cola', 'eating', 'taco', 'de', 'cabeza', 'shame', 'drinking', 'mexican', 'coca', 'cola', 'noon', 'fantastic', 'delicious', 'taco', 'broth', 'always', 'order', 'cheek', 'taco', 'broth', 'husband', 'order', 'cabeza', 'tongue', 'taco', 'filling', 'lunch', 'two', 'u', 'never', 'cost', 'best', 'taco', 'tucson', 'come', 'every', 'weekend', 'family', 'recommend', 'one', 'sesos', 'taco', 'order', 'jugo', 'bichi', 'beef', 'stew', 'amazing', 'taco', 'place', 'casual', 'great', 'street', 'taco', 'cash', 'option', 'vegetarian', 'option', 'carnivore', 'definitely', 'try', 'taco', 'best', 'ever', 'go', 'stand', 'grant', 'school', 'week', 'always', 'get', 'cabeza', 'cachete', 'staff', 'helpful', 'kind', 'speak', 'spanish', 'hard', 'communicate', 'sometimes', 'lol', 'definitely', 'recommend', 'first', 'day', 'tucson', 'accidentally', 'went', 'parking', 'lot', 'realized', 'food', 'truck', 'ton', 'white', 'tent', 'seating', 'knew', 'stop', 'try', 'aa', 'part', 'first', 'food', 'tucson', 'menu', 'immediately', 'visible', 'decided', 'order', 'cabeza', 'since', 'seemed', 'specialty', 'based', 'name', 'waitress', 'spoke', 'limited', 'english', 'bit', 'tough', 'u', 'since', 'neither', 'sister', 'speak', 'spanish', 'difficulty', 'asking', 'meat', 'taco', 'came', 'delicious', 'corn', 'tortilla', 'best', 'meat', 'taco', 'super', 'cheap', 'think', 'horchata', 'bottle', 'cost', 'two', 'taco', 'got', 'lolll', 'note', 'outdoor', 'seating', 'since', 'food', 'truck', 'hot', 'hot', 'az', 'definitely', 'sweating', 'quickly', 'car', 'extremely', 'hot', 'without', 'sun', 'shade', 'definitely', 'need', 'go', 'back', 'even', 'daydream', 'taco', 'get', 'munchies', 'got', 'cheek', 'head', 'roof', 'mouth', 'tongue', 'taco', 'little', 'disappointed', 'ran', 'eye', 'lip', 'brain', 'taco', 'great', 'flavor', 'mild', 'side', 'good', 'early', 'day', 'bite', 'price', 'good', 'cash', 'best', 'taco', 'cabezas', 'tucson', 'son', 'make', 'mission', 'sample', 'every', 'beef', 'pork', 'cabezas', 'discover', 'tucson', 'flavor', 'taco', 'cabezas', 'nothing', 'short', 'miracle', 'flavor', 'seved', 'tortilla', 'depth', 'flavor', 'spice', 'without', 'heavy', 'grease', 'sometimes', 'associated', 'particular', 'epicurean', 'delight', 'try', 'broth', 'take', 'home', 'freezer', 'midnight', 'craving', 'adventurous', 'try', 'mixed', 'meat', 'cabezas', 'blend', 'headmeats', 'prepared', 'expertly', 'experience', 'exquisite', 'beef', 'flavor', 'without', 'bizarre', 'texture', 'usually', 'associated', 'head', 'meat', 'true', 'jewel', 'tucson', 'cuisine', 'offer', 'like', 'oh', 'less', 'adventurous', 'offer', 'standard', 'selection', 'expect', 'see', 'mexican', 'food', 'tuck', 'best', 'home', 'style', 'taco', 'missing', 'home', 'would', 'give', 'five', 'star', 'however', 'get', 'different', 'quality', 'depending', 'go', 'overall', 'still', 'great', 'girlfriend', 'really', 'craving', 'taco', 'de', 'cabeza', 'past', 'day', 'finally', 'found', 'place', 'serf', 'good', 'one', 'town', 'basic', 'plastic', 'table', 'tarp', 'covering', 'food', 'truck', 'let', 'fool', 'place', 'know', 'going', 'still', 'get', 'table', 'service', 'waitress', 'take', 'order', 'super', 'super', 'fast', 'like', 'joke', 'fast', 'looking', 'authentic', 'taco', 'place', 'super', 'fast', 'friendly', 'even', 'though', 'super', 'busy', 'taco', 'de', 'cabeza', 'lengua', 'vichi', 'tasted', 'super', 'good', 'bit', 'small', 'order', 'extra', 'ordered', 'taco', 'vichis', 'soda', 'total', 'place', 'super', 'busy', 'weekend', 'prepare', 'wait', 'say', 'enough', 'good', 'thing', 'taco', 'de', 'cabeza', 'guy', 'best', 'cabeza', 'ever', 'eaten', 'arizona', 'even', 'mexico', 'reasonable', 'price', 'great', 'authentic', 'selection', 'cabeza', 'typical', 'mexican', 'food', 'great', 'space', 'eat', 'shade', 'stand', 'staff', 'nice', 'even', 'pasty', 'white', 'gringo', 'speak', 'spanish', 'love', 'amazing', 'mexican', 'food', 'always', 'accommodating', 'ordering', 'time', 'order', 'cabeza', 'go', 'get', 'large', 'stack', 'good', 'quality', 'corn', 'tortilla', 'fairly', 'spicy', 'red', 'citrusy', 'green', 'salsa', 'big', 'bag', 'lime', 'accentuate', 'flavor', 'delicious', 'meat', 'broth', 'cachete', 'cheek', 'taco', 'full', 'unconditional', 'support', 'cannot', 'go', 'wrong', 'never', 'tried', 'cabeza', 'fear', 'strange', 'texture', 'anything', 'worry', 'favor', 'give', 'try', 'two', 'note', 'make', 'writing', 'location', 'yelp', 'located', 'street', 'alaska', 'northeast', 'corner', 'small', 'sign', 'visible', 'road', 'also', 'used', 'take', 'card', 'year', 'ago', 'since', 'stopped', 'back', 'cash', 'situation', 'found', 'place', 'yelp', 'neighborhood', 'thought', 'would', 'give', 'shot', 'disappointed', 'food', 'wonderful', 'ordered', 'slew', 'beef', 'cheek', 'taco', 'recommendation', 'kind', 'folk', 'table', 'next', 'u', 'waitress', 'speak', 'word', 'english', 'printed', 'menu', 'little', 'tough', 'figure', 'taco', 'arrived', 'quickly', 'piping', 'hot', 'texture', 'meat', 'wonderful', 'guy', 'thought', 'food', 'pretty', 'extraordinary', 'spouse', 'thought', 'flavor', 'little', 'strong', 'one', 'complained', 'could', 'smell', 'meat', 'finger', 'afternoon', 'would', 'consider', 'bonus', 'quite', 'fond', 'idea', 'lunch', 'people', 'including', 'couple', 'coca', 'cola', 'quite', 'bargain', 'would', 'give', 'place', 'star', 'food', 'would', 'great', 'made', 'thing', 'little', 'easier', 'u', 'gringo', 'menu', 'card']
4 -> (Document: 83) -> Score: 0.38
   ['name', 'taqueria', 'el', 'cheke', 'category', 'burger', 'food', 'truck', 'street', 'vendor', 'food', 'restaurant', 'mexican', 'rating', 'review', 'los', 'taco', 'estan', 'muy', 'buenos', 'autentico', 'sabor', 'de', 'sonora', 'la', 'barra', 'de', 'salsa', 'muy', 'fresco', 'buena', 'atencion', 'abren', 'hasta', 'tarde', 'little', 'food', 'truck', 'serf', 'taco', 'tortas', 'hot', 'dog', 'flavorful', 'carne', 'asada', 'little', 'dry', 'side', 'hod', 'dog', 'delicious', 'kuddos', 'topping', 'bar', 'best', 'sonoran', 'hot', 'dog', 'northside', 'town', 'everything', 'made', 'fresh', 'delicious', 'recommend', 'doubt', 'mexican', 'food', 'cart', 'fyi', 'hotdog', 'tuesday', 'riquisimos', 'taco', 'bien', 'super', 'recomendados', 'estuvimos', 'todo', 'el', 'grupo', 'de', 'barbershop', 'gracias', 'must', 'start', 'observation', 'none', 'employee', 'mask', 'pandemic', 'going', 'follow', 'common', 'sense', 'heath', 'practice', 'go', 'one', 'competitor', 'food', 'service', 'otherwise', 'good', 'best', 'mexican', 'food', 'tucson', 'near', 'tucson', 'mall', 'sonoran', 'hotdog', 'chipilones', 'taco', 'tortas', 'papancha', 'lorenza', 'taco', 'macho', 'burro', 'amazing', 'taco', 'n', 'sonoran', 'hotdog', 'lorenzas', 'de', 'asada', 'favorite', 'toasted', 'tortilla', 'asada', 'melted', 'cheese', 'salsa', 'truly', 'recommend', 'cheke', 'mexican', 'food', 'everyone', 'delicious', 'pork', 'taco', 'quesadilla', 'chicken', 'burrito', 'awesome', 'great', 'customer', 'service', 'friendly', 'food', 'really', 'good', 'real', 'mexican', 'food', 'like', 'cafeteria', 'food', 'guadalajara', 'grill', 'ole', 'service', 'okay', 'expect', 'food', 'truck', 'sometimes', 'wait', 'obnoxious', 'salsa', 'selection', 'good', 'wish', 'used', 'real', 'mexican', 'corn', 'tortilla', 'thick', 'yellow', 'one', 'maybe', 'future', 'couple', 'carne', 'asada', 'taco', 'hotdog', 'pretty', 'good', 'seem', 'like', 'lot', 'food', 'place', 'one', 'place', 'go', 'taco', 'burrito', 'tucson', 'yes', 'cost', 'drive', 'thru', 'picky', 'food', 'promise', 'regret', 'burro', 'taco', 'extremely', 'fresh', 'salsa', 'bar', 'delightful', 'staff', 'closed', 'sunday', 'monday', 'tried', 'place', 'first', 'time', 'taco', 'amazing', 'really', 'good', 'quality', 'meat', 'taco', 'bar', 'clean', 'kid', 'even', 'loved', 'taco', 'son', 'ate', 'back', 'sure', 'probably', 'one', 'new', 'go', 'abodaba', 'absolute', 'best', 'ever', 'spice', 'perfect', 'moist', 'flavorful', 'lorenza', 'toasted', 'street', 'taco', 'caramello', 'delicious', 'corn', 'tortilla', 'lorenza', 'toasted', 'perfectly', 'chipilon', 'style', 'sonoran', 'dog', 'good', 'star', 'dish', 'service', 'friendly', 'last', 'night', 'one', 'brother', 'business', 'saw', 'daughter', 'purse', 'table', 'party', 'three', 'came', 'got', 'chair', 'another', 'table', 'put', 'end', 'table', 'put', 'purse', 'sweet', 'today', 'went', 'see', 'daughter', 'work', 'asked', 'plan', 'got', 'replied', 'going', 'go', 'eat', 'asked', 'replied', 'back', 'taco', 'place', 'laughed', 'said', 'thinking', 'day', 'good', 'hilarious', 'fact', 'abodaba', 'excellent', 'top', 'favorite', 'mind', 'blowing', 'good', 'definitely', 'return', 'go', 'way', 'go', 'worth', 'every', 'dime', 'money', 'outstanding', 'tucson', 'top', 'tier', 'element', 'quite', 'good', 'get', 'still', 'worthy', 'regular', 'business', 'good', 'experience', 'might', 'repeat', 'business', 'convenient', 'option', 'one', 'category', 'whim', 'would', 'among', 'first', 'thing', 'come', 'mind', 'would', 'definitely', 'recommend', 'trying', 'get', 'take', 'good', 'would', 'recommend', 'waste', 'money', 'still', 'business', 'stay', 'away', 'cost', 'adobado', 'taco', 'excellent', 'sonoran', 'dog', 'good', 'well', 'love', 'salsa', 'bar', 'spicier', 'salsa', 'make', 'eye', 'water', 'heat', 'spice', 'lover', 'joy', 'guy', 'great', 'job', 'adobo', 'taco', 'favorite', 'tucson', 'standard', 'sonoran', 'hot', 'dog', 'wrong', 'easy', 'access', 'river', 'good', 'food', 'costumer', 'service', 'trash', 'bad', 'vibe', 'rather', 'drive', 'extra', 'mile', 'bk', 'taco', 'food', 'good', 'order', 'hot', 'dog', 'taco', 'de', 'carne', 'asada', 'red', 'salsa', 'super', 'good', 'specially', 'love', 'spicy', 'food', 'overall', 'customer', 'service', 'bit', 'guy', 'got', 'order', 'seem', 'mad', 'welcoming', 'guest', 'review', 'mention', 'expensive', 'place', 'taco', 'burrito', 'spot', 'taco', 'burrito', 'small', 'best', 'special', 'flavor', 'wise', 'might', 'underwhelming', 'priced', 'taco', 'spot', 'ever', 'love', 'place', 'sonoran', 'hotdog', 'leave', 'slot', 'desired', 'rest', 'food', 'amazing', 'el', 'cheke', 'opened', 'tucson', 'mall', 'recently', 'thankful', 'new', 'awesome', 'place', 'get', 'authentic', 'mexican', 'food', 'side', 'town', 'pork', 'taco', 'steak', 'taco', 'sonoran', 'dog', 'sonoran', 'dog', 'usual', 'topping', 'perfectly', 'executed', 'taco', 'well', 'seasoned', 'meat', 'perfect', 'amount', 'char', 'great', 'meat', 'tortilla', 'ratio', 'well', 'condiment', 'bar', 'fully', 'stocked', 'usual', 'extra', 'complete', 'meal', 'got', 'taco', 'hotdog', 'definitely', 'steal', 'service', 'also', 'friendly', 'fast', 'definitely', 'back', 'try', 'item']
5 -> (Document: 729) -> Score: 0.33

## 4 - Query Expansion
- Expand the query using embeddings
- Also Testing using Wordnet for synonyms since my dataset is small
- Goal: Create a function with both and test results later

In [11]:
# use sentence transformer model
model_s = SentenceTransformer('all-MiniLM-L6-v2')
# Retrieve index tokens and embedded the vocabulary
vocab = list(invert_index.keys())
embeddings = model_s.encode(vocab)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [12]:
#Query expansion func
def query_expand(query):
    #tokenize query
    # q_tokens = query.lower().split()
    q_tokens = preprocessv2(query)
    # print(q_tokens)

    #embedding for query
    query_embeddings = model_s.encode(query)

    #dot product vocab * query embeddings
    prod = cosine_similarity([query_embeddings],embeddings)[0]
    top = np.argsort(prod)[-3:][::-1]
    # expansion.extend([vocab[i] for i in top if vocab[i] not in q_tokens])
    expansion = [vocab[i] for i in top if vocab[i] not in q_tokens]
    return q_tokens + expansion

In [13]:
# Testing query expansion via embedding OUTPUT -> new query
query_expand('What are the best vegan taco shops?')

['best', 'vegan', 'taco', 'shop', 'taquitos', 'tacobell']

Now lets test wordnet for synonym based query expansion

In [14]:
#Wordnet Synonym expansion
def syn_expand(query):
    # query = query.lower().split() #basic tokenization
    q_tokens = preprocessv2(query) #consistent approach
    # print(q_tokens)
    #Set - for unique values
    expanded = set(q_tokens)

    for word in q_tokens:
        syn = wordnet.synsets(word)

        for syns in syn[:2]: #2 synonym limit
            for lemma in syns.lemmas():
                expanded.add(lemma.name().replace("_", " "))
    
    return list(expanded)

In [15]:
syn_expand('What are the best vegan shops?') #taco was bad

['best', 'vegan', 'store', 'workshop', 'topper', 'shop']

Okay lets not use synonym based expansion that was unexpected

## 5 - Semantic Embedding Similarity

In [16]:
doc_embeds = model_s.encode(documents, show_progress_bar=True)

Batches:   0%|          | 0/31 [00:00<?, ?it/s]

In [17]:
#Semantic Search Func
def semantic_search(query, test = False, k=10):

    # preprocess query using preprocessv2
    q_tokens = preprocessv2(query)

    #Query Expansion
    exp_tokens = query_expand(query)

    extra_tokens = [x for x in exp_tokens if x not in q_tokens] # just new query words that were added in the expansion of the query
    exp_text = " ".join(q_tokens + extra_tokens)

    
    # vector = model_s.encode(query)
    vector = model_s.encode(exp_text)


    similarity = cosine_similarity([vector],doc_embeds)[0]

    top_doc = np.argsort(similarity)[-k:][::-1] #top 10 ordered descending

    for x in range(k):
        doc_id = top_doc[x]
        score = similarity[doc_id]

    if test:
        #for relevance testing
        pass
    else:
        for x in range(k):
            doc_id = top_doc[x]
            score = similarity[doc_id]
            print(f'Score: {score:.2f} --> {tokens[doc_id]}')
        
    return list(set(top_doc))

In [18]:
semantic_search('What are the best vegan taco shops?')

Score: 0.67 --> ['name', 'la', 'chaiteria', 'category', 'mexican', 'taco', 'vegan', 'vegetarian', 'food', 'truck', 'food', 'restaurant', 'rating', 'review', 'hungry', 'friday', 'afternoon', 'lunch', 'looking', 'restaurant', 'driving', 'saw', 'new', 'place', 'dropped', 'ordered', 'al', 'pastor', 'taco', 'raja', 'taco', 'green', 'chile', 'mushrooom', 'cream', 'al', 'pastor', 'taste', 'authentic', 'oily', 'raja', 'tasteless', 'bland', 'horrible', 'wow', 'either', 'another', 'note', 'place', 'clean', 'tidy', 'stopped', 'today', 'pick', 'large', 'order', 'family', 'taco', 'night', 'everything', 'tasted', 'incredible', 'fresh', 'ordered', 'taco', 'al', 'pastor', 'mole', 'taco', 'definitely', 'back', 'happy', 'wendy', 'opened', 'cafe', 'closer', 'neck', 'wood', 'great', 'menu', 'item', 'featuring', 'best', 'vegetarian', 'food', 'cafe', 'vegetarian', 'love', 'magic', 'food', 'wendy', 'creates', 'potato', 'filled', 'taco', 'jackfruit', 'carnitas', 'go', 'wrong', 'happen', 'day', 'cashew', 'based', 'alfredo', 'gluten', 'free', 'pasta', 'menu', 'whoa', 'tastebud', 'love', 'forever', 'yessss', 'la', 'chaiteria', 'vegan', 'menu', 'regular', 'menu', 'also', 'make', 'vegan', 'dish', 'vegetarian', 'adding', 'cheese', 'jackfruit', 'flavorful', 'recommend', 'house', 'drink', 'orchata', 'good', 'turmeric', 'lemonade', 'jamaica', 'also', 'great', 'portion', 'big', 'food', 'worth', 'every', 'penny', 'staff', 'super', 'friendly', 'attentive', 'want', 'ensure', 'great', 'experience', 'big', 'fan', 'tumerico', 'spot', 'happy', 'location', 'tucson', 'saffron', 'latte', 'espresso', 'mesquite', 'latte', 'ropa', 'vieja', 'raja', 'taco', 'place', 'amazing', 'portion', 'good', 'size', 'taste', 'quality', 'ingredient', 'created', 'fun', 'artistic', 'space', 'enjoy', 'new', 'favorite', 'restaurant', 'amazing', 'customer', 'service', 'fast', 'service', 'best', 'food', 'tucson', 'place', 'amazing', 'compared', 'one', 'owned', 'company', 'one', 'feel', 'bigger', 'portion', 'needed', 'great', 'side', 'town', 'plus', 'much', 'closer', 'seeing', 'lost', 'vegan', 'burrito', 'side', 'town', 'definitely', 'make', 'definitely', 'would', 'recommend', 'al', 'pastor', 'taco', 'little', 'spicy', 'make', 'even', 'spicier', 'salsa', 'make', 'salsa', 'amazing', 'tad', 'pricey', 'side', 'compared', 'regular', 'mexican', 'food', 'place', 'around', 'vegan', 'healthy', 'non', 'vegan', 'mexican', 'food', 'right', 'point', 'price', 'come', 'disappointed', 'place', 'point', 'vegan', 'non', 'vegan', 'option', 'staff', 'absolutely', 'amazing', 'kind', 'helpful', 'create', 'fantastic', 'atmosphere', 'food', 'delicious', 'worth', 'try', 'normally', 'amazing', 'place', 'however', 'get', 'cuban', 'jackfruit', 'today', 'tried', 'jackfruit', 'pineapple', 'say', 'stream', 'taco', 'tiny', 'bit', 'jackfruit', 'sour', 'pineapple', 'cutting', 'sorry', 'next', 'time', 'stick', 'like', 'carne', 'con', 'chili', 'burro', 'one', 'best', 'rice', 'bean', 'also', 'really', 'good', 'miss', 'spot', 'best', 'vegan', 'mexican', 'food', 'town', 'support', 'local', 'woman', 'owner', 'finally', 'got', 'check', 'spinoff', 'tumerico', 'location', 'also', 'cute', 'little', 'market', 'food', 'snack', 'beverage', 'toiletry', 'desert', 'go', 'food', 'truck', 'outside', 'meat', 'dish', 'make', 'friendlier', 'wider', 'base', 'people', 'inside', 'vegan', 'vegetarian', 'menu', 'always', 'changing', 'always', 'go', 'tostados', 'yummy', 'combination', 'crunchy', 'savory', 'flavorful', 'bean', 'well', 'cooked', 'seasoned', 'food', 'tends', 'bit', 'oily', 'downside', 'also', 'tried', 'one', 'juice', 'pricy', 'healthy', 'balance', 'veggie', 'fruit', 'citrus', 'another', 'reason', 'check', 'place', 'amazing', 'mural', 'artwork', 'tucson', 'must', 'see', 'great', 'addition', 'tumerico', 'family', 'much', 'needed', 'boost', 'vegan', 'community', 'went', 'friend', 'try', 'something', 'new', 'liked', 'cafe', 'restaurant', 'going', 'coffee', 'good', 'got', 'horchata', 'latte', 'hot', 'lacking', 'flavor', 'cup', 'steaming', 'hot', 'coffee', 'lukewarm', 'meal', 'customer', 'got', 'look', 'great', 'though', 'also', 'friend', 'liked', 'mole', 'latte', 'complaint', 'latte', 'come', 'soy', 'milk', 'fantastic', 'place', 'vegan', 'meat', 'dish', 'bad', 'meal', 'time', 'went', 'hear', 'coffee', 'good', 'go', 'food', 'give', 'shot', 'glad', 'west', 'side', 'town', 'west', 'side', 'getting', 'great', 'addition', 'different', 'tumerico', 'great', 'salsa', 'bar', 'instead', 'salsa', 'topping', 'already', 'appearing', 'plate', 'great', 'drink', 'menu', 'coffee', 'mexican', 'drink', 'vegetarian', 'food', 'menu', 'fantastic', 'original', 'tumerico', 'store', 'buy', 'burrito', 'salsa', 'tamale', 'find', 'quince', 'homemade', 'chip', 'much', 'pandemic', 'also', 'offering', 'toilet', 'paper', 'hand', 'sanitizer', 'etc', 'whole', 'staff', 'friendly', 'feel', 'like', 'home', 'delicious', 'fresh', 'coffee', 'friendly', 'staff', 'added', 'meat', 'friendly', 'food', 'truck', 'able', 'serve', 'selection', 'guest', 'also', 'great', 'store', 'selection', 'bottled', 'drink', 'absolutely', 'love', 'getting', 'freshly', 'cut', 'coconut', 'everytime', 'stop', 'first', 'time', 'trying', 'place', 'got', 'takeout', 'called', 'order', 'staff', 'nice', 'cuban', 'burro', 'side', 'rice', 'bean', 'veggie', 'filling', 'delicious', 'definitely', 'go', 'back', 'try', 'food', 'absolutely', 'love', 'good', 'drink', 'staff', 'everyone', 'respectful', 'energy', 'welcoming', 'never', 'disappointed', 'coming', 'absolutely', 'love', 'absolutely', 'love', 'restaurant', 'gem', 'side', 'town', 'dish', 'packed', 'flavor', 'every', 'bite', 'portion', 'generous', 'price', 'fair', 'also', 'love', 'refrigerator', 'full', 'awesome', 'dessert', 'refreshing', 'drink', 'kombucha', 'tap', 'get', 'started', 'salsa', 'bar', 'gosh', 'welcoming', 'wonderful', 'restaurant', 'loyal', 'devotee', 'tumerico', 'someone', 'explained', 'u', 'la', 'chaiteria', 'tumerico', 'sister', 'restaurant', 'make', 'trip', 'lot', 'similar', 'vegan', 'option', 'find', 'tumerico', 'husband', 'delighted', 'find', 'la', 'chaiteria', 'option', 'meat', 'eater', 'omnivore', 'generally', 'enchilada', 'chile', 'relleno', 'delicious', 'portion', 'size', 'large', 'ended', 'taking', 'part', 'meal', 'home', 'got', 'full', 'finish', 'tried', 'turmeric', 'lemonade', 'delighted', 'good', 'tasted', 'staff', 'much', 'like', 'staff', 'tumerico', 'delightful', 'food', 'came', 'quickly', 'la', 'chaiteria', 'applying', 'liquor', 'license', 'sell', 'beer', 'wine', 'think', 'place', 'get', 'better', 'thought', 'adding', 'adult', 'beverage', 'meal', 'sound', 'even', 'amazing', 'folk', 'complained', 'thing', 'oily', 'experience', 'either', 'tumerico', 'folk', 'also', 'complained', 'price', 'la', 'chaiteria', 'source', 'majority', 'ingredient', 'organic', 'food', 'supply', 'organic', 'food', 'cost', 'money', 'also', 'think', 'quality', 'ingredient', 'reflected', 'taste', 'food', 'looking', 'fabulous', 'southwestern', 'food', 'la', 'chaiteria']
Score: 0.63 --> ['name', 'taco', 'shop', 'company', 'category', 'restaurant', 'fast', 'food', 'mexican', 'rating', 'review', 'good', 'fast', 'inexpensive', 'like', 'get', 'veggie', 'burrito', 'husband', 'love', 'bacon', 'egg', 'cheese', 'burrito', 'available', 'time', 'breakfast', 'place', 'ambiance', 'get', 'go', 'happy', 'got', 'carne', 'asada', 'burrito', 'avocado', 'used', 'fresh', 'significantly', 'took', 'away', 'ingredient', 'finish', 'whole', 'thing', 'could', 'sure', 'see', 'visit', 'place', 'bar', 'taco', 'shop', 'pretty', 'decent', 'place', 'late', 'night', 'l', 'always', 'get', 'rolled', 'taquitos', 'always', 'satisfies', 'good', 'food', 'especially', 'drunk', 'overall', 'complain', 'pretty', 'good', 'tasting', 'taco', 'spot', 'driving', 'city', 'happened', 'upon', 'taco', 'shop', 'great', 'fish', 'taco', 'shrimp', 'burrito', 'great', 'price', 'tiny', 'spot', 'serf', 'yummy', 'authentic', 'dish', 'counter', 'taco', 'shop', 'tried', 'carnitas', 'unimpressed', 'pork', 'lean', 'flavorless', 'dry', 'side', 'tried', 'carne', 'asada', 'similarly', 'unimpressed', 'meat', 'similarly', 'flavorless', 'bit', 'salty', 'side', 'sure', 'think', 'might', 'detected', 'hint', 'pork', 'somewhere', 'eat', 'pig', 'might', 'want', 'ask', 'hearing', 'friend', 'rave', 'place', 'decided', 'give', 'another', 'shot', 'actually', 'really', 'glad', 'star', 'show', 'al', 'pastor', 'burrito', 'marinated', 'pork', 'tender', 'full', 'flavor', 'ingredient', 'presented', 'perfect', 'proportion', 'even', 'put', 'fresh', 'chopped', 'cilantro', 'really', 'set', 'burrito', 'apart', 'al', 'pastor', 'saucy', 'accustomed', 'work', 'really', 'well', 'dare', 'say', 'tastiest', 'al', 'pastor', 'part', 'town', 'favor', 'try', 'also', 'delicious', 'green', 'chili', 'burrito', 'pork', 'reasonably', 'good', 'really', 'make', 'awesome', 'douse', 'entire', 'burrito', 'heavy', 'helping', 'green', 'chili', 'sauce', 'cheese', 'lettuce', 'call', 'wet', 'style', 'call', 'yummy', 'slightly', 'putting', 'though', 'practice', 'sticking', 'burrito', 'microwave', 'styrofoam', 'container', 'melt', 'cheese', 'polystyrene', 'supposedly', 'microwave', 'safe', 'probably', 'like', 'clearly', 'systematically', 'jeopardizing', 'customer', 'health', 'still', 'took', 'notice', 'ordered', 'less', 'exciting', 'red', 'chili', 'burrito', 'thing', 'guess', 'wet', 'style', 'thing', 'microwaving', 'styrofoam', 'make', 'uncomfortable', 'probably', 'stay', 'away', 'wet', 'style', 'offering', 'aside', 'menu', 'item', 'neither', 'blown', 'away', 'disgusted', 'anything', 'tried', 'taco', 'shop', 'two', 'thing', 'really', 'delicious', 'would', 'still', 'probably', 'recommend', 'staying', 'away', 'carne', 'asada', 'carnitas', 'overall', 'converted', 'taco', 'shop', 'quite', 'alright', 'super', 'basic', 'eatery', 'three', 'watery', 'anemic', 'salsa', 'salsa', 'bar', 'guac', 'thin', 'seems', 'like', 'come', 'pourable', 'vessel', 'chunk', 'resembling', 'avocado', 'tomato', 'onion', 'etc', 'chicken', 'taco', 'meat', 'little', 'hard', 'tough', 'nugget', 'tasted', 'like', 'meat', 'sat', 'day', 'warmer', 'several', 'ua', 'student', 'place', 'quite', 'old', 'decrepit', 'run', 'big', 'hole', 'plaster', 'wall', 'booth', 'sat', 'appears', 'clean', 'need', 'overhaul', 'friendly', 'clerk', 'town', 'many', 'stellar', 'place', 'get', 'taco', 'would', 'return', 'one', 'meh', 'maybe', 'serious', 'need', 'food', 'night', 'looking', 'really', 'luscious', 'fresh', 'quality', 'taco', 'gone', 'way', 'time', 'care', 'admit', 'let', 'face', 'cheese', 'quesadilla', 'go', 'perfect', 'time', 'day', 'taste', 'amazing', 'used', 'live', 'street', 'right', 'behind', 'shop', 'heart', 'broken', 'move', 'away', 'nothing', 'better', 'cab', 'driver', 'drop', 'friday', 'night', 'walking', 'home', 'ultimate', 'prize', 'cheese', 'quesadilla', 'horchata', 'extra', 'lime', 'place', 'eat', 'late', 'night', 'business', 'name', 'suggests', 'go', 'want', 'drunken', 'taco', 'get', 'fried', 'fish', 'real', 'good', 'carne', 'asada', 'recommend', 'burrito', 'best', 'value', 'cheaper', 'betos', 'nicos', 'better', 'quality', 'biggest', 'gripe', 'place', 'wait', 'weekend', 'night', 'ridiculous', 'get', 'steak', 'egg', 'burrito', 'breakfast', 'shrimp', 'burrito', 'lunch', 'able', 'try', 'anything', 'else', 'b', 'c', 'two', 'good', 'expect', 'ambience', 'stellar', 'service', 'good', 'food', 'delicious', 'burrito', 'really', 'set', 'establishment', 'apart', 'hour', 'taco', 'stand', 'salsa', 'delicious', 'load', 'much', 'please', 'use', 'meal', 'home', 'truly', 'hit', 'spot', 'especially', 'late', 'night', 'arizona', 'burrito', 'delicious', 'one', 'best', 'burrito', 'ever', 'definitely', 'satisfied', 'okay', 'little', 'confused', 'place', 'little', 'star', 'think', 'deserves', 'fine', 'dining', 'going', 'impress', 'date', 'well', 'lived', 'close', 'location', 'month', 'love', 'late', 'night', 'run', 'quick', 'lunch', 'greasy', 'mexican', 'fast', 'food', 'found', 'general', 'menu', 'item', 'consistently', 'good', 'affordable', 'think', 'veggie', 'burrito', 'california', 'breakfast', 'burrito', 'outstanding', 'thing', 'order', 'like', 'chicken', 'burrito', 'maybe', 'felt', 'like', 'something', 'chicken', 'guac', 'salsa', 'bar', 'job', 'small', 'shop', 'nice', 'cool', 'employee', 'efficient', 'rarely', 'wait', 'minute', 'get', 'food', 'even', 'packed', 'full', 'drunk', 'college', 'kid', 'salsa', 'tasteless', 'meat', 'could', 'use', 'salt', 'spice', 'fish', 'taco', 'good', 'bad', 'salsa', 'elevate', 'let', 'honest', 'else', 'gonna', 'eat', 'around', 'area', 'morning', 'restaurant', 'fabulous', 'food', 'satisfying', 'healthy', 'reasonably', 'priced', 'come', 'one', 'come', 'glad', 'delicious', 'food', 'gotta', 'love', 'big', 'burrito', 'good', 'price', 'clean', 'place', 'open', 'favorite', 'place', 'get', 'late', 'night', 'burrito', 'college', 'whenever', 'back', 'town', 'visit', 'stop', 'clarify', 'thing', 'ua', 'session', 'break', 'cut', 'midnight', 'ish', 'taco', 'shop', 'awesome', 'time', 'never', 'satisfied', 'taste', 'food', 'open', 'hour', 'thing', 'would', 'advice', 'go', 'night', 'prepared', 'deal', 'sketch', 'situation', 'like', 'people', 'fighting', 'seen', 'also', 'made', 'interesting', 'taco', 'shop', 'win', 'great', 'food', 'lot', 'various', 'great', 'eats', 'open', 'best', 'quick', 'dirty', 'mexican', 'food', 'tucson', 'far', 'better', 'nico', 'mexican', 'fast', 'food', 'excellent', 'food', 'great', 'tasting', 'homemade', 'salsa', 'various', 'level', 'picante', 'service', 'always', 'friendly', 'fast', 'nothing', 'ever', 'ordered', 'greasy', 'overlooked', 'favorite', 'chicken', 'fajitas', 'burrito', 'amazing', 'flavor', 'also', 'customize', 'breakfast', 'burrito', 'order', 'hesitate', 'make', 'way', 'want', 'open', 'always', 'delicious', 'portion', 'plentiful', 'sabroso', 'one', 'thing', 'see', 'take', 'eat', 'dining', 'several', 'small', 'table', 'got', 'group', 'room', 'order', 'home', 'cooked', 'tasting', 'food', 'dine', 'home', 'well', 'worth', 'checking', 'one', 'regular', 'spot']

[549, 709, 647, 361, 842, 715, 43, 751, 730, 318]

## 6 - Hybrid Scoring Approach
- Combine both BM25 Results with Semantic Searching with a split % between their scores
- GOAL: To achieve a moderate output based off the strenghts of both methods

In [19]:
def hybrid_search(query,a =.2):

    # preprocess query using preprocessv2
    q_tokens = preprocessv2(query)

    #Query Expansion
    exp_tokens = query_expand(query)

    extra_tokens = [x for x in exp_tokens if x not in q_tokens] # just new query words that were added in the expansion of the query
    exp_text = " ".join(q_tokens + extra_tokens)

    # print(extra_tokens)
    print(f'Query: {exp_text}')

    #BM25 Scoring - weight original query strongest followed by little of expansion
    bm25_scoring = (
        1*np.array(bm25.get_scores(q_tokens)) +  .3*np.array(bm25.get_scores(extra_tokens))
    )

    #Semantic Scoring
    vector = model_s.encode(exp_text)
    semantic_scoring = cosine_similarity([vector],doc_embeds)[0]

    #Combination
    final = a*np.array(bm25_scoring) + (1-a) * semantic_scoring

    top_documents = np.argsort(final)[-10:][::-1]
    for x in range(10):
        doc_id = top_documents[x]
        score = final[doc_id]
        print(f'Score: {score:.2f} --> {tokens[doc_id]}')

    return list(set(top_documents))

In [20]:
hybrid_search('What are the best vegan taco shops?')

Query: best vegan taco shop taquitos tacobell
Score: 2.66 --> ['name', 'taco', 'stop', 'category', 'caterer', 'event', 'planning', 'service', 'food', 'truck', 'food', 'restaurant', 'mexican', 'rating', 'review', 'excellent', 'taco', 'price', 'reasonable', 'quality', 'quantity', 'received', 'hope', 'around', 'next', 'visit', 'tuscon', 'wanted', 'know', 'hype', 'tried', 'jackfruit', 'burro', 'mind', 'vegan', 'vegetarian', 'wanted', 'try', 'also', 'actually', 'hate', 'jackfruit', 'asian', 'family', 'think', 'love', 'big', 'fan', 'kind', 'fruit', 'durian', 'jackfruit', 'lychee', 'etc', 'think', 'eating', 'jackfruit', 'burro', 'long', 'long', 'time', 'marinaded', 'something', 'good', 'felt', 'like', 'best', 'burro', 'far', 'life', 'soooo', 'big', 'usually', 'never', 'finish', 'one', 'whole', 'burro', 'size', 'one', 'sitting', 'ate', 'put', 'good', 'mood', 'texted', 'sister', 'florida', 'good', 'service', 'great', 'super', 'friendly', 'food', 'fresh', 'made', 'order', 'glad', 'moved', 'would', 'never', 'experienced', 'today', 'stopped', 'little', 'food', 'truck', 'cause', 'obviously', 'hungry', 'typical', 'mexican', 'food', 'menu', 'noticed', 'bacon', 'wrapped', 'burro', 'decided', 'give', 'try', 'ground', 'beef', 'holy', 'f', 'k', 'one', 'best', 'damn', 'burrito', 'ever', 'hard', 'impress', 'mexican', 'food', 'day', 'even', 'wanna', 'right', 'review', 'keep', 'gem', 'secret', 'community', 'disservice', 'food', 'take', 'time', 'cook', 'rushing', 'sweet', 'little', 'old', 'abuela', 'cause', 'back', 'cooking', 'love', 'thanks', 'taco', 'stop', 'making', 'today', 'great', 'day', 'treat', 'east', 'side', 'tucson', 'two', 'sonoran', 'hot', 'dog', 'veg', 'meat', 'one', 'flavorful', 'jackfruit', 'birria', 'available', 'taco', 'burrito', 'taco', 'absolutely', 'delicious', 'best', 'prepared', 'jackfruit', 'ever', 'wish', 'ordered', 'plenty', 'vegan', 'option', 'available', 'looking', 'new', 'delicious', 'food', 'side', 'town', 'keto', 'burrito', 'amazing', 'net', 'carb', 'delicious', 'meat', 'better', 'food', 'truck', 'keto', 'friendly', 'really', 'excited', 'try', 'taco', 'stop', 'little', 'hard', 'get', 'time', 'actually', 'open', 'supposedly', 'open', 'monday', 'friday', 'time', 'hour', 'truck', 'actually', 'closed', 'today', 'ordered', 'jackfruit', 'taco', 'carne', 'asada', 'burrito', 'sonoran', 'hotdog', 'place', 'tucson', 'serve', 'jackfruit', 'vegetarian', 'vegan', 'option', 'stoked', 'actually', 'unfortunately', 'big', 'fan', 'spice', 'used', 'jackfruit', 'seemed', 'overpowering', 'probably', 'much', 'chili', 'powder', 'whatever', 'spice', 'probably', 'overpowering', 'accentuated', 'sweet', 'salsa', 'crema', 'taco', 'came', 'flour', 'tortilla', 'spiced', 'jackfruit', 'pico', 'de', 'gallo', 'avocado', 'slice', 'side', 'rice', 'bean', 'carne', 'asada', 'best', 'either', 'thought', 'bit', 'strange', 'came', 'cabbage', 'cheese', 'bean', 'hoping', 'really', 'good', 'work', 'though', 'help', 'meat', 'grilled', 'super', 'good', 'however', 'sonoran', 'hotdog', 'save', 'meal', 'although', 'bit', 'burnt', 'outside', 'fixing', 'everything', 'right', 'really', 'would', 'love', 'give', 'star', 'place', 'really', 'hoping', 'improvement', 'next', 'time', 'also', 'today', 'birria', 'would', 'great', 'try', 'next', 'time', 'well', 'anyways', 'take', 'taco', 'stop', 'hopefully', 'people', 'try', 'food', 'give', 'feedback', 'could', 'try', 'see', 'work', 'ordered', 'two', 'jackfruit', 'burrito', 'three', 'bean', 'cheese', 'burrito', 'kid', 'stuffed', 'delicious', 'ingredient', 'toasted', 'outside', 'delicious', 'definitely', 'making', 'primary', 'east', 'side', 'burrito', 'place', 'found', 'taco', 'truck', 'heading', 'back', 'hotel', 'rating', 'looked', 'good', 'stopped', 'disappointed', 'apprehensive', 'first', 'basic', 'looking', 'truck', 'small', 'number', 'rating', 'however', 'carne', 'asada', 'burrito', 'chicken', 'quesadilla', 'burrito', 'big', 'good', 'size', 'meat', 'tasty', 'chicken', 'quesadilla', 'best', 'seasoned', 'perfection', 'would', 'go', 'back', 'would', 'given', 'five', 'star', 'price', 'touch', 'high', 'little', 'salty', 'although', 'like', 'salty', 'wish', 'could', 'given', 'four', 'half', 'star', 'taco', 'truck', 'amazing', 'everyone', 'family', 'got', 'something', 'different', 'loved', 'bit', 'wait', 'usually', 'one', 'two', 'lady', 'working', 'well', 'worth', 'wait', 'delicious', 'vegan', 'option', 'really', 'enjoyed', 'jackfruit', 'street', 'taco', 'option', 'everyone', 'great', 'costumer', 'service', 'best', 'quesa', 'birria', 'taco', 'town', 'absolutely', 'delicious', 'worth', 'wait', 'patient', 'good', 'thing', 'take', 'time', 'excellent', 'partial', 'beef', 'burrito', 'ambiance', 'would', 'something', 'would', 'expect', 'poor', 'dusty', 'town', 'northern', 'mexico', 'super', 'cheap', 'metal', 'folding', 'table', 'cheap', 'metal', 'really', 'cheap', 'folding', 'chair', 'set', 'rear', 'back', 'taco', 'truck', 'really', 'loud', 'generator', 'running', 'irritating', 'carne', 'asada', 'taco', 'dry', 'must', 'cooked', 'many', 'hour', 'let', 'dry', 'flour', 'tortilla', 'thin', 'lone', 'per', 'taco', 'broke', 'open', 'picked', 'usually', 'street', 'taco', 'like', 'tortilla', 'awful', 'threw', 'garbage', 'belonged', 'order', 'side', 'rice', 'bean', 'total', 'wast', 'money', 'good', 'part', 'really', 'love', 'jackfruit', 'burrito', 'would', 'buy', 'one', 'eat', 'girlfriend', 'love', 'amount', 'vegan', 'option', 'available', 'super', 'tasty', 'tell', 'vegan', 'quesadilla', 'apart', 'normal', 'one', 'good', 'thank', 'much', 'vegan', 'option', 'hand', 'best', 'mexican', 'vegan', 'place', 'town', 'favorite', 'humongous', 'jackfruit', 'burrito', 'delicious', 'filling', 'bean', 'rice', 'tasty', 'love', 'guy', 'use', 'cabbage', 'instead', 'lettuce', 'burrito', 'salsa', 'spot', 'creama', 'die', 'work', 'butt', 'truck', 'friendly', 'miss', 'taco', 'truck', 'stopped', 'visiting', 'mount', 'lemmon', 'everything', 'delicious', 'especially', 'loved', 'birria', 'taco', 'perfectly', 'crispy', 'shell', 'tortilla', 'seemed', 'really', 'fresh', 'meat', 'flavorful', 'right', 'amount', 'cheese', 'highly', 'recommend', 'lady', 'running', 'truck', 'one', 'rude', 'people', 'ever', 'dealt', 'spoke', 'slowly', 'think', 'knew', 'much', 'english', 'even', 'still', 'rude', 'short', 'answer', 'question', 'acted', 'like', 'bothering', 'literally', 'made', 'feel', 'like', 'terrible', 'human', 'treated', 'customer', 'like', 'gold', 'terrible', 'people', 'even', 'worth', 'food', 'service', 'bad', 'military', 'even', 'cadre', 'ruthless', 'omg', 'veteran', 'vegan', 'believe', 'great', 'ordered', 'jackfruit', 'vegan', 'burrito', 'little', 'buck', 'sooooo', 'worth', 'tasty', 'literally', 'hold', 'title', 'burrito', 'say', 'alot', 'happy', 'finally', 'went', 'actually', 'bumped', 'owner', 'maybe', 'idk', 'one', 'day', 'safeway', 'produce', 'saw', 'looking', 'vegan', 'food', 'told', 'taco', 'stop', 'thankful', 'good', 'back', 'prob', 'way', 'much', 'haha', 'awesome', 'taco', 'worker', 'masked', 'customer', 'required', 'masked', 'wait', 'go', 'back', 'asada', 'ground', 'beef', 'chicken', 'came', 'cabbage', 'tomato', 'onion', 'cilantro', 'salsa', 'side', 'great', 'eating', 'surprisingly', 'good', 'food', 'unimpressive', 'looking', 'food', 'truck', 'way', 'location', 'enjoyed', 'carne', 'asada', 'taco', 'quesadilla', 'couple', 'ice', 'cold', 'agua', 'frescas', 'back', 'location', 'moved', 'recently', 'jackfruit', 'alone', 'make', 'must', 'stop', 'food', 'truck', 'even', 'cupcake', 'super', 'slow', 'time', 'promise', 'worth', 'wait', 'new', 'food', 'truck', 'great', 'food', 'courteous', 'staff', 'great', 'location', 'east', 'side', 'atspeedway', 'houghton', 'must', 'try']
Score: 2.65 --> ['name', 'la', 'chaiteria', 'category', 'mexican', 'taco', 'vegan', 'vegetarian', 'food', 'truck', 'food', 'restaurant', 'rating', 'review', 'hungry', 'friday', 'afternoon', 'lunch', 'looking', 'restaurant', 'driving', 'saw', 'new', 'place', 'dropped', 'ordered', 'al', 'pastor', 'taco', 'raja', 'taco', 'green', 'chile', 'mushrooom', 'cream', 'al', 'pastor', 'taste', 'authentic', 'oily', 'raja', 'tasteless', 'bland', 'horrible', 'wow', 'either', 'another', 'note', 'place', 'clean', 'tidy', 'stopped', 'today', 'pick', 'large', 'order', 'family', 'taco', 'night', 'everything', 'tasted', 'incredible', 'fresh', 'ordered', 'taco', 'al', 'pastor', 'mole', 'taco', 'definitely', 'back', 'happy', 'wendy', 'opened', 'cafe', 'closer', 'neck', 'wood', 'great', 'menu', 'item', 'featuring', 'best', 'vegetarian', 'food', 'cafe', 'vegetarian', 'love', 'magic', 'food', 'wendy', 'creates', 'potato', 'filled', 'taco', 'jackfruit', 'carnitas', 'go', 'wrong', 'happen', 'day', 'cashew', 'based', 'alfredo', 'gluten', 'free', 'pasta', 'menu', 'whoa', 'tastebud', 'love', 'forever', 'yessss', 'la', 'chaiteria', 'vegan', 'menu', 'regular', 'menu', 'also', 'make', 'vegan', 'dish', 'vegetarian', 'adding', 'cheese', 'jackfruit', 'flavorful', 'recommend', 'house', 'drink', 'orchata', 'good', 'turmeric', 'lemonade', 'jamaica', 'also', 'great', 'portion', 'big', 'food', 'worth', 'every', 'penny', 'staff', 'super', 'friendly', 'attentive', 'want', 'ensure', 'great', 'experience', 'big', 'fan', 'tumerico', 'spot', 'happy', 'location', 'tucson', 'saffron', 'latte', 'espresso', 'mesquite', 'latte', 'ropa', 'vieja', 'raja', 'taco', 'place', 'amazing', 'portion', 'good', 'size', 'taste', 'quality', 'ingredient', 'created', 'fun', 'artistic', 'space', 'enjoy', 'new', 'favorite', 'restaurant', 'amazing', 'customer', 'service', 'fast', 'service', 'best', 'food', 'tucson', 'place', 'amazing', 'compared', 'one', 'owned', 'company', 'one', 'feel', 'bigger', 'portion', 'needed', 'great', 'side', 'town', 'plus', 'much', 'closer', 'seeing', 'lost', 'vegan', 'burrito', 'side', 'town', 'definitely', 'make', 'definitely', 'would', 'recommend', 'al', 'pastor', 'taco', 'little', 'spicy', 'make', 'even', 'spicier', 'salsa', 'make', 'salsa', 'amazing', 'tad', 'pricey', 'side', 'compared', 'regular', 'mexican', 'food', 'place', 'around', 'vegan', 'healthy', 'non', 'vegan', 'mexican', 'food', 'right', 'point', 'price', 'come', 'disappointed', 'place', 'point', 'vegan', 'non', 'vegan', 'option', 'staff', 'absolutely', 'amazing', 'kind', 'helpful', 'create', 'fantastic', 'atmosphere', 'food', 'delicious', 'worth', 'try', 'normally', 'amazing', 'place', 'however', 'get', 'cuban', 'jackfruit', 'today', 'tried', 'jackfruit', 'pineapple', 'say', 'stream', 'taco', 'tiny', 'bit', 'jackfruit', 'sour', 'pineapple', 'cutting', 'sorry', 'next', 'time', 'stick', 'like', 'carne', 'con', 'chili', 'burro', 'one', 'best', 'rice', 'bean', 'also', 'really', 'good', 'miss', 'spot', 'best', 'vegan', 'mexican', 'food', 'town', 'support', 'local', 'woman', 'owner', 'finally', 'got', 'check', 'spinoff', 'tumerico', 'location', 'also', 'cute', 'little', 'market', 'food', 'snack', 'beverage', 'toiletry', 'desert', 'go', 'food', 'truck', 'outside', 'meat', 'dish', 'make', 'friendlier', 'wider', 'base', 'people', 'inside', 'vegan', 'vegetarian', 'menu', 'always', 'changing', 'always', 'go', 'tostados', 'yummy', 'combination', 'crunchy', 'savory', 'flavorful', 'bean', 'well', 'cooked', 'seasoned', 'food', 'tends', 'bit', 'oily', 'downside', 'also', 'tried', 'one', 'juice', 'pricy', 'healthy', 'balance', 'veggie', 'fruit', 'citrus', 'another', 'reason', 'check', 'place', 'amazing', 'mural', 'artwork', 'tucson', 'must', 'see', 'great', 'addition', 'tumerico', 'family', 'much', 'needed', 'boost', 'vegan', 'community', 'went', 'friend', 'try', 'something', 'new', 'liked', 'cafe', 'restaurant', 'going', 'coffee', 'good', 'got', 'horchata', 'latte', 'hot', 'lacking', 'flavor', 'cup', 'steaming', 'hot', 'coffee', 'lukewarm', 'meal', 'customer', 'got', 'look', 'great', 'though', 'also', 'friend', 'liked', 'mole', 'latte', 'complaint', 'latte', 'come', 'soy', 'milk', 'fantastic', 'place', 'vegan', 'meat', 'dish', 'bad', 'meal', 'time', 'went', 'hear', 'coffee', 'good', 'go', 'food', 'give', 'shot', 'glad', 'west', 'side', 'town', 'west', 'side', 'getting', 'great', 'addition', 'different', 'tumerico', 'great', 'salsa', 'bar', 'instead', 'salsa', 'topping', 'already', 'appearing', 'plate', 'great', 'drink', 'menu', 'coffee', 'mexican', 'drink', 'vegetarian', 'food', 'menu', 'fantastic', 'original', 'tumerico', 'store', 'buy', 'burrito', 'salsa', 'tamale', 'find', 'quince', 'homemade', 'chip', 'much', 'pandemic', 'also', 'offering', 'toilet', 'paper', 'hand', 'sanitizer', 'etc', 'whole', 'staff', 'friendly', 'feel', 'like', 'home', 'delicious', 'fresh', 'coffee', 'friendly', 'staff', 'added', 'meat', 'friendly', 'food', 'truck', 'able', 'serve', 'selection', 'guest', 'also', 'great', 'store', 'selection', 'bottled', 'drink', 'absolutely', 'love', 'getting', 'freshly', 'cut', 'coconut', 'everytime', 'stop', 'first', 'time', 'trying', 'place', 'got', 'takeout', 'called', 'order', 'staff', 'nice', 'cuban', 'burro', 'side', 'rice', 'bean', 'veggie', 'filling', 'delicious', 'definitely', 'go', 'back', 'try', 'food', 'absolutely', 'love', 'good', 'drink', 'staff', 'everyone', 'respectful', 'energy', 'welcoming', 'never', 'disappointed', 'coming', 'absolutely', 'love', 'absolutely', 'love', 'restaurant', 'gem', 'side', 'town', 'dish', 'packed', 'flavor', 'every', 'bite', 'portion', 'generous', 'price', 'fair', 'also', 'love', 'refrigerator', 'full', 'awesome', 'dessert', 'refreshing', 'drink', 'kombucha', 'tap', 'get', 'started', 'salsa', 'bar', 'gosh', 'welcoming', 'wonderful', 'restaurant', 'loyal', 'devotee', 'tumerico', 'someone', 'explained', 'u', 'la', 'chaiteria', 'tumerico', 'sister', 'restaurant', 'make', 'trip', 'lot', 'similar', 'vegan', 'option', 'find', 'tumerico', 'husband', 'delighted', 'find', 'la', 'chaiteria', 'option', 'meat', 'eater', 'omnivore', 'generally', 'enchilada', 'chile', 'relleno', 'delicious', 'portion', 'size', 'large', 'ended', 'taking', 'part', 'meal', 'home', 'got', 'full', 'finish', 'tried', 'turmeric', 'lemonade', 'delighted', 'good', 'tasted', 'staff', 'much', 'like', 'staff', 'tumerico', 'delightful', 'food', 'came', 'quickly', 'la', 'chaiteria', 'applying', 'liquor', 'license', 'sell', 'beer', 'wine', 'think', 'place', 'get', 'better', 'thought', 'adding', 'adult', 'beverage', 'meal', 'sound', 'even', 'amazing', 'folk', 'complained', 'thing', 'oily', 'experience', 'either', 'tumerico', 'folk', 'also', 'complained', 'price', 'la', 'chaiteria', 'source', 'majority', 'ingredient', 'organic', 'food', 'supply', 'organic', 'food', 'cost', 'money', 'also', 'think', 'quality', 'ingredient', 'reflected', 'taste', 'food', 'looking', 'fabulous', 'southwestern', 'food', 'la', 'chaiteria']

[549, 263, 361, 751, 529, 690, 883, 820, 284, 318]

This appears to be the best approach so far based on the slight investigation I have done reading the reviews and comparing them to the query. 
Though some results are being overpowered by the word "vegan" allowing ice cream and cafes/bakeries to be on the top 10...

## 7 - Ranking Relevance
- NDCG@10 for 
- BM25
- Semantic Search
- Hybrid Search

In [21]:
#make test queries for testing purposes
# 1) food preference
# 2) price related
# 3) occasion based
# 4) restrictions


queries = [
    'What are the best vegan taco shops?', #1/4
    'Cheap sushi restuarants', #1/2
    'Romantic Italian dinner spots', #1/3
    'Vegan restaurants', #4
    'Best date night food spots', #3
    'Sweet treats', #1,
    'Where can I get a sandwich?', #1
    'Is there any inexpensive steak houses?', #1/2
    'Coffee shops nearby' #1
]

In [22]:
# Dictionary of results for each method
semantic_results = {}
bm25_results = {}
hybrid_results = {}

for q in queries:
    semantic_results[q] = semantic_search(q, test = True)
    bm25_results[q] = bm25z(q)
    hybrid_results[q] = hybrid_search(q)

Query: best vegan taco shop taquitos tacobell
Score: 2.66 --> ['name', 'taco', 'stop', 'category', 'caterer', 'event', 'planning', 'service', 'food', 'truck', 'food', 'restaurant', 'mexican', 'rating', 'review', 'excellent', 'taco', 'price', 'reasonable', 'quality', 'quantity', 'received', 'hope', 'around', 'next', 'visit', 'tuscon', 'wanted', 'know', 'hype', 'tried', 'jackfruit', 'burro', 'mind', 'vegan', 'vegetarian', 'wanted', 'try', 'also', 'actually', 'hate', 'jackfruit', 'asian', 'family', 'think', 'love', 'big', 'fan', 'kind', 'fruit', 'durian', 'jackfruit', 'lychee', 'etc', 'think', 'eating', 'jackfruit', 'burro', 'long', 'long', 'time', 'marinaded', 'something', 'good', 'felt', 'like', 'best', 'burro', 'far', 'life', 'soooo', 'big', 'usually', 'never', 'finish', 'one', 'whole', 'burro', 'size', 'one', 'sitting', 'ate', 'put', 'good', 'mood', 'texted', 'sister', 'florida', 'good', 'service', 'great', 'super', 'friendly', 'food', 'fresh', 'made', 'order', 'glad', 'moved', 'would', 'never', 'experienced', 'today', 'stopped', 'little', 'food', 'truck', 'cause', 'obviously', 'hungry', 'typical', 'mexican', 'food', 'menu', 'noticed', 'bacon', 'wrapped', 'burro', 'decided', 'give', 'try', 'ground', 'beef', 'holy', 'f', 'k', 'one', 'best', 'damn', 'burrito', 'ever', 'hard', 'impress', 'mexican', 'food', 'day', 'even', 'wanna', 'right', 'review', 'keep', 'gem', 'secret', 'community', 'disservice', 'food', 'take', 'time', 'cook', 'rushing', 'sweet', 'little', 'old', 'abuela', 'cause', 'back', 'cooking', 'love', 'thanks', 'taco', 'stop', 'making', 'today', 'great', 'day', 'treat', 'east', 'side', 'tucson', 'two', 'sonoran', 'hot', 'dog', 'veg', 'meat', 'one', 'flavorful', 'jackfruit', 'birria', 'available', 'taco', 'burrito', 'taco', 'absolutely', 'delicious', 'best', 'prepared', 'jackfruit', 'ever', 'wish', 'ordered', 'plenty', 'vegan', 'option', 'available', 'looking', 'new', 'delicious', 'food', 'side', 'town', 'keto', 'burrito', 'amazing', 'net', 'carb', 'delicious', 'meat', 'better', 'food', 'truck', 'keto', 'friendly', 'really', 'excited', 'try', 'taco', 'stop', 'little', 'hard', 'get', 'time', 'actually', 'open', 'supposedly', 'open', 'monday', 'friday', 'time', 'hour', 'truck', 'actually', 'closed', 'today', 'ordered', 'jackfruit', 'taco', 'carne', 'asada', 'burrito', 'sonoran', 'hotdog', 'place', 'tucson', 'serve', 'jackfruit', 'vegetarian', 'vegan', 'option', 'stoked', 'actually', 'unfortunately', 'big', 'fan', 'spice', 'used', 'jackfruit', 'seemed', 'overpowering', 'probably', 'much', 'chili', 'powder', 'whatever', 'spice', 'probably', 'overpowering', 'accentuated', 'sweet', 'salsa', 'crema', 'taco', 'came', 'flour', 'tortilla', 'spiced', 'jackfruit', 'pico', 'de', 'gallo', 'avocado', 'slice', 'side', 'rice', 'bean', 'carne', 'asada', 'best', 'either', 'thought', 'bit', 'strange', 'came', 'cabbage', 'cheese', 'bean', 'hoping', 'really', 'good', 'work', 'though', 'help', 'meat', 'grilled', 'super', 'good', 'however', 'sonoran', 'hotdog', 'save', 'meal', 'although', 'bit', 'burnt', 'outside', 'fixing', 'everything', 'right', 'really', 'would', 'love', 'give', 'star', 'place', 'really', 'hoping', 'improvement', 'next', 'time', 'also', 'today', 'birria', 'would', 'great', 'try', 'next', 'time', 'well', 'anyways', 'take', 'taco', 'stop', 'hopefully', 'people', 'try', 'food', 'give', 'feedback', 'could', 'try', 'see', 'work', 'ordered', 'two', 'jackfruit', 'burrito', 'three', 'bean', 'cheese', 'burrito', 'kid', 'stuffed', 'delicious', 'ingredient', 'toasted', 'outside', 'delicious', 'definitely', 'making', 'primary', 'east', 'side', 'burrito', 'place', 'found', 'taco', 'truck', 'heading', 'back', 'hotel', 'rating', 'looked', 'good', 'stopped', 'disappointed', 'apprehensive', 'first', 'basic', 'looking', 'truck', 'small', 'number', 'rating', 'however', 'carne', 'asada', 'burrito', 'chicken', 'quesadilla', 'burrito', 'big', 'good', 'size', 'meat', 'tasty', 'chicken', 'quesadilla', 'best', 'seasoned', 'perfection', 'would', 'go', 'back', 'would', 'given', 'five', 'star', 'price', 'touch', 'high', 'little', 'salty', 'although', 'like', 'salty', 'wish', 'could', 'given', 'four', 'half', 'star', 'taco', 'truck', 'amazing', 'everyone', 'family', 'got', 'something', 'different', 'loved', 'bit', 'wait', 'usually', 'one', 'two', 'lady', 'working', 'well', 'worth', 'wait', 'delicious', 'vegan', 'option', 'really', 'enjoyed', 'jackfruit', 'street', 'taco', 'option', 'everyone', 'great', 'costumer', 'service', 'best', 'quesa', 'birria', 'taco', 'town', 'absolutely', 'delicious', 'worth', 'wait', 'patient', 'good', 'thing', 'take', 'time', 'excellent', 'partial', 'beef', 'burrito', 'ambiance', 'would', 'something', 'would', 'expect', 'poor', 'dusty', 'town', 'northern', 'mexico', 'super', 'cheap', 'metal', 'folding', 'table', 'cheap', 'metal', 'really', 'cheap', 'folding', 'chair', 'set', 'rear', 'back', 'taco', 'truck', 'really', 'loud', 'generator', 'running', 'irritating', 'carne', 'asada', 'taco', 'dry', 'must', 'cooked', 'many', 'hour', 'let', 'dry', 'flour', 'tortilla', 'thin', 'lone', 'per', 'taco', 'broke', 'open', 'picked', 'usually', 'street', 'taco', 'like', 'tortilla', 'awful', 'threw', 'garbage', 'belonged', 'order', 'side', 'rice', 'bean', 'total', 'wast', 'money', 'good', 'part', 'really', 'love', 'jackfruit', 'burrito', 'would', 'buy', 'one', 'eat', 'girlfriend', 'love', 'amount', 'vegan', 'option', 'available', 'super', 'tasty', 'tell', 'vegan', 'quesadilla', 'apart', 'normal', 'one', 'good', 'thank', 'much', 'vegan', 'option', 'hand', 'best', 'mexican', 'vegan', 'place', 'town', 'favorite', 'humongous', 'jackfruit', 'burrito', 'delicious', 'filling', 'bean', 'rice', 'tasty', 'love', 'guy', 'use', 'cabbage', 'instead', 'lettuce', 'burrito', 'salsa', 'spot', 'creama', 'die', 'work', 'butt', 'truck', 'friendly', 'miss', 'taco', 'truck', 'stopped', 'visiting', 'mount', 'lemmon', 'everything', 'delicious', 'especially', 'loved', 'birria', 'taco', 'perfectly', 'crispy', 'shell', 'tortilla', 'seemed', 'really', 'fresh', 'meat', 'flavorful', 'right', 'amount', 'cheese', 'highly', 'recommend', 'lady', 'running', 'truck', 'one', 'rude', 'people', 'ever', 'dealt', 'spoke', 'slowly', 'think', 'knew', 'much', 'english', 'even', 'still', 'rude', 'short', 'answer', 'question', 'acted', 'like', 'bothering', 'literally', 'made', 'feel', 'like', 'terrible', 'human', 'treated', 'customer', 'like', 'gold', 'terrible', 'people', 'even', 'worth', 'food', 'service', 'bad', 'military', 'even', 'cadre', 'ruthless', 'omg', 'veteran', 'vegan', 'believe', 'great', 'ordered', 'jackfruit', 'vegan', 'burrito', 'little', 'buck', 'sooooo', 'worth', 'tasty', 'literally', 'hold', 'title', 'burrito', 'say', 'alot', 'happy', 'finally', 'went', 'actually', 'bumped', 'owner', 'maybe', 'idk', 'one', 'day', 'safeway', 'produce', 'saw', 'looking', 'vegan', 'food', 'told', 'taco', 'stop', 'thankful', 'good', 'back', 'prob', 'way', 'much', 'haha', 'awesome', 'taco', 'worker', 'masked', 'customer', 'required', 'masked', 'wait', 'go', 'back', 'asada', 'ground', 'beef', 'chicken', 'came', 'cabbage', 'tomato', 'onion', 'cilantro', 'salsa', 'side', 'great', 'eating', 'surprisingly', 'good', 'food', 'unimpressive', 'looking', 'food', 'truck', 'way', 'location', 'enjoyed', 'carne', 'asada', 'taco', 'quesadilla', 'couple', 'ice', 'cold', 'agua', 'frescas', 'back', 'location', 'moved', 'recently', 'jackfruit', 'alone', 'make', 'must', 'stop', 'food', 'truck', 'even', 'cupcake', 'super', 'slow', 'time', 'promise', 'worth', 'wait', 'new', 'food', 'truck', 'great', 'food', 'courteous', 'staff', 'great', 'location', 'east', 'side', 'atspeedway', 'houghton', 'must', 'try']
Score: 2.65 --> ['name', 'la', 'chaiteria', 'category', 'mexican', 'taco', 'vegan', 'vegetarian', 'food', 'truck', 'food', 'restaurant', 'rating', 'review', 'hungry', 'friday', 'afternoon', 'lunch', 'looking', 'restaurant', 'driving', 'saw', 'new', 'place', 'dropped', 'ordered', 'al', 'pastor', 'taco', 'raja', 'taco', 'green', 'chile', 'mushrooom', 'cream', 'al', 'pastor', 'taste', 'authentic', 'oily', 'raja', 'tasteless', 'bland', 'horrible', 'wow', 'either', 'another', 'note', 'place', 'clean', 'tidy', 'stopped', 'today', 'pick', 'large', 'order', 'family', 'taco', 'night', 'everything', 'tasted', 'incredible', 'fresh', 'ordered', 'taco', 'al', 'pastor', 'mole', 'taco', 'definitely', 'back', 'happy', 'wendy', 'opened', 'cafe', 'closer', 'neck', 'wood', 'great', 'menu', 'item', 'featuring', 'best', 'vegetarian', 'food', 'cafe', 'vegetarian', 'love', 'magic', 'food', 'wendy', 'creates', 'potato', 'filled', 'taco', 'jackfruit', 'carnitas', 'go', 'wrong', 'happen', 'day', 'cashew', 'based', 'alfredo', 'gluten', 'free', 'pasta', 'menu', 'whoa', 'tastebud', 'love', 'forever', 'yessss', 'la', 'chaiteria', 'vegan', 'menu', 'regular', 'menu', 'also', 'make', 'vegan', 'dish', 'vegetarian', 'adding', 'cheese', 'jackfruit', 'flavorful', 'recommend', 'house', 'drink', 'orchata', 'good', 'turmeric', 'lemonade', 'jamaica', 'also', 'great', 'portion', 'big', 'food', 'worth', 'every', 'penny', 'staff', 'super', 'friendly', 'attentive', 'want', 'ensure', 'great', 'experience', 'big', 'fan', 'tumerico', 'spot', 'happy', 'location', 'tucson', 'saffron', 'latte', 'espresso', 'mesquite', 'latte', 'ropa', 'vieja', 'raja', 'taco', 'place', 'amazing', 'portion', 'good', 'size', 'taste', 'quality', 'ingredient', 'created', 'fun', 'artistic', 'space', 'enjoy', 'new', 'favorite', 'restaurant', 'amazing', 'customer', 'service', 'fast', 'service', 'best', 'food', 'tucson', 'place', 'amazing', 'compared', 'one', 'owned', 'company', 'one', 'feel', 'bigger', 'portion', 'needed', 'great', 'side', 'town', 'plus', 'much', 'closer', 'seeing', 'lost', 'vegan', 'burrito', 'side', 'town', 'definitely', 'make', 'definitely', 'would', 'recommend', 'al', 'pastor', 'taco', 'little', 'spicy', 'make', 'even', 'spicier', 'salsa', 'make', 'salsa', 'amazing', 'tad', 'pricey', 'side', 'compared', 'regular', 'mexican', 'food', 'place', 'around', 'vegan', 'healthy', 'non', 'vegan', 'mexican', 'food', 'right', 'point', 'price', 'come', 'disappointed', 'place', 'point', 'vegan', 'non', 'vegan', 'option', 'staff', 'absolutely', 'amazing', 'kind', 'helpful', 'create', 'fantastic', 'atmosphere', 'food', 'delicious', 'worth', 'try', 'normally', 'amazing', 'place', 'however', 'get', 'cuban', 'jackfruit', 'today', 'tried', 'jackfruit', 'pineapple', 'say', 'stream', 'taco', 'tiny', 'bit', 'jackfruit', 'sour', 'pineapple', 'cutting', 'sorry', 'next', 'time', 'stick', 'like', 'carne', 'con', 'chili', 'burro', 'one', 'best', 'rice', 'bean', 'also', 'really', 'good', 'miss', 'spot', 'best', 'vegan', 'mexican', 'food', 'town', 'support', 'local', 'woman', 'owner', 'finally', 'got', 'check', 'spinoff', 'tumerico', 'location', 'also', 'cute', 'little', 'market', 'food', 'snack', 'beverage', 'toiletry', 'desert', 'go', 'food', 'truck', 'outside', 'meat', 'dish', 'make', 'friendlier', 'wider', 'base', 'people', 'inside', 'vegan', 'vegetarian', 'menu', 'always', 'changing', 'always', 'go', 'tostados', 'yummy', 'combination', 'crunchy', 'savory', 'flavorful', 'bean', 'well', 'cooked', 'seasoned', 'food', 'tends', 'bit', 'oily', 'downside', 'also', 'tried', 'one', 'juice', 'pricy', 'healthy', 'balance', 'veggie', 'fruit', 'citrus', 'another', 'reason', 'check', 'place', 'amazing', 'mural', 'artwork', 'tucson', 'must', 'see', 'great', 'addition', 'tumerico', 'family', 'much', 'needed', 'boost', 'vegan', 'community', 'went', 'friend', 'try', 'something', 'new', 'liked', 'cafe', 'restaurant', 'going', 'coffee', 'good', 'got', 'horchata', 'latte', 'hot', 'lacking', 'flavor', 'cup', 'steaming', 'hot', 'coffee', 'lukewarm', 'meal', 'customer', 'got', 'look', 'great', 'though', 'also', 'friend', 'liked', 'mole', 'latte', 'complaint', 'latte', 'come', 'soy', 'milk', 'fantastic', 'place', 'vegan', 'meat', 'dish', 'bad', 'meal', 'time', 'went', 'hear', 'coffee', 'good', 'go', 'food', 'give', 'shot', 'glad', 'west', 'side', 'town', 'west', 'side', 'getting', 'great', 'addition', 'different', 'tumerico', 'great', 'salsa', 'bar', 'instead', 'salsa', 'topping', 'already', 'appearing', 'plate', 'great', 'drink', 'menu', 'coffee', 'mexican', 'drink', 'vegetarian', 'food', 'menu', 'fantastic', 'original', 'tumerico', 'store', 'buy', 'burrito', 'salsa', 'tamale', 'find', 'quince', 'homemade', 'chip', 'much', 'pandemic', 'also', 'offering', 'toilet', 'paper', 'hand', 'sanitizer', 'etc', 'whole', 'staff', 'friendly', 'feel', 'like', 'home', 'delicious', 'fresh', 'coffee', 'friendly', 'staff', 'added', 'meat', 'friendly', 'food', 'truck', 'able', 'serve', 'selection', 'guest', 'also', 'great', 'store', 'selection', 'bottled', 'drink', 'absolutely', 'love', 'getting', 'freshly', 'cut', 'coconut', 'everytime', 'stop', 'first', 'time', 'trying', 'place', 'got', 'takeout', 'called', 'order', 'staff', 'nice', 'cuban', 'burro', 'side', 'rice', 'bean', 'veggie', 'filling', 'delicious', 'definitely', 'go', 'back', 'try', 'food', 'absolutely', 'love', 'good', 'drink', 'staff', 'everyone', 'respectful', 'energy', 'welcoming', 'never', 'disappointed', 'coming', 'absolutely', 'love', 'absolutely', 'love', 'restaurant', 'gem', 'side', 'town', 'dish', 'packed', 'flavor', 'every', 'bite', 'portion', 'generous', 'price', 'fair', 'also', 'love', 'refrigerator', 'full', 'awesome', 'dessert', 'refreshing', 'drink', 'kombucha', 'tap', 'get', 'started', 'salsa', 'bar', 'gosh', 'welcoming', 'wonderful', 'restaurant', 'loyal', 'devotee', 'tumerico', 'someone', 'explained', 'u', 'la', 'chaiteria', 'tumerico', 'sister', 'restaurant', 'make', 'trip', 'lot', 'similar', 'vegan', 'option', 'find', 'tumerico', 'husband', 'delighted', 'find', 'la', 'chaiteria', 'option', 'meat', 'eater', 'omnivore', 'generally', 'enchilada', 'chile', 'relleno', 'delicious', 'portion', 'size', 'large', 'ended', 'taking', 'part', 'meal', 'home', 'got', 'full', 'finish', 'tried', 'turmeric', 'lemonade', 'delighted', 'good', 'tasted', 'staff', 'much', 'like', 'staff', 'tumerico', 'delightful', 'food', 'came', 'quickly', 'la', 'chaiteria', 'applying', 'liquor', 'license', 'sell', 'beer', 'wine', 'think', 'place', 'get', 'better', 'thought', 'adding', 'adult', 'beverage', 'meal', 'sound', 'even', 'amazing', 'folk', 'complained', 'thing', 'oily', 'experience', 'either', 'tumerico', 'folk', 'also', 'complained', 'price', 'la', 'chaiteria', 'source', 'majority', 'ingredient', 'organic', 'food', 'supply', 'organic', 'food', 'cost', 'money', 'also', 'think', 'quality', 'ingredient', 'reflected', 'taste', 'food', 'looking', 'fabulous', 'southwestern', 'food', 'la', 'chaiteria']

In [24]:
#Results 
semantic_results
# bm25_results
# hybrid_results

{'What are the best vegan taco shops?': [549,
  709,
  647,
  361,
  842,
  715,
  43,
  751,
  730,
  318],
 'Cheap sushi restuarants': [326, 905, 683, 459, 364, 242, 116, 854, 572, 765],
 'Romantic Italian dinner spots': [962,
  695,
  44,
  78,
  114,
  914,
  183,
  443,
  574,
  763],
 'Vegan restaurants': [228, 751, 144, 785, 175, 798, 436, 824, 281, 318],
 'Best date night food spots': [1,
  513,
  132,
  937,
  523,
  971,
  557,
  183,
  376,
  319],
 'Sweet treatsWhere can I get a sandwich?': [417,
  425,
  873,
  778,
  366,
  16,
  371,
  499,
  186,
  671],
 'Is there any inexpensive steak houses?': [256,
  769,
  386,
  651,
  366,
  207,
  145,
  593,
  279,
  253],
 'Coffee shops nearby': [608, 109, 685, 239, 465, 439, 697, 282, 700, 510]}

In [23]:
#view function for results in depth
def view(results, query):
    print(f'\nQuery: {query}\n')

    for rank,docid in enumerate(results[query],1):
        row = docs.iloc[docid]

        print(
            f'{rank}. {row["name"]} | '
            f'{row["categories"]} | ' 
            f'{row["stars"]}  (ID: {docid})')

In [24]:
def display_text(text):
    display(Markdown(f'{text}'))

def view_reviews(results,query, rank=1):
    print(f'\nReview for query: {query}')

    docid = results[query][rank-1] # indexed at 0
    row = docs.iloc[docid]

    print(f'Restaurant -- {row["name"]}\n'
        # f'{rank}. {row["text"]}'
    )
    display_text(row['text'])

In [27]:
#check out results 

view(semantic_results, queries[0])
view_reviews(semantic_results, queries[0], rank =2)

Query: What are the best vegan taco shops?

1. The Taco Shop Company | Restaurants, Fast Food, Mexican | 3.5  (ID: 549)
2. Taco Rico | Food Trucks, Food, Tacos, Restaurants, Fast Food, Mexican | 5.0  (ID: 709)
3. Taqueria Alamos | Tacos, Food Trucks, Food, Restaurants, Mexican | 4.5  (ID: 647)
4. Taco Stop | Caterers, Event Planning & Services, Food Trucks, Food, Restaurants, Mexican | 4.5  (ID: 361)
5. Del Taco | Fast Food, Mexican, Restaurants | 3.0  (ID: 842)
6. Tacos De Cabeza | Food, Food Trucks, Restaurants, Mexican | 4.5  (ID: 715)
7. Lonchos Street Tacos & Spirits | Hot Dogs, Nightlife, Sports Bars, Bars, Food Stands, Mexican, Restaurants | 4.0  (ID: 43)
8. La Chaiteria | Mexican, Tacos, Vegan, Vegetarian, Food Trucks, Food, Restaurants | 5.0  (ID: 751)
9. Alejandro's Tortilla Factory | Restaurants, Bakeries, Meat Shops, Specialty Food, Food, Mexican | 3.5  (ID: 730)
10. Lovin' Spoonfuls Vegan Restaurant | Restaurants, Gluten-Free, Vegetarian, Comfort Food, Vegan | 4.0  (ID: 318)

Review for query: What are the best vegan taco shops?
Restaurant -- Taco Rico

Absolutely delicious! Best Mexican truck in Tucson! Glad they are located on Ina because driving to the south sometimes is a drag. Why do I waste time writing a review if it's just going to not show up a few days after I write it? There have been many reviews deleted as well!

I'm sure it's not the owners of the business since I gave them a 5 star review, So I have to assume it's Yelp? Great tacos. Taco truck which specializes in just tacos. I ordered a chicken and carne asada (steak) taco which came with sliced radishes, grilled onions, cilantro, and their sauce. Tried the Pastor, Asada, and Cabeza tacos and they were delicious! The tortillas were excellent and the meat was fresh and very moist. Served with radishes, cucumbers and onions on the side which was a plus. I traveled from Oro Valley and I can say it was worth the trip and  will be back soon! This food truck is actually really good. I tried their asada, cabeza, pollo, and pastor tacos and they were all excellent. The pollo was super moist and the cabeza was not greasy. My wife is a carne asada connoisseur and liked the asada so that really tells you something. They are new from Cali which is probably why I liked them too. Don't forget to add cheese! Salsas are homemade and bomb too! Super good food, maybe best in town?

Nice people and fresh and clean food!

Homemade horchata was outstanding too!

Hopefully they move closer into town I would be there all the time! This was my first time at this taco truck. I'm so glad i stopped by on my way home. Its probably in the top 3 of the best tacos I've had in Tucson when it comes to carne asada and al pastor. They also have a red chili hot oil sauce that is amazing. For the lightweights out there beware, its HOT! But so dang flavorful. I'm definitely gonna be picking up some more tacos when I'm on that side of town again. They don't skimp on the meat either or their side/salsas. This place is legit.  Go support these great local food trucks. Especially when they have awesome prices.

RUBRIC FOR RELEVANCE
- 4) Perfect Match: Matches each constraint in a certain way lexically or semantically
- 3) Great Match:  Very relevant, just missing a singular detail
- 2) Decent Match: Missing some details, some correct outputs some incorrect mixed in
- 1) Poor Match: Lots of unnecessary results
- 0) 0 Match: Nothing is correct

In [34]:
# Grading labels function
qrels = {}
def label(results, query):

    qrels[query] = {}

    print(f'Label Query: {query}\n')

    for rank, docid in enumerate(results[query],1):
        row = docs.iloc[docid]

        #markdown
        display(Markdown(f""" 
                         ## Rank: {rank}: {row['name']} | ({row['stars']})
                         **Category: {row['categories']}
                         {row['text'][:5000]}
                         """)) #limit 5000
        rel = int(input("Relevance 0-4: "))
        qrels[query][docid] = rel

In [29]:
# merge to label together

def merge_results(*methods):
    return list(set(doc for m in methods for doc in m))

In [35]:
#Label for each method

for q in queries:
    combined = merge_results(
        bm25_results[q],
        semantic_results[q],
        hybrid_results[q]
    )

    temporary = {q:combined}

    label(temporary,q)

Label Query: What are the best vegan taco shops?

                         ## Rank: 1: Taco Bell | (3.0)
                         **Category: Restaurants, Fast Food, Tex-Mex, Mexican, Tacos, Breakfast & Brunch
                         My five star service goes out to Rhonda! She is always so happy and cheerful I love going through the drive thru she makes my day! There's nothing in this world I love more than a beef chalupa with fire sauce, or a Mexican pizza... with fire sauce. Imagine my disappointment, when time after time, I get home from a taco Bell drive thru and open up that beautiful brown bag full of wonder, only to find that there's no fire sauce. The drive thru attendant asks every time if I would like any sauce with my order. My response is and always has been, yes, fire please. I should make it a habit to double check, but when it's late, and I'm exhausted, and have a ton of stuff on my mind, I'm relying on my fire sauce to be there when I need it. I will continue to visit this store on a regular basis because I need my fix, but I cannot in good conscience give any more stars on this review based on my disappointment over the lack of attention to this important detail. This location has the best employees of any Taco Bell in town! They always have someone in the Drive Thru that's super energetic and sweet. And even when I go inside I'm ALWAYS met with nice employees. This is also the only location in town that's never messed up my order. A round of applause for the manager here, seriously. Went in & ordered a cheese quesadilla combo. Andrea, who took my order, had 5 star service. I received my meal in 2 minutes. Only bad thing was that the CHEESE quesadilla had some weird sauce on it. It was a little upsetting because I didn't eat my meal until I was already back at work. This is the best taco bell in town. The service is always friendly, quick and efficient whether you are in the drive thru or dining in. The food is consistently good and I always get plenty of sauce :-) If you want breakfast don't go. Actually don't go to this Taco Bell at all. They serve breakfast until 11am supposedly. Sat in the drive thru for 20 minutes to find out that they ran out of breakfast at 9:30 am! It is unbelievable how mismanaged this location is. Avoid it! On our way home from a camping trip, was actually trying to find a decent restaurant in the area with out door seating since we had our dog with us. Basically we ended up going through the drive through here.
So what can I add here for this location? Typical when you've been to one fast food restaurant, your experience is most likely the same everywhere else. No different here.
Food was OK
Time through the drive through was fast
Service was good
Lady at the cash register was very nice
So the experience was fine. Oh by the way, the new quesolupa sucks. Been there twice.  First time it was closed when it was supposed to be open, second time they had no ground beef... At a place known for its tacos.  No Bueno.  (Both visits were after 9pm - might have better luck when the night crew isn't there) Closest to my work, cheep fast food place.  Lady who took my order at the drive thru was pleasent, and took my order quickly.  I had my food within 3 minutes and it was made correctly. I came in here in the middle the night for a snack. I was not expecting to get such nice service from the person at the window her name is Crissy. I am vegan and my order needed to be made correctly. And it was made perfectly thanks to her making sure that my order was correct. Ok so this Taco Bell does most everything right. They have good customer service, nice ladies that work in the morning, and I love the new breakfast menu-- believe it or not. The thing that bugs me so bad is they do not give you enough sauce for anything that you purchase. Anyone that has ever eaten at taco Bell knows you need at the very least 2 or 3 packets of sauce per item. Well this location just does not like to give out sauce. You would think it came out of the paycheck of the employee who gives it to you. I just want sauce :) My husband and I specifically come to this Taco Bell because every time they get our order right and they don't skimp on the ingredients. Most of the Taco Bells we go to usually put barely any cheese on anything and their food was just ok. This Taco Bell has not done us wrong yet. Admittedly it's Taco Bell but I am basing this review on the location itself compared to other locations I have been to. You know what you are getting into if you decide to go to any fast food place. This last trip to Taco Bell was much improved. They improved their speed of service and customer service. They also served breakfast until 11am! This Taco Bell... all I can say is ‍. Asked for no cheese on my tacos and look what I get? Also we ordered two soft tacos and these guys give us 1. Smh ‍ This Taco Bell has the best workers! They always have someone at the Register who is friendly and gracious. And even when I eat inside I'm met with polite staff. This is also the only taco bell in town that's never messed up my drink order. They deserve an award for the management here, seriously. Seriously the worst food presentation, driveline Skim

                         ## Rank: 2: HUB Ice Cream Factory | (4.0)
                         **Category: Restaurants, Food, Juice Bars & Smoothies, Ice Cream & Frozen Yogurt
                         Fantastic ice cream.  I had the cafe du monde coffee flavor and my wife enjoyed the banana Nutella variety.   Only comment is the service could be a bit friendlier.  Pouty college students serving gourmet ice cream when it is $4 a dish is unbecoming. Average, Average, Average.

Nothing special about this place. It is a bit pricy (It's downtown tucson)
This place is Average; but there are much better ice cream places near by. Delicious! The lady at the counter was very sweet about letting me try many of the flavors. I had the peanut butter and also a s'mores scoop. The base is excellent and definitely the product of great milk. I loved loved both of my flavors and will come back again. We went across the street for dessert after dinner a Pizzeria Bianco.  They were busy but service was fast.  The ice cream was delicious.  Too pricey for regular consumption though, otherwise they'd have five stars. Delicious! Good service, great & unique flavors. Super fun place to stop in for a treat downtown. HUB ice cream is pretty awesome!  Their flavors are often rich and delicious, if not a bit overly sweet (but hey, it's ice cream!).  I personally am quite upset their coffee and donut flavor, which is one of the best ice cream flavors I have ever encountered, is not a staple on the menu.  Last visit I had the blueberry cheesecake that was like an elevated DQ blizzard (I mean that in the best of ways).  HUB is similar to Salt & Straw in my opinion, but lacks the originality and out of the box flavors.  I'd like to see HUB try some more adventurous flavor combos and definitely need to have coffee and donut always available. Great ice cream!! Cute ice cream shop!! You have to try it!!

I highly recommend this place even if you aren't in the area. Make a special trip if you want good old-fashioned ice cream.  With a spin on the flavors... Yum!!! Really tasty! My group tried the Oatmeal cookie dough (finally a cookie dough variety that's not chocolate chip!), pumpkin pie, and the bourbon almond brittle. We'd recommend all of them! The Hub Ice cream from both locations are too amazing, I go in at least twice a week for either homemade chocolate tacos, or just to get a 4 oz to satisfy my cravings! Only one vegan choice here, the "vegan strawberry".  It's good.  Not fancy but good.  Not happy about all the cruelty based dairy here but glad they have a vegan flavor to show people you don't need cruelty for dessert.  If anything special is going on downtown, plan on waiting in a long line. This place was pretty good. I wish the ice cream was little bit harder... too soft in my opinion. Their flavors were good, different, yet unique. No room for seating. Listing key ingredients would be nice. One sample didn't taste of coconut but the serving was full of it. Literally the best ice cream I've ever had!
I sampled about 5 flavors and loved them all!!

My top picks are Hokey Pokey & the Oatmeal Cookie Dough!

Good prices and a great atmosphere too. Would highly recommend They're ice cream is wonderful!! I'd rate it the 'Best in Tucson.' My favorites are Salted Caramel and Bourbon Almond Brittle.  They give you samples of any and all flavors.  You can get Hub ice cream at this location as well as The Hub restaurant. I prefer the restaurant location. They give you more!! And at the restaurant location, the one scoop is really two scoops and they'll let you get two flavors in that 'one' scoop. I usually like to come here after taking my kids to the children's museum for a few hours.  It's a nice mid-afternoon treat/snack, and a short walking distance from the museum.

Flavors are unconventional and definitely not lacking in flavor.  I can't say I adore the ice cream in texture.  There are other "artisanal" and "gourmet" ice cream places that I'd choose over The HUB, but we do come here because of the convenience to where we are beforehand.  Price I suppose is decent and comparable to shops of this sort.  And my son, who has some food allergies, loves their sorbets.  So that alone is worth the visit for me.

One thing that does bother me is the way the menu of flavors is displayed.  While mirrors add to the decor and is a neat idea, writing the flavors on a surface that also reflects images from opposing walls makes it hard to read from where you're standing, and that's right in front of the ice cream case.  And not to mention, they do it in white ink.  Talk about annoying. Great menu and food selection. We sat at the bar where they had a very good selection of local beers. My steak salad was good. The staff is young and friendly. Modern looking place with outside seating. Here's the deal:

HUB definitely makes the most delicious, local, small-batch ice cream in Tucson (sorry Isabella's, but you can't top HUB's Bourbon Almond Brittle!).
But even for HUB ice cream, this place is a bit over hyped. I really, really like this ice cream, but it's not really worth waiting 20 + minutes in line on a Friday or Saturday night. Furthermore, the

                         ## Rank: 3: Taqueria Alamos | (4.5)
                         **Category: Tacos, Food Trucks, Food, Restaurants, Mexican
                         Around the area of my new place of employment there are a gazillion food trucks that are not even on the Yelp radar yet. This is one of them.

As you can see from my photo of their menu, they have only a few items. I ordered the tacos barbacoa as I wasn't feeling adventurous for any of the other items. The quality is good. Tortillas are fresh. Plenty on their condiments cart to spruce up your tacos however you want. I just wasn't that impressed with the barbacoa. It was OK, but nothing to get excited about for me. This place should have an average higher than three stars. The reason to come here is to get the Gordita VIP, the chicharron mixed tacos, and/or Quesadilla con Asiento (which I believe is a quesadilla with meat drippings, but am not positive. It's just really good).

The chicharrones here are made by the owner of the truck. It isn't the type of meat that you see in a grocery store. It's flavorful, crunchy and got some good fat on it. The condiments compliment the food perfectly. The portion size is ample. The horchata is on point. This place is a diamond in the rough. Do yourself a favor and get a mixture of any of the above three things. So glad they opened back up.
Love the fresh tortillas, and the salsa
With everything going in they had everything pre-packaged onion, cabbage, limes and salsa.
Quick easy, to go orders so good. Can't wait to go back! Catered a business lunch at our office for people from all over the US.  They were going back for seconds and thirds! That never happens!  People are still coming up to me the next day, thanking me for ordering lunch from Taqueria Alamos!  Very professional set-up, everyone was so impressed.  Thank you so much! This is the cleanest food truck in Tucson the tacos are well portioned then other tacos out there , the tortitas are freshly made by hand, the menus simple and easy to read, my favorite menu item is there VIP with Barbacoa/ shredded beef horchata is made from scratch as well as the Jamaica/ Hibiscus drink service is fast the staff are friendly one of the things that I noticed was the size of the tacos and the VIP'S for what they cost it is affordable I will usually get the Cabesa & Chicaron tacos they are the best! Beans are good as well! All the food that I have had is very yummy Loved the roadside taco truck experience! When in Tucson, you have to have Mexican food and this place as a hit amongst me and my colleagues, some of them Arizona natives. The customer service is also top notch because they come take your order asap and food is delivered fast and fresh. The menu is pretty simple but hits the mark. I got the carne asada tacos and barbacoa caramello (which is a quesadilla). I also got a horchata which was an excellent choice since i was piling on that red and verde sauce. I enjoyed the barbacoa caramello but the hit amongst the group were the carne asada tacos. Soooo good. The toppings and salsas are on the side for you to pile on as much as you like. Couldnt beat the food for the price point and the experience. Yum! Good food NO PROBLEMS WITH FOOD.

Now, closed almost more than open.  Everytime I'm hungry and want to stop by always close so I just go elsewhere now.

Why sit out in the hot heat for the same price as an air conditioned restaurant?

 Not sure why closed half the week and early. Nothing fancy except the taste! I love taco trucks, but they are often hit or miss. This place was a definite hit. Most importantly, great food. I had the Barbacoa and Carne Asada tacos. They were excellent. My daughter had a cheese quesadilla and as a picky kid who has turned her nose up at many a quesadilla, she gobbled it up as soon as it cooled down enough. But what makes this truck stand out is the friendly service and cleanliness. Everything is organized and they don't make you pay until you finish your meal. This lends to a more relaxed feel to many other food trucks where the person taking your order is just in a hurry to get your money and move on to the next order. Very happy I found it and I will be back! Unless they decided to move the food truck for the holidays this place may be out of business. There's just something about food truck tacos that really hits it home for me. I didn't even realize that there were so many taco options - from beef cheek to pork crackling. Even better, the House Special has some of the most bomb quesadillas and corn cakes packed with pork drippings.

They just added online ordering, so you actually get 20% off your first order through their website taqueriaalamos.com

With so many condiment options and decent portions, I will be back to check out this hidden gem. Besides the food being delicious. The customer service here is great. The girls are very attentive and nice.

                         ## Rank: 4: Red Captain Coffee Company | (5.0)
                         **Category: Food Trucks, Food, Coffee & Tea
                         If you want to find service with a smile, amazing coffee, and the most delicious vegan pastries here it is, folks! The original draw to this place was the fact that Houldens Rise Above pastries are served here but as a big coffee fan as well, I was not dissatisfied whatsoever. The flavor was amazing and the staff were courteous and sweet. Great addition to the Tucson coffee scene! Hands down, one of the best coffee stands in town! The owners- Ramses and Julia are the sweetest and really get to know their customers (it's literally like going to see family when you visit Red Captain). All their coffee drinks are amazing. They also carry local bakery- Houlden's Rise Above. I also highly recommend getting one of their housemade breakfast burritos (soyrizo for the non-meat eaters). The Jalapeño pastry is also fantastic!

Their hours are Monday- Saturday 7AM- 1PM.

They are located at Hem and Her Bridal- 4004 N. Stone Ave. Red Captain has moved to just a hair north of Stone & Roger (east side of Stone).  Still same great coffee and friendly service. This coffee truck is amazing! I got an Americano and my wife got the Guatemalan hot coffee with a homemade poptart. They were absolutely amazing! There is also a large sitting area that is beautifully landscaped with a small fountain. We will definitely be coming back here As a big coffee drinker (and a picky one at that), I rejoice anytime a new coffee shop opens in Tucson! Red Captain Coffee Company opened in March 2021, but as I usually head out on lunchtime for an afternoon pick me up perk, I kept missing the truck.

Open Monday's through Saturday's, 7AM to 1PM they are perfect for the on the way to work boost your day java. I went with my go-to order, a dirty chai latte with almond milk. The staff were SUPER kind and helpful when I walked up, wearing masks, and very appreciative for the business. My drink was delicious, and I don't say that lightly.

I am so glad to have another coffee shop near the north side of Tucson, and will definitely be back, highly recommend checking them out and tagging them on social media. YAY FOR MORE LOCAL COFFEE OPTIONS! Coffee is so tasty and the crew is so nice! I like my coffee with lots of cream and sugar and they were super nice about it even though some people may feel that ruins the coffee when I ask for that ‍ but they said all that matters is that you get it the way you like it  they are parking in front a wedding store that has a beautiful courtyard with seating and it's just a really beautiful landscape and a hidden gem!  The only bummer is that they close at 1 pm but otherwise amazing and local & latinx owned Love love love ! Employees are so kind and welcoming love supporting them ! The drinks are great and I especially enjoyed my soyrizo burrito it was delicious. I had first heard about Red Captain Coffee through some foodie friends of mine. The Mr and I went to their first location and have been hooked ever since!

I love their new location at Hem & Her Bridal on Stone (cross street is Roger Rd.). Better parking, more shade, and more seating options. Owners Ramses and Julia are super sweet and we've developed sort of a friendship (I'm not just a customer sort of thing). They take the time to actually get to know their customers and it's great. It's one of the main reasons why I love shopping/eating local.

My go-to drink is their Iced Mocha. They also offer vegan pastries via local favorite- Houlden's Rise Above.

Check them out! Wow! This place is so super neat! First it has a nice garden to enjoy your coffee in that is outside a wedding shop with beautiful dresses in the window to check out! The service is wonderful and the owners are who serve you and they are very passionate about what they serve! I live the energy and the coffee!! We had a Cortado, Berrychico, and cold brew coffee....delightful!! The morning bun to start your day is great!! I encourage you to try it all!!

Wi-fi, beautiful outside seating and Latin-owned!  Yellow brick roasting company is locally sourced. Support local business!!! What a cute spot by the Tucson Mall! I loved the quality of their cold brew and breakfast burritos.  They offer both chorizo and soyrizo options for their breakfast burritos. Annnd they carry the amazing vegan pastries by Houlden's Rise Above. The best coffee in town. Beautiful coffee cart. Everything on the menu is awesome but I believe it's the best latte in town. Really nice and genuine people. Great tasting and very strong coffee. Excellent value Such a cute little coffee trailer.
They always have interesting lattes and coffee drinks as well as a few rotating non-coffee drinks. They pull really good espresso shots too and the baked good selection always entices me.

The owners are so friendly and welcoming, too.
The location has plenty of parking and is in front of Hem and Her Bridal shop.

                         ## Rank: 5: Ensenada Street Food | (4.5)
                         **Category: Mexican, Tacos, Restaurants, Food Trucks, Food
                         Saw an article on Tucson.com about this place and decided to come on a Saturday night. Employees were all really welcoming and were helpful with picking tacos. I had an asada and a pastor taco. Food came out quick and they have a salsa bar. I recommend the avocado sauce and some limes. My boyfriend had the hot salsa and said it was really good too! The pastor isn't like a Sonoran pastor, it's less sweet and REALLY good! They had just sold out of the vegan tacos but I'll be back to try those. Really enjoyed it! Thanks ladies! This place is freaking yummy! Get the Tacos al Pastor! Very different flavor profile ... I really don't like leaving bad reviews, but I have to be honest. The waitress was sweet and the spot is cute, loved the sayings on the walls.  The food was not great,  well not for my Mexican palate. I was disappointed with the carne asada,  it was not grilled as accustomed,  it tasted pan cooked and reheated. The birria was ok not delicious.  The only thing somewhat decent was the adobada. I really wanted to like this place, I did. The environment was so cute and welcoming I wasn't expecting to be waited on either but they brought us our food quick and were so nice. The food was amazing and I'm definitely going back! Everything here is amazing! From the service to the food! Would definitely recommend la frida and anything else on the menu! Rachel was awesome! Definitely coming back!! This place doesn't look like too much, but the food is amazing. This place is a small business trying to get off the ground. I've been twice and both times it's been great. The dishes run between $3 to 8. I believe this is Baja region Mexican food? I would advise parking across the street as there isn't a lot of parking near the restaurant. Don't miss out on this place, it's excellent. This place has the BEST tacos. There are so many authentic Mexican restaurants in Tucson, but this one is by far my favorite. I came here looking for a quick bite to eat and asked Rachel about her favorites on the menu. I got the taco special and was not disappointed. 10/10 would recommend to anyone who needs something quick but unforgettable. I've been here twice. They are a women owned and operated business and their food is so amazing. The tortillas are the best in the city and their food delicious. They will totally walk you through the menu. You can eat there or take to go. I cannot stop thinking of how good their food is, especially their el pastor. Go there now! It was sooo good! And the service was great too  we will definitely be coming back! We had rojitos and al pastor tacos. Amazing I've been meaning to try birria tacos for the longest but could never find a place to go. I saw this place had a lot of good reviews so my mother and I decided to try it out. The customer service was amazing. The girl taking orders had no problem explaining what each item was and helping us pick what to eat. I also like how you can pick if you want certain things on your tacos like onions, cilantro & cheese. The food is made to order and super fresh so we ate it in the car to get the full experience! Definitely will be stopping by any chance I get for more! We had never tried this food truck/restaurant before this weekend. We pulled in to the small parking lot, got out to peruse the menu, and ordered our the items. I was excited to see that they had a keto option which was lower in carbs. We ordered two different tacos on corn tortillas and my keto one. It seems there might be a more efficient way of getting orders taken, paid, and delivered than what they did, but I realize that covid19 has made everyone do things differently than they normally would. Since we weren't in any hurry, it was ok that it took quite awhile before we actually had our food in hand. My husband enjoyed his tacos, but I really enjoyed my cheese shell shrimp taco. Several pieces of shrimp topped with cabbage, cilantro, and pick de Gallo all in a thick fried cheese shell. The mild sauce on the side was still too spicy for my tastes, so I ate it without. It was a fun, new adventure for us. Ensenada never disappoints! The best tasting birria in Tucson! Yes The best, and I've tried a lot of birria spots here in Tucson. The cheesy tacos (rojitos) are full of flavor crispy cheesy goodness, dipped in the broth for sure. First time trying the Sopa, which is pretty much noodles and their birria, comes with two mini rojitos, full of flavor and character it's a must for sure. Loaded with birria and noodles, it's a great deal! This is our go to for the birria! You are  gonna be waiting a cool 20 minutes but that is nothing for great tasting food! Enjoyed this cool indoor /outdoor covered restaurant Baja style menu, decor & vibe in tucson not far downtown , u of az , south , west & central tucson on park s of 22nd street .
Catalina was so accommodating & proud of this female & family owned restaurant.
Big menu with something for everyone!
I chose the vegan pastor tacos , piled high on

                         ## Rank: 6: Donut Bar Tucson | (4.5)
                         **Category: Donuts, Food, Wine Bars, Nightlife, Bars, Beer Bar
                         Boyfriend decided to get some treats today and I just so happen to want to try out the new donut place. We ordered the grilled cheese, Monte Cristo, mud pie, creme brulee, and the Homer Simpson. Surprisingly we agreed we like the mud pie the best. Just creamy chocolate pudding topped off with cookie crumble on a savory donut. Was just so delicious! Second is definitely the grilled cheese. Definitely dip it in the sriracha mayo.

 It cuts through the ooey gooey cheese and good ole glazed donut. Homer is a classic pink frosted donut while the creme brulee is more on the play of texture with the caramelized sugar on top. Monte Cristo was yummy, but boyfriend thought that it was filled with too much jam and brie. Overall it's a great place to try unique donuts if you happen to be nearby and hungry, or just wanting to eat something new. This was my first visit to Donut Bar after drooling over their pictures on Instagram and it was so worth the wait! They had a huge variety, and their donuts are good sized and taste amazing! Our fam favs were the monte cristo, maple bacon, and  the red velvet! Friendly service and easy location to access for quick pickup! Try them out! First visit to Donut Bar. Impressed with
The concept. I ordered the Cake Better and Maple Bourbon. Only tried Cake Better, saving maple for tomorrow. So impressed I went back later and bought a shirt to advertise. Friendly staff and nice atmosphere! These poor three; Michael, Brad and Mary. For Father's Day, we came in for a special treat for my husband. Brad, Michael and Mary were the only three manning the place as people had called out. They were super flustered and were trying their damndest to answer the phones, curbside pickup, pre orders, door dash and those coming into the shop. For being a holiday, especially for men who LOVE donuts, I believe they did a stellar job. Not to mention the mud pie, the Father's Day donut and the ultimate donut - the monte Cristo we're freaking amazing!!! These three deserve kudos, especially for apologizing every second they got. We will absolutely come back for seconds and thirds!!! Best donuts around! You guys, seriously great donuts. Last night a few friends and myself were walking back to the parking garage from dinner and noticed Donut Bar. I haven't been  downtown in a couple of months and didn't know it had opened. We decided to go in and we're helped right away and the staff was wonderful answering any questioned we had. We each got something different, a total of four donuts and we all tried each other's. Every donut we had was perfection. Perfectly fluffy, perfectly topped, perfected cooked. I've been to a few local donut shops in town and have never been impressed with the selection or quality. I'm so happy to say this place had PERFECT donuts.

I might have to start coming back downtown more often. Walked in on a Monday morning, and the girl behind the counter who helped me choose my donuts was so chipper! Which is not usually expected for a Monday morning! I kept changing my mind with which donuts I wanted and the girl was still super sweet! The donuts are a whole experience, from being in the shop and seeing all the decor and beautiful pastries, to the tastes and smells of the donuts! Great quality of ingredients ! Best donuts in town! I would eat them all the time if they had the same nutritional value as fruits and vegetables!! The Homer donut is a must. When we want a really good donut, this is the place to go.  It can be a little tricky when it comes to parking because it's downtown. But worth it even if you have to go for a little walk!  really good donuts!! Went inside store and was welcomed. Didn't have to wait since no one was in the store just yet. Donuts were amazing! I was recommended a few and would definitely go back for more! Best and biggest donuts ever! I had a maple bar which was more like a log! Huge and deeeeelicious! Personally loved the bar tender and the idea behind the donut and the beer. I wanted coffee but when I arrived to the location and realized it was beer and donuts forget the coffee. The donuts were huge!!! The beer was right. Display amazing and the location super clean. The staff was attentive. We were greeted immediately and there was only one lady in front of us. We over heard that she had told them it was her daughter's birthday and wanted something with sprinkles. So they were joking around and this donut expert really went in the back to add specialized sprinkles to the donut for her daughters birthday. That donut definitely made that girls day! Then when it was our turn they made their way down the donuts to describe each one. Like presenting a series of art. Yumminess upon yumminess!! We couldn't ignore the suggestions. I loved the whole experience. We took our donuts home because social distancing (which is fine by me). It was delicious but it was also just a really great experience thanks to the men behind the counter. Donut Bar is a good spot for a tas

                         ## Rank: 7: The Taco Shop Company | (3.5)
                         **Category: Restaurants, Fast Food, Mexican
                         Good, fast, and inexpensive. I like get the veggie burrito and my husband loves the bacon, egg, and cheese burritos (available all the time, not just for breakfast). The place has no ambiance so we get it to go and we're happy. Got a carne asada burrito.  The avocado used in it had not been fresh, and significantly took away from the other ingredients.  Did not finish the whole thing. I could for sure see myself visit this place after bar. The taco shop is a pretty decent place for late nights. l always get the rolled taquitos and it always satisfies. It's good food especially when you're drunk. Overall can't complain with a 24/7 pretty good tasting taco spot Just driving through the city and happened upon The Taco Shop. Great fish tacos and shrimp burrito at a great price. This tiny spot serves yummy, authentic dishes from the counter. For a while, I was down on the Taco Shop.  I had tried the carnitas and was unimpressed: the pork was lean, flavorless, and on the dry side.  I had tried the carne asada and was similarly unimpressed: the meat was similarly flavorless and a bit on the salty side (I'm not sure, but I think I might have detected a hint of pork somewhere in there, so if you can't eat pigs you might want to ask).  But after hearing some friends rave about the place, I decided to give it another shot.  And actually, I'm really glad I did.

The star of the show here is the Al Pastor burrito.  The marinated pork is tender and full of flavor, the ingredients are presented in perfect proportions, and they even put in some fresh, chopped cilantro that really sets the burrito apart.  They do their al pastor saucy, which I'm not accustomed to, but it works really well here.  I dare say this is the tastiest al pastor in this part of town.  Do yourself a favor and try it!

Also delicious is the green chili burrito.  The pork itself is reasonably good, but what really makes it awesome is that they douse the entire burrito in a heavy helping of green chili sauce, cheese and lettuce -- they call it "wet style"; I call it yummy.  Slightly off-putting, though, was the practice of sticking the burrito in the microwave in its styrofoam container to melt the cheese.  Now, some polystyrenes are supposedly microwave-safe, so it's probably not like they're clearly and systematically jeopardizing their customers' health, but I still took notice.  I've ordered the (less exciting) red chili burrito and they did the same thing, so I guess it's just a wet-style thing.  If microwaving styrofoam makes you uncomfortable, then you should probably stay away from the wet-style offerings.

Aside from these menu items, I've been neither blown away nor disgusted by anything I've tried at the Taco Shop.  But those two things were really delicious.  I would still probably recommend staying away from the carne asada and carnitas, but overall, I've been converted: the Taco Shop is quite alright! Super basic eatery.  Three watery, anemic salsas at the salsa bar, guac very thin, seems like it comes out of a pourable vessel, no chunks resembling avocado, tomato, onion, etc. I had chicken tacos and the meat was little, hard, tough  nuggets of what tasted like meat that had sat all day in a warmer. Several UA students in the place.  It is quite old and decrepit and run down, big hole in the plaster/wall in the booth we sat in. Appears clean, but in need of overhaul.  Friendly clerk.  In a town with so many stellar places to get tacos, I would not return to this one.  It was just "meh".  Maybe if you are in serious need of food after being out all night, but not if you are looking for a really luscious, fresh, quality taco. I've gone here way more times than I care to admit. Let's face it, a cheese quesadilla from here goes perfect any time of day. 2pm or 2am.  Tastes amazing!!!

I used to live on the street right behind this shop and was heart broken when I had to move away. There was nothing better than having my cab driver drop me off here after a Friday night on 4th and then walking home with the ultimate prize: Cheese Quesadilla, Horchata and extra limes. THE place to eat late night. As the business name suggests, this is where you go when you want some drunken tacos. Get the fried fish, they're real good. Carne asada too I recommend.

Burritos are the best value cheaper than Betos or Nicos, and better quality.

My biggest gripe with this place is the wait, on a weekend night it is just ridiculous. Get the steak and egg burrito for breakfast and the shrimp burrito for lunch. We haven't been able to try anything else b/c these two are so good! Don't expect ambience or stellar service, but good food. Delicious burritos. But what really sets this establishment apart from all of the other 24-hour taco stands is its salsa. Its delicious, and you can load up with as much as you please to use for your other meals at home. Truly hits the spot, especially late-night. The Arizona burrito was delicious!!! One of the best burritos I've ever ha

                         ## Rank: 8: Lonchos Street Tacos & Spirits | (4.0)
                         **Category: Hot Dogs, Nightlife, Sports Bars, Bars, Food Stands, Mexican, Restaurants
                         Just YES!!!! The place is clean, the food was bomb.com, the staff was friendly,  and the environment was on point. Glad we stopped in and we will definitely be back. Well Done. So thought I would give Lonchos/Tio Wills another try. Bad decision. Ordered two shredded beef tacos. Go home with them and they are 90% potato's and 10% beef. Far cry from a shredded beef taco. Don't know which I am more upset about, the terrible quality of food or the fact that they lie about being Tio Wills just a new name to keep people confused. This is a COVID rich establishment. A roll of paper towels are placed on your table. You take what you want. When done it is placed on another table. You can't disinfect a full roll of towels. Done with this place very bad. Stopped in for lunch and was pleasantly surprised.
Highly recommend this establishment for either a Asada Street Taco or tostada. Green salsa is fantastic. Had their Birria torta and it was delicious. Girls up front were nice and everything was perfect when they brought out our food. Will definitely go back. Yummy stuff!!!  Have a taco and a beer nice!!!  Food is great!  We will be back.

Must try.  You won't be disappointed! We just bought a house in the area and was looking for places to eat. This is a brand new spot and has so much potential post covid. It's so clean and sleek here. The food was fresh and my margarita was yummy. We'll definitely be back! Lonchos surprised us given the "okay" reviews...

My bf & I would come into Tio Wills occasionally (prior owners) for the games & drinks etc. Then it was "okay".

Now, the food & service at Lonchos are much, much better. *Must try Lonchos tacos-carnitas! Happy hour  (everyday 2-7). The quality of service is markedly improved. We sincerely appreciate the attention we receive from the owner who works most days and her daughter, the pride they take in their business and ingredients shows in your drinks & food.

The place isn't fancy place, but absolutely perfect for getting out for great affordable meals, a casual, friendly environment, big screens with games on, & local chill vibe.

Love this place, our new happy hour fav! Service was super slow. It took 15 minutes to get 1 drink and we were the only two there. $26 got us 1 small taco, a shallow bowl of pozole and two drinks. There were 3 girls working and 1 cook. But really only one girl did any work. The cook is a good cook. The girls didn't work they just watched videos on a phone while one had a alcoholic drink. Our food took 20 minutes the drink came with the food. The Posole was reheated. Three stars are for the food tasting good. -3 for service. I feel bad for the girl who did all the work. The cooks a good cook but Portions are small. Really nice and authentic taqueria in Rita ranch. Great food, super reasonable.  Folks are really nice and a great place to watch sporting events.  Well stocked bar and decent selection of the expected plus local brews. Definitely a new go- to for me. We came to vail to see the Sahuaro buttes and decided to eat here. GREAT customer service. It's a little bit pricey but food was good.  They do charge for chips and salsa. Guacamole is really good as well as salsa. Super nice ladies :) very clean atmosphere DELICIOUS i got the fish tacos and they are in my top favorites! My dad tried all three meats and he liked it too! Not only that we had a wonderful conversation with the owner in the parking lot! I don't have to drive into town for fish tacos anymore! : ) Just had the tacos dorados. Disappointed. I wanted to like this restaurant, but it did not want me to come back, so I can't like it. There was just a bit of shredded beef in two of the tacos (some potatoes) the third taco had no meat, and a small amount of potatoes. I ate mostly fried corn tortillas!  It is inexpensive, but id rather pay more for a better meal.
I hope they get better. Absolutely delicious. Just tried them out for the first time. Got our food to-go. The birria tacos are amazing (I got the soup on the side to dip), and so are the asada tacos. My husband got a chipilon hot dog and his reaction said it all, so good. Atmosphere was clean and relaxing, very sport bar style. We will be back to eat in soon and try out the drinks. Really good tacos and salsas! Great value for the price as well. I ordered an asada and carnitas taco, both on flour, and was pleasantly surprised with how much meat was on each. We ordered a plain hotdog for my toddler, which was bacon wrapped and had a really delicious bun. My husband ordered the Super papas with carne asada meat- they were definitely loaded! Fries were not my style, but he enjoyed them.
The food took a little while to come out, but we were the first order on Saturday and they're new, so I won't hold that against them. We asked if they had happy hour and were told "I think so, during the week." We will definitely be back to follow up on that given the large, full bar.
Note *it is order at the counter * they do offer mi

                         ## Rank: 9: Le Cave's Bakery & Donuts | (4.0)
                         **Category: Restaurants, Donuts, Vegan, Bakeries, Food, Custom Cakes
                         Their donuts are super yummy. We tried the ones with powdered sugar and the maple glazed ones. My impression is that they are a bit more fluffy and lighter than other donuts.

We paid something like $8 for a dozen. It was not very busy when we went there and we didn't have to wait (it was on a weekday at about 8am).

Also, most of the donuts are vegan. Ask the employees if you are not sure which ones are vegan. Need to put the hole back in the donuts there doughy in the middle. Still just as tasty though. Nice building and layout. This is the one of Tucson's best bakeries in my opinion!  Their donuts and coffee cakes are simply amazing!  I haven't been by in a while but think I'll be dropping in this week! Unbelievably good doughnuts.  I've had a total of 5 types of doughnuts and one cookie over 3 visits and everything has been great, but the standouts are the maple raised (my favorite by far) and the mango filled.  The maple raised is really what keeps bringing me back; the texture is unique (fluffy, almost like a non-greasy sopapilla) and the the glaze is amazing.  The mango filling is like an especially good marmalade--seriously, if they canned it, I would buy it.  And when was the last time you had a jelly doughnut that could be described as "deliciously tart"? The stanky dank...liked more than Alvernon and Estrella...but you pay a premium for the nasty. Their empanadas are dirty af. After the Molina's closed the original location on 6th Avenue, the new owners did what Le Cave's always aspired to be. The donuts are the same as they were, in a great new location. They're learning how to work all new equipment and technology but they'll get it dialed in. Got there first today because I wanted to get and go and the 45 minute wait was worth it. Delicious. Hope they expand their selection and add cake donuts but what they had was awesome. This location will thrive and the owners will be very successful. Thanks for bringing Le Cave's back!! OMG - on National Doughnut Day - or on any day. One dozen glazed doughnuts - heaven in a box. Sure glad Le Cave's is still doing their usual great job. This is at least my fifth decade going there. Everything I've tried from here is delicious. I would especially recommend the maple glazed donut. I was on a dairy-free kick for awhile and wondered if I'd ever be able to eat donuts again. I found Le Cave's and realized not only could I have donuts, but better donuts than most. I highly recommend it to people with food restrictions or dairy allergies.

Now ignore what I just wrote. Le Cave's makes delicious delicious donuts that just happen to be vegan. I highly recommend it to people who love donuts. So everyone, obviously. I keep hearing these are the best doughnuts in Tucson. They're good, but I'm not sure about "best." I got a regular glazed donut, which was pretty good, and a mango filled one. I'd never had a mango jelly donut before, so that was pretty good. Good variety overall, more than a standard donut place. No prices visible on anything other than the donuts, so I couldn't calculate before buying. I wasn't offered a free glazed donut even though I made a point of saying that it was my first time there. I purchased a dozen cookies, 5 donuts, an empanada, and two creme horns.

Their donuts are no different than anyone else's except for using veggie oil (and that's only if you don't want anything creme or custard-filled, of course). But, hey, I'm not vegan; however, I do know that deep fat frying in vegetable oil is not necessarily better for you than frying in lard. I'm a fan of cake donuts myself, which, of course you won't find at Le Cave's.

The cookies were good, like pecan sandies with flaked almonds, but since they were not even 2" across, $6/doz. seems a bit pricey to me.

The cream horns tasted like they'd been made and then refrigerated several times before I bought them. I would be extremely surprised if they told me they make them fresh every day. I've had fantastic cream horns, and these were not. They left an unpleasant aftertaste.

The empanada was highly disappointing -- all crust, little fruit, and, while the crust was flaky, it had no flavor (vegetable oil, remember, but with an egg wash, so not vegan friendly).

Also, I was disappointed at having nothing but a park bench to sit on. It seems it wouldn't take that much more effort to put in three or four cafe tables and put on a pot of coffee. I would have stayed there with my friend, and I would have spent more for the coffee. There was plenty of room for tables and, in fact, tables would be preferable to large, empty pastry cases.

. Hands down, the BEST donuts in all of Tucson!! Beats Krispy Kreme's donuts all day! Friendly welcoming atmosphere and always smells so good when you walk through the front door! Be sure to buy a dozen (4 maple, 4 glazed, and 4 chocolate), cause their donuts are so delicious, I bet you can't eat just one! Wow, amazing cakes, pies, donuts, and a veritable smorgasbord of

                         ## Rank: 10: Geronimos Revenge | (4.5)
                         **Category: Food, Food Trucks
                         Great food, they have a tucson spin on the famous cubano sandwich, absolutely delicious! The owner/cook is a kind, smart young man that has a good taste in food and customer service It just doesn't get any fresher or better!
Great Vegan options I tried the beef burrito and my husband tried the beef torta. Mmm where to start the meat was flavorless, the tortilla break as soon as I open the burrito, it taste like chorizo, and they told me that it was carne asada, and guess what? It wasn't carne asada, it was "carne desebrada (like beef for tamales)". I know Mexican food I lived all my life in Mexico so I know how a burrito should taste, go to filibertos, los betos, Jason's, other place but for a burro and a torta don't eat here. I think that what pissed more it that they sold the meat as carne asada and it taste like freaking chorizo, not even adobada o Al pastor, definitely I not recommend this place and I will not coming back. Thank God, I finally ran into this food truck! I've heard nothing but good things and had been wanting to try them but didn't go out of my way. Lucky me, they were outside of Danny's Baboquicari (chill dive bar) for the Christmas party. I split a burrito with the hubs and quickly thought, I'm gonna need some mac and cheese after this, but I was too full so maybe next time! The burrito was bomb, the meat was full of flavor and it was juicy. Holy crap, such amazing food!! I stopped here and picked up a veggie burrito that changed my life... it was so freaking good.  My guy had the pork tacos and he said they were dee-licious!! Customers for life... will be back later for some food to go! I was drunk downtown in a super shitty mood. My friend stops at this food truck. All I wanted to do was go home when I noticed vegan substitute for cheese. Being lactose free I became intrigued and asked if they used Diaya products or something else. They told me they fucking make their own house cheeze using sautéed onions,cashews and a ton of other dank shit. I dropped $10 on some cheese fries easy. My bank account is hurting right now but I 100% do not regret getting those fries let me tell you what. I'm following this truck even if it's set up on the other side of town idc. I hope this business grows and I wish the best for the dude who checked me out. Great customer service! Tried the this food truck for the first time tonight. We had a Chicken Burrito (6.30) - The chicken was tender and seasoned right. It was made with whole pinto beans rice, shredded cabbage and salsa. The cabbage was shredded nice and thin giving just the right amount of crunch. Also tried a vegan taco with calabacitas, pickled onion, cabbage, and perfectly piquant salsa. It was delicious.
The tacos are pretty tiny. They were 3.50 each or 3/$9. But the flavor was so big I didn't care. Can't wait to go back and try some different items. Everything was super yummy, fresh, & fast. I'm not quite sure how to define the category of food offered here. While it may provide a large Mexican menu, it offers some uncharacteristic treats like macaroni and cheese and garlic noodles. After randomly running across this truck in front of Che's on a Thursday night, we ordered the burrito and garlic noodles. We both settled on pork upon the recommendation of the worker. The garlic noodles were well garnished with cilantro, lettuce, and a spicy sauce. I can't say much of my boyfriend's burrito aside from the fact that as soon as he bit into it, he was raving about how good it was. The size of his burrito was a bit smaller than expected, given that I had a decent amount of noodles for my dish. The absolute treat to both of these dishes was, indeed, the pork. It wasn't overly greasy or dry and delightfully seasoned. I'm not sure what the other protein options taste like, but can almost guarantee that the experience was so positive, I'd have a hard time ordering something aside from the pork.

If I were to go again (which is likely), I would definitely order the pork burrito. Prices are a bit standard for a food truck at $7 an entree, but the service was pleasant, wait wasn't bad, and the food was thoroughly enjoyable. For something we ran across by chance, I couldn't be more pleasantly surprised! Geronimo's Revenge has been around only for about two months, but I can already see it being a hit if more people were to stumble upon it. Geronimo's Revenge has an awesome selection to suit all tastes! The vegan Mac n cheese was heavenly with cilantro and pico de gallo on top. The cashew based sauce and crumble is robust and flavorful. Calabacitas street tacos are affordable and delicious! Fresh good, friendly staff willing to explain any menu items. The truck is great too, with the skate-chalk-board menu gives it a really cool feeling. Awesome food truck, we'll definitely seek it out in the future. Thank you Geronimo's Revenge! Great food... burrito was awesome, avoid the overpriced taco. Noodle dish was AMAZING!!! Seriously the best food in Tucson! I'

                         ## Rank: 11: Lovin' Spoonfuls Vegan Restaurant | (4.0)
                         **Category: Restaurants, Gluten-Free, Vegetarian, Comfort Food, Vegan
                         Great vegetarian restaurant in tucson.  My favorite veggie burgers in tucson. My bestie (the vegan) made me go here and... it was awesome! I have been here a number of times with her and with others. Now I am not going to become a vegan (even if this is my bestie's personal goal in life) but I do enjoy the food here! I have had the chicken nuggets with ranch, ravioli, meatloaf, stroganoff, and classic burger and they have all been really good! Servers are excellent and the atmosphere is laid back. This is a great place for breakfast, lunch, and dinner! I am not vegetarian or vegan, but I enjoy the food and if it's available, will gladly partake. My sister prefers vegetarian food, so while she was in town, we had lunch at Lovin' Spoonfuls.

I ordered the Adzuki Burger and thought it was fine. I felt it needed a little additional seasoning and something crunchy. It did have a crispy outside, so that was nice. The coleslaw could have been crunchier. The portions were good and the service was quick and friendly.

We all enjoyed our meals and left feeling satisfied ... but I can't say I'm a fan just yet. I would like to preface my bad review with this statement: We have only been to this restaurant once. We are vegetarians and were very excited to try out this vegan restaurant- we had high hopes! We had the spring rolls, the beer-battered brat bites and the southwest veggie burger. The spring rolls were very mushy and slimy on the inside, not to mention the fact that they were FILLED with OIL! They tasted identical to the spring rolls you get from the frozen food section of any grocery store. The brat bites were good- not something I would usually even try, but the name sounded interesting. The burger was extremely lackluster. This place was said to have to best veggie burger in Tucson... If so, this is a sad situation for Tucson. It is unnecessary to have everything so drenched in oil- this is supposed to be a healthy and wholesome restaurant... I saw nothing healthy or wholesome about it. This is not a place for real vegetarians or vegans.
On a more positive not: I didn't try any, but the desserts looked amazing. Perhaps that is the one thing Lovin' Spoonfuls gets right. stopped here while in Tucson, ordered the southwestern burger and the deli club both were excellent.
the guacamole was fresh and spicy and the black bean burger patty taste very good. Absolutely amazing!! Staff very friendly and remember me every time :) HIGHLY recommended Nice to have a vegetarian option in town.  You order and pay at the counter and then wait for someone to bring the food.  This makes it seem more like fast food, but the wait time is pretty substantial.  The atmosphere is a random assortment of old people-ish junk and it's kind of dark in there.  The menu has a huge variety.  However,  I haven't had anything amazing.  The veggie burger was just a veggie burger.  The Thai-style curry was watery.  I'm not lovin' the idea of going back there. I just found this gem. The first day I went, I had lunch and dinner there.  This place is a must if you like vege food. Food is very good as usual.  Service on Sunday mornings lately by two young guys has been excellent. So so food....kinda bland no zing or spiciness...kinda pricey...if you're gonna make it bland lower the prices....the ambience is bland also...kinda like eating in a vegan morgue.  I've been to much better places in different parts of the US.  Guru's cafe in Provo Utah comes to mind...what a cool place....very adventurous ambience and foods....same prices but much more interesting food. This is restaurant is a gem!!  What a wonderful experience.  The ambiance is very nice.  Lovely design in a clean and comforting space.  My starter salad had the best dressing ever!!  The Thai green curry with tofu definitely hit the spot.  I had this over whole wheat penne.  This kept my healthy commitment while exciting my taste buds.  I'll definitely be back in the next couple days.  :) So good!! Like, take a bite and your eyes roll back in your head kind of good! The best vegan food in Arizona! If I could give higher than 5 stars, I would! Fair disclaimer: I'm definitely a fan of meat, and that has a lot to do with how I feel about Lovin' Spoonfuls.  But I should also mention that I am a fan of vegetarian and vegan cooking, and given the great reviews I've heard about this place, I came to Lovin' Spoonfuls filled with eager anticipation.

First, the good: the owner is just so incredibly warm, friendly, and approachable.  She clearly loves what she's doing, and I think that's awesome.  Also I live with a vegan, and I have a number of friends who don't eat animals to varying degrees (sometimes chicken's okay; sometimes the line is at fish; sometimes as long as it's not meat we're in the clear).  These are people who have grown accustomed to opening menus at restaurants and having a very few options to choose from.  Seeing their eyes light up when they look at an extensive menu from whic

                         ## Rank: 12: Taco Rico | (5.0)
                         **Category: Food Trucks, Food, Tacos, Restaurants, Fast Food, Mexican
                         Absolutely delicious! Best Mexican truck in Tucson! Glad they are located on Ina because driving to the south sometimes is a drag. Why do I waste time writing a review if it's just going to not show up a few days after I write it? There have been many reviews deleted as well!

I'm sure it's not the owners of the business since I gave them a 5 star review, So I have to assume it's Yelp? Great tacos. Taco truck which specializes in just tacos. I ordered a chicken and carne asada (steak) taco which came with sliced radishes, grilled onions, cilantro, and their sauce. Tried the Pastor, Asada, and Cabeza tacos and they were delicious! The tortillas were excellent and the meat was fresh and very moist. Served with radishes, cucumbers and onions on the side which was a plus. I traveled from Oro Valley and I can say it was worth the trip and  will be back soon! This food truck is actually really good. I tried their asada, cabeza, pollo, and pastor tacos and they were all excellent. The pollo was super moist and the cabeza was not greasy. My wife is a carne asada connoisseur and liked the asada so that really tells you something. They are new from Cali which is probably why I liked them too. Don't forget to add cheese! Salsas are homemade and bomb too! Super good food, maybe best in town?

Nice people and fresh and clean food!

Homemade horchata was outstanding too!

Hopefully they move closer into town I would be there all the time! This was my first time at this taco truck. I'm so glad i stopped by on my way home. Its probably in the top 3 of the best tacos I've had in Tucson when it comes to carne asada and al pastor. They also have a red chili hot oil sauce that is amazing. For the lightweights out there beware, its HOT! But so dang flavorful. I'm definitely gonna be picking up some more tacos when I'm on that side of town again. They don't skimp on the meat either or their side/salsas. This place is legit.  Go support these great local food trucks. Especially when they have awesome prices.

                         ## Rank: 13: Del Taco | (3.0)
                         **Category: Fast Food, Mexican, Restaurants
                         Quick and friendly service. Always walk from my house for a quick lunch. Make sure to try there caramel cheesecake bites. Yumskies to the max. Would recommend for anyone trying not tl spend a lot. Yes, I should not be eating Del Taco when there are so many authentic restaurants near by. Okay, now that that is out of the way, they make decent food but have trouble hearing my order correctly. It's a bit irritating, perhaps they should invest in a new speaker We go here multiple times for the big fat chicken tacos on soft pita bread and sometimes the deluxe taco salads. The low stars is for the workers and inconsistencies. Sometimes they forget the beans on the side when asking for them to be off of the salad and sometimes they forget a fork! Their water isn't filtered and it always is in a tiny cup. The most annoying thing is having to repeat what you want to the workers in the drive thru speaker. Every time I order the big fat chicken tacos, they say, "you want soft chicken taco"? Learn better English and turn up your volume or clean out your ears! I've tried other things like breakfast sandwiches and fish tacos but they were all yuck. Paying $1.69 for a small drink is ridiculous and this lady forgot the drink while I sat at the window tonight and she took an order with someone at the counter, so I asked if she'd up it to a large and she said I ordered a small. She got soda on the top and asked for a napkin and she gave to me and closed the window. How rude. I never get a call or anything when I leave feedback. Jerks. Too bad those items taste so good and we drive across town just to get them since there are no other locations in mid town or east. EEK is right! I haven't been here for a while but am so disappointed as many others now. I went past here and planned on getting the taco salad for it's famous fluffy, crunchy shell. NOPE, I went through drive thru and the guy there said the total was $5 and change for this and 3 flatbread chicken tacos?? He repeated this total again at the window and I questioned it and he said, I meant $15(and change). I thought the bag for the taco salad was strangely small. No shell, just a few chips beside the lettuce and blah on the salad plus 3 sliced browning avocados. Yuk. I pulled around to the parking lot and went in. I asked for 2 flatbread steak tacos instead and may not return to Del Taco again unless the salad is made the same way as before again. I explained to the guy that took my order I wasn't going to eat that crap and he said they are getting this reaction from a lot of people. He graciously gave me the steak flatbreads instead. They were only .01 difference in price too getting 2 of those at 2.79+tax. I like this Del Taco, for under $5 bucks I get a bean tostada & a turkey taco. I ask for extra lettuce, it's always crisp and fresh. My favorite little cheapie tacos plus they have ground turkey, and they do not charge for extra lettuce. It's good here Ugh I really don't know why I chose to eat here, tacos were a bust! They were soggy and the sour cream looked curdled! The only thing they had going for them was the cheese fries! I stopped by for the first time. I got one of their cheese burgers with fries and oh my! Best burger I've had in a long time! I'll be coming back soon! definitely recommend their burgers! I admit it, I love Del Taco's taco salads. My rating is for the food and service we've received when they are actually open. My husband works nights and Del Taco is on his way home from work. For over 6 months they have been closed whenever he's tried to get an order there. Their signs say 24 hours, the website says 24 hours, you call and they say they never close. Not true. They are not open after around 2:00 am anymore. I emailed corporate several times and got no response. I'm not sure what is going on with this place, but they have lost consistent customers in us. I know that emails to corporate are usually forwarded to the owner or district manager. Apparently they don't care that this location has changed its hours without notifying the patrons or changing the signs or website. Too bad. Del Taco, it was good knowin' you. The food is the worst you ever had but at 60 cents a burrito.... also they are open 24/7. Even though their hours and prices are great I still can't give them more than 1 star because the food they serve is a disgrace to Mexican food. we stopped through the drive thru today and the only problem is no response when we got to the speaker. We ordered the big fat chicken and steak tacos(on flatbread) and cheesy potato poppers with the jalapeno. we always get a hamburger for each of our 3 dogs. they seemed dry but they are for them. our food was delicious. we haven't been there for a very long time since we live on the other side of town, but were driving downtown today. Just came back from drive-through, ordered steak and potato burritos. And I found some potatoes and a bunch of bacon when I got home. How incompetent do you have to be

                         ## Rank: 14: Tacos De Cabeza | (4.5)
                         **Category: Food, Food Trucks, Restaurants, Mexican
                         No complains about the food is excellent. My complain is how the place looks they never clean up the yard looks ugly. This place is extraordinary. Best "cabeza" tacos in Tucson...hands down. When I go I usually take 7 "tacos de cabeza" (beef head) tacos, a "bichi" (beef stew w/onions & cilantro) and a Coca- Cola. When eating "tacos de cabeza" there is no shame in drinking a mexican Coca-Cola before noon Fantastic delicious tacos and broth! I always order cheek tacos and broth, while my husband orders cabeza and tongue tacos. Filling lunch for two of us NEVER costs more than $12. Best tacos in Tucson. I come here every weekend with my family.  I recommend one sesos tacos in your order and the jugo bichi(beef stew ) This is an amazing taco place. Very casual but great street tacos. It's cash only and there are no options for vegetarian options but if you are a carnivore you should definitely try it! These tacos are the best I've ever had! I go to the stand on 6th and Grant after school during the week and always get cabeza and cachete :)The staff is helpful and kind because I don't speak Spanish and it's hard to communicate sometimes. lol Definitely recommend! First day in Tucson, and we accidentally went into this parking lot. When we realized it was a food truck with tons of white tents with seating, we knew we had to stop and try some aa part of our first food in Tucson. No menu immediately visible, but decided to order the cabeza since it seemed to be their specialty based on their name. Waitress spoke limited English, so it was a bit tough for us since neither my sister nor I speak Spanish and were having difficulty asking about other meats.

When our tacos came out, it was on a delicious corn tortilla with some of the best meat I have had in a taco. Super cheap too. I think my horchata, which was in a bottle, cost more and the two tacos I got lolll. Do note this is all outdoor seating since it's a food truck, so if it is hot (and when is it not hot in AZ?) you will definitely be sweating quickly, and the car extremely hot without a sun shade.

I definitely need to go back, and even daydream about these tacos now when I get the munchies! Got cheek, head, roof for mouth and tongue tacos. Little disappointed that they ran out of eye, lip and brain. Taco was great, flavor on the mild side, good for early of the day bite. Price is good and cash only. The best taco cabezas in Tucson! My son and I make it our  mission to sample every beef and pork cabezas we discover in Tucson. The flavor of Taco Cabezas is nothing short of a miracle of flavor seved up on a tortilla. A depth of flavor and spices without the heavy grease sometimes associated with this particular epicurean delight. While you're there, try the broth, which I take home to have in the freezer for those midnight cravings. Be adventurous and try a mixed meat cabezas with a blend of headmeats. Prepared so expertly, you'll experience exquisite beef flavor, without bizarre textures usually associated with head meat.

A true jewel of what Tucson cuisine has to offer like no other.

Oh, for those less adventurous, they offer standard selections you'd expect to see at a mexican food tuck. Best home style tacos if you're missing home, I would give them five stars however I get different quality depending on when I go but overall still great. My girlfriend was really craving tacos de cabeza the past few days. So I finally found a place that serves good ones here in town. This is a basic, plastic tables with a tarp covering it food truck, but do not let that fool you! This place knows what they are going. You still get table service, and a waitress to take your order. They are super super fast, like no joke fast! If you are looking for authentic tacos, THIS IS YOUR PLACE!!!! Super fast and friendly even though it was super busy. My tacos de cabeza, lengua and vichi tasted super good. They are a bit small so order about 2 extra. We ordered 9 tacos, 2 vichis and 2 sodas and our total was under 20$ This place is super busy on the weekends so be prepare to wait. I can't say enough good things about Tacos de Cabeza. These guys have the best Cabeza I've ever eaten in Arizona or even in Mexico. They have very reasonable prices, a great and authentic selection of both Cabeza and other more typical Mexican food, and a great space to eat under the shade at their stand. The staff are very nice (even to me as a pasty white gringo who doesn't speak Spanish but loves amazing Mexican food) and always are accommodating when ordering.

Any time you order the Cabeza to go, you'll get a large stack of good quality corn tortillas, some fairly spicy red and more citrusy green salsas and a big bag of limes to accentuate the flavor of the delicious meat. Both the broth and the cachete (cheek) tacos have my full and unconditional support. You cannot go wrong here, and if you've never tried cabeza for fear of a strange texture, you don't have anything to worry about here. Just do

                         ## Rank: 15: Alejandro's Tortilla Factory | (3.5)
                         **Category: Restaurants, Bakeries, Meat Shops, Specialty Food, Food, Mexican
                         Stopped in for a few tacos on the way to the airport and will definitely be back.
Noticed they had 6 different types of tamales as well as what seemed to be a full menu of typical items. I'll go back to check out the tamales.
I didn't recognize one of the taco offerings and asked - it was shredded beef and that's what I had. I doubt there is any better shredded beef taco - but taco fans know the best one is the one in your hand. As I said, I'll def go back.
Interesting to note: you can buy your carne at the meat counter and they'll spice and grill it for you for free. (at least that's how I interpreted the painted sign outside the store and might have seen another mention of this.)
Another interesting thing: the tables are stainless steel which is easy to keep clean. And easy to see that it is clean. They were. As well, I saw an inspector in the kitchen taking temperature measurements. And it appears they have excellent ratings from the health dept. which was easy to see as the kitchen is open. So big thumbs up and will re-rate when I've had more food there.
BTW - you gotta get their hot dog buns to take home. This is the best Carne Asada on the planet. The home made Tortillas are excellent as well.  Lived here 6 years and just found this place after trying many many carnecerias in town.  It is way on the other side of town, and I go anyways.

Just get it.  There is nothing else that comes close.  And it is incredibly cheap!  Cook over charcoal if you can and eat while hot.  We do this often, and whenever company comes in from out of town - nothing but 5 star reviews here.

It is the best kept secret in town. I will be back OFTEN. What a secret treasure trove. Made a quick stop for some buns and tortillas. Didn't realize that they run an entire market with other local items.
Store was filled with the fresh bakery smells as they were reloading the racks with buns and empanadas   Awesome.
Good selection of Mexican cheeses and the meat counter had fresh made carne seca. Can't wait to try that. Staff was extremely helpful.
If you want to prepare any Mexican specialties this is the place to go for authentic ingredients. Tamale time, tamale time, tamale time!!!

Alejandro's helps me keep my family tradition going by being the go-to place to get my corn ground to make green corn tamales. I came in Sunday morning, grabbed a wheeled cart and loaded it with my tub of white field corn kernels and it was quickly whisked away from me. Not even 10 minutes later my tub was returned with 66 lbs of soft, silky smooth ground corn! You pay by the pound for grinding your corn and I can't imagine a better spent $19.80. It would have taken all day for me to grind that much corn and the consistency would NEVER be like Alejandro's does it.

Customer service can be hit or miss and sometimes it's hard to get the cashier's attention when she's busy talking to the security guard but it's all good. Once they turn their attention to you, it's all smiles.

They've got some seriously good eats and treats at Alejandro's too. Not only can you order up some hot, delicious Mexican food from the window inside the store but there is a meat/deli counter too. Huge chicharróns and cooked meats are kept hot and ready to be purchased and so tasty. Alejandro's is a decent sized Mexican market where you'll find tortillas, laundry soap, comals, molcajetes, spices, tons of Mexican candy, fresh vegetables and chiles, beverages and so much more.

While waiting for the corn to be ground we perused the aisles, got some steaming, hot rojo menudo to take home and picked up a delicious tamarindo covered "candy" apple. Good stuff! I've never been to the actual store in Tuscon, but I buy these tortillas all the time and I LOVE THEM!!!!!!!  I live in the Phoenix area and when it's time to buy tortillas, I look for these every time!!!  I hate buying other brands, they're that good. Not every store sells them unfortunately. They taste homemade and traditional, not like those mass produced thick pita looking tortillas Mission makes...These are the real deal! :)  Keep up the great work guys! You see their tortillas at all the major grocery stores here in Tucson. If you have had a Sonoran Dog anywhere in town, whether a brick and mortar restaurant or a food truck, you have probably had their buns. Alejandro's is everywhere. So you should go to the source of the "everywhere" and try them out.

I occasionally like to make my own Sonoran Dogs so I go to the source that everyone else does: Alejandro's Tortilla Factory. I get a bag of their buns, usually a bag or two of their tortillas (which I find to be among the best I've ever tasted), and in their smallish grocery section, get a can of pinto beans for the Sonoran Dogs as well as their salsa fresca. I even got a donut there. It was very good!

I haven't tried their in-house cafe yet. It looks tempting. Prices are right and the menu looks good.

Service is friendly. Nice family-run business feel.

Check out this T

                         ## Rank: 16: Taco Stop | (4.5)
                         **Category: Caterers, Event Planning & Services, Food Trucks, Food, Restaurants, Mexican
                         Excellent tacos. Prices were reasonable for the quality and quantity  I received. I hope they are around on my next visit to Tuscon. Wanted to know what the hype was all about and tried the jackfruit burro. Mind you I am not a vegan nor vegetarian, I just wanted to try it. I also actually HATE jackfruit, having an Asian family, you'd think I'd love it but no. I'm not a big fan of those kind of fruits (durian, jackfruit, lychee, etc.)

BUT I think I'll be eating jackfruit burros from here for a long, long time because it was marinaded in something so good, I felt like I had the best burro so far in my life. It was soooo big (and I usually never finish one whole burro that size in one sitting), and I ate it ALL. It put me in a good mood and I texted my sister in Florida about it. It was that good.

Service was great too! Super friendly and the food is fresh and made to order. I'm so glad I moved here or I would have never experienced this. Today I stopped by this little food truck cause I was obviously hungry. Typical Mexican food menu but I noticed the bacon wrapped Burro. Decided to give it a try with the ground beef and HOLY F$@K!!! One of the best damn burritos I've ever had!! And it's hard to impress me with Mexican food these days. I don't even wanna right a review so I can keep this gem a secret but I'd be doing the community a disservice if I didn't. The food takes time to cook, so don't be out there rushing that sweet little old abuela, cause she's back there cooking with love. Thanks Taco stop for making today a great day :) This is such a treat for the east side of Tucson. We had two Sonoran hot dogs (a veg and a meat one) and they were flavorful. They had their jackfruit birria available as tacos or burritos. I had the taco and it was absolutely delicious. Best prepared jackfruit I've ever had. I only wish I had ordered more. Plenty of vegan options available for those who are looking for new, delicious food on this side of town. Keto burrito Amazing!! 4 net carb, delicious meats. better food truck I have been. #keto friendly I've been really excited to try Taco Stop but it was a little hard to get here at a time they're actually open. Supposedly, they're open Monday to Friday 10am to 7pm but most times during these hours the truck is actually closed until today. We ordered the jackfruit tacos, carne asada burrito, and Sonoran hotdog. There are very few places in Tucson that serve jackfruit as the vegetarian/vegan option so I was stoked they actually had them. Unfortunately, I'm not a big fan of the spices they used for the jackfruit. It seemed to be overpowering probably with having too much chili powder or whatever spice it was. It probably wouldn't have been overpowering if it had been accentuated with a sweet salsa or crema but it wasn't. The tacos were $3 each came with 2 flour tortillas, the spiced jackfruit, pico de gallo, an avocado slice and a side of rice and beans. The carne asada wasn't the best either, I thought it was a bit strange that it came with cabbage, cheese, and beans but was hoping for it to be really good. It didn't work though and didn't help that the meat wasn't grilled super good. However, the Sonoran hotdog did save the meal. Although it was a bit burnt on the outside the fixings and everything on it was just right. I really would love to give more stars to this place so I'm really hoping for more improvement next time. Also, today, they didn't have their birria which would be great to try next time as well. Anyways, that's my take on Taco Stop. Hopefully, more people try their food, give them feedback so they could try to see what works. We ordered two jackfruit burritos and three bean and cheese burritos for the kids. They were stuffed with delicious ingredients and toasted on the outside. So delicious! We are definitely making this our primary east side burrito place from now on. Found this taco truck while heading back to my hotel, the rating looked good so I stopped. I wasn't disappointed. I was apprehensive at first because it was a basic looking truck, and they only had a small number of ratings. However, I had a carne asada burrito and a chicken quesadilla. The burrito big a good size and the meat was very tasty. The chicken in the quesadilla was the best. It was seasoned to perfection. I would go back. I would have given it a five-star, but the price was a touch high, and it was a little salty (although, I like salty). I wish I could have given four and a half stars... This taco truck amazing, everyone in my family got something different and LOVED IT. It is a bit of a wait as there is usually only one or two ladies working. WELL WORTH THE WAIT. they have delicious vegan options too, I really enjoyed the jackfruit street tacos. An option for everyone. Great costumer service. Best quesa Birria tacos in town Absolutely delicious and worth the wait.  Be patient.  Good things take time.  It's all excellent, but I'm partial to the beef burritos. The ambiance would

                         ## Rank: 17: Presta | (4.5)
                         **Category: Coffee Roasteries, Coffee & Tea, Food
                         Nice strong coffee with an inviting atmosphere. We tried the Coco Rosie and the Honey Cinnamon Latte. Both were great, and not too sweet. You'll only find one size for iced drinks, but because of the flavor profile, it's a coffee you'll drink more slowly to enjoy the flavors.

There was some pastries that looked appetizing, but I didn't get around to trying them. The inside of the shop is nice, currently no indoor seating but it looks like there are spots for it in the future. There is outdoor covered patio seating available, looks like a nice place to hangout when it's not too hot outside. Baristas were great when I came here on Sunday morning.

For anyone that's been to Austin, the coffee reminds of Thunderbirds which is definitely a compliment. Very sterile vibe. Not sure it was as appealing as other places. Upon walking in felt a little pretentious. HOWEVER that said, the coffee and pastries are fire!!! The morning bun gooey thing is stellar out of this world. Also had the vegan pop tart and that was delicious too. Bought a lb of beans. Will see how that goes. I'm sure it won't disappoint. I'm a fan of Presta based on their other locations, but I have to say this new spot might be my new favorite for them!

The converted garage is a charming, quirky space that feels very relaxed and welcoming, and it's nice and serene despite its proximity to 4th Ave. and downtown. I really like their patio -- well spaced tables! -- and the way it's sort of tucked into a crook of the building.

Today I got an iced Coco Rosie, which I highly recommend! It's a coconut caramel latte with rosewater and vanilla, and a lovely sprinkling of coconut flakes on the top! Yum!

My most typical orders are chai (usually with oat milk) or an iced coffee, which are both standard but very well done here.

Lots of love for Presta! Love to start my mornings off at Presta!
The new location is a beautiful site to see and in a great location. The baristas are super knowledgeable & you can tell they not only enjoy it but truly care for each guest who walks in their doors!

Today we enjoyed a vanilla iced latte w/oat milk and a regular oat milk iced latte! Best coffee in town and will always recommend to all coffee lovers!

Today we also decided to take the Costa Rica roast home with us! "Earthy & citrusy that melts in your mouth" after one of my friends took a sip of it! Right on the spot, loved the roast, everyone give it a try! Yummy lattes and homemade pastry options! We got a "pop tart" and a scone. They have Oatmilk, Whole milk and Half and Half only, so milk options are a bit limited, but drinks are delicious! It's a cute place and they have some nice sounding drinks, but I got a plain drip coffee that had gone sour from sitting too long, and my friends latte tasted the same way. Won't be returning It's no secret that I love Presta Coffee Roasters. We order a giant bag every month for our morning coffee at home. Their new shop on 9th is awesome- it's airy, bright and offers covered patio seating. The menu is the same as the Mercado and 1st avenue locations, which I appreciate. We buy their PSI espresso roast for our morning brew. For an afternoon pick me up, their oat milk matcha latte ia my favorite! Curtis, owner of Presta, has really cultivated an awesome team. I feel so welcomed at all three stores. Now, we just need a Presta on the North side :)

Other things to note for locals:
Presta offers free home deliveries in the Tucson Area on bags of coffee with code "local."

You can place your order online via their website. I didn't have any coffee here so I cannot speak to the options or prices. I stopped in because a local vegan pastry maker drops off her goods off and I had to try one. I got her bear claw and it was delicious! The staff was friendly and the place was packed. It reminded me of a chic New York style coffee shop. I loved the outside patio. The inside was a bit small but cozy. If I was a big coffee drinker I would definitely frequent this place. Blair and her team always make my morning when I come in for coffee. I'm a bit of a coffee snob and the Pride and care that these people have in service and coffee keeps me coming back. I drive past three coffee places to get my coffee here. Presta Coffee Roasters has opened their third and newest location, in this iconic 100 year old building that was once home to a gas station in the 1920's!

There currently is no indoor seating available due to COVID, but plenty of fun outdoor spots, and they make it easy to order and go (like I did!).

Pastries are all made by the local vegan baker, Hannah Houlden (@houldens.riseabove on Instagram)! This spot definitely has the charm I've come to know from Presta, and the staff was as helpful and friendly as they could possibly be! I'll definitely be back, and am so glad to see another amazing spot in the downtown area. Located just one short block off of the Historic 4th Avenue, it's close to other fantastic local businesses, but the

                         ## Rank: 18: La Chaiteria | (5.0)
                         **Category: Mexican, Tacos, Vegan, Vegetarian, Food Trucks, Food, Restaurants
                         Hungry on Friday afternoon for lunch was looking for a restaurant while driving and saw this new place so we dropped by. I ordered the al pastor taco and Rajas tacos which is green Chile mushrooom and cream. The al
Pastor did not taste authentic and very oily while the rajas was tasteless and bland... they're not horrible but not wow either.
On another note, the place is clean and tidy. Stopped by today to pick up a large order for my family for taco night. Everything tasted incredible and fresh. We ordered the tacos al pastor and mole tacos. Will definitely be back! So happy Wendy opened a cafe closer to my neck of the woods. It has the same great menu items featuring the best vegetarian food as her other cafes. I am not a vegetarian, and I love it. There is magic in the food Wendy creates, from her potato filled tacos to her jackfruit carnitas-you just can't go wrong. And if you happen on a day where her cashew based Alfredo on gluten-free pasta is on the menu whoa-your tastebuds will love you forever. Yessss!! La Chaiteria has a vegan menu and a regular menu. You can also make your vegan dish vegetarian by adding cheese. The jackfruit is flavorful. I recommend their house drinks. The orchata is so good! The turmeric lemonade and Jamaica are also great. The portions are big.  The food is worth every penny! Staff are super friendly, attentive and want to ensure you have a great experience. I have been a big fan of the other Tumerico spots and so happy now there's a 3rd location in Tucson! We had the saffron latte (no espresso in it), mesquite latte, ropa vieja and the rajas tacos place---AMAZING! Portions are a good size, you can taste the quality of ingredients and they created such a fun, artistic space to enjoy it in. My new favorite restaurant. Amazing customer service, fast service and some of the best food I've had here in Tucson! This place is so amazing! Compared to the other ones that are owned by the same company this one I feel has bigger portions and needed over here which is so great for this side of town. Plus there's so much closer to me now. Seeing that we lost the vegan burrito on this side of town this definitely makes up for it. I definitely would recommend the Al Pastor tacos. They're a little on the spicy but you can make them even spicier with the salsa that they make there and their salsa is amazing too! I tad on the pricey side compared to regular Mexican food places around here, but for vegan and healthy non vegan Mexican food it's right on point with the price. You come here you won't be disappointed!!! This place is on point! There are vegan and non vegan options. The staff is absolutely amazing, kind, helpful and create a fantastic atmosphere. The food is delicious worth a try! Normally this is an amazing place. However only if you get the Cuban jackfruit. Today o tried the jackfruit that has pineapple in it and all I can say is $14 for to stream tacos with a tiny bit of jackfruit and sour pineapple is not cutting it. Sorry. Next time I'll stick to what I like here. The carne con chili burro was one of the best I've had. Rice and beans were also really good. It's a can't miss spot. Best vegan mexican food in town! Support local women owners. Finally got to check out the spinoff of Tumerico. This location is also a cute little market with food, snacks, beverages, toiletries, and deserts to go. there is a food truck outside with meat dishes, which makes it friendlier to a wider base of people. Inside is vegan and vegetarian. The menu is always changing but I always go for the tostados. They're a yummy combination of crunchy, savory, and flavorful. The beans are well cooked and seasoned. The food tends to be a bit oily is the only downside. I also tried one of their juices, while pricy, it was a healthy balance of veggies, fruit, and citrus. Another reason to check out this place is all the amazing murals and artwork. It is a Tucson must see. It's a great addition to the Tumerico family and a much needed boost to the vegan community. I went here with a friend to try something new. I liked the what the cafe/restaurant is going for but the coffee was not good at all. I got the horchata latte, hot. But it was lacking in flavor. The cup was steaming hot, but the coffee was lukewarm. The meals that other customers got looks great though! Also, my friend liked the mole latte, no complaints from her. All lattes come with soy milk. This is a fantastic place and I'm no vegan. But they do have meat dishes, but I've not had a bad meal any time I've went. I hear their coffees are good too, but I go for the food. Give them a shot. I'm so glad this is on the West side of town! The West side has been getting some great additions! This is different from Tumerico in that there's a great salsa bar instead of all the salsas and toppings already appearing on your plate for you.  There's a great drink menu, coffees and Mexican drinks, a vegetarian food menu, which is just as fantastic as the original

                         ## Rank: 19: Seis Kitchen | (4.5)
                         **Category: Street Vendors, Nightlife, Food, Bars, Food Trucks, Restaurants, Mexican, Breakfast & Brunch
                         Their food is so good!! My favorite is the squash street tacos, they are the best!! They have setting outside. So make sure to go there when it's not too hot!! We tried twice. Guac was black,like sitting around, SOGGY hot chips sucked! Using leftovers from day of the dead.( as relayed by the waitress)  We were given one fork for two people, Nickeled & dimed for an ice tea refill. Who likes this place? We threw away most of the food. UNEATABLE
REALLY, how does it stay open.
We will never return. Same thing for the street taco, dried out & hard,
Fresh is not part of the program. Fine for tourists, they don't know the difference.
Our previous experience was worse Service was fast. It has outdoor seating in a shared courtyard. The food was very good. So this place isn't perfect. You'll have to endure a long line at the order window to turn in your order, and all of the tables are outside in the brutal Tucson heat (but shaded and misted). And at least on the day we were there, it took a really long time to get our food. But in return for your patience, you will be blessed with REALLY good Mexican food. I had one each of their three pork street tacos (Cochinita Pibil, Al Pastor, and Puerco Verde). All three were excellent, maybe the best I ever had (sorry, Torchy's). Others in our group had Chicken Tinga tacos, Plato Chorizo tortilla, and "El Guapo" burrito, all with rave reviews. I also had the Watermelon Cucumber Aqua Fresca, which was exceptional. I'd go back in a heartbeat.... Excellent chorizo breakfast burrito, tomatillo salsa fantastic. Will be back for sure. Another fabulous breakfast at the Mercado's Seis. I've now had breakfast burritos,  chilaquiles,  and tacos here. All great. Go now farther - Get your coffee at Stella,  and walk directly to Seis for a delicious breakfast,  lunch, snack,  etc etc. Food is good. Not as good as Street Tacos a block away. The service is terrible. They screwed up my order and actually acted as if it were my fault. Not apologetic at all. The general attitude there is terrible when I order, very apathetic. They act as if they dont have to engage customers with positive customer service. They must think they are gods gift to Mexican food, they really shouldn't considering there are many better options within a 5 mile radius. Also, wife got sick from the chicken salad, maybe health department should look into seis. Big middle finger to Seis at the Mercado. Ate here for lunch.  Hubby got CHICKEN TINGA TACOS GRANDE PLATTER, I got AL PASTOR TACOS GRANDE PLATTER.  He had one of my tacos and I had one of his tacos.  Both were amazing, so fresh tasting, seasoned beautifully!   Side black beans was very salty, I could not eat it.  Someone else in our group got the side black beans and he too could not eat his.  Hubby got Smashed Beans and that was very good.  Next time I will get the Smashed Beans.  I'm hoping the overly salty black beans is not always that salty. These tacos are amazing! I got the Al Pastor and they were TERRIFIC. I will definitely be coming back here hopefully a lot. It is also in a beautiful court yard that sometimes has live music. Definitely  would recommend. I have been pleasantly satisfied everytime I eat here which has been at least 7 times. Definitely worth trying if you are near the San Agustin area. The meat they put in the tacos and quesodillas is well seasoned and full of flavor and never greasy. Seis has the best tacos and breakfast burritos in town. I don't live too close by, but if I'm craving tacos, Seis is always worth the drive. Definitely try the Al Pastor tacos, because they will blow your mind. There's nothing remarkable about the food here. It's decent, but there are quite a few food trucks around that serves better tacos and burritos. The quality of food does not justify the price or wait. The location is nice and would probably be the only reason I'd try their food again. If you live in or are driving thru Tucson, you need to come to the MSA (Mercado San Augustine)! It is a small open air market with quaint little shops and restaurants.
We were on our way to San Diego and needed some fresh air, sunshine and some delicious tacos.
Seis seriously hit the spot. Handmade corn tortillas and the most flavorful tacos. We had the Cochinita Pibil and Poc Chuc tacos and loved every bite.
This will be a repeat next time we are in town. I was there a couple of days ago for a work conference. My routine traveling west is to find great and authentic mexican food.  This place did not disappoint!  Very cosy outside scene with entire menu full of flavor.  Also, they are not skimpy with their portions.  I got the street tacos any many different flavors and the taste was remarkable.  My co-worker had the burrito that was big as a house.  The word started to travel around the 200 folks at the conference about this place. This will be a mandatory stop the next time I'm in Tucson. I like the crispy avocado taco and birria taco/burrito.

I tried the cilantro ric

Label Query: Cheap sushi restuarants

                         ## Rank: 1: Deliciocho | (3.5)
                         **Category: Restaurants, Food, Shaved Ice, Mexican
                         I really wanted to love this place but unfortunately it wasn't for me. Staff was friendly and prices are fair but I was disappointed with the food. My birriachan was very dry and bland and hardly any birria was in it. The quesadilla quesabirria was just ok, the Kiko taco had a strange flavor sort of like a chemical taste is the best I can describe it and unfortunately the churro ice cream sandwich had raw dough in the churro and wasn't fully cooked. I wish them well but likely won't be eating there again. Maybe my expectations were a bit too high. But i didn't love this place. Over all it was an ok experience. Not bad and not great either. Ordered the quesobirra quesadia, el godinez torta and 2 agua frescas. The torta was the best part for sure. It had good flavor, the off putting part was that it came with jalapeños inside but they didnt cut them up it was a whole jalapeño  just sitting in the torta not sliced or anything. The birria quesadia was alright. It was missing a little bit of flavor and doesn't come with the consume to dip it so that was a bit disappointing. Fries with thw torta were good. The drinks were also alright. Not too sweet and not too bland, but also felt like it was missing something. Like i said, it wasnt a bad experience just not a great one and if you don't live close by I'm not sure i would go back, if I lived close by I'm sure I'd give it another shot. It sucks cuz i really wanted to love this place from the pics i saw on IG and google. Thanks to our Yelp community I get to hear about outstanding places like Deliciocho. After seeing some recent pics and reading about them in the paper I was convinced to make the drive and try some tacos!

The Birria tacos were outstanding and I'd recommend giving them a try. Next time I'll save room so that I can try some of their incredible desserts. If I were to guess, no matter how good the tacos are, the desserts look like they will be what this place is known for (churro ice cream sandwich!).

As a tip, there is no indoor seating so the overall feel is more like a food truck than a restaurant. I was so upset after going to this place today I waited almost 20 minutes for my food and then they served me a taco with the tortilla falling apart and it had a hair in it. I politely told the girl that my taco had a hair in it and the tortilla was ripped and she said she would give me another. Waited another 20 minutes, more people came after me and ordered large to go orders and got all their food before me  very disappointed so I just ended up leaving without getting my taco I follow these folks on Instagram and I finally stopped in for the October specials.  The Machete taco. 18 inches of quesobirria taco with your choice of Birria, Pollo, or Asado.  I chose Birria and it was delicious. My family and I have been to this restaurant plenty of times and it never disappoints.
We recently enjoyed the Chilendrina which is a birria torta with delicious fries! We also had the quezabirria, birria tots and carne asada burrito! So delicious!

For dessert, I recommend the mango strawberry raspado with ice cream and lechera! And the churro ice cream sandwich which is to die for! Best churros ever! I wish the owner would give me the recipe!

Please go! You won't be disappointed.

                         ## Rank: 2: Sushi-Kito | (2.5)
                         **Category: Restaurants, Italian, Food Trucks, Japanese, Burgers, Food, Mexican, Sushi Bars
                         I tried the new place on 12th Ave, what a great experience. I had the Evil Kani roll with a siracha mayo and soy, wife had a Terriaki Chicken Taco salad. Tasty, great flavor and price was very good. Will return soon! Interesting rolls.

Didn't really enjoyed the sea land and sky (lacked flavor, a bit dry) but did enjoyed the sushi kito roll, pretty flavorful! Thank goodness for ample signage. I was driving down the road when I saw "sushi" on the banner.

Now, this is the southside. Those of us who live down this way are highly accustomed to having ample access to tacos and chimis and burritos and tostadas and the famous Sonoran hotdog.

Ugh, just how many molcajetes do you need in one week?

The day we find an Indian, Caribbean, East African or *good* Vietnamese food spot on this side of town -- I will purposefully eat out every single day of the week...for a month!

OK, no. No, I won't. But I will likely eat out more often.

So, seeing the Sushi-Kito sign made me make a haphazard U-turn in 10 seconds flat.

I'm glad I stopped in.

The proprietor tells me that this food truck is brand new. Apparently, they only been in business this month. And it looks like they will stay in this location for who knows how long. That's cool, especially since we only have one decent sushi restaurant on the southside - that would be Sushi Lounge just up the road.

Kito specializes in a fusion - it is northern Mexican style food meets Japanese street food. At least that's my best guess.

They even have yakimeshi -- a Japanese style fried rice.

For my first order, I went with the Kito specialty burger. I do not know why it's called a burger when it is, quite frankly, a glorified California roll top with all sorts of delicious flavor accompaniments.

Seriously, for eight bucks I had a meal for two. And it was pretty good.

It's the type of food that excites the overly curious palette. I found that eating my single dish, the flavors kept changing. It was like a buffet in a single sushi roll. It was spicy, it was soft and smooth, it was crunchy and sweet. Night even tasted something that reminded me of fried mozzarella.

And this humongous roll, stacked skyhigh with shrimp and other glorious goodness, came with a shaving of carrots and a side of a nice, fresh crab salad. Absolutely perfect for the summer months!

The only downside is that I could tell where that the tent in menu are in bright red and so the menu was very difficult to read. Also, the rice was a bit bland. It's certainly not sushi rice. It seems like it's your standard long grain rice.

But, not bad for first visit. I'll be giving them another go and highly recommend that you do so as well. food is not that good at all, rolls are all rice and cucumber. very big. all you eat is rice. service was no good as well. the server admitted to not knowing anything. didn't even know the menu. very slow. overall wouldn't go back if you paid me. Horrible customer service, sushi is just ok. They give you a price then they change it up on you when you are picking it up. I ordered a "especialidades" sushi platter over the phone and when I went to pick it up they said only 2 can be specialty sushi's and the other two have to be regular ones even tho on the menu it says it's 4 specialty rolls. They didn't give me a call back or anything and they waited until I showed up to tell me. If it wasn't because I had people over I would have just left. I had to sit there for an additional 40mins waiting on the platter. Did I mention they never even apologized? They made it look like it was all my fault. I even pointed to the menu and asked for clarification if I was mistaken. To which the girl at the register just couldn't justify it. This isn't the first incident I've had with their customer service. They always look like you are just an annoyance to them. I rather spend my money somewhere were customer service is a priority and not just wanting to take your money. Super disappointed I got the norteño(more expensive roll) and sushi Kito. They put everything on top like a stack of nachos and inside the roll was just cut up cucumber which definitely isn't worth 15 dollars. I was also given a different price on the phone then what I actually had to pay. And then after everything else I was told 35 minutes and ended up waiting another 40 sitting outside the store and the food was already cold. Should have just went to Sushi Lito. Best Mexican Sushi in Tucson! I always go here even though it is 20 minutes from my house because of how amazing the sushi is and how nice the staff is. I like to eat the sky,earth and sea roll and it is hands down my favorite. They are improving in their speed which is good because a few months ago it would take about 30-40 minutes for my food and yesterday it only took like 10-15 minutes. The food here will not disappoint! Tried the charola with 2 sushikiyo rolls empanizados and 2 boneless orders and it was great just like the ones from nogales mexico Customer

                         ## Rank: 3: Sushi Valley | (4.0)
                         **Category: Sushi Bars, Restaurants, Food, Chinese
                         Very fresh and very generous in serving size. Well priced. Small but clean and friendly servers and sushi chef. I will definitely come back next time I'm in town. I used to come to this quiet little restaurant a lot for the good prices and great food. Today I was shocked to find that the price of my favorite dish has almost doubled in a years time. I ordered it anyway, remembering how good it always was. However today my chicken yakisoba was not up to par. All the chicken was cooked to the point of being dry and the green onions which were always chopped well were merely  cut in half in the dish. It looked very rushed. The taste was not near as good as I remember, but that could just be my taste buds. At this point I'm unsure if I'd return, especially if the prices stay this high. We've been coming to his restaurant for years. The food is AMAZING and the service is always on point and helpful. The rolls here are HUGE!  Bring your appetite and flexible pants. :) This is an awesome little hole in the wall place. I am so happy that I found a sushi place that's with in walking distance. The sushi is amazing and the rolls are huge. I just wish that they learned how to roll them better. Also the one negative thing that I could say is that the service is a little slow, it seems like they have 1 waitress for the entire place. Overall a great place tho!! Not bad for Tucson, of course I compare it to sushi from Makuni's in Sacramento, so it's pretty hard to beat.  Most of what I ordered was cooked though, so I wonder how much is fresh.
Given that we are inland, in Tucson, this sushi place is alright.  Give it a shot, you might like it. When you are a new restaurant, your goal should be to draw customers in.  This is done by providing a quality product at good value.   This place place does neither.   The sushi was not fresh, it was clearly dyed, and the tempura was soggy. But the single star rating comes from the fact that you charge twice what sushi on oracle does without any quality.   Try again... I really like this place. The décor is nice, nice seating area. Restaurant is not too big inside and the sushi bar is a bit small, but you don't feel crowded. The food is excellent and they offer a good variety. I get the spicy shrimp ramen a lot. I like several of their rolls and their lunch specials are super good - huge - so bear this in mind. Food is fresh and tasty. Owners are friendly.

They do deliver for a $25 minimum (which is a bit steep unless you're all sharing/multiple orders). Deliver is about 30 minutes. Not too bad. The food has always been good here as is the service. Prices are moderate. I'm a total fan! I love this place. The food is good, there is a lot of different types of food and the staff is super nice. I have tried a lot of different rolls and for the most part they have all been pretty good. I was very impressed with the speed of the service as well as the cleanliness of the place. Also, their cute little orange slices put the experience over the top. They made me laugh, they were adorable

I find the comments about this place having an identity crisis hilarious. Variety is the spice of life! Not everyone eats sushi, people have food allergies and let's face it, this is Tucson. A lot of people here don't know the difference between Thai food and Chinese food. I do know the difference and I say as long as it is yummy, bring it on!!

Last thing, I love that they deliver, lunch just got much more exciting!! Visiting from NC and this is the BEST sushi restaurant we have been to... Maybe the best ever! The sushi is very fresh and high quality. The nigiri portions are huge! And the staff is so sweet. The owner clearly takes pride in his restaurant, and it shows! Good service, great sushi... There aren't a lot of reasonably priced sushi options in town & I'm glad to see one open! They're also willing to accommodate requests for items not on the menu at no extra charge. This place was amazing! My family and i stumbled upon it on our way back to town from the Biosphere. The food was delicious. The service was great. Cant wait to come back again Called 6 times an hour before close and no one answered. Guess they didn't feel like working tonight. Nigiri pieces are HUGE!! and so delicious. Albacore, salmon, and spicy scallops were all great. You get miso with it. It isn't the cheapest but it is definitely worth it. The service was good and always is quick. Ive been at all times of the day. Always on par. Never been disappointed with a meal here. Rolls were great too. Visiting from CA with not much hope for good sushi and I was surprised.  I ordered about $40 buck worth togo for my room at Conquistador Resort.  Delicious, and I mean it.  The salmon was perfect and fresh, the tuna melted in my mouth, and I got a couple rolls that were bomb.  Oh yeah I ordered the pot stickers too and they threw in salad and miso soup; best miso soup ever it had pickled burdock root in it ... super tasty.  I was the only o

                         ## Rank: 4: Pei Wei Asian Kitchen | (3.0)
                         **Category: Chinese, Asian Fusion, Restaurants, Fast Food, Gluten-Free
                         I once liked Pei Wei. The Innovative modular menu and the Americanized Chinese food which was not in anyway authentic but which was appealing. Unfortunately they've gone down the road of pop culture far too much. The last time I went I had Dan Dan noodles which I've had in many restaurants all over the world. Basically it's a slightly spicy ground beef and noodle dish. Pei Wei's version is made with chicken I know that I've had it there before. Only, in its latest iteration it's sweet. This dish is never sweet. And in fact that's the case with their whole menu everything has been sweetened and more sauce been put on it. There are some other touch I don't like for instance if you want water they give you a very small glass. And then there are your fellow diners at the self-service setup station many of which will stand there for a long time hogging the entire setup completely unaware that there's anyone else trying to get in any of the condiments or beverages.
All in all the food is no longer good and the dining experience is not pleasant. Lettuce wraps were great as usual.  Sushi rolls - no - obviously made in advance and refrigerated yuck.  Will return again for non-sushi items. Quality ingredients and lots of tasty sauce options. I was a little sad because the girl who built my bowl wasn't nearly as good as the guy who was working in front of her- I really wanted him to be the one to assemble mine! She was a little skimpy with my choices. All in all I'd go again. I hadn't been to Pei Wei for quite a while but when I went the other day, I enjoyed it. The new lettuce wraps were really tasty and I liked that their soda machine had several diet options. I think the food at Pei Wei is very good, not too pricy, and is served in a casual atmosphere that makes it a great place for lunch! Walked in and was glad to see lots of vegetarian options. I got the ginger broccoli with veggies and tofu and brown rice and boy, my dish was drenched with the sauce. It was too salty in my opinion. Typically, I'd probably send it back but being on an hour lunch, I don't have the time. I just built a wall with the rice and picked at my dish. I've been to several pei wei before and generally like it. I would come back to this one, but I just would not get this dish again.

Restaurant is clean and the cashier was nice. my dad use to take my sister, Mom, and i here and i loved it.

we would always get fried rice and it is the best fried rice i had anywhere. am heading there now. I remember when this place used to be really good.

I mean, it's still busy enough. But not as packed as it once was. There's a reason for it. The menu's updating quite a bit lately, and they've instituted a rewards program. Those aren't things you do when the Status Quo is working. Minor things, such as moving all the plates, napkins, and chopsticks to a single location and having customers get them themselves are other signs that they're pushing towards cost control which... don't look good.

The main manager has stayed the same but the staff have undergone significant turnover. Which makes sense, you employ young part-timers who are on the career upswing, but the folks who used to be there were better trained and were... I don't know, friendlier. Maybe that's personal bias.

The biggest concern though over the last few years is the food. It's chain-restaurant Asian food, so I understand this is not going to knock my socks off. That's fine. But meals are inconsistent, sometimes the sauces aren't even consistent, so each meal is different from the last. The biggest concern however, is with cross contamination of food. I ordered Mongolian Chicken my last visit which had carrot in it (Which is not part of the meal), and this is a minor issue. However, I've ordered Shrimp Pad Thai which has had steak and chicken in it before. Now, I happen to LIKE the idea of a "House" combo where it's a little of everything, but that is a MAJOR problem for anyone with any sort of health concern. I could not with a straight face tell someone that a dish is (Anything)-Friendly here. Not vegetarian, gluten, what have you. If you have a dietary restriction, you absolutely must avoid this location like the plague.

There's other minor things... I order appetizers that come anywhere from a minute before to five minutes after my entree. The kitchen back room smells so strongly of chemicals that the tables nearby are unusable to anyone with a sense of smell, etc. But hey, I still show up once in a while like a sucker, seeing if they figured out how to recapture what they used to have. Being born and raised in Hawaii I have had many great Asian food experiences. So for this being my first time eating at this establishment in Tucson I must say that my overall experience was satisfying. Very clean! Employees are friendly.... food was great! We ordered wings, sushi and a spicy ramen. I have no complaints This is one of those reviews that I'm really hoping someone at management will re

                         ## Rank: 5: Sushi Tran | (3.0)
                         **Category: Sushi Bars, Food, Restaurants, American (New)
                         I'm a regular here for sure. Fresh ingredients fast service. Quality taste service price makes a hard to beat combo. Special crunchy roll awesome. Gyosa unique and a little crisp rather than soft. Perfect. The main reason I ever come here is because it's the closest place for sushi on my lunch break. As for as a restaurant goes I would hardly consider it one. The quality of the good is passing except for the few times I have had nigiri. I will probably never order nigiri here anymore after I had the worst piece of salmon. The rolls and hand rolls that I have had are not bad and specially the baked California roll is actually better than most others in my opinion. Other than that I don't have the urge to go outside of what I know to be decent. All I can say about this restaurant is WOW and I think I've found my new favorite sushi joint in Tucson!!

The b/f and I were up on the way northwest side of town and just happened to be driving by at dinner time.  We decided meh, why not stop in? We haven't had sushi in a while...and MAN was I glad we did!

We ordered: a Las Vegas roll, the special crunchy roll (regular crunchy roll w/ spicy tuna slathered on top), a spicy tuna roll, a crunchy roll, and the M.T. roll(spicy crab mixture).  Yes, it was a lot of food and YES we had leftovers! The Las Vegas roll wasn't my favorite, but since I'm not a big fan of them anyways, I let the b/f judge it.  He said it was delicious.  By far, the special crunchy roll was my favorite! I'm not sure how they make their spicy tuna but wow.  It's melt in your mouth deliciousness.  It has just the right amount of spice, with a creamy texture. The M.T. roll was also delicious, but I don't feel that I did it justice since I'd already filled up on the other rolls.  We were able to get 5 rolls and 2 drinks for $50, which isn't bad at all for a sushi joint.

The atmosphere is pretty basic, with a nice sushi bar in the middle and tables lining the walls.  It's small, but the sushi chef and servers were friendly and always making sure we had enough to drink.

This place is definitely worth the drive up north! The sushi was fresh and tasty, but you'd better know what you want when you go in because there is not description of what comes in the different rolls at all. The menu is weak from a readability perspective, but the food was good and the service was fast. A great little mom and pop shop nestled away from the hustle and bustle of the big city that serves delicious sushi!

 Prices are decent and the specials are delightfully different and tasty. I was surprised that they have Japanese beer too!

 The owners were very friendly and we chatted with them during a slow spell until some customers came in. They've been in business for 13 years now, so they must be doing it right! I have no idea how this place has 4 stars, or is even in business. It is not often that I give a place 1 star, but I would never recommend anyone eat here. The sushi quality is extremely low, to the point that I am scared I might get sick, and the sushi chef is not a sushi chef. The service is non existent and the atmosphere is dingy, not something I want to accompany my sushi. You would be much better off driving 4 miles down the road to Sushi Cortaro for a real dining experience. I want to support local Tucson restaurants whenever possible but unfortunately Sushi Tran's prices make that difficult to do on a regular basis. My wife and I spent nearly $40 on two rolls, yellowtail nigiri, an order of patay chicken, and two non-alcoholic drinks. That might not seem like a lot for a dinner for two but consider that our usual sushi expeditions leave us full and swearing to never eat that much sushi again; with Sushi Tran, we were left wishing we had ordered more.

These slightly-higher-than-average prices wouldn't be a problem if the sushi rolls themselves were better than average, but sadly they are not. One of our rolls was the "daily special," a shrimp roll that cost in the double digits but wasn't anything particularly mind-blowing. Our biggest disappointment was the $6.99 chicken patay, which was literally three little chicken tenders skewered and served with peanut sauce. I know that's what chicken patay IS, but the whole point of eating sushi is the value proposition, is it not? This should not have been priced as high as some of the hand rolls, which could easily serve two, since this could barely serve one.

On the plus side, the wait staff and sushi chefs were incredibly generous and answered questions that we had. Also, their Thai drinks (we know them as "bubble tea") are worth investing in for sure. My wife and I agreed that we wouldn't swear off Sushi Tran entirely but it's a shame that a place so close to our house is not immediately desirable when we are craving sushi at a great value. Oh, this is bad sushi!  Don't waste you money or time.  The Philly roll hardly had any cream cheese and it fell apart.  Gyosa was overcooked and hard as a rock.  The ch

                         ## Rank: 6: Goyita's | (4.0)
                         **Category: Nightlife, Cocktail Bars, Restaurants, New Mexican Cuisine, Bars, Food
                         My wife had the fajitas. Lots of sour cream and guacamole, she said they were nice and tender. Fajitas reserves sizzling hot with Fresh Tortillas. I had the green chili with rice beans and tortillas. It was really loaded with hatch green chiles. I thought the temp was just right for me medium hot just breaking a little sweat on my forehead. We went on a Monday night and walked right in no problem Saturday night there was a little weight as the kitchen tries to put out some perfect meals. Great service and great food, portions are large! Brandon provided excellent customer service, they accommodated dietary restrictions. We will be back for sure! So how to rate this restaurant is basically a question of price versus quality. The food is good it's not great. Since my chili rellenos were tasty but also a little soggy. Clearly they had been made in advance and then reheated. I found that the food is generally okay but not great and although the lunch specials are reasonable the prices are a bit high. So the restaurant really deserves 3 and 1/2 Stars which are not possible herein. Consequently it doesn't rate four stars... so I've got to give it 3. Let's start with the chips and dip: very good! I had the combo plate with beef taco, green sauce cheese enchiladas, awesome Chile relleno, and excellent rice and refried beans. Thee sopapilla is on the way out. Margaritas very good. Knock one star only because the meal took longer than expected to be served, but not too long. Overall very good and I'll be back on next visit to Tucson. Take It or Leave It

Maybe I'm to critical since I am from NM. The food was ok. The beans and rice were edible. Most restaurant  rice is dry and tasteless. We had gorditas and stuffed sopapillas. Both were $11.99 each The ground beef was just missing that New Mexico taste. The sopapillas were so thin that you had to eat them with a fork. 2 sopapillas and no rice no beans. What the heck? Beans and rice are cheap. The gorditas were just basically sopapillas made from corn meal. Thin and tasteless. If you have ever had a good gordita, you know that they are supposed to be so thick that they have to be sliced open not hollow. They just lacked that deep fried corn meal chewiness. 3 Gorditas, beans and rice for the same price.

The chips and salsa would be around a 4 out 5. Chips were warm and tasty. Salsa was better than most places.

Now comes the service! OMG was it bad. We were seated in a back corner and nearly forgotten. Every once in while our waitress would see us and would almost look surprised as if she forgot about us. She made an excuse that the place was busy. Well, we could see a lot of empty tables and it was slow for a Friday night. No surprise. She forgot to replenish our chips and salsa. Half way through my meal I asked for the salsa that she was supposed to bring. She then offered the "Gordita Sauce". Shouldn't that have came with the gorditas?

After we sat down and waited for our food. You could tell that it took a long time to make other people's food, we were no exception. There was also at least 5 tables near us that were not cleared. No biggy, but still gross.

We drove 45 minutes from Vail and probably won't ever again.
I wish I could suggest a good NM resturaunt, but I can't. Well, not in Tucson at least.

If you are in the Las Cruces area....Chopes or Bravos for cheap not fancy but yummy chile rellenos.  For dam good gordita, Little Diner a hole in the wall on the other side of Las Cruces. Excellent food. I had the green chili con carne burrito. It was very flavorful and not to spicy. I wish it came as a combination plate. Be prepared for a long wait. We waited ,45 minutes for our food. Great food!  This restaurant is really New Mexican and better than many in New Mexico itself!  Good Hatch chilis in the dishes!  Great addition to the restaurant scene in Oro Valley! Best hatch green chiles I've ever eaten. I've never had it with sirloin, I've always had a other pork. I had bean burritos with green chile con carne on top. Amazing. And, the giant margaritas were tasty and strong, and cheap ($6.50). How hard is it to get a beef burrito to go? Apparently too hard for this place. Utterly confounded by easiest order ever, they then told me some chips to go with burrito would be 3.50. And they couldn't even get the burrito made. Or bus the many tables of dirty dishes. Avoid unless dying of hunger. Good Mexican, not traditional.  Service was a little slow. Nice variety of spice and flavor. Good variety of alcohol and options. Nice to have Mexican close to us in Oro Valley. We've lived near this place for a while now, but we has a bad experience at the restaurant before it was Goyita's so we kind of avoided it. But after reading its great reviews, we decided to give it a try. We are SO glad we did!! The food was all excellent. I got two burritos: one carne con chile (red) and one shredded beef. The shedded beef was the best I've ever had anywhere in the US. Seriously! The c

                         ## Rank: 7: JA Ramen Curry | (4.0)
                         **Category: Restaurants, Japanese, Ramen, Food, Japanese Curry, Salad, Desserts
                         The curry here was delicious. A little sweeter than I prefer but still good. Had to drop a star based on the price. Pretty expensive meal for a Chipotle type environment. Food wasn't that bad. I just think it's way too expensive for what it is. $12-15 for a plate of curry with rice? I think a decent price for the food would be about $7-10 at most. They're definitely up selling the food to make up for the cost of opening their business but I just don't see it at $15. Sorry but until they lower their prices I probably won't be back. I really wanted to like this place but unfortunately it was bit of a disappointment.   Ever since I've been to Japan and tasted all the different thing they put curry in (curry stuffed donuts, so delicious!  Must try if you get a chance! ) I've been craving Japanese curry!  Low and behold a Facebook ad popped up advertising a new Japanese restaurant serving Japanese Curry, I just had to go and see if it measured up.  The parking lot is a one way that raps around the restaurant so if you are coming from the north and miss the first turn in the you will have to make a U turn and come back around.  The inside is very casual and you order at the front and they bring out your entree to your table.   I ordered the chicken katsu with a level 6 spicy (1-10 spicy level available) and my friend ordered a miso ramen and a beer.  The drinks are self served with water glasses and utensil on the side.  My chicken katsu came out within about 5 minutes but my friend's ramen didn't come out until I was half way done eating and she had to ask one of the servers if her food was ready.  The curry itself was okay with a few peicesof carrots, but the chicken was super tough and rubbery.  Makes me think that it was old chicken they just reheated. My friend's ramen was just okay, definitely had better ramen elsewhere.  Overall I wasn't impressed with the food and service can be somewhat slow depending on what you order.  I wish the food was better because I really wanted to have a place to go for great Japanese curry. My husband and I have now visited twice in the last month to try new menu items and have loved everything thus far. We've had the naan, tempura vegetable curry, takoyaki, tempura shrimp, chicken dumpling, spicy tonkatsu ramen, and chicken curry. Absolutely delicious. Everyone who was working both times were ridiculously friendly. The dining area is always spotless and the decor is very pleasing. I love this place and already cannot wait to go back. Me and my boyfriend went here a few days ago and we loved our food and service! I got the tempura shrimp curry with the spice level at 4, it was spicer than I expected but it was still really good. I'm kind of a baby with spicy stuff so that's probably why. My boyfriend got the vegetable tempura curry and he loved it! The portion sizes I thought were pretty big, so I left full and happy. The staff was very friendly and attentive, overall we had a great time. Very good ramen and curry options!!!! Have tried both the Spicey tonkotsu and non spicy. Very delicious!!! Great for groups and never a huge crowd to keep you waiting I don't think everybody that goes here writes a nice review like they should I think mainly people only write the bad reviews because there's no way this place could be a three star restaurant. From the time I walked up and ordered from the time I got up to leave everybody was so nice the food came out hot and delicious. The smell was great aroma was beautiful. The lady at the front and took my money even rounded up the dollar so that she didn't have to give me change back because she didn't have the one dollar bills in her register. Which is only a few cents I'm sure but still she could've been hard to work with and asked me to pay card or something. But she wasn't she was great delightful. There's only one other Ramen place that can compete with this that's over on speedway I think most people know what I'm talking about. I think eventually this place will be a good competition for that one. One of the best things about this place is you don't have to feel entitled to paying an overpriced tip like at the other Ramen place. They have a tip jar upfront which you can leave a dollar or two or whatever but at the other place you have to leave at 10 15 20% tip.  That bumps up the bill by $7.00. Saw somebody mention that this place was expensive I don't know what they're talking about 10 $11 for a Ramen is a good deal most places it's 13 14 or $15 per bowl!  Here you also don't have to sit at a community table! You can have your own space at your own table. You can refill your own drink or waters which is good. Parking is good.I will be back next time I want to try the tempura shrimp. Ramen and curry in one spot: best idea ever. Their curry really hit the spot. Definitely coming back. Okay so if you've ever been to a CoCo Ichibanya and loved it, this is the place to go in Tucson. The Japanese curry is a bit pricey but it is so good.

                         ## Rank: 8: Sushi Lito | (4.5)
                         **Category: Food, Mexican, Tacos, Food Trucks, Sushi Bars, Restaurants
                         Good Mexican style sushi. It located south of Nebraska rd. Red cart on the west.good price,and taste Just went to have "Mexican" style sushi and this was great!!!! Great prices for great taste!!!!! Fun take on sushi-- it's Mexican style! Good prices, good food. Tempura style Teriyaki roll is my favorite there!! Highly recommend this place is your looking to get some quick quality sushi, service is great! Sushi Perron pa los munchies cuando quemas un gallito pa el stress Very good Mexican sushi. Its the best in town. I have tried many of them and none have disappointed.  Give it a try ! When it comes to Mexican sushi, this is hands down the best in Tucson. We haven't had a bad sushi, or even disliked anything we've ordered from here. The vaquero sushi it our favorite, taste amazing. And the crab that comes with is the best I've had at any sushi place. The chipotle sauce they make is great. My girlfriend always asked for multiple because how good it is. Overall it's an amazing sushi place. And there's a reason why we go here over anywhere else. So bomb.  Not your ordinary Japanese sushi.  It's mexicanized sushi. All of them have avocado, cucumber,  and cream cheese. Have been ordering here for the past few years and always get the charolla... carnivoro is def a must have! Love the food and quality is great. Down side is they hardly EVER answer their phone. It's such a hassle and hit or miss situation with trying to place an order. Otherwise, would have given them perfect 5 stars.

                         ## Rank: 9: Pure Poke and Prep | (4.5)
                         **Category: Poke, Food, Seafood, Restaurants, Hawaiian
                         Simply FANTASTIC!!!   Super high quality fish and plenty of fresh toppings!  All of the sauces we tried were flavorful and unique.  The staff helped us build three different and delicious poke bowls.  The tuna was fresh and FANTASTIC!  I highly recommend the momo sauce!!!

On a side note, ANYONE who gives a new restaurant a less than favorable review on the first or second day they are open is a bad human and should not eat out! Just been twice. I've had Poke and sushi all over the west coast and Kuaia. This equaled some of  the best of them. Fresh yellow tail, tuna, & salmon. Homemade sauces, topping a nice touch. Quick service, responsive wait personnel. I'll be back. We ordered take out on the first day they opened. The place was very clean, the fish was fresh and the service was very friendly and polite.

The food was mostly bland though. I got a custom bowl with their noodles, a scoop of tuna and a scoop of yellowtail with their "spicy" sauce. The taste just wasn't there. Same thing with most toppings. The only redeeming things in the plate were the raw jalapeno slices.

I really wanted to like this place and become a regular, but I wasn't blown away. Pure Poke will remain an economic alternative to the slightly pricier Chriashi bowl at other sushi restaurants. I was pleasantly surprised. My poke was fresh and flavorful. This was a nice surprise. It's not often when I like a place the first time I visit. The servers were helpful and pleasant and I could tell they were trying hard to make it a nice experience. Great fast lunch spot. Glad we have something like this on our side of town. Very friendly employees and seemed very clean. Don't know what kind of rice they use, but was not tasty at all. I ate all the toppings off and left the rice.  Rice has to be good ! I was highly disappointed, won't be eating here again.
Also very pricey, one bowl cost me $17.00. That's without avocado! Clean and good place to dine-in with all that happening nowadays. Generous portion with enough selection of toppings and sauces.
Nice and friendly service. For sure will come back again. This was my first time having a poke bowl, didn't know what to expect.  It was okay, maybe I need to try it one more time to give a far post.  I didn't think that it was a little expensive. First time checking out Pure Poke and Prep! Went on a Tuesday evening and was met with fast service and friendly faces. I went with the momo marinated (a spicy mayo) salmon and tuna proteins along with white rice and a ton of fresh vegetables. All of the proteins and toppings looked and tasted fresh along with generous portions in both mine and my husbands bowls. Everything was delicious! Even had a nice Kona spiked seltzer to go with the meal! They adhered to covid distancing, and staff members wore masks at all times! Would recommend and will be coming back soon! Not very good. They were in training. The fish was fresh but the prepared  fish was tasteless. I had one scoop of Haole Poke tuna, one scoop of Momona Poke salmon. There was hardly any sauce and The sauce was just okay. Then I added crab which was additional. In Hawaii you get either a scoop of macaroni salad or crab salad with the rice and poke

My husband and I were in line together and a nice young lady took my husbands order which was a lovely portioned bowl. Mine was made by a trainee. I had hardly any fish and my husband had a beautiful bowl filled with fish.  This isn't real poke it's just like a chipotle but with fish and rice. The crab was just shredded and no flavor. They had  no macaroni salad like true Hawaiian poke.
Chef driven means nothing when no flavor and small portions are more  important
we spent $36 on lunch in a fast food joint. Ok I rarely write a 5 star review but I am way impressed. The food was so fresh and yummy! I love all the options of toppings.

What I really really loved was the booze options they had!! They were all Hawaiian and unique island related beers. You could tell they were handpicked with love. I want to try them all!! I love everything Hawaiian so this was a super special discovery.

I will for sure be back! Love this place! Not many authentic poke places in Tucson with high quality fish. The flavors are great and the prices are just right. These guys do poke right. It's not cheap, but good quality never is. So many choices and toppings, I have to come back again and again to try it all Fresh, easy and voluminous.

You come in, are greeted, get pleasant assistance with your order if you desire (I sure did), can load up on veggies and then have a couple meals out of a huge poke bowl.

Ordered house ahi and spicy salmon. The first was simple with flavor and allowed for some fun with the dipping sauces. The latter was not too much mayo but close - the flavor melts with the fish however. You can mix your base so I had brown rice (cooked perfectly), noodles (tasty and as oily as it looked) and salad (healthy mixed greens). I added seaweed for a buc

                         ## Rank: 10: Jimmy's Pita & Poke | (4.5)
                         **Category: Poke, Food, Salad, Sandwiches, Restaurants
                         Coming from San Francisco and having been to Hawaii a million times, I was pleasantly surprised at what I found in the middle of the desert. There a few things on the menu that was absolutely delicious like fried jalapeños?!!! Like it was slap your Asian momma good and I have to say they had Pumpkin Spice Black tea (the basic white girl in me did a "woot woot!") - yum. If I lived here I would be eating here everyday and prolly die of mercury poisoning from the fish but it's that good! In all seriousness, this was a good find and I can recommend it enough! Great service and food! Bridger and Melanie helped us with our order. Very friendly and we will definitely be back! My partner and I were surprised at how good the poke bowls are at this place plus it's a great value for the quality.  The portions are so large (I got the large - 3 scoops) with ahi, salmon and aloha salmon (the best of the three) and all the toppings with exception of the seaweed because I didn't want it all stuck in my teeth.  My partner ordered the ahi, salmon and crab.  I highly recommend this place plus the workers are exceptionally nice.  Also, they don't currently charge for avocado which is a surprise. So happy we finally a Poke place on the northside.   I had the spicy salmon poke with house spicy sauce, delicious and healthy.  Wasn't sure at first where it was, but its in the Sprouts plaza. Finally, some good poke this side of town. They don't mess around with portion sizes here so if you get the three scoop bowl, either be hungry or be ready to take some home. In my experience, the staff was very helpful, friendly, and they were set to make sure my poke bowl would be exactly to my liking. The place also has a unique marinade for some of the meat, so be sure to try it. If someone in your party doesn't eat meat/raw fish, they can get a pita, so no excuses to try this place. I'm SOOOOO SOOOOO excited!!!! Jimmy's now has a location on the NW side (River/Orangegrove)
BEST POKE hands down!! Super fresh and a nice variety of options.  If u like Poke you'll LOVE Jimmy's!! They also have a variety of pitas and salads that are also super fresh.

BONUS ~ Family owned/operated and excellent customer service Wonderful customer service, extremely attentive and responsive owner and employees! They treated us with such respect and kindness. The food is amazing and we will definitely be coming back My fiancé and I looooove eating here! We wish there was one closer to the Tucson mall, that way it was closer to us, but we will always make the drive! I've been back twice since the change to not marinate the aloha salmon in the sauce, and everything seems fine now. No more off smells or tastes coming from the salmon! Went in this evening to give this place another try. First time there was a wait for white rice. Get up to order and she said let me look if we have more white rice. Comes out to tell me it's going to be 15 minutes.  2 visits and the same problem. I would think white rice would be kind of important. And i understand not wanting to waste food. But this is a bit ridiculous. So that's the reason for my one star. Even though I have never tried there food. This restaurant is the best. They give tasty food and large portions. I was thoroughly impressed by the quality of food. I hope more people try this out because it is sooooo good! 100x better than any fast food joint and 100x healthier for your body. Tucson is blessed to get this new fast food joint! Never had poke before and loved it ! Great location and the staff was really helpful and patient! Tried the salmon (with quite a bit of skepticism) and it was fresh and delicious. I can't wait to go back! I've eaten at Jimmy's five times in the past month: four poke bowls, and one pita. Up until today, the poke bowls have been delicious. Really delicious! Fresh lettuce, fresh fish, and fresh toppings. Everything is flavorful individually, but not overpowering when it comes together. I would have expected a little more fish for the price, but the generous portions for the toppings made up for it.

Today, however, the most important thing was not fresh. I got my usual regular-size poke bowl with 2 scoops of fish---aloha tuna, and aloha salmon. The tuna was great, but something wasn't right about the salmon. It had a fishy smell, and as anyone who eats sushi knows, the fish should not smell fishy. The taste was also off. I took two bites and threw the rest out.

I haven't gotten food poisoning yet, but we'll see what happens in the next few hours. I'll update this review accordingly. If you like poke or even if you don't this place also serves up rice bowls with or without protein along with a wide variety of pitas and salads. It's cornered location along river road makes this place quite the hidden gem!  I have a feeling this place won't be unknown for long. Great food and portion size! I haven't had a poke bowl before, but I have had a ton of sushi.
I see a lot of reviews complaining about the

                         ## Rank: 11: Cold Stone Creamery | (3.5)
                         **Category: Comfort Food, Custom Cakes, Ice Cream & Frozen Yogurt, Restaurants, Food, Desserts, Cupcakes
                         Interesting combinations but the ice cream is very very sweet! It masks any trying to taste a rich flavor. 5 stars goes to Jourdan for his customer service.  He's very aware of his customers and totally personable even during busy times.  His ability to multitask is great! Regularly visit this location.  Service is always good. Customer service is always awesome here but super upset that they no longer have chunks of cookie dough as they did pre-recall. They are now those same ones at DQ. Frankly, since I realize that I have no longer have returned because there's no need for me to pay nearly $6 for something I could get for half the price at another place down the street. Ice cream is delicious and the staff is super friendly! Love that this location is close to home and open late on Sundays. They recently advertised with a daily deal site and it was an amazing deal! The only thing I would like is if there was more than 1 outside table. It's never a bad choice to stop here and get some delicious ice cream & made they was you like it. Grey place and friendly service when I go, I'm getting a cup of the cream, peanut butter and blueberry tonight.

I would recommend this place anytime! I've always loved Cold Stone, and the staff are always friendly, but there's never enough people on shift. Every time I go in there, whether it's a Friday or Saturday night, there's usually one girl, stressed and rushing all on her own. There are nights where multiple customers have left because it just takes too long. I have been here several times. Service usually varies between not great and decent. This experience yesterday night was nothing short of unremarkable. There was three of us, we were greeted with a half hearted greeting. I ordered last out of our group of three and I waited an unnecessary amount of time (5 minutes) to be greeted and asked what I would like to order. Mind you, this is with no one else in front of me. That said, once the lady asked what I wanted, she completed my request in a reasonable amount of time and correctly.

Ice cream is always good. 3/5 stars due to wait time and general indifference to us walking in. This is the BEST ice cream place in town!!  If you haven't tried or heard of Coldstone you must have been living under a rock.

Staff is always friendly and prices are very reasonable.

Alma helped us and she was very friendly and personable. Cold Stone is some tasty ice cream mixed up with some tasty candies.  All the standard Cold Stone offering are available here.  Service is friendly and cheerful.
This particular location is right next to a Harkins theater and a sushi restaurant, all the way back across the hellishly hot asphalt of the worst-designed shopping area in town.  But hey, after crossing that heat sink of a parking lot get yourself some ice cream.  You deserve it! VERY disappointed. I ordered a salted caramel ice cream cake for Fathers Day. It was inedible. I think they just added table salt to the caramel. AWFUL, and far from cheap. They also screwed up the inscription, which we just laughed about. The cake ended up in the garbage. Next time I'll pay half the price and see if Dairy Queen can make something edible. Girls behind counter we're totally confused! One girl started helping me then another jumped in. Don't know why because the first girl was doing fine. Second girl had us all confused! My fiance just wntd the regular mint choc chip & she was trying to tell him tht she would hv to chrg us because it had three mixins. She didn't realize tht he only wanted the regular mint choc chip ice cream not the fancy kind.
Then, they got my order wrong! I ordered 1/2 black raspberry & 1/2 butter pecan. I got 1/2 coffee instead of butter pecan. I ate the black raspberry but threw the other away.
They need to have girls in there who actually listen to what u say instead of just half assing their job!!! Needless to say i'll prob go to DQ or some place else next time!! :( Not very COVID conscious! I went in to get ice cream and it was packed and they allowed customers to talk and lean over the counters where ice cream toppings were without a mask! I left without getting anything after I saw this happen for about 5 minutes. Classic me was In search of some diabetes in a cup but like I don't think this location exists. I drove around for a solid 5 min looking and no cold stone.  Maybe I need some glasses but last time I checked I had 20/20 vision This was my first time at that Cold Stone!! It was very neat and the ice cream was so good!! We wanted to go for a sweet treat, and ended up very disappointed. First off, the price is too high for the quality we did not receive. Second, all of our ice cream was melting right after we got it. From my understanding, after putting it on the "cold stone" it should stay frozen longer? The taste was also off and finally the employees weren't very knowledgeable when we asked for certain ice creams. Norberto and Jourdyn gave great customer servic

                         ## Rank: 12: Bombolé | (4.5)
                         **Category: Restaurants, Food, Indian, Empanadas, Honduran
                         This place is absolutely delicious. You can tell they put a lot of time and effort into making each empanada from homemade and high quality ingredients. I will be back forsure. 100% recommend!! Love this place. Always have a great experience coming in. The staff is always friendly and ready to answer any questions that you might have. The selection of empanadas is wonderful and they're all delicious. My favorite restaurant to eat at downtown for lunch.  Quick to get in and out of and has great food at decent prices. I don't know how this place got 5 stars. The only way I could consider that is if they were being evaluated solely on location. It's across from the library main and in the office building by Ike's, so great if you work downtown. The location is clean, well lit and the staff is pleasant and courteous. That's it.

Here's the thing I've had Honduran and Indian food. This is neither, or both done poorly. The meat pies should not be called samosas, just meat pies. The filling is dry and tastes like the tears of the colonized ancestors of both countries, not like an actual samosa or paneer! To be honest I went at 2:00 and they were out of the butter chicken AND the slaw so I cannot speak to them, but I probably won't try it again. There were no beans, there were curry lentils, which looked suspiciously under-seasoned, so I didn't try them.

I had to leave and finish my lunch with a half hummus salad from Ike's next door because I was hungry and I had to wash the taste of that dry, cardamom-less dough out of my mouth. Blech.

This is one fusion/bistro concept that somebody's ethnic friend should have STRONGLY DISCOURAGED. Consider yourself warned. Went to Bombole as part of a Taste of Tucson Downtown tour this past Wednesday. Bombole features a fantastic assortment of empanadas and homemade refreshing teas. Mine was made with paneer and was adorably stamped on the crust to let you know what you were eating! The homemade dipping sauces were excellent, my favorite being the mint chutney and the cilantro sauce. Would definitely eat there again. Whoa, this place is one of a kind!!
I was immediately intrigued by the concept, and I absolutely love fusion cuisine. It's awesome seeing how people's unique cultures intertwine to create some amazing new food.

The restaurant is cute and the smell of the aromatic Indian food hits you right when you open the door. Unfortunately there is pretty limited seating, but since the food is a relatively quick eat, turnover is pretty quick as well!

I tried both the chicken and pork empanadas, and they were both so tasty! I like that they have different fillings that correspond with different Indian dishes, so you can have completely different food experiences with both. I think what put me over the edge were the sauces. They were so good, and super flavorful and added just the right touch to the empanadas.

I can't wait to go back and try the other flavors. Already dreaming about my next trip there! This restaurant just opened Monday, July 30th in the Pioneer building in downtown Tucson.  The empanadas are delicious.  Bombolé fills its empanadas with Indian curries like butter chicken and spiced potato aloo matar.  The potato aloo matar is flavorful, spicy, and the empanada dough is not too thick.  The combo plate comes with two sides plus iced tea for about $9 - an affordable price for lunch downtown.  There is not much seating but given the downtown lunch crowd most people will be taking away.  The staff is super friendly and helpful.  Great addition to the downtown food scene. I stopped in here for lunch and looooved it :) I had the butter chicken empanada with tikka masala, beans, rice, and salad. The empanada was crispy and flaky and buttery goodness filled with a delicious savory chicken filling. There's a spicy "warning" on it but I found it on point. It went perfect with the tikka masala sauce which was also spiced to perfection. Now, I love me some beans and rice, and I was skeptical of their lentils at first, but I'm converted now! They were smooth and creamy and paired excellently with the rice, which was cooked perfectly.  The salad was a nice cooling crunchy tangy side to compliment everything.

The restaurant itself is brand new and the style matches the fusion food well. It's bright and airy and clean. Service was friendly and fast! My only problem was I should have got more because it was so good! I will be back for sure. I was in town for work and was looking to try out something new for lunch. Came across Bombolé and was intrigued by the fusion concept. The chicken empanadas was good. May be it's just me but I wish they had an option to serve  warm basmati rice, lentil curry and chai. I tried the cilantro sauce good. I am giving  because I feel it is great fusion but still has room to improve The flavors!  What a great little lunch spot. I like that the food is healthy too.
I went with a combo that included a butter chicken empanada and two sides: l

                         ## Rank: 13: Sushi To Go & More | (4.5)
                         **Category: Sushi Bars, Sandwiches, Fast Food, Restaurants, Food, Juice Bars & Smoothies, Bubble Tea
                         This is a great spot for grabbing sushi quickly. I recommend having them make one fresh versus one that's been sitting. My favorite is the Hawaiian roll. Their rice is so much better than Frys or Safeway or most sushi places here. I don't recommend their boba drinks. I've been disappointed in them. Otherwise a great addition to the Eastside. Although we didn't order food today I have to say this restaurant is almost like an asian deli/lunch spot with what they have on their menu. Their sushi looked very fresh. No brown avocado or transparent cucumber. We ordered two of their blended mango boba teas. Normally boba is super sweet and this was not. It was very refreshing and had plenty of tapioca pearls that I love! I was a bit sad that they didn't offer iced tai tea boba but the mango was so good it made up for it! I'm hoping to come back soon to try their sushi! The staff is very friendly and worked super fast. We will be back again soon. My only recommendation is that they get more fruit and gummy candies for their boba and add in iced not only blended. People love boba and this place will be super busy if they have more options for the boba alone. Thanks for the great service and boba today! I eat sushi two or even three times a week. I go to takamatsu almost every time. I just moved into the neighborhood near Sushi to Go. I support as many local businesses as I can so I wanted to try what they offered. I was not disappointed at all. I got the party tray and was very happy with the rolls. All were put together and flavorful. The spicy salmon was my favorite. I also got some salmon nigiri that was just as good or better then takamatsu. I will definitely be back and order different rolls. The sushi chef was nice as well. We talked about beer and wine while he made my rolls. Says he is gonna have beer next time to sell. I walk by Sushi To Go frequently when I go the restaurant next door. I don't ever remember seeing anyone inside. This time I ordered a couple of items to see how it is. The roll I ordered was pretty good; it reminds me of the rolls that are made fresh daily at the grocery stores. The price is very similar too. The Vietnamese hot dog they serve there is very inexpensive, but I will definitely not order it again. The bun was very stale and the lady in back microwaved the hot dog. The vegetable toppings were fresh tasting, so it made it edible. I work in the area and stop into this place regularly. I'd say that Sushi 2 Go is great for what it is. They make basic sushi fast and quick and their prices are phenomenally low. It's worth noting that I've eaten just about everything here and enjoyed the food every time. Brought a lot of doubters from work and everybody has enjoyed it. I would not go into this place expecting Sushi on Oracle or one of the highest end sushi places in town. This is a nice quick stop for cheap lunch sushi, something you could afford to eat for lunch all the time which isn't what sushi is for most people in Tucson. Rating it based on what is essentially fast take away Sushi it gets 4 stars from me.

I've personally tried a good bit of the menu but I'd say the Tucson Roll and the many variations of the California Roll are my favorites. Their sushi rice is nice, I've gotten a side of it alone to supplement a roll before. I regularly got the nigiri sushi before but I'll say they go a little too heavy on the rice for the nigiri, with the rice-to-fish ration a bit off. Everything tastes great and as stated before and by others on here the prices are cheap. $4.25 for a California Roll is a nice cheap lunch. They do NOT have some of the crazier rolls they'd have at a sit down sushi place, like the deep fried whole rolls (ie the Vegas roll), which has disappointed people I've taken before.

Same young man and nice older lady are in there every time I've gone. Both are very friendly and helpful with any questions every time I've gone in. Place is very minimalist, just a few nice looking tables and a counter.

Worth stopping in to check it out one day when you're feeling something lighter for lunch, or you've been going to Hot Wok next door and need something different for once.

An Edit: Based on another reviewer's experience I will say that if you order a California Roll or other roll and there is one in their cooler up front that they already prepared they will go up and take the already prepared roll and give it to you. I've never had an issue with this but I could see some people having an issue, the people at the restaurant have always been so friendly I can't see them refusing a request for the order to be made fresh but I can see this catching some off guard. This is behind the Chinese restaurant that I had gotten take out a few times... I can't believe I never noticed it. The sushi is outstanding. The gentleman preparing the sushi would sing to himself, and I really liked that because I figure he really likes what he's doing. I got the spicy scallop, spicy crab, and tempura s

                         ## Rank: 14: Fresh Sushi Pho | (4.0)
                         **Category: Japanese, Restaurants, Sushi Bars, Food, Coffee & Tea, Vietnamese
                         Freshest and best sushi in Tucson. I have eaten here multiple times and every time has been fabulous. My boyfriend and I came here today around 2pm. It wasn't busy at all which is what we like. Customer service was great, they were always on top of things. My boyfriend ordered the Pho Chicken and I ordered some sushi rolls. Both came out in a timely manner and looked really good! He enjoyed his pho and I thought the sushi was impressive. We'll be returning here soon :) After trying this restaurant based on the yelp reviews... I found that their PHO was alright. Not my favorite as the broth was either too sweet or, too salty. and the Pho Ga... was actually chicken thighs rolled into little chicken balls. Sadly, I feel as though I have had better.

The sushi however, seemed really well prepared and the service was very good. Also their "ice tea" is a blend of jasmine and green tea. Whatever the tea was... I would recommend.

Great atmosphere and love the decorations within this restaurant. I love coming here for the small and quiet atmosphere. The pho is great, plenty of sauces to add to it if you want. Sushi is fresh! Nagiri on fire is awesome. Very attentive service. I have nothing bad to say about this place! We have always had great service and food at this restaurant. Kind of a unique set up inside but the food is always good. Hidden gem. We stopped in here the other night wanting some pho. We arrived around 6:15 and grabbed a table right away. Not long after, the place filled up and finding a table would have been difficult. My sons ordered beef fried rice to share. I tell you it could have fed 3 people. The rice was perfectly cooked and the beef was tender. I ordered the seafood pho which was the best seafood pho I've ever had. It was more meat than I expected and full of salmon, scallops, shrimp, and mussels. Everything tasted fresh and was not over cooked. My hubs ordered the beef pho special which came with an order of California rolls. The meat was all lean with no fat and the broth was perfect. I am a sushi lover and was dying to try some of their sashimi and rolls however, being pregnant, I will have to wait to go back for the fresh sushi. Judging by the California rolls, I am sure it will be excellent. The rice was not too sticky, seaweed was high quality and not too fishy. The crab was fresh and not too creamy, leaving for flavor that typically lacks in California rolls. In addition, the cucumber and avocado were fresh. The pickled ginger (my personal favorite) tasted fresh and not from the jar which is what I expect from any sushi place but sometimes hard to find. We also ordered the egg rolls which is my hubby's favorite. They were small but tasty and the sweet and sour sauce they came with was amazing. The staff was attentive and friendly but not annoying. They checked in periodically but gave us our privacy to enjoy our meal. The restaurant was clean and the lighting was so relaxing. Ok I'm not going to rate their customer service since it's just open and staffs are new. This review is only for their food.

We ordered Pho dac biet, lemon grass beef with noodle, spring rolls and one salmon roll. Pho's broth is tasteless and of coz you gonna need help from hoisin and Sriracha sauce; very little meat... Lemon grass beef is under seasoned, we expect a good aroma and flavor from the meat, but no, just plain; and on top of that, the fish sauce is plain as well, it does a poor job complimenting the dish. Spring rolls are ok, peanut sauce is good. Sushi is bad and it's understandable since it's not a sushi place, I guess $5 is worth it for 8 super small pieces of sushi rolls.

In short, the restaurant need to put way more work toward food quality, very nice decoration though. I love their seat, very comfortable :) Awesome!  Great sushi, original rolls, and amazing prices.   My favorite sushi and Pho in Tucson.  Gets busy time to time. Best sushi in Arizona! Great service and pho as well..I didn't think you could be great at both Pho and sushi,  but they found a way.  Loved it, definitely coming back! Delicious food, cheap sushi, and awesome Thai tea! Small location, super friendly staff, and cheap! This place is a must if you like sushi and pho Food is great, but they only have one waitress. If it's busy, expect to wait a while. I went right when they opened and got my rolls within 10 minutes. I got the tuna mini roll & Vegas roll and both were delicious! Staff was really friendly and attentive. My only complaint is they were stocking the table while I was eating. Not a big deal but being they just opened I would imagine it was something that should have been done at closing/before opening or at least wait until I'm gone. I will definitely come back and reccomend this place to friends, family and strangers. I've been here several times for both dine in and Togo. Today, I decided to go since I've recently caught a cold and figured some hearty pho can help me heal. Searched online for a menu and wh

Label Query: Romantic Italian dinner spots

                         ## Rank: 1: Wildflower | (4.5)
                         **Category: Event Planning & Services, American (New), Food, Beer, Wine & Spirits, Gluten-Free, Venues & Event Spaces, Burgers, Restaurants
                         Yum. One of my Favs in Tucson. You can't beat the happy hour deals. Full portions for tiny prices.
I had my favorite... sliders. Real hamburgers with bacon and Irish cheddar cheese. Delish.
My friend had the fish and chips and said they were fresh, light and tasty.
Waitstaff was attentive and friendly. I just love sitting on their outdoor patio.
We try to visit at least once a month. Wildflower is amazing. Not only is it reasonably priced, but the service is great, and the drinks were fabulous. My favorite Sam fox restaurant for 20 years. A lite dish artichokes with a glass of wine is excellent. Or if very hungry their spinach pasta or their braised beef. Yum!!! Be sure to make reservations at this place since it usually fills up extremely quickly.  I love the decor in here and the food is wonderful.  They serve just about anything you can think of from seafood to streaks to salads-it's all good.  Service is second to none but prices are a little high-that's my only beef with this place. 1st timer for dinner and we loved this place. Made a resv through OpenTable app for our anniversary and they made it special. Patio is great in cooler season. 'Chef's board' appetizer is a tasty start. And we still got fresh-baked bread before that came. My wife's pork loin was to die for - perfectly cooked and moist throughout. My sea bass was awesome. And they comp your dessert for a special occasion if they know about it in advance. We'll be back again! Wildflower is one of the slightly more upscale places that I have been to in Tucson. I feel that it has a country club vibe (though I was brusquely reminded I have never been to a country club). Nevertheless, they have a cute little bar, indoor and outdoor seating, and comfy paisley green booths.

The cocktail menu was fun, I should not have gotten the mint skinny. But what is a girl to do when she's planning to eat a lot since the menu looks delicious. The other drinks going by me looked tasty though.

The bread was toasted (plus!), and served with two herbal butters (double plus!).
The Grilled Whole Artichoke was yum. Getting my hands dirty is always a must in a complete meal.
We then had the Butterleaf Salad which was good, but has already faded from my memory.

The Spinach Pappardelle !!! Let me just say pappardelle, which I didn't even know how to pronounce last week, is my new favorite pasta. (fyi the pasta is made with spinach, there is no spinach in the dish)

Happy Hour every day from 3-6 pm! Includes beer/wine/sangriawell drinks and food specials Great food.   Pappardelle   with chicken is outstanding. All dishes were good. Fun place to celebrate  a b day Friends wanted to go to Wildflower for dinner.  We ordered the half chicken.  It was service raw and returned.  They then service chicken so overcooked that it was a rubber chicken.  House salad was bland and small.  Fried shrimp and vegetables were tasteless.  Other main courses were average.  To compensate for the chicken, the manager considerately gave us free dissert, donuts and toppings.  The donuts did not even remotely taste like donuts, just dough.
I think that the restaurant is relatively pricey for Tucson and is very pretentious.  Not worth the money. Went their for a Birthday celebration.  The table was ready to go and everything was fine until the service started............

10 ppl, entrees came out staggered, first 2 plates, seafood so by the time the last entree was delivered, the first two plates were cold.

Server never came back to see if everything was prepared correctly, if she had she would have discovered that one seafood item was raw and the other overcooked.  Two entrees were served with Polenta and the person who was celebrating her birthday had to ask where the polenta was.  Very small portion.  The same with the other entree with polenta, very little polenta.

Ordered coffee, delivered the coffee but had to get up and ask a server for re-fills, if she had come back to ask if we needed more coffee, she would have discovered that she forgot to deliver one that was ordered.

Never saw a Manager on the floor and the server must have determined she was not going to work any harder for her guaranteed 18%.

Will I go back??????  Probably sit at the bar for happy hour  or just  come as a couple, they seem to be incapable of handling medium sized parties. Delicious foods with interesting flavor combinations that will tickle your taste buds! The French dip was very good.  The cheeseburger with their strawberry and thyme cocktail was wonderful. Definitely going to this restaurant again! I normally love Fox restaurants, but this one leaves a lot to be desired. I ordered the sweet potato tortelli with savoy cabbage, bacon and sage, as well as a side of baby bok choy. I do not eat bacon, so the bartender had a great suggestion to substitute the bacon with butternut squash.  The tortelli and bok choy arrived and right off there were some issues.  The butternut squash was missing. The bok choy

                         ## Rank: 2: Ciao Down | (4.5)
                         **Category: Food Trucks, Pizza, Italian, Restaurants, Food
                         It was clearly fate, we came home and decided to try Marana Craft and Wine. Ciao Down was parked outside and this pizza is amazing! Service is friendly and probably some of the best pizza in town. If given the chance you should do yourself a favor and try some. There is always somthing that draws you in on food trucks, with this one it all starts with the awesome renavation of an old bus in to a cute Italian pizza shop on wheels. They hand craft your pizza cook and serve it to you in minutes. The truck is all windows so you watch them toss and pull the making perfect crust mind you they are about 10 inch rounds but pile with the best fresh ingredients. The pizza was so delicious from just the right amount of sauce, generous amount of mozzarella and the topping are just soo fresh! For the price this was a great deal I order the edgy veggie and it fed three of us. They are vegan friendly too! Wash it all down with a hand crafted Italian soda. Check out their fb page for were to catch this moving hot spot cause you wont wanna miss this one on pizza night. https://www.facebook.com/ciaodowntucson/ Seriously the BEST food truck in Tucson! I tried the Snake Bite Pizza, it truly compares to none! So so delicious, full of flavor and it was cooked to perfection. One person ordered a pizza and added additional ingredients to it and the staff was eager to do so. I paired my pizza with an ice cold Strawberry Italian Soda and it was simply amazing. If you have the chance, check out Ciao Down. I promise, it won't be last! I am in LOVE with the Snake Bite!!! This is so freaking good. Has a nice heat to it from the fresh jalapeños, the jam adds just the right amount of sweetness, clothe crust is perfect between crispy and soft and the BACON! It adds all the right feels to this dish! Very good pizza, as long as they don't sell out! How do you sell out two hours before your scheduled to close!!???? Very disappointing. The best pizza in town hands down! From their inventive recipes and high quality ingredients, to their A++ service, the crew at Ciao Down doesn't disappoint!! Honestly, I was a little hesitant when I had my first bite- the breakfast pizza. Who puts gravy on a pizza after all?!? Well, let me just saw it was an explosion of taste I couldn't have imagined and I was all of a sudden surrounded by the comfort of back home. I was the happiest clam in the bunch!! They deserve a Michelin star for their creative and absolutely delicious approach to food. If you haven't tried them, wow you are missing out! If you want an absolutely divine eating experience, head over and Ciao Down with them!!!! You won't be disappointed! Absolutely the best pizza in town! I think I might be addicted to it! The snake bite is incredible, with the extreme supreme coming in close at second place! They can even cater special events! Definitely check them out, you won't be sorry! Some of the best pizza I have ever had..... and, trust me, I have had a lot of pizza in my 50 years.    So many options for all likes and tastes.    Love that you also have gluten free options too!!!! Had the Snake Bite tonight and it was amazing! For real. Totally different (raspberry chipotle sauce, cream cheese, jalapeño, bacon & mozzarella). It isn't often the hubby and I agree on a pizza, but we both loved this! It's a must! This is hands down the best pizza in Tucson! The champagne dough is chewy and fluffy on the inside, and packs the perfect crunch with ever wood fired bite. I've tried nearly every one of the pizzas and while they are all incredible, the snake bite is my fave! I look forward to their monthly pizza, their creative offerings are unmatched. Talk about fantastic tasting pizza....and from a food truck.  Hands down, our pizza was delicious!  I got The Classic Cheese with fresh basil, and the hubby got the The Classic Pepperoni.  Piping hot, bubbles on the crust, fresh ingredients....total deliciousness.  I am in love with this pizza!  Great customer service!  A+++ We will be on the lookout for this food truck's future stops. Absolutely the best pizza we've had in Tucson! The snake bite is amazing and one of a kind!

                         ## Rank: 3: Mama Louisa's | (3.5)
                         **Category: Italian, Restaurants, Nightlife, Bars, Pasta Shops, Caterers, Food, Specialty Food, Event Planning & Services, Cocktail Bars
                         My husband and I visited mama Louisas last week and were pleasantly surprised. We hadn't been here in awhile and wanted something different. They handed us their new menu.. If I recall the old menu was a couple of pages, they narrowed it all down to one page with the top being items from the original menu and the lower portion being items from the "new generation". They managed to keep all of their core meals and everything sounded amazing. I  ordered their red blend wine and their chicken parmesean and my husband ordered Joe's special.

If you are a cabarnet drinker, stay away from the red blend wine.. I took a sip and it seemed carbonated.. I asked our server who then explained that the red blend was in a keg.. I couldn't wrap my head around that.

Overall the food was amazing as usual and the atmosphere is comfortable. I really enjoyed our meal and thr service was awesome. Our visit today was amazing as usual. Fast service, great food, friendly staff. It's no wonder this place has been in business as long as it has, and I hope it continues for many more years. Food: They are known for there fresh homemade food so, coming in I expected a lot. Bread stick with the meal where typical like Olive Garden but more flavor. For the appetizer we got pizza bread, which was like small thick crust pizza, light on sauce, heavy on cheese, we asked for a side of ranch, and it was also fresh. We got egg plant parmesan and penne with Italian sausage. Both where good except the sauce had zero flavor. I had to dump salt on it and when I ask for cheese they pointed to the shaker on the table, basically lowering them to the level of peter piper pizza. If the sauce had any taste to it I could give this place a better review. Drinks: they served drinks in little 12 oz plastic cups that had to be refilled every 10 mins. Atmosphere: Its actually quite nice inside. Decor was theme like Italy in the summer and they had a full bar. Bathroom was a one seater but not that clean. Service was ok but the cook but must work slow because it took two of us about 1.5 hours to have a meal, mostly waiting for food on a pretty slow night. Parking is scary as it was low lit in a not great part of town. Over all if the sauce was good this place would be nice for dates but due to what seemed like higher then average price to quality ratio I wouldn't take your whole family. Hadn't been in a while but was hearing good things about the food with the generational change in management. Wish I could say things lived up to the 'good thing's but can't. Service was hot and cold. Took awhile to get water and then the waitress disappeared for an unusual amount of time. Other diners seated after us were attended to and some actually ordered and had appetizers before our waitress reappeared. She would check on us but seemed very distracted and unenthusiastic to be waiting on anyone. Food arrived. Tasty but the sauce was skimpy. I had th scampi. Sauce flavorful, pasta done well, shrimp seasoned well and cooked well but there just wasn't much sauce. Partner had chicken Alfredo. Chicken well seasoned and tasty but again the sauce was skimpy
All in all food is tasty but between the skimpy sauce and the on again off again service not something I'm eager to return to. We were in town & decided to try this place. Overall pretty good. Everyone liked their meals & the breadsticks were fluffy & delicious. They have a salad bar too.

Like most places- the portions were ridiculously huge. I wish there was an option to get a half size for a cheaper price. $11 for a bowl of pasta is a bit much. & since we were in a hotel, taking leftovers wasn't an option.

What really made me happy was that this place had aperol spritzes. I hadn't  yet seen an italian place in the Arizona with this real Italian drink! It was made correctly & delicious. The location is great since we're staying at the FamCamp at Davis-Monthan AFB. But we were a bit disappointed in the Chicken Marsala. The chicken was overcooked, and the mushroom sauce was more like beef gravy, hard to imagine it was made with Marsala wine. Fettucine was very good, as I would expect, given that they make all their own pasta. Maybe we'll try the lasagna next time. Or the soup, salad, pasta bar. But it's thumbs down for the Marsala. Good service, though, and very nice ambience. Love Mama Louisa's! They're super close to where I work and they have a lunch time special where you can choose "All you can eat Pasta". They make your pasta the way you want it! Mix any type of sauces together with any type of pasta you want! You can never go wrong Went here last month as someone gave me a gift certificate for Christmas.  I have always wanted to try this place, as I love homemade pasta.

I ordered the Joe's Special.  This is their signature dish.  I thought it was pretty good.  Not spectacular, but good.  While I don't think the pasta is the best in Tucson, I think the other items they offer make up for it.  I really liked the soup

                         ## Rank: 4: Caffe Torino | (3.5)
                         **Category: Wine Bars, Italian, Food, Nightlife, Bars, Coffee & Tea, Breakfast & Brunch, Restaurants
                         Best service I ever had ! Love the food and the server ! I would highly recommend the sea bass that was on the special for the evening, as well as the sever Ryan. One happy customer ! Will be back ! Delicious Italian for Breakfast, Lunch and Dinner. Great service and a nice atmosphere combine for a great experience. I've never had a bad experience. This place is a gem. Staff is friendly and attentive. Always check out the specials. Crab cakes are great. All pasta homemade. Daniella and staff are friendly and interested in making sure you have a good meal. Breakfast served quickly with very fresh fruit, lovely prosciutto over eggs, and toasted ciabatti bread. Service was friendly and conversed about local events to help provide information to me as a new visitor to Oro Valley. Tea is fresh brewed and plentiful. There were 4 of us for dinner. Our entries were all different and 3 out of the 4 were extremely well prepared and presented. The veal piccata was disappointing in that it was thin and tough. One of our guests received the wrong entree but the restaurant quickly corrected the mistake. The wine list was above average and they had a special discount that night on their wine list which was a real "price performer". The ambience was decent and the location was extremely convenient. I would recommend this restaurant and will go there again. Our server was fabulous! Maybe the chef was having a bad night with the veal piccatta...... I've been here for breakfast several times and today stopped in for lunch. I had an awesome salad - full of fresh greens, chicken, salami, artichoke hearts, capers, red onions, etc.. -- so good! I can see myself craving it often! Best part is they serve their salads in big pasta bowls! That's how I serve it at home - much easier to eat from than a plate!
Breakfast is also really good here, great coffee!
I'm definitely going to try it out for dinner! Love Love Love Caffe Torino!! This place has fantastic breakfasts, especially the blueberry pancakes! The lunches and dinners at Caffe Torino are delicious too!! The Ollie's Pizza is Amazing and can easily be shared. The menu has plenty of choices to please everyone. The servers and bartenders are extremely friendly and informative!! Really nice bar with comfortable booths in both bar and restaurant areas. Lovely patio dining!! The owners are super nice and really care about their customers! Highly recommend!!! You will Love it too!!! We had dinner here tonight...the food is outstanding, try the lasagna, you won't be disappointed, we had great service, wonderful food, best in town. First timers at Caffe Torino and LOVED it. Wow the atmosphere is great and the food is beyond spectacular. My husband and I went here on a date night and were so glad we did. The bread they bring out for the table is extraordinary. I wish I could put it in my pocket to eat whenever I'm feeling down. We also got the bruschetta appetizer, split the garden salad, and each had a pasta dish. The portions are pretty big so we definitely left full. Their traditional, family recipe Bolognese sauce is out of this world. It reminded me of my grandfathers sauce who passed away a few years back. It's been difficult to recreate his recipe, so this sauce almost had me in tears. I may just go back to order a gallon of it to use for me Dinners in the future. My husband really enjoyed his rigatoni dish with sausage and pink sauce. We will definitely be going back, and I can't wait to bring my family to enjoy this sauce as much as I did. As a side note, dinner moved pretty fast, so I would space out your ordering if you want to hang for awhile. We had received and finished al portions of our meal in just over an hour! It also gets very busy so a would recommend making a reservation.

Bottomline: Sauce it up, baby! Why go 6,178 miles when you can be insulted in a Tucson Italian restaurant? Ok, here is the scoop, had reservation,  showed up on time, told we could have a nice booth until behind us arrives the "friends" (complete with two cheek kissing.),that were late for their reservation (fashionably I am sure).We are then offered a "quaint" table for two in what only can be described as an alley way to the kitchen.
Waitress was cheerful and efficient, but waited for food in about the same time that it took ancient Romans to build the highway system. Seriously, this was our second visit, last time we were seated next to the kitchen and witnessed an all out fight amongst the cooks (training for the Coliseum??). Not sure if that was what was going on this time as we were in the alley and did not have a view of the gladiators (cooks).
Food was good, wine was good but typically over priced. With all of the choices for Italian food in Tucson I just dont get it why service   (again not the waitress) should be this bad, but it was.
Io sono per la mia strada per l'Italia, at least there I can be insulted by real Italians The service was great and the refills were plentiful.

3 sta

                         ## Rank: 5: Perche’ No Italian Bistro | (4.0)
                         **Category: Bars, Food, Gluten-Free, Coffee & Tea, Nightlife, Wine Bars, Restaurants, Italian
                         Four of us had dinner here with a reservation before going to the ATC.  We were seated promptly.  Server was friendly and accommodating.  Service was prompt.  Food was excellent. Great atmosphere.  We will return. What a disappointment! Saw a new place in town and all 5 star reviews (lies, or from nut jobs)
Everything was frozen. Started with the calamari and it's served with the Mae Poy chili sauce. Remind you it's an Italian restaurant. Calamari was blatantly frozen and not sure about the Panko crumbs....
Also got the carpaccio. Too many capers which made it salty. Served with several baby tomatoes uncut. Lazy chef who didn't think of dicing them perhaps?
Entrees were a disgrace! The veal tasted like chicken fried steak smothered in a salty and sour cheese that I scrapped off. The polenta was a rectangle and also not fresh. Burnt asparagus along with a vegetable medley that was probably frozen but not cooked well. Is it hard to sauté fresh vegetables with olive oil and some basic seasoning? Apparently at this place, the answer is yes
Brother got the sea bass piccata. Fish was soggy as ever and I asked the waiter if it was fresh. He told the truth and said no. Since we had been gutting a house all day we were starving and ate the proteins at least but overall what a disaster. Our waiter was very nice and the best thing on the menu was the tiramisu. This place ain't going to make it. The entree prices are 25$ or so and if you can't serve simple fresh food what is the malfunction? Will not return New to Downtown Tucson.  Food was excellant.  Had Ling Cod off the Happy Hour menu.  Nice patio with fans and heaters.  Family owned.  Don't miss this one! We started going to PERCHE' NO since it opened. My wife is a fantastic Italian Chef, but even she needs some time away from the kitchen. So I started taking her to Perche' No when it opened just three weeks ago. To our amazement it was fantastic. All of a sudden, my great wife is looking for more time away from the kitchen.  Since the food at Perche' No is so fantastic, I have no problems making my wife happy.  We have only gone back 6 times in three weeks...but who's counting!
Love the place and the people.  The family has only been in the restaurant business for 20 years, so they know what they are doing.
BTW PERCHE' NO means WHY NOT! Classic case of owner/chef who thinks he can cook but doesn't understand that using frozen ingredients for everything results in a disappointing dish. How does this place have five stars? I'm sure he requires all the new hires to leave a review. This place will sadly stay open because of all the 70 year olds who have no taste that enjoy microwaved dinners because it reminds them of their pathetic childhoods. My advice? Burn it down and collect the insurance money. We had a wonderful afternoon at Perche No. We were well received by the staff and owner, Jules. The food was delicious and served hot! Loved it and will definitely go return soon. We were heading to eat something before a concert downtown, 10/15/21, and noticed a new Italian restaurant was open. The inside is similar to the previous restaurant that was in this space. I loved the decor and the atmosphere at night. We changed our plans, on impulse, and went in. It was a good decision.

We were sat at a nice window table and everyone was inviting and friendly. We told them we had just over an hour to eat, they made it work, and the timing was pretty good.

I had a glass of wine and my husband had an Italian soda. We were given bread with olive oil and vinegar but we didn't get a chance to try it.

The menu isn't large but there were many good options. We thought the prices were good, especially after we saw the portion sizes and tasted the food. We decided to start with soup (lobster bisque) and a salad then share an entree. The soup and salad were large and good. Either of these items would have made a nice light meal. The cod entree was delicious. We paid a $2 split plate fee for the cod and it was worth it. Everything was fresh, the correct temperature, and cooked perfectly.

We hear they have a happy hour menu and even a kid's menu. They also have a dessert menu.

We will be back again soon. I am so glad there is a new good option for dinner downtown. My wife and I decided to give this a try since we were going to a show at the Fox.  Of course we compared every experience here to when it was the wonderful Cafe Milano so the bar is set high.

My  first hint that this wasn't going to be a great experience was the bread - cold, tasteless and something that could have come off the shelf at Costco.  We, of course did not come for the bread so onto the main courses.

We ordered the Bruschetta as an appetizer and although I know it is served with the toppings cold, the bread is normally right off the grill and still warm but it all tasted like it had been refrigerated before serving.

I'm trying to eat a little lighter so just ordered the lobster bisque which was quit

                         ## Rank: 6: Sbarro Italian Eatery | (3.5)
                         **Category: Italian, Pizza, Restaurants, Food Court
                         Took 10 minutes to get anyone's attention to actually buy or meal tonight - others in our group who got food elsewhere were halfway through their meals before we could get anyone to come out from the back! We even tried calling the phone number and they didn't answer - had to yell towards the back - unacceptable. Asian cashier is also a cook prep. Never washed his hands before adding toppings to our pizza. They only have 2 food choices for this new mall. Not good for the consumers. Please consider eating before you come to this mall. Pete and the team are handling the busy Black Friday like champs and treating customers like they matter. Great experience. Thank you. First time delivery order with Sbarro. I always thought it was a place like Pizza Hut or Peter piper pizza. I was so wrong, the pizza was delicious. I ordered a pepperoni mushroom pizza. It was so tasty. Way better than Little Caesars or Dominos. Slices are a little pricey, but we usually buy a whole pizza for our family which is a bit cheaper. Wow! It's been a long Timmy e since I've had thIs kInd of service. What kind of service, you say? The Kinney where a manager goes out of his way to make things right. They just started serving pasta so I thought I'd give it a try. But was disappointed as the bottom of my pasta container was vvery watery. I told the young woman aardvark she was happy to drain it and give me more sauce. Fine. That solved the problem. However, not so for the manager. He went out of his way to come over to our table and apologize. Then offer me an entree to take home. I left very happy and will return.

                         ## Rank: 7: Signature Grill | (3.5)
                         **Category: American (New), Restaurants, Southern, Breakfast & Brunch, Beer, Wine & Spirits, Food
                         So the place was packed with conference attendees and very noisy. The atmosphere was elegant yet comfortable.
Service was attentive and very helpful.
We both ordered the filet medium, one came medium well the other rare, but both tender and juicy, with a delectable sauce, perfect finger potatoes, and grilled tomatoes. The Conn Creek Cab was wonderful. Did not care for the chocolate cake though. Disappointed in the meals here. Plastic was around the short rib and the filet was very bland. I think the short rib was pot roast. The fielt had to much butter sauce. Scallops were good. I would like to say the server was awesome The chipotle chicken salad Is delicious! The outdoor seating is highly recommended. You can't go wrong with the view.   Came back for breakfast  and dinner,  both times the service and food was excellent! Fresh and tasteful! ! Amazing service and delicious food!  The food came out pretty quickly, which is always nice when you're hungry.  The atmosphere inside and outside is nice as well.

Normally I would have given this 5 stars, but the prices here are crazy!  I know it's a resort but $5 for a bagel??  Seriously?  $5 for one bagel??  That's nuts!

Besides the crazy expensive prices, this place was great! Great breakfast buffet.  Very pleasant staff- Terry, Celina, Joe were so nice and knowledgeable about the area.  This is the best way to start a great day at the resort.  Also, my son loved the southwestern salad at lunch. If you didn't know that Spa Week was in AZ last month, you definitely missed out.  Spa Week means $50 services at great Resort Spas, Salons, Day Spas, etc.

Sara G. and I were on a mission to relax, outside of the Valley of the Spa.  We ventured down to the JW Marriott Starr Pass Resort in Tucson.  The setting is nestled directly beside the Saguaro National Monument and offers amazing views of the Tucson valley.  We truly soaked up the views from the patio of the Signature Grill.  After a great massage (Sara G. didn't agree), we ordered some Chips and table-side Guacamole to start.  Sabino was a great server and no, he wasn't named after Sabino Canyon, but rather his grandfather.

The setting, the salads and the price point are on par with a 4-5 resort, no complaints here.... HOLY AMAZING BREAKFAST BUFFET!  Oh my gosh.  I love buffets.  Love them.  And once I came here for breakfast during a conference at the JW Marriot Starr Pass, I was hooked.  It's pricey, so I just got the continental buffet.  To my absolute great delight, this included not just the pastries, breads, cereals, nuts, seeds, and oatmeal, but also six different types of fruits (strawberries, blackberries, blueberries, and three kinds of melons when I was there in September) but also the SMOKED SALMON BAR!  Endless smoked salmon, capers, sliced grape tomatoes, diced egg, onion... I was in complete heaven.  Everything was fresh, the wait staff were friendly, and they've got a great patio overlooking the pools and mountains, although I only took advantage of this twice, as the rest of the time I wanted to be as close to that amazing buffet as possible.  Oh yeah, the non-breakfast buffet options were good, too- I went there for lunch once and enjoyed whatever it was that I had, which was not nearly as memorable as the AMAZING BREAKFAST BUFFET.  I don't suppose I mentioned that I liked the breakfast buffet?  Yeah. We were staying at the hotel and had dinner here. The kids buffet was great for them and they enjoyed the selection of items. The New York Strip and corn entrée that both my wife and I had was very good. The steaks were cooked to a perfect mid-rare and the sauce was a perfect compliment to the steak. Though we are used to eating spicy food the corn's aioli had a good lick to it. The only down side to our visit was the only adequate service, it took a little too long for refills on our drinks. Overall, a pleasant experience. I had the Angus Burger and enjoyed it immensely.  If you're in the area, try to visit.  I highly recommend this restaurant. I have eaten here out of convenience twice.  Both times it was disappointing.  Breakfast was ok but highly overpriced.
Lunch was very disappointing, order came out wrong and I told them of a food allergy and my plate came out with that food on there. Returned it and seems they just took it off the plate.  Had to send it back again because it had touched my other food.  Positive for this place is the service, they have great servers that are on top of their game. Food is just average and prices above average. My friends stayed at the hotel and not wanting to leave and lose our parking spot, we decided on the Signature Grill.

We sat on the patio because the weather was nice and our waitress was very friendly. We ordered our drinks and it came quickly. However when my friend and I asked for an orange slice for our blue moon, it took a long time to get it and we had to ask someone else. I'm assuming it must have been busy or she must have forgot.

When ask

                         ## Rank: 8: Roma Imports | (4.5)
                         **Category: Cheese Shops, Delis, Specialty Food, Restaurants, Food, Caterers, Event Planning & Services, Italian
                         I used to work at Roma Imports and was spoiled! Lillian who owns and runs the business is one of the smartest and hardest working women I have ever met. She is tireless and has the most incredible staff and they LOVE what they do and it shows. You can make any occasion special with a little Roma whether you want to have a fast oven ready dinner after work that the entire family will love or if you want to have a special lunch that will feed your soul along with your big appetite. It is ALL SOUL food at Roma's! I will only go to Roma's to provide special platters of imported deli meats (they have real Spanish chorizo among other hard to find meats),  the best imported cheeses and exquisite finger foods such as stuffed olives (they stuff on site), grilled roman style artichoke hearts (they grill on site), white wine vinegar anchovies....etc. I have found no better place to spoil my family and friends.They make all their sausage from scratch every other week as well as the inventory of frozen dinners and sauces.
Here is my list of must must try's...
Spicy Sausage Sauce
Home-Made Sausage
Sausage Sandwich
Salami Stuffed Olives Marinated in Olive Oil
Anchovie Stuffed Olives Marinated in Olive Oil
Imported Bulgarian (goat milk) Feta Cheese Drizzled with Extra Virgin Olive Oil and Fresh Garlic
GRILLED ARTICHOKE HEARTS!!!!! OMG!
Home-Made all natural Hummus
The BEST Baba Ghanoush (eggplant spread)
Unbelievably GREAT Olive Oil  and Balsamic Vinegar
Imported Olive Oil Packed Tuna (great all by itself)
Spicy Cilantro Sauce! You have to try it!
Home-made mouth watering Pesto Sauce
Chicken Pesto Pasta Dinner
QUALITY Lasagna of many types and kinds...ready to bake!
The best cup (or two) of Espresso EVER!
Imported Italian Soda (never knew it existed till I worked there..now I am hooked )
Apparently I could go on and on...ha!
As far as pricing goes Lillian is more than fair and truly cares about quality. The food is all natural and good for you! Her sandwiches are a great deal and so are her dinners when you consider the generous portions and quality of ingredients that go into them.
All I know is that if I still love the place this much after working there for a year then it has to be good!
Ciao I can't eat any dairy that comes from a cow (cheese, milk, butter, everything that is tasty really), and Roma's still knocks my socks off. This review is for the takeout food from Roma Imports. (I haven't tried the restaurant yet). I stopped in earlier this week to purchase a couple trays of lasagna, as I had a few extra people coming to dinner, and I wasn't going to have time to cook. Roma Imports is in an industrial location, that seems to be about the most unlikely spot for a restaurant, but I was impressed to find that they have an amazing array of takeout food. From homemade pastas, sauces, breads, lasagnas, plus bakery items and desserts. I have a lot of family in the Boston area, and Roma Imports reminds me of one of the Italian places in the North end of Boston. The food is that good, and it's truly authentic!

They have a great selection of takeout food, which made it tough to decide what to get. But I ended up buying one tray of beef lasagna (which was frozen), and one tray of spicy sausage lasagna (which was made fresh that day), as well as a small tray of beef lasagna that we gave to a friend who was ill. I would give Roma 5 stars, but the spicy sausage lasagna was over the top spicy, so much that three teenage girls (my daughter and two of her friends) could not eat it. I thought it was very flavorful, but I had to mix in a little sour cream with mine- to cut the spicy chili taste.

Let me say that if you are in a jam for dinner, and need to feed a lot of people, this place rocks! I got three trays of lasagna and a loaf of Italian bread for $35! You can't beat the prices, and this food is about as authentic Itailan as any place in the North end of Boston. What a great find in Tucson! I will be back soon- even though it's hard to find this place- a very obscure location... Hint: if you have a GPS, plug the address (627 S. Vine) into your GPS- otherwise you may get lost. Wow Wow Wow we have a winner.  Finally I have found a place that makes a real sandwich.  Where have you been the last 5 years that I have lived here.

Thank you fellow Yelper's for helping me find this gem in the middle of nowhere.  I just wish that I had found it sooner.

On to the food.  I was so overwhelmed I just ordered the first thing on the menu, the Ultimate Roma.  This is what a Italian sandwiches from Philadelphia taste like.  I should know I grew up on these.  Just a great balance of meat, cheese, peppers, bread, and vinaigrette.  I just wish I would have read the next item on the menu which is Matt's special.  It's the Ultimate Roma with prosciutto and fresh mozzarella.  Well there is always next time.

My wife ordered the antipasti salad yes it was good but who cares the sandwich was so good why would you order anything else.

T

                         ## Rank: 9: Fiamme Pizza | (4.5)
                         **Category: Italian, Restaurants, Food Stands, Farmers Market, Food Trucks, Caterers, Pizza, Event Planning & Services, Food
                         My Wife & I have been wanting to visit Fiamme's since it's inception, but due to it's limited hours and the distance to drive from So AZ, it never happened.
SO, when we had a Stay-cation in the Foot Hills, we jumped at the opportunity dine @ Fiamme's.
It is located in a strip mall.  A long, deep and narrow venue with few tables; much reminiscent of Hanover Street in the Nahth End of Boston!
The store is immaculate and the help is uber friendly.
We got a simple Caprese salad that was divine, as was the bread served with it.
The 13" Carne pizza was amazing!  Several types of meats, a bit of cheese and a scant dolep of red gravy on a dough pie that literally puffed up around the outside into an airy, slightly burnt crust.
The Owner, Mr. Scott Volpi was interacting with the customers as well as his staff.  He is a very personable young man! We wish him well!
As I told him on the way out, my only regret is that we didn't come up from SE AZ sooner; we've been missing A LOT! Ordered a pizza for the first time. Love the crust, just the right size and very yummy! They make their own gluten free crust, my daughter says it's among the best. The only thing is they don't have dairy-free cheese available but the Pizza Chef said we can bring our own and they will put it on for us. I imagine it will be extra good melted in the wood burning oven. The place smells awesome would love to go there just to smell the mix of aromas...wood and baking pizza! After looking at other reviews on Yelp, I had to come here! I also noticed seating seemed limited, but we decided to go at an off hour (even then it was still busy, but we managed to snag a table).

I will say every review that cites this place as being slow in service is spot on - it is slow. I don't think the kitchen is well organized to be honest, and they don't encourage take out orders, which is why they are always so full.

We ordered two lunch combos, one with a Figo pizza, and a caprese salad; the other with a Margherita pizza and a caesar salad. For the beverage we both got the unsweetened iced tea (I wish they had better beverage options!).

The pizzas were both amazing and perfectly balanced, on par with Pizzeria Bianco (though I say Pizzeria Bianco is just a little better). The salads were delicious, but my husband was a little off put by the piece of anchovy on top (on the caesar). Then there was this crusty bread that was complimentary with olive oil (to die for).

At the end of the meal we were given a tiny spoonful of the gelato, I was given sweet cream, my husband hazelnut. We thought the gelato was delicious, but quite frankly we were completely out of room. I think they should lead the visit with a gelato sample (or do a special with dessert OR salad)! Maybe next time!

Overall, I would say the food was excellent, service was ok, but slow and the prices were reasonable! They do need a larger dining room with more staff and a better layout! Time to expand! BEST PIZZA IN TUCSON!! Amazing service. Great friendly staff and even better food. Everything's good. Absolutely everything on the menu is amazing. This is my favorite restaurant in Tucson by far. It is always packed. Be prepared to wait but that wait is well worth it! Best pizza ever tasted! Its different from any other pizza you could go buy & made with all the freshest ingredients. They offer many options on the menu to make it a tough decision & the workers are pleasant and friendly. Worth your time to go try! You won't be disappointed Best pizza I have had in a long time. The lunch special was a really good value. $10 for a small pizza, choice of salad and a soda. The crust was great, the sauce was really flavorful. I love that you can see the pizza oven when you walk in the door. I will remember this place the next time I'm in town for lunch. This is the best pizza in the state. Everything is amazing. I've tried 5 different pizzas from them and I've never been disappointed. I literally drove 2.5 hours to get it and it was worth it if that tells you anything. This may be my new favorite pizza place in Tucson. The food was amazing. The figo and picante pizzas are top notch. You can tell that everyone working there is passionate about food, and it shows in the quality of their dishes. Places like this are the reason I don't eat at chains and support local. Wow, absolutely amazing.  We had the caprese salad, the Diavalo and Bianca pizzas and everything was outstanding. We will definitely be back.

Update 7/8. We came back and it was more "glorious" (term my GF required I use) than previous visits.  Arturo our waiter is fantastic and Scott really takes care of his clients. I was in Tucson this weekend and had read that Fiamme was worth a visit.  The review didn't do it justice.  This is absolutely the most amazing pizza.  I was in Italy this summer and this is better.  I'm so impressed and will literally make the drive to Tucson just for the pizza.  Thank you!!!!! Simply the best, most authentic Italia

                         ## Rank: 10: Bacio Italiano | (4.0)
                         **Category: Pizza, Restaurants, Italian, Gelato, Food
                         This place just opened a few weeks ago right at the U of A's  Main Gate. Luckily for me it's walking distance from my house. I've already been once for pizza at lunch, once for dinner and once just for Gelato.

The place is solid. Pizza crust is great... light crunch, not dripping with grease like too many other places nearby.
Then I had the Chicken Parm.. it was tender and had enough Cheese/Sauce without smothering the whole plate. Finally a gelato that was 1/2 Tiramisu and 1/2 Peanut Butter Cup. I was feeling like I was 5 again and chasing the Ice Cream truck down the street!

I'll be back soon. This is one of the worst Italian restaurants I have ever been to. The pasta was dry and they charge extra for bread that is stale. On top of that, the owner and bartender were highly unprofessional. The bartender screamed at me on my way out for having a dog on the patio, after the staff already told me my dog was allowed to be there. I have never experienced such awful and rude behavior at a restaurant like this in my life. Incredible food and service. Sadly, they have to deal with people who like to taunt them. The owner handles it with grace. The food is outstanding, homemade and they will cater to food allergies. A girl in my party has a dairy allergy and they made her a meal that didn't include dairy and it was delicious!!! Highly recommend! I love this place! Very affordable and great! The owner is a really sweet guy as well as the workers. I got the chicken cutlet sandwich and it came with this pasta that was AMAZING. 10/10 everyone should try Good pizza, cold beer, friendly service. The calamari was great also.   Very Busy after after the U of A football game but service was very attentive and friendly. Best pizza in Tucson!  Had the Firenze pizza- the crust was crispy and hearty, mozzarella was high quality, overall super delicious.  Had a house salad too which was light and refreshing.  Didn't get to try the gelato because I was so full, but it looked so good and a big selection too.  Would recommend! Oh my. This was my first time trying out this restaurant. It was cute and ambiance was nice, outdoor seating available. But that's about all that was good. Our server was new, which was fine, everyone has to start somewhere but that was the least of our problems. The food was mediocre and served lukewarm. Half way through our meal we see a MOUSE scurry across the floor and the table next to us saw it too. Absolutely disgusting. Then when we ask for the check and a dessert to go we get the check back within a few minutes but the dessert takes another 5-7 minutes to get, which would be fine if they were busy or it was an elaborate dessert but it was a piece if cheesecake!  at this point we were standing up at our table wanting to leave. Would not go back Got the tortellini all's vodka. Nothing special about it. Didn't taste like vodka sauce just tasted like normal marinara sauce. If I could give zero stars I would. Also they were completely out of soda and the fountain machine was broken. So that was a turn off as well. Great place! I'm east coast Italian so very picky about my red sauce! Their sauce is great! People commented on the pizza being greasy? Maybe they had pepperoni which tends to make its own grease. I can tell you the calzone wasn't greasy at all! In fact the crust consistency was perfect, light and crispy. Also the cook took the time to come out and let us know that our calzones take a little longer than a meal we ordered for my nephew. Since the waiter informed the cook my nephew needed to get to class be wanted to see if we wanted his meal out before us.  What great customer service!! We arrived at the restaurant and the aroma was fantastic. The waitstaff did a very good job.

We ordered the antipasto, fettuccini Alfredo and Rigatoni Siciliano.

The antipasto arrived and was well displayed. A very simple one, it was tasty.

The main dishes arrived and looked very nice. But the flavor was lacking. The pasta was very prominent in the flavor... not much more.

I looked at another table and they didn't eat their orders. A few bites and that's it.

I wish them luck Most of the hidden reviews are 5 star -- I find that troubling. We have eaten here 3 times now and love it! The pizza is the best in Tucson IMHO. Nice atmosphere. See my other review posted in December. Some of the BEST pizza I've had in Tucson in a long time. Bravo to the person making the dough and then the pizza itself. The dough is SUPERB. Pizza comes out beautiful, crusty and crisp in all the right places. Fresh ingredients and the cheese and oil is phenomenal. Folks if you understand pizza and how true gourmet pizza should  be done, don't come in here saying it's greasy or fatty or whatever other nonsense. You don't know how to eat pizza nor do you know quality. Excellent all around!

Thank you! And please keep it up! Food was great, drinks were great, cant wait to go back! Also enjoyed a lovely jazz band during our meal, f

                         ## Rank: 11: Falora | (4.5)
                         **Category: Restaurants, Pizza, Salad, Cafes, Food, Vegetarian, Desserts
                         Just another pizza restaurant. Great location and super clean, but I have no idea why is the topping fall apart. It that how Italian piazza supposed to be? The topping is flying before I put it into my mouse. Pizza and salad are amazing here! Ingredients always fresh, unique, and local. Pizza crust and bread are best I've ever had. The salads are handcrafted to be so healthy and tasty at the same time!! I can't get away from the Arrosto (eggplant, potato, feta, dates). So simple and delicious! Wood fired pizzas come out quickly and service is always pleasant!! My new favorite restaurant.

It's so rare that vegans and carnivores can sit side by side in harmony at the same restaurant and both can be so happy. Thank you Falora for making me a vegan pizza! What a nice surprise. You guys rock.

Bright, sunny space. Modern and fresh feel, but with character.

We had great service. Really good pizza that's made from scratch takes a minute. Reading some of these review and I'm thinking that these guys should go to the Pizza Hut buffet. Have a Peroni and enjoy the company of your friends and family - it's the journey not the destination. But in this case, the destination is pretty amazing.

So good! We enjoyed their salads and Pizza here very much. A salad and Pizza is plenty for 2 people so the pricing is great. The Pizzas are freshly cooked in the brick oven, and very tasty. The butter pecan salad is excellent. Falora's decor is modern, and it's awesome to see their brick-oven right when you walk in--apparently, it was shipped here from Italy. It's beautiful. The prices are reasonable. We were a group of five and we split three pizzas, caprese, and a salad--which, for us, amounted to enough food. With tip, I spent about $15. We tried the Pesto, the Marinara, and the Cura--my favorite was the Cura, the soppressata added a nice salty flavor to the mix. When ordering, figure two people per pizza, but if you are hungry or a big eater you can probably polish one off on your own.

Falora claims to be a Neapolitan style pizza, so thin crust--which I actually prefer, being from Connecticut, that is the traditional pizza we had growing up. However, this did not hold a candle to the pizza in CT--I doubt any place in AZ really could beat Sally's, Peppe's, or Grand Apizza. The crust was thin enough, but a little bland--and one of our pizzas came somewhat burnt. What was most disappointing to me was the marinara pizza. A tomato pie is classic in the Neapolitan style, but Falora did not deliver as the sauce was runny and thin where I was expecting a thicker sauce with some diced tomatoes in the mix. There was also no grated cheese on the tables, which is a staple for most pizza places.

There is also this weird musty smell that lingers in the place. My friends and I were playing "where is the smell coming from?" We concluded it might have been the wood that was on display or perhaps the carpeted window seat we were near.

I think I am just ruined forever when it comes to expectations in regards to pizza. Growing up in CT an Italian-American has made me a pizza snob. I'm sure most would really like Falora, but I thought it was just ok. Is there anything better in Tucson than this nationally recognized pizza? I think not.  Kale salad phenomenal. Arrosto pizza to die for.  Music always perfect. (They have an awesome record collection!) My friend and I went running at Reid Park last night and found ourselves hungry for dinner afterward.  Falora was in the neighborhood.  I had been wanting to eat here for a while, as I'm a big Sparkroot fan and basically anywhere with kale salad is my jam.

An employee was putting up chairs as we walked in (8:30 on a Friday night).  She told us (very nicely!) that the kitchen closed at 9, but we were welcome to stay as long as we liked, and that we could sit either at the community table or at the bar.  We opted for the bar.  My friend really enjoyed the scenery, and that could include the wood pizza oven or the guy making the pizza.  Ahem.

Ambiance was very cute and charming, a small building with long communal tables and a small, efficient white bar with a direct view of the pizza oven.  There was a small kitchen to the right.  Right by the window there was a record player.  A few people put records on.  I LOVE me some vinyl so that was awesome and a reason alone to return.

We got a glass of wine each and split a pizza and a kale salad.  It wasn't easy convincing homegirl to get a kale salad--for some reason, to many, the word "kale" is appetite-repellent.  I think that's because some places just don't know how to prepare kale.  Kale is a very sensitive little vegetable; you must massage it and tell it how much you love it before you hack it into pieces and marinate it in dressing.  Falora's version even had artichokes, olives, and sun-dried tomatoes.  It was so delicious, even my friend enjoyed it!  I also liked that it came out before the pizza, as we were very hungry.  I'll probably

                         ## Rank: 12: Pizza Hut | (3.5)
                         **Category: Pizza, Chicken Wings, Restaurants, Buffets, Fast Food, Italian
                         Love this Pizza Hut! Always kind and speedy service. These hoes upped the price for family sized Chicken Alfredo then had the nerve to reduce the chicken portion to no joke 6 parcels of meat each roughly the size of a cheeze-it. To hell with them. Amazing Service: they always ate nice and they are always willing to help you..
Lunch Buffet available at a very reasonable prices
 and pretty spacious enough room for a party/get together or just a simple date for two or more.  Love this make for lunch or dinner. They also have a drive thru window which allows you quick drive up service and at the end of the day not. Many pizza hut offers this. Wasn't impressed with the service, for being totally empty it took a while for someone to even welcome me and see what I needed. The older gentleman that helped me wasn't the friendliest and I had to remind him of the soda I had ordered. The pizza ended up being quite greasy, the bottom pulled away from the top, so after the first bite you were getting more topping than crust. Next time I think I'll order from the golf links location, they seem to care about customer service and a quality product. This is for my dine in experience only.  Have ordered online and picked up, and never had an issue with that.

Only 3 tables, way too empty for a Pizza Hut at 5pm!  Was yelled to by guy behind counter if we were dining in.  Yes, then told to wait.  Server Casey told us from a distance to sit anywhere.  OK.  Quick look around.  Booth tables had stainless steel tops.  Thought they were dirty, but they only looked dirty b/c of what looked like spots of tape that they couldn't get off.  Not appealing.  When Casey finally got to us my menu was so "GRODDY" that I had to wash my hands after.  When she took our order I told her about it, and no comment, she just flipped it onto another table.  I'm sure she didn't clean it or dispose of it (which it needed).  Wasn't friendly at all during our entire visit.  Window sills and woodwork near booth needed a serious, serious cleaning.  Heavy dust on the ceiling fans.  Just felt like I wanted to take the pizza and run.  Ordered pizza and breadsticks.  In any  other PH I have been to, the breadsticks come out first.  After 15 min I asked Casey where the BS were, and she flippantly said.... they take as long as the pizza.  I told her to cancel that part of the order.  A. I didn't need her attitude and B. I wanted to eat my BSs first!  Pizza was good, as always, but the poor service was uncalled for.  With only 3 tables, one of which was done, there was no reason for her to be this way.  Oh, and we were not given plates or silverware, so after the pizza was brought to us, I waited to see what she would do.  She took plates off the salad bar, gave them to us and walked away.  I had to yell to her to ask for silverware.  Even that took a while.  I ate a small piece of pizza in full while waiting for the silverware to arrive. So last night at Chapman Honda a lot of us were here late. We ordered 2 pizzas and what we got was amazing, the most tantalizing properly crisp crust and juicy flavors. The food was hot and perfect!!! Best pizza I ever had from Pizza Hut EVER. Thanks for the great pizza. Did the online order as always.  at the 45 min mark called the store to see where my pizza was.  The person that answered the phone acted like we trying to place a new order kept asking about sodas and cookies  Finally just asked for the manager because you have no clue what you are doing.  Was told by the manager that my pizza left over 30 mins ago.  So I got a credit of 5.00 off next order.  15 mins later the guy shows up with my now lukewarm pizza.  The driver seemed like he could care less that you ordered a pizza.  We asked for cheese and we got 2 packets. Very helpful people. Came up with candle for our birthday cookie. Decent pizza, very clean, attentive service Our waitress was great but the quality of Pizza Hut dine in is going down the drain. It was boring and lifeless. Very drab. Of course all the kids ate including my picky eater. They really need to get with the times though. The service and food is always great at this location! Bianca's service and attention to detail was excellent! The manager, Toby went above and beyond to make this yelpers dinner a great one! This is an excellent establishment for the tastiest pizza around at a good price.  The drive through service is an efficient way to pick up your order. the building looks nice and clean then I seen why thats it went inside the place was empty no one came to help us i seen four employees just walking around doing nothing looked straight in our eyes and ignored us completely Had all but given up on "fast food" pizza chains, until going to this Pizza Hut on Friday night. I was unbelievably surprised! This may have been the best Pizza Hut order I've ever received & the guy who helped me out was awesome! Stopped in with my son for a quick lunch after the carwash next door. Children 3 and under

                         ## Rank: 13: Zona 78 | (4.0)
                         **Category: Desserts, Food, Restaurants, Pizza, Italian
                         A friend and I met for lunch here a week or so ago.  I hadn't eaten here in years.

We each had the Roasted Tomato Basil Soup.  I'd put it more in the bisque category as it was very heavy on the cream.  The basil, while fresh and tasty was probably a Thai basil and had a very strong anise flavor which wasn't great with the cream base.  Needed more tomatoes too.

We shared a Mediterranean Pizza which was very nice.  Loved the whole wheat option for the crust and the thin crispy crust was wonderful.  A very nice pizza.

Excellent service with a very pleasant waitress.  I found the prices a tad on the high side for lunch but everything was very fresh.

I'd be happy to eat here again. Good service and their chicken parmesan pasta was fantastic!! They are pretty pricy but you get your moneys worth!! So last year Zona 78 was at Viva La Local, they had delicious pizza and a lavender lemonade. The staff was incredibly sweet and gave us a bunch of free app cards...

Never ended up coming back. Had family in town and the restaurant we wanted to go to was really busy and then we remembered Zona.

At 6pm there were tables available but still a good crowd. Hosts were very friendly. Service was decent, food took a while.

Ordered bbq pizza and chicken parm.

Hubs liked the pizza. I hated it. Bbq sauce had zero flavor. Crust had good flavor but too crispy burnt. I couldn't even eat it...

The chicken on the parm was amazing, breading was delicious, cooked perfect. But pasta was boring. Sauce did taste really fresh but lacked flavor. Put a bunch of butter on the pasta so the marinara didn't stay on the pasta.

Over all I just wasn't impressed enough to come back. They've got a good beer menu, fun drinks. Salmon ravioli was wonderful!! And Jim the Bartender Was Fantastic! Really enjoyed the wood fired Mediterranean pizza. The butternut soup was to die for. One of the best ever.  Very pleasurable. Zona 78 is my favorite restaurant. Their mediterranean pizza and mediteranean penne pasta are to die for. They also have a milk stout that the best I have ever tasted. My teenager consistently gets a make your own pizza with goat cheese.  I can't recommend this place enough! Delicious food, on the pricey side but very good. They now serve freshly made donuts and milkshakes! The drinks they made us were strong and about 10$ a piece there wasn't much flavor to them besides the taste of alcohol which was pretty disappointing to me. I had the blueberry mojito so I was hoping for a hint of blueberry but it tasted like straight rum. The eggplant Parmesan was delicious! They didn't come around and offer to grate any fresh parm onto my plate which I wish they would've I should've asked though. The Brussels and bacon were delicious but also had a few things wrong, they were a bit burnt and very salty. Overall I've had both good and bad experiences here with the food. My favorite dish is the eggplant parm and the best appetizer would be the Bruschetta it is AMAZING! I love this place. I am in Tucson only a few times a year (I live in Scottsdale AZ) but try to stop by for a drink with friends whenever I'm in town.  The cocktail menu is fantastic, and their salads are delicious!! I highly recommend this place for those who visit Tucson! This place cooks from scratch.  They make their own pizza dough, sauces and cheeses.....the food is very good.  Service has always been great.  The cilantro hummus was delicious as well as their homemade bread.  I haven't liked some of the wines, but that may be my own choosing.  Great healthy happy hour!! I have been to this place on multiple occasions but had yet to write a review. The servers and food are fantastic. I wish they would have non-alcoholic cocktails on their menu.  I also wish that they would bring back some of their old menu items (such as the Burrata Caprese).  Their homemade mozzarella tastes great.  We always get their signature pizzas and I have not had any complaints about those.  Overall, great establishment :) One of the best happy hours in town. Always a good beer selection and the garlic cheesy bread with a side of marinara can't be beat. Keep going back :) I haven't written a review in awhile. I've checked in to places but nothing moved me to write something down until last night when Zona 78 fell into my lap, by chance.
Went to the movies and afterwards wanted Italian. Good ole google steered us to Zona 78 and I am so grateful because it was AWESOME!
We sat in the bar area. Our waitress was the definition of friendly. Her photo should be by the word friendly in the dictionary. It was her birthday. I only know this because customers were coming in with desserts and wishing her happy birthday. Customers were doing this so that just says she's legit!
Anyway to the food. She recommended two dishes. The mediterranean penne, which I had, and the bolognese that my partner had.  The penne was a mouthful of high fives and cheering. Man it was good. The sauce, the artichoke, olives, c

                         ## Rank: 14: Locale Neighborhood Italian | (4.0)
                         **Category: Seafood, Food, Pizza, Bakeries, Wine Bars, Nightlife, Bars, Italian, Restaurants
                         Food, ambiance, staff. All the reasons I'd come back and invite friends! The hostess was cheerful and inviting, our waiter Jake was honest helpful with the menu! Fried calamari, Tagliatelle bolognese, half chicken, Caesar salad, chicken sandwich and the truffle fries! Love this place. Amazing wine list, good is incredible. Highly recommend the Sfolgia pasta or the panzanella salad. Everything is super fresh and great ambience. FINALLY A GREAT ITALIAN RESTAURANT IN TUCSON
Puts that dump overpriced Italian spot in the foothills to shame I love this place, but my goodness I wish they took reservations! The only time I've been able to get a table in under 45 minutes was at 4pm on a weekday. Super amazing freshly made pasta, good & affordable wine, and their leek & mushroom flatbread is awesome! It's definitely worth a try if you are patient or want to have an early dinner. I rarely leave reviews, but when I do, it's because a place has truly gone above and beyond. Locale, you are a gem.

From the hostess who managed to be super friendly despite dealing with a very long wait list and plenty of impatient customers, to the server who went out of his way to get us drinks even though we were simply sitting near his section while waiting for our table, to the gentleman who lit a fireplace just because we were waiting nearby, and all the way to our own wonderful server, Megan, the service here was incredible start to finish.

And, as great as the service was, the food is the real star here. Before Locale, I had only had a proper Italian lasagna with béchamel sauce in the U.S. once. To find it five minutes from my home in Tucson was such a treat. Our server said the the lasagna "melts in your mouth" and she was SO RIGHT. My significant other had the casarecce pasta with meatballs and it did not disappoint. We started to discuss how excited we were to return before we had even finished our meal.

Thank you for such a lovely evening. We'll see you again soon! Jazer was so kind to us. He wasnt our server, and to be honest our server had an attitude...but he really made us feel welcome and special. For that reason we will be back. The  restaurant is VERY cute and we will give it another chance because of him. Must visit! Excellent prices, food, service! I had fresh made bread with whipped gorgonzola butter, caesar salad, and a pizza. Everything was delicious, my server, the bartender, was excellent. Will be back! My husband and I were very excited about a new restaurant opening in Tucson. We tried it Fri, Dec 11th and we were not disappointed!! Everyone was friendly and courteous. Tables were separated to adhere to COVID-19 restrictions. The entrees were delicious. The bread was AMAZING!! Next time I want to try the desserts...they looked great. We'll definitely be back. Gorgeous Patio seating, really tasty food, and solid cocktails. This was a perfect date night spot and we have already recommended it to friends. Will be back soon. Probably one of the best restaurants in Tucson. The service was incredible! We haJake and Jake as our servers and they were both so attentive and made great conversation!! The food!!!!! The polenta is a must get!! Excellent food and service!  Ricky was attentive and personable.    Will be back soon, just for the creamy polenta, and to try more good stuff! WOW! The food here is delicious! We went for the Thursday Pizza and Salad deal - one large rectangular slice of unique pizza and a large salad for only $10. I had the Country Bacon pizza with dates. Yummy! My husband had the Pepperoni pizza. I was surprised how it had so much packed in - definitely not your basic pizza. Our server Janelle was very attentive.

I have two suggestions for Locale. First, have the hostesses point out the white chairs where you can wait for your table. They are comfortable and situated throughout the outside gardens. Second (and this is BIG) have someone roaming these areas to take drink orders! Apparently the wait staff serves food tables and might not have "time" to ask if you want a drink. I asked if we could go inside to order a drink, but the hostess said, "Oh no! That's for our wait staff!" So I didn't get any wine until we were seated half an hour later. This is a no-brainer! Make $$$ selling drinks to waiting customers! While in Tucson visiting a bed and breakfast we decided to check this place out based on it's reviews and let me tell you, it did not disappoint! It has a great outdoor area with a large grassy area with adirondack chairs and a bocce court! It is very large and immaculately clean and offers a very welcoming atmosphere.   The bar is fantastic and they have specialty drinks that cater to the atmosphere and my wife found hers very tasty, I stuck with a local beer.  The menu was amazing and needed time to be all taken in, which was fine because their bread is unforgettable and for this non carb eating guy can easily state this was the best he has ever had and my wife, a carb lover .... fully a

                         ## Rank: 15: Dante's Fire | (4.0)
                         **Category: Restaurants, Cocktail Bars, Gastropubs, Beer, Wine & Spirits, American (New), Bars, Nightlife, Food, Tapas/Small Plates
                         The mussels are without question the best in town. This is a first class restaurant. Drinks are excellent and great hsppy hour. After 3 years it seems like the word is getting around...this place rocks. Loved the food! The smaller plates were also great for sharing.
Waitress seemed a little bored, though. I have been going to Dante's FIre for about a year and a half, the food is always excellent as has the service. Kim is amazing and is absolutely one of the most fun people I have come across. She goes out of her way to make sure that all of your questions about the incredible menu options are explained and makes really spot on suggestions. I just went back with two of my friends that had never gone there - they are new converts to Dante's.  One of them swore she hated jalapeno poppers (which we had ordered) this is the only place now that she will even eat them - she was so impressed by how delicious they are.  The Asiago cheese foam on ANYTHING is to die for... so incredibly amazing! Great food and martinis. The bread is amazing
We eat here on a regular basis
Everyone should try. Also the music on the weekends is always great I've been a long time regular here. What brought me in was the name, what kept me coming back was the menu. If you want something completely original and unlike anything you've had anywhere else then come here. The jalapeño poppers are amazing! I love that they aren't fried and are so full of flavor. The chorizo sliders and chicken marsala are some other favorites.

Honestly though, there's very little here that I haven't liked and trust me I've tried everything they've made so far.

What I love the most though, is that they are constantly rotating the menu so that I always have the chance to try something new! Decided to give this place a try for my birthday dinner with my family, and definitely glad I did!

I would have given this place five stars, but the service was a bit slow and the food took a while to come out for each course we had. Our waitress was friendly, but I had a feeling she was new and maybe a bit new to waiting tables. She was knowledgeable about the menu enough and was able to answer most questions we had..

Now the food, the reviews on here did not disappoint! My brother and I started with the Arugula & Bleu Cheese Salad with pecans, one bite and I was in heaven! We both agreed that we could eat that all day! For the main entrees, my mom had the Thai Curry Shrimp which she loved, I had a bite and it was pretty damn good. My brother had the Poached Salmon which he enjoyed and I had the Lamb Thagliardia pasta which was just as damn good! Now, normally I wouldn't recommend bring kids here, but my 16yo (EXTREMELY picky!) nephew came along and had the Kobe Burger. We had them cook it without the herb mayo and just plain fries instead of the garlic fries. He said he enjoyed the burger, I had a bite and thought it was pretty good, so if you must bring the kids, that's a good option for them. For dessert we shared the Mango Crème Brule and Devil's Chocolate Cake. Good thing they tasted pretty good because we waited for about 15 minutes or so for it to come out.

We didn't have any drinks, but I will definitely be back with friends and have a few. Don't pass this place up, it's worth an evening here! Went there last night for happy hour.  Inside has been done nicely, so don't just the book by its funky A-Frame outside cover.  It's also nice that it goes until 7 compared to the usual 6 for so many places.  We each had 2 cocktails which were excellent, and shared two excellent appetizers:  Thai shrimp and tuna tartare.   Very helpful and friendly staff. Can't speak to dinner, but the menu is varied, interesting and average-priced for good food. Well I knew this was a gastropub, essentially a bar with food, and from the menu the food looked good.  Admittedly the salads I ordered were very tasty and that is why I gave this two stars, for the salads.  The service, wait there wasn't any service.  We were seated at a bare table, finally a service person came over and said she would bring us homemade bread.  It was good, but hard to use the butter without utensils!  They did not come, until our food arrived...................... After waiting and waiting.  Our server took our order, at first thinking she would remember it, then decided to scribble it down.  I ordered two salads, which I said were good, then said I would have dessert when H had his burger.  He ordered the clam chowder, which I cannot comment on because we never got it, the duck egg roll, which he said were good and the medium burger, which was overlooked and dry from sitting under the heat lamps too long.  The wait person brought out the appetizer, duck egg rolls and burger, all at once.  Where is the clam chowder. "Oh I'll go get it". We canceled it, as either the chowder or the overlooked burger would be cold by time we got to it.

This place has potential with the food, but someone, maybe the owner, shou

                         ## Rank: 16: Dominick's Real Italian | (4.0)
                         **Category: Pizza, Food, Restaurants, Italian, Bars, Nightlife, Cocktail Bars
                         Heard a lot of good things about the food so we ordered a pizza for take out. We reheated it a few hours later and to tell you the truth, it was the best pizza we have had in Tucson. They told us it it would be 45 minutes and it was ready 5 minutes early. Great service by phone and in person, too. The place was packed around 1pm on a Saturday--Has to be a good sign! Delicious marinara on the pizza, really sets this pie apart. Much better than Mama's, Chariot's, Magpie's, etc. My wife lived in Chicago and NYC and she was really in awe, too. Awesome! Delicious food! Great prices! Superb customer service! Please make sure you you make it a priority to stop in and enjoy yourself. Today was our first time having the priviledge of dinning here. The customer service was genuine, friendly and inviting. Everyone smiled and made sure we felt welcome there. Although we had take out, it was a refreshing delight. Next time we will habe to dine in to get the full expierience. My family appreciates the high caliber of service Dominick's provides.. Thank you to ALL of the wonderful staff here and keep up the good work! We went to Dominick's for the first time tonight. My husband got the chicken piccata and I got the chicken fettuccine alfredo; we both loved our meals! We'll definitely be back for more of those complimentary garlic knots and to try the pizza! I've been here twice (both days were actually in a row!) and I can say that each time was great! Each time I ordered takeout so I can't really comment much on the service. My first visit my boyfriend and I split the meatball sub and the chicken parmesan sub...YUM. I will be going back for both of these! My second visit we again split two things - the fettucine alfredo and a pizza. Again both DELICIOUS.

Fresh ingredients and extremely tasty. I already recommend this place to everyone I know. I can't wait to try more of their menu items, it all sounds delicious.

I give four stars because the second time I went to pick up my food I was waiting inside and overheard one employee make a rude comment towards another employee about how my order was taken over the phone. It made me uncomfortable and I felt bad for the employee on the receiving end because nothing was even wrong with my order - she had just forgotten to get my name.

Besides that small incident this place is amazing and I will be returning. I hope this restaurant fares better than Bella Vita did. It is excellent and you NEED to give it a try!! I have never been crazy about pizza until I visited this place.  I love the lunch special with the slice and soda.  What a deal, and enough for two lunches.  My husband and I probably stop here once a month - you can call me - a Dominick's Pizza lover.  Support you local small businessperson by frequenting this great place for Italian Food, period.  I also love the Caesar Salad.  :) Great little spot. Casual atmosphere. Attentive service. Everything we had was great. Chicken piccata and pizza especially! The pastas and pizzas here are so awesome! Highly recommend trying the chicken Marsala or the pasta with clams in a garlic sauce. Kids love the pizza and they deliver! Last night we had dinner here for the first time in months. The change was awesome! We were seated right away and served immediately. The bread knots are endless and the appetizers were fast and good. The pizza came out shortly and the two babies ate for free! There was a man singing jazzy tunes as we are and he was freaking awesome! I like the atmosphere, felt like my kids could get a bit loud and blend, the price for all of us was $39.00 before too! 3 adults and two kids! Awesomely cheap but yummy! The bar has been set high, fresh and high quality ingredients make for a delicious meal. The fried zucchini is not overly or cheaply breaded and Very fresh. Pizza cooked to perfection, the Dominick's special pizza was out of this world. The right amount of crunch in the crust and vegetables while still having enough sauce and cheese. We will definitely be going back! Great Lasagna and garlic knots! Not a fan of minestrone, however our server Alex was above and beyond a great server! 30% + Thank you Alex! Now my favorite pizza in Tucson. Think Mama's with a better sauce and a nice crust that's not got a better flavor, texture and snap. Amazing service and authentic Italian food. My husband liked the atmosphere and the Italian dinner. My husband is Italian. Had a nice birthday late lunch/early dinner here today. I love the newly expanded and renovated space and the food was delicious as usual. So far so good. Packed when we walked in. We were sat as soon as a table opened up. Wine is good and my boyfriend is enjoying his Peroni beer. Warm delicious knots were just delivered. Cozy Italian ambiance. Super impressed so far.... Excited for our food! Minestrone soup was yummy! Still haven't received our waters. Dinner was delicious with plenty of left overs. We are taking dessert home too! Over all experience was r

                         ## Rank: 17: Tavolino Ristorante Italiano | (4.0)
                         **Category: Pasta Shops, Gelato, Italian, Food, Restaurants, Salad, Pizza, Diners, Specialty Food
                         Get the Penne al Funghi, and top it off with a Bonet.

For those that judge Italian restaurants by their bread, Tavolino's is dense, chewy and oh so wonderful with just a touch of oil and balsamic vinegar. Their homemade tagliatelle pasta is another doughy standout, and the kitchen is accommodating whenever I ask to sub that in for the Penne al Funghi (mmm, pungent mushroom sauce; definitely my favorite of the different dishes I've tried). What I love most about this place is that they stick to deliciously flavorful Italian simplicity, and for this level of cuisine, the portions and price are almost too reasonable.

For chocolate connoisseurs, the Bonet is absolutely marvelous. They describe it as a custard, but it comes off as more of a mousse, with a texture I can only describe as dreamily dense. A scoop of gelato turns this 10 into an 11.

You might want to call ahead for their hours, because they might be in pre-dinner limbo (happy hour only), or closed early (summertime?). Once they were amenable to firing the kitchens up a little early, but the waiter was a sourpuss for the rest of the meal. I had the best fish soup omg it was great and this was a few months ago and I'm still thinking about it. I had a lovely time. Thanks a bunch. This place is really good. It is very expensive though, not sure why it only has 2 $$. Should be at least 3. But other than that, the food was really good, staff knowledgeable and professional. Even had a manager stop by and ask how everything was, I like when places do that. If you are looking for a nice Italian restaurant, this place is great start! This place has some of the best food in the foothills!!  Amazing and super yummy!  Come join me in a cocktail and pasta! Excellent!!!! Great food :). My drink was so so so good. I love the atmosphere and my server remembered my name. Can't wait to come back! Am I playing favorites, writing 4 reviews for one restaurant when I haven't reviewed some even once? Yup! You betcha! Because the places is just awesome, plain and simple. And in this update I bring you the INSANE happy hour menu including pizzas for $5! I don't even think you can get a pizza at Domino's for $5, and let me tell ya, this is going to taste much better. They offer up small places, some salads, and a soup of the day at happy hour pricing from 3-7, so you don't need to leave work twenty minutes early to get there, unless your job sucks. Happy hour pricing is only in the bar and rumor has it starting around 5:30 it fill in and people get naaaaaasty. Dinner and a show? Yes please!

Know Before You Go: Happy Hour is a great way to try different parts of the menu without shelling out lots of cash. Peep the photo I uploaded for descriptions and prices! Alright, listen up: Tavolino's ossobucco-style braised lamb shank over wild mushroom risotto is one of the best things I have ever eaten in my entire life.  To my knowledge, there is not a single food item in Tucson that even approaches it.  (And if there is, I want to know what it is.)  People who don't like food (e.g., 'I hate mushrooms,' 'I complain when there is fat in my meat') might disagree, but I don't care what they think.  Food doesn't get better than this: it only equals it by excelling along different dimensions.

Given how irrelevant the other details are here, I hardly feel motivated to write any more.  But it bears mentioning that the eggplant rollatine appetizer was amazing, as were the caprese-style stacks of tomato, prosciutto, mozzarella (burrata?), and basil (I think we ordered the prosciutto separately?).  They made gluten-free pasta for my special lady friend which -- swear to god -- was indistinguishable from normal pasta in both texture and taste (it wasn't even sticky! -- gluten-free eaters will know what I mean), and the mushroom and spinach sauce was unreal.  The waiter was really great about checking into the gluten status of every single thing we ate.  They even managed to pull off a really great tilapia special (who knew "really great" and "tilapia special" could even go together?).  Overall, the experience was just about as wonderful as one could ask for.  This is what splurging on dinner should be like.

Seriously: go here. We enjoyed happy hour on the patio. The menu had a good amount to choose from.
We orderd two items: the Burrata pizza with prosciutto and the Calamari Fritti.
The pizza was delicious. The creaminess of the Burrata combined with the slightly salty ham was wonderful. Although the bottom of the crust was a little soft from moisture, it was still very good.
The fried calamari was tender and when dipped in the spicy sugo, added good flavor. We even dipped the bread and pizza crust in the sauce.
For drinks: I had the Venetian Spirit... I did not like it. It tasted like bitter orange Fanta. BF liked the Italian amber bottled beer. And later on we tried the Rosso Ferrari, an Italian blood orange margarita... It was very good. Not too sweet and not tart...a different tast

Label Query: Vegan restaurants

                         ## Rank: 1: Burger King | (2.5)
                         **Category: Burgers, Restaurants, Fast Food
                         yay!  for the impossible burger!!!
BK Lounge goes Vegan Friendly!!!
thank you thank you thank you!!!!!
cows dont need to be ground up for a whopper anymore!!!!
keep up the good work!! OMG..their new taco is the most vital disgusting food I have ever eaten. Its absolutely not even close to the poster on the building..not real meat..beef paste..taco shell soft where paste is..rest like a brick.  I implore people to listen and not waste even a dollar on this junk Place has horrific customer service. Samuel is as rude as they come. I asked what was on a sandwich and he told me that there was a spicy sauce and I asked him if it was mayonnaise based or cream based and he basically freaked out and said I already told you it's a spicy sauce what else can I tell you. I couldn't help but chuckle but I could tell you that I won't go out of my way to eat here again I went in to order two Whopper's for 6 $  and the staff were nice and the place was clean inside and outside of Burger king. The Men's bathroom was also clean and had hand soap and paper towels. I then went shopping at Walmart to stock up on a 60 day's supply of food and water. Because of the supply chain and the debt ceiling and the the Goverment shut down on 12/ 03/2021. So please every one go and stock up on your 60 day's of food and water and other supply's. Also please do the Survey on the receipt and get a Free Whopper . I came here while waiting on my vehicle to be serviced in the auto center. I hadn't gotten food from this establishment in a year because my last experience was not so great. The new staff is doing a great job! My food was fresh and the restaurant was very clean. Will be back! So the assistant manager with the ponytail is a joke for an employee total lack of customer service  no sense of guest accommodation. Not even worth a description just wanted to say this guy is a loser

                         ## Rank: 2: August Rhodes Bakery | (4.5)
                         **Category: Event Planning & Services, Food, Sandwiches, Bakeries, Restaurants, American (New), Caterers
                         This is a crazy cool new restaurant concept.  Very wholesome and makes you think about mom's kitchen.  Fresh bread, sandwiches and soup abound.  From the creators of Prep and Pastry and Commoner and company! Great food.  Had the tri tip dip.  Lean no fat, but flavorful.  My son had the grinder and loved it.  Bread is baked fresh in front of you.  Took a loaf of sourdough home.  Great service with a smile!  Will definitely be back. My favorite place for sandwiches and salads near the University! Ingredients are fresh and thoughtful in combination. The bread and jam are absolutely delightful and are a must. The catering is amazing, well organized and personal. Long story short: great artisanal sandwich shop. Scratch made soup/salad/sandwiches/lemonades/teas so worth the price. Beer and wine menu looks legit too.

Pointer for management/owners: get a breakfast sandwich, coffee/iced coffee and open a little earlier (even just 10am).I had the turkey club today and if you subbed the turkey for egg and served it on an English muffin I would eat there EVERY.SINGLE.DAY.

Also... open one in Oro valley.... Great food with one off traditional styles. The coffee and desserts were on point. I want seconds! Great lunch this week at August Rhodes but surprised there were not more people in the restaurant. The bread and the turkey club were extremely well done. Great atmosphere and service. This place is so good. I came during their soft opening and was sooo happy. I picked up lunch for my work and ended giving one of my coworkers a bite of my sandwich. All of us were astounded by how amazing the sandwiches were. It's suffice to say the sandwich made my day. I've recommended this place to everyone I know, and am waiting to back in with some more of my friends. This place had so many fabulous vegan options, and I rarely have had a sandwich so good in my life. This place is a must go. The service is absolutely exceptional and I plan on returning very soon. I'm so delighted and impressed by August Rhodes!

Their menu looks great overall, and the good news is that if you're having a hard time picking just one sandwich, you don't have to! You can combine two halves of different sandwiches! Such a great option, and one that both my friend and I took advantage of. I got half each of the eggplant sandwich and the roasted cauliflower sandwich, and she got half each of the roasted cauliflower and vegan BLT. We also had cups of the ratatouille and the kale and white bean soup.

Everything was phenomenal! The bread is amazing, soft and flavorful, holding up well to the heavy fillings. The eggplant sandwich delivers strong Mediterranean flavor, with smooth hummus, salty olives, and subtle heat from the peppers. The roasted cauliflower is a bit tangy, with the pickled turnips and tahini. I'd definitely recommend both! The sandwiches are quite large; I only ate half of each half.

We also got and loved the cactus fruit kombucha. It was a lovely light/sour contrast to the rich, salty flavors of the soup and sandwiches. I can't wait to try more of their offerings! Really great food, great ambience and service. Laid back but still very put together. Everything in this restaurant feels like it's been made with love. Will definitely be coming back. I want to try everything on the menu! I loved the New Jersey Joe Sandwich. The toasted Japanese milk bread really makes the sandwich and  I'm so glad to see a chef that is utilizing this bread I grew up with and bringing it to the forefront. The pillowy sweet taste pairs well with the contrasted smoked brisket. I actually love the portions because I can box up half to take home for another meal.

I bought a baguette of sourdough to take home for my charcuterie board. Sliced and toasted it with butter and it was absolutely delicious.

The staff was very friendly and helpful in guiding me in my decisions. (I was indecisive and wanted to try everything ). They were attentive and the service was fast.

The decor is beautiful and very clean.

I look forward to coming back to try more sandwiches on their menu! Absolutely love the new addition to the P&P family! Sandwiches are made to order and are not lacking in ingredients or flavor! Everyone is so friendly and service is awesome! What is not to love about August Rhodes Market?! The space is bright and welcoming, complete with an Instagram-worthy tropical print wall. You order at the counter, grab your number and then take a seat (either inside or on the shaded patio). The service is exceptional (shout-out to Jeremy and Nate!!). I had the Vegan BLT with Tomato Basil Soup, as well as the Iced Madagascar Coconut White Tea. The Vegan BLT consists of: tofu, romaine lettuce, the reddest tomatoes I've ever seen, vegan aioli and sandwiched between to delicious slices of their baked in-house sourdough bread. The Tomato Basil Soup was creamy and comforting. The tea was the perfect refreshing punch of flavor. After taking that first bite, I was hooked.

Duri

                         ## Rank: 3: HUB Ice Cream Factory | (4.0)
                         **Category: Restaurants, Food, Juice Bars & Smoothies, Ice Cream & Frozen Yogurt
                         Fantastic ice cream.  I had the cafe du monde coffee flavor and my wife enjoyed the banana Nutella variety.   Only comment is the service could be a bit friendlier.  Pouty college students serving gourmet ice cream when it is $4 a dish is unbecoming. Average, Average, Average.

Nothing special about this place. It is a bit pricy (It's downtown tucson)
This place is Average; but there are much better ice cream places near by. Delicious! The lady at the counter was very sweet about letting me try many of the flavors. I had the peanut butter and also a s'mores scoop. The base is excellent and definitely the product of great milk. I loved loved both of my flavors and will come back again. We went across the street for dessert after dinner a Pizzeria Bianco.  They were busy but service was fast.  The ice cream was delicious.  Too pricey for regular consumption though, otherwise they'd have five stars. Delicious! Good service, great & unique flavors. Super fun place to stop in for a treat downtown. HUB ice cream is pretty awesome!  Their flavors are often rich and delicious, if not a bit overly sweet (but hey, it's ice cream!).  I personally am quite upset their coffee and donut flavor, which is one of the best ice cream flavors I have ever encountered, is not a staple on the menu.  Last visit I had the blueberry cheesecake that was like an elevated DQ blizzard (I mean that in the best of ways).  HUB is similar to Salt & Straw in my opinion, but lacks the originality and out of the box flavors.  I'd like to see HUB try some more adventurous flavor combos and definitely need to have coffee and donut always available. Great ice cream!! Cute ice cream shop!! You have to try it!!

I highly recommend this place even if you aren't in the area. Make a special trip if you want good old-fashioned ice cream.  With a spin on the flavors... Yum!!! Really tasty! My group tried the Oatmeal cookie dough (finally a cookie dough variety that's not chocolate chip!), pumpkin pie, and the bourbon almond brittle. We'd recommend all of them! The Hub Ice cream from both locations are too amazing, I go in at least twice a week for either homemade chocolate tacos, or just to get a 4 oz to satisfy my cravings! Only one vegan choice here, the "vegan strawberry".  It's good.  Not fancy but good.  Not happy about all the cruelty based dairy here but glad they have a vegan flavor to show people you don't need cruelty for dessert.  If anything special is going on downtown, plan on waiting in a long line. This place was pretty good. I wish the ice cream was little bit harder... too soft in my opinion. Their flavors were good, different, yet unique. No room for seating. Listing key ingredients would be nice. One sample didn't taste of coconut but the serving was full of it. Literally the best ice cream I've ever had!
I sampled about 5 flavors and loved them all!!

My top picks are Hokey Pokey & the Oatmeal Cookie Dough!

Good prices and a great atmosphere too. Would highly recommend They're ice cream is wonderful!! I'd rate it the 'Best in Tucson.' My favorites are Salted Caramel and Bourbon Almond Brittle.  They give you samples of any and all flavors.  You can get Hub ice cream at this location as well as The Hub restaurant. I prefer the restaurant location. They give you more!! And at the restaurant location, the one scoop is really two scoops and they'll let you get two flavors in that 'one' scoop. I usually like to come here after taking my kids to the children's museum for a few hours.  It's a nice mid-afternoon treat/snack, and a short walking distance from the museum.

Flavors are unconventional and definitely not lacking in flavor.  I can't say I adore the ice cream in texture.  There are other "artisanal" and "gourmet" ice cream places that I'd choose over The HUB, but we do come here because of the convenience to where we are beforehand.  Price I suppose is decent and comparable to shops of this sort.  And my son, who has some food allergies, loves their sorbets.  So that alone is worth the visit for me.

One thing that does bother me is the way the menu of flavors is displayed.  While mirrors add to the decor and is a neat idea, writing the flavors on a surface that also reflects images from opposing walls makes it hard to read from where you're standing, and that's right in front of the ice cream case.  And not to mention, they do it in white ink.  Talk about annoying. Great menu and food selection. We sat at the bar where they had a very good selection of local beers. My steak salad was good. The staff is young and friendly. Modern looking place with outside seating. Here's the deal:

HUB definitely makes the most delicious, local, small-batch ice cream in Tucson (sorry Isabella's, but you can't top HUB's Bourbon Almond Brittle!).
But even for HUB ice cream, this place is a bit over hyped. I really, really like this ice cream, but it's not really worth waiting 20 + minutes in line on a Friday or Saturday night. Furthermore, the

                         ## Rank: 4: Govinda's Natural Foods Buffet | (4.0)
                         **Category: Religious Organizations, Buffets, Vegetarian, Restaurants, Food, Vegan, Desserts, Salad
                         Tuesday night - India night!  Govinda's reminds me of a little place in India.  So you go in a grab a dish, grab some papadum or lushi bread, and grab your salad (fresh greens, not just sprouts, cherry tomatoes, hot pickles, etc) and salad dressing (a nutritional yeast one and a tamari one - both vegan).

You grab your potato curry, your veggie curry, your mint/tamarind chutneys, your yogurt sauces, your curried paneer cheese, and your rajma kidney bean curry.  You grab your DELICIOUS reverse osmosis purified water or your iced or hot chai.  You absolutely do not ask where the dessert is because you will be pointed to a little section of rice or noodle pudding and be embarrassed.  You will not find any meat.  Then, you will pay $10 or so.

You find a seat (possibly with other people eating there), and if you are sitting in a chair, you do not need to worry about taking your shoes off.  Then, you refill your food as many times as you want and put your own dish away.  You will not go hungry, and you will not get a food coma. The food is fantastic! It's super clean. Totally vegetarian! I've been coming here for the last 15yrs. and I've never had a bad meal. Wonderful place! Good prices, tasty food and incredible atmosphere. It is a must-visit! My favorite in Tucson Very nice well stocked vegetarian buffet, and super nice staff.  The ambiance is peaceful, and I absolutely love the live peacocks out back!  I can so rarely visit here since I live in California, but Govindas is one of the (many) reasons I make the trip out to Tucson.  The Sunday evening gathering is lots of fun. Can't wait to go back... My boys and I have enjoyed eating at Govinda's for years. We LOVE so many things about Govinda's.
We love the people (like Gino), the food (like the Samosas), the wildlife (like the peacocks), the shop (clothing, etc)and the overall ambiance. We always feel welcomed and loved and will continue to not only frequent this establishment for meals, but also for the events that they frequently host as well.
Thank you all for everything you continue to do to make Govinda's a diamond in the rough here in Tucson.
See you next Vegan Thursday buffet!
Aloha~Kimber, Leroy, & Dominic Very high quality food and eastern atmosphere. Very nice staff too. Wish they had a bigger selection, but what they have is good! I just scanned some of the recent 2-star ratings and am completely baffled. Totally off base reviews, but everyone's entitled to their opinion. I discovered Govinda's after a friend raved about it. I can't say enough good things about Govinda's. The food is incredible (try as I might, I cannot duplicate the lentil soup!) and is enhanced by a relaxing, calming atmosphere. Salads are fresh with delicious dressings; there are always several options for "heartier" dishes such as curried vegetables with rice, pakoras, and the daily entree(s); and the price is very reasonable if not a bargain for the variety of tasty, healthy food you get. In fact, I cook at home more often now just so I can "reward" myself by going to Govinda's on Thursdays for vegan night! Don't miss it. This is my favorite restaurant in Tucson (even if I have to head somewhere else for my adult beverages :)). I visited on "Sweet n' Tangy Organic Tofu & Falafels" day. You serve yourself food from a buffet on to paper plates. This is old -school 'Health food': nutritious, filling, and a chore to eat. I think 'okay' might be too generous a description of the overall flavor of the dishes, which were either bland, too salty, or contained hard chunks of spice. On the plus side, they apparently have a lot of gluten-free selections, though they don't bother to indicate this with their signage.

There's simply no comparison to Lovin Spoonfuls. Even Ghandi - a mediocre Indian restaurant - is a better value. The workers are nice but the food is only okay.

I went on a night when they had an Indian curry dish and vegan enchiladas.  The enchilada sucked.  The curry was decent but a much better dish could be had at any Indian restaurant.  Most of the dishes were too cold.  They need to put up some heat lamps.  The spaghetti and meatballs sucked real bad.  The meatballs were dry and tasted nothing like meat.  The meatball and sauce was

I think if you're vegetarian and want quality food, you're better off going to a regular restaurant and asking for vegetarian versions of whatever they have. I dont eat here often, but it is a treat when I do..would i like to sit Indian style on  the floor? YES.. would i like to know how they can make all this food so amazingly satisfying and vegan? YES. I must say this is one of my all time favorite tucson attractions/restaurant! The food is magnificent. Delicious and fresh! people are super friendly. VEGETARIAN HEAVEN! you can sit inside and outside, there is also a place inside you can take off your shoes and sit on the floor! TUESDAY NIGHTS INDIAN NIGHT! I really like thursday nights too its VEGAN night. two thumbs up! Husband and

                         ## Rank: 5: La Chaiteria | (5.0)
                         **Category: Mexican, Tacos, Vegan, Vegetarian, Food Trucks, Food, Restaurants
                         Hungry on Friday afternoon for lunch was looking for a restaurant while driving and saw this new place so we dropped by. I ordered the al pastor taco and Rajas tacos which is green Chile mushrooom and cream. The al
Pastor did not taste authentic and very oily while the rajas was tasteless and bland... they're not horrible but not wow either.
On another note, the place is clean and tidy. Stopped by today to pick up a large order for my family for taco night. Everything tasted incredible and fresh. We ordered the tacos al pastor and mole tacos. Will definitely be back! So happy Wendy opened a cafe closer to my neck of the woods. It has the same great menu items featuring the best vegetarian food as her other cafes. I am not a vegetarian, and I love it. There is magic in the food Wendy creates, from her potato filled tacos to her jackfruit carnitas-you just can't go wrong. And if you happen on a day where her cashew based Alfredo on gluten-free pasta is on the menu whoa-your tastebuds will love you forever. Yessss!! La Chaiteria has a vegan menu and a regular menu. You can also make your vegan dish vegetarian by adding cheese. The jackfruit is flavorful. I recommend their house drinks. The orchata is so good! The turmeric lemonade and Jamaica are also great. The portions are big.  The food is worth every penny! Staff are super friendly, attentive and want to ensure you have a great experience. I have been a big fan of the other Tumerico spots and so happy now there's a 3rd location in Tucson! We had the saffron latte (no espresso in it), mesquite latte, ropa vieja and the rajas tacos place---AMAZING! Portions are a good size, you can taste the quality of ingredients and they created such a fun, artistic space to enjoy it in. My new favorite restaurant. Amazing customer service, fast service and some of the best food I've had here in Tucson! This place is so amazing! Compared to the other ones that are owned by the same company this one I feel has bigger portions and needed over here which is so great for this side of town. Plus there's so much closer to me now. Seeing that we lost the vegan burrito on this side of town this definitely makes up for it. I definitely would recommend the Al Pastor tacos. They're a little on the spicy but you can make them even spicier with the salsa that they make there and their salsa is amazing too! I tad on the pricey side compared to regular Mexican food places around here, but for vegan and healthy non vegan Mexican food it's right on point with the price. You come here you won't be disappointed!!! This place is on point! There are vegan and non vegan options. The staff is absolutely amazing, kind, helpful and create a fantastic atmosphere. The food is delicious worth a try! Normally this is an amazing place. However only if you get the Cuban jackfruit. Today o tried the jackfruit that has pineapple in it and all I can say is $14 for to stream tacos with a tiny bit of jackfruit and sour pineapple is not cutting it. Sorry. Next time I'll stick to what I like here. The carne con chili burro was one of the best I've had. Rice and beans were also really good. It's a can't miss spot. Best vegan mexican food in town! Support local women owners. Finally got to check out the spinoff of Tumerico. This location is also a cute little market with food, snacks, beverages, toiletries, and deserts to go. there is a food truck outside with meat dishes, which makes it friendlier to a wider base of people. Inside is vegan and vegetarian. The menu is always changing but I always go for the tostados. They're a yummy combination of crunchy, savory, and flavorful. The beans are well cooked and seasoned. The food tends to be a bit oily is the only downside. I also tried one of their juices, while pricy, it was a healthy balance of veggies, fruit, and citrus. Another reason to check out this place is all the amazing murals and artwork. It is a Tucson must see. It's a great addition to the Tumerico family and a much needed boost to the vegan community. I went here with a friend to try something new. I liked the what the cafe/restaurant is going for but the coffee was not good at all. I got the horchata latte, hot. But it was lacking in flavor. The cup was steaming hot, but the coffee was lukewarm. The meals that other customers got looks great though! Also, my friend liked the mole latte, no complaints from her. All lattes come with soy milk. This is a fantastic place and I'm no vegan. But they do have meat dishes, but I've not had a bad meal any time I've went. I hear their coffees are good too, but I go for the food. Give them a shot. I'm so glad this is on the West side of town! The West side has been getting some great additions! This is different from Tumerico in that there's a great salsa bar instead of all the salsas and toppings already appearing on your plate for you.  There's a great drink menu, coffees and Mexican drinks, a vegetarian food menu, which is just as fantastic as the original

                         ## Rank: 6: Welcome Diner | (4.0)
                         **Category: Restaurants, Nightlife, Comfort Food, Cocktail Bars, Bars, Diners, American (Traditional), Breakfast & Brunch
                         I concur with most previous reviewers that this place is mos' def' damn good food.  I had a burger with very premium ingredients cooked right, my wife had some fish that was delicious, and the kids enjoyed the jambalaya.  A 5-star gets knocked down by 2 stars due to 1) a bit pricey for a "diner" environment & portions, & 2) a slight mix-up on drink order.  But still, I'd come back if I was a Tucson local (shuttering thought). While there are only a few vegan options, they are just amazing. I loved the vegan burrito. It has perfectly cooked sweet potatoes and tempeh inside, corn kernels and beans. Then it is seared or grilled for a nice crisp texture. Topped with a lovely mix of guacamole and sprouts only after it is smothered in a delicious ranchero sauce that screams"MORE" to your palate. Add to that the small side of chile  de arbol purée that needs only one drop to make you sing!
I also decided to try the sourdough bread with homemade jam to just a touch of sweetness, which was very nice. Kind of a cranberry and cardamom or cinnamon flavor. Pretty good.
Coffee is STRONG AND FRESH. I'll be back soon for the jackfruit po boy! Stopped here on our way out of town and very glad we did! The food was great! (Eggs, biscuit, hash browns and fruit) Girlfriend had the veggie burrito and loved it. Service was friendly and the environment was colorful, quirky and had that old school diner feel.  Couldn't stop taking pictures of the decor! Would highly recommend this brunch paradise to anyone in Tucson! We ordered two of the Fried Chicken dinners and the big Jim.  The chicken was over breaded and the white meat chicken was severely over cooked.  Very dry and tough.  Liked the mashed potatoes and gravey but the  Pico de gayo didn't work with the plate.  Very expensive too.  Our bill for the 3 of us was over $70 and we didn't drink any alcohol Admittedly, I was a bit hesitant to go in at all because of my love of the former Chaffin's. Boy, was I missing out. Welcome Diner honors this building and its history like no other establishment could. The service is always excellent in the many times I have stopped in since then. The food...incredible. I would recommend everything from here. Glad to have you all in the wonderful OP culinary scene. Spicy Bloody Mary was bomb!

Breakfast was some of the best!!!

Great quality, great service, great atmosphere.

We drove in from California last night and saw that it was packed. So we had to try it today and we are glad we did!! This place has moved to the top of my list. I can't wait to go back. I celebrated Mother's Day a bit early with my daughter and we both loved it. She had the French omlette and proclaimed it the "best omlette she had ever had". I had asked the waitress for her recommendation and she suggested the vegan breakfast burrito. It was amazing! Such a fantastic combo of flavors. I just kept saying "wow!" as I was eating. I did share with my daughter and she said "if all vegan food was this good, I'd become a vegan myself". (Neither of us are ). They source most locally, and the renovation is very pretty. We can't wait to go back! I wanted to love this place SO bad.  I love that they remodeled the old diner.  I love its location and the concept of locally sourced ingredients and a unique menu.  But that is where all the joy ended.  My partner and I brought our niece and nephew by for brunch.  After waiting over 30 minutes for our food (and no one checking in with us to see if we needed anything else), the food arrived cold.  We didn't send it back because the kids were starving and we didn't know how much longer we would have to wait.  When I thought something was missing from my order, the waiter said he would go check on it... AND NEVER CAME BACK.  When we did manage to catch someone's attention, we had to ask three times for refills on ice tea.

The really strange thing was that the staff seemed very friendly and engaged.  They just didn't feel as though they had any work to do in serving us our breakfast or making sure we enjoyed our visit.  I was sad when I left because I was really looking forward to going here a lot and recommending to all my friends. I need to get back! The appetizers we ordered were so unique and delicious that I almost didn't have room for my chicken. The tempura broccolini - SO GOOD! And the grilled romaine salad, was so much tastier than I would have expected as well! Great service and great food! As we were getting ready to say bye to the desert heat, as I like to otherwise call, Tucson, our tour guide, AKA cousin took us here for our last meal.

I wasn't too hungry, so I decided to share some pulled pork fries for the table and a cup of cold brew coffee.

The fries were delicious! The pulled pork was too die for and the slaw that they put on top of it worked so well together.

The icing on the cake was the service of the restaurant. Our server was super attentive and made sure we were constantly taken care of. He even gave us a l

                         ## Rank: 7: Substance Diner | (4.5)
                         **Category: Vegan, Food Trucks, Coffee & Tea, Food, Restaurants, Breakfast & Brunch
                         Recently moved to Tucson and been looking for good vegan food. Had the substance burger with fries. My friend had the spicy fricken things. Both were delicious!! I think it was a busy night so it was a bit of a wait but didn't other me. It's hard to find vegan food this good here! We attended MSA Annex Night Market on Friday.  This looked like a cute food truck and we liked the menu options.  We were waited on quickly and received friendly service.  My son ordered a grilled cheese and a chocolate shake.  He's super picky, but said it was amazing.  I ordered the Mac n Cheese croquettes.  I agree with his opinion; my food was also amazing.  We both ordered fries, one with gravy and the other without.  I'm quite the fry connoisseur and thought they were good.  I didn't see any drink options besides shakes so I ordered from the bar.  We only waited about 15 minutes for food.  I'd definitely like to try a burger and the breakfast options.  If you see this food truck, try it! My partner and I decided to try this truck when it was parked outside of Crooked Tooth Brewery. I'm not vegetarian, but they are. I ordered the substance burger with avocado and cheese, and they ordered the vegan breakfast burrito. Wow! I swear, my burger tasted just like a delicious, upscale, veggie version of In N' Out. It was amazing. My partner deemed their meal the best breakfast burrito they'd ever had.

The only reason for the four stars is that I wasn't a huge fan of the gravy fries. The gravy was a little lacking in flavor and kind of watery. Still, this is a really solid place that will please carnivores and vegetarians. Highly recommend! Amazing juicy flavorful burger! So delicious that I devoured it before I could even snap a picture of it. But I did manage to stop for a pic of the huge fries. Worth the wait if you walk up to order your food. Definitely recommend for your belly. Checked this place out when it was outside of Motorola Sonora Brewery. I'm vegan and tried the fish less tuna sandwich which was AMAZING. I wish I knew how they did it! My meat eater hubby also.said mine was bomb and he loved his BLT. The fries are amazing as well. The order took about 30 minutes which was no big deal to us because it was just one guy working and we were chilling and drinking beer anyway :)  Definitely worth the wait!! I'm so glad Substance Diner delivers!! I first tried the food from this vegan food truck while at MotoSonora Brewery. If you go in person, save room for the banana split sundae! The ice cream is from Cashew Cow on Broadway (yum!). Everything I've tried has been tasty and the sandwiches, hotdogs, and fries actually deliver fairly well. Worth the wait! We've been eating his food for the last few times we've been at Moto Sonora and it's always been beyond our expectations. The best fried pickles we've ever had and a vegan burger worth recommending to a friend!! Would highly recommend ordering from him, and I highly suggest ordering ahead online. He's only a one man show so give him a heads up on your order! I look forward to watching his business expand, and I know it will!!! Amazing!! If this is the right substance it's outside of moto Sonora pretty often they do a really good job with burgers sandwiches french fries I'm sure they're milkshakes awesome and it's all vegan but you can't tell I fooled to carnivores today it was pretty cool I'll keep it short and simple, food is great, but service can be frustrating. I have ordered and paid online only to show up to pick up order and they didn't know anything about it. I have also ordered in person and have been told it will be ready shortly, and show up minutes later and they have no record of order, had to start all over again. Still worth it I think,
but not sure I'll return if this happens again. Rainy day in Tucson called for a drive to the Substance Diner! Vegan Sonoran Dog & Mac'n'Cheese Croquettes with spicy mayo dipping sauce were amazing. The tastes! Every bite was full of flavor. Truly spoiled myself. AMAZING! I had their burger and the Sonoran dog and they were so damn good! Last time I had the fried pickles which were just as fantastic. On the pricey side but it's totally worth it for the quality of food and supporting a local vegan friendly restaurant. Get the burger, trust me!! Great vegan food.  A ton of vegan options. Everything I've ordered always impresses my vegan and non vegan friends. The prices are fair and the food is always made fresh with quality ingredients. My favorite things to order: Vegan breakfast burrito add tofu bacon and the spicy fricken things (seitan bites.) This guy works magic! Fr fr every time I go I forget to take a picture until halfway through haha because I am obsessed with the deliciousness. OKAY so you take a look at the menu... kind of standard sounding, nothing spectacular but I'm telling you now, he makes the ordinary, extraordinary! Prices and oil are high but they have true diner food and most of it vegan.  The food is good if

                         ## Rank: 8: Epic Cafe | (3.5)
                         **Category: Cafes, Food, Restaurants, Bakeries, Coffee & Tea, Vegan
                         I came here after searching on Yelp for "Gluten Free bakeries" but they had only one type of crusty muffin available. She forgot about my son's ice cream and when I went up to ask about it she stopped mopping,
didn't wash her hands and put it In a to-go cup because I guess she wanted to leave right at closing. I was too stunned to say anything. The furniture is also really threadbare and gross. Slow, staff was overworked, they didn't assign names to order which made it really difficult to know what food was which. This led to people taking orders that didn't belong to them and awkward conversations. Apparently it's really good but this experience was subpar. Maybe just avoid them in the early morning? Breakfast, lunch, coffee, wifi... Why WOULDN'T you go to Epic?
Breakfast menu is pretty great. They have all the regular stuff and it's made to order pretty quickly.

Lunch, they mostly have sandwhiches and cafe sort of foods which have yet to disappoint!

LOTS of different kinds of coffee and tea drinks. Their espresso shots are very high quality, so it's all good.

Mostly, this place is just fun and quirky. They encourage people to write on the walls in the bathroom, and it shows. There's a TON of stuff on every surface of the bathroom. Most of it benevolent.

If you're in downtown Tucson, first I'm sorry you're stuck in such an awful town. But secondly, good news; epic is right off Euclid! I went to Epic Cafe for lunch with my family and was served by Skyler. Skyler was very helpful and polite. She not only took our order, but made the food, which was great. Good job Skyler! After ages of meaning to, finally made my way to Epic and am so very happy I did.
Four specific things I can rate:

- Snappy service with a hip little smile.
- Funky old couches and clever bathroom graffiti that made me miss Seattle.
- Crazy delicious Chai!
- Even crazier delicious carrot cake - a slice of which is THE SIZE OF A FAT CHIHUAHUA!

And now I know, that if it ever came down to it, I can eat a whole Chihuahua. I can also try to make may way back to this epicness as often as possible. I had more fun hanging here and meeting people than anywhere ever. The open mike was good, the drinks were good, I like the staff, I like a little attitude, keeps the stupid people away. The smoking section on 4th Ave and University is a priceless hang. On my travels I measure every cafe coffee etc joint by comparing it to Epic! The atmosphere is nice, the food/coffee is decent, and the crowd is pleasantly quirky as they always are in such places- but the staff is undeniably cold. Never any smiles or hint of chatter. The kind of thing where the employee acts as if all the customers are just a bunch of nuisances. For some people that aspect (service) isn't as important as others, but because of the consistent unfriendliness of the staff at Epic I have found other cafés to frequent (you really have a nice selection to choose from around that area). So yeah, it's a pretty sweet place if you don't mind interacting with the cold staff behind the counter when you have to. Everyone is welcome at the Epic Cafe.  This place is the heartbeat of Tucson, Ariz., which boasts a wide diversity of people and cultures.  Close to the University of Arizona and downtown Tucson, the Epic has a wide array of freshly baked goods and numerous coffee options.  LET IT BE SAID,  I have never met a more conscientious staff--the owner could moonlight as a headhunter for Tucson corporations as he only hires the best.  I am a vegan, and the staff has gone out of the way to make sure that the items I receive are vegan.  I have never had one staff member say, "Do you want me to check if it's vegan?"  They just simply do it.  I spend a good part of the year on the road with my work, and know cafes from coast to coast.  The Epic Cafe is without parallel. I visit Tucson occassionally having gone to college there but I live in San Diego. I really love the scene at the Epic.  Before I get into that let me just say that the coffee and treats at the Epic are awesome but the vibe is what keeps me coming back. Talk about an eclectic clientel. Where can you see students, professors, desert rats, Rastafarians, political leaders, Buddhists, intellectuals, old hippies, and lap top jockeys under one  roof? The Epic. Nothing like this in "very Republican" San Diego. The few that did exist have been gobbled up by Starbucks. This place is not the fanciest spot in town but it is certainly the coolest and the food is good as well. Went here on a whim yesterday for breakfast.
The little lady behind the counter was very sweet and very nice. As it was our first time there, she was very helpful in explaining the menu and was patient with us.
We ordered two breakfast burritos, one with bacon and one with turkey and a strawberry scone.
We took the scone and went to go sit someplace but here, that is hard to do.  Most of the folks in here looked as though they had been here for a very long time.  Lapto

                         ## Rank: 9: Cup Cafe | (4.0)
                         **Category: Breakfast & Brunch, Bars, Restaurants, Food, Nightlife, Cafes, Desserts, American (New)
                         Amazing food.... This time I had the nicoise, and a bite of everyone else's baked skillet, the classic burger, huevos rancheros... simply delicious! Heads and shoulders above the rest for quality ingredients and excellent  execution. There is ambiance, great patio and really excellent cocktails. With family to visit here, I eat out quite a bit in Tucson and for me, this is it. It's not a fast food place, so be prepared to linger and savor the experience... it may take some time to be seated, order and get your food so come with good company and know that they won't rush your table either. Really good food, good service, and good atmosphere. A group of us went there for breakfast after reading the positive reviews online, and they did not disappoint. My only "con" is that it is rather expensive...bagels & lox with a bloody marry was $20 (after tip). Worth the price if you can afford it, though. The few vegan options they have are outstanding for Tucson.  Cauliflower tacos are flavorful if a bit too oily.  Queer steer made vegan is delicious. Breakfast plate with vegan sausage used to always please but lately is lacking in flavor.... Servers have been very knowledgeable about what is and isn't available as vegan on their menu and have also been very accommodating.

BLOODY MARY BAR WITH VEGAN OPTIONS on SUNDAY!!! YES
They have vegan worcestershire sauce! Great food with an inventive, southwest flair.  The heartbreaker appetizer is great: roasted garlic, brie, artichoke hearts, marinated cherries and toast is a wonderful starter.  `Enjoyed the duck ravioli, the chicken tacos, and the steak salad.  Everything was well prepared, great service, and relatively inexpensive pricing.  When downtown Tucson, this is the place to go. I love this restaurant... along with its vintage charm this is one of the best places to go for breakfast, lunch, or dinner. Their menu is very diverse and will be sure to satisfy. I had the Huesvos rancheros and iced horchata latte for breakfast this morning. It was just what I was looking for. Excellent job, and keep doing what you're doing!!! Overall I was let down, I have heard such good things about this place but last night it didn't deliver. My first ever trip to the cup was for breakfast, only I had a piece of chocolate cake and a coffee, both were wonderful. The breakfast looked much better than the dinner we had.

Our dinner server was very timid. He was slow and didn't know answers about the menu, bummer! We started with the tortilla soup. Chef Ramsey never would have let that leave the kitchen. We added a teaspoon of salt which made it edible. The dish names were creative and funny like the heart-breaker, our appetizer! It was good but for four people there was five pieces of bread, and remember the slow waiter, well we got more bread to finish off our starter, later.

The dinners were OK, nothing special at all. The salads were a tad over dressed with bland dressing, the sandwich was good not great. The highlight was the lemon meringue pie. The crust was like buttery candy, the lemon was nice and tart with pulp, and the meringue was done with pounds of perfection. The end result, the price tag was to high for the quality of food served minus dessert.

I dug the atmosphere, the patio, the floor, the old architecture, being downtown, and I will go back for breakfast but I will have to pass on the dinner fare. Staff and clientele here friendly and interesting. Recommend: "Omelette Bar: albeit not really a "bar" in the salad bar sense of the word.  You tell them which of the numerous ingredients you want and they bring it to your table prepared. If the coffee was better I'd rate at Five, but it's your Standard American Restaurant brew, a.k.a. "dirt coffee" as my charming and eloquent wife terms it... Funny-adult story about the 1st time I ate here. Starts with my BFF recovering from a breakup, there's 2 French Policemen on holiday & ends with the heart breaker & chicken satay. I've tried other dishes but always go back to the heart breaker & chicken satay. I wouldn't be surprised if they don't have them on the menu anymore because the funny story happened, well nevermind how long ago it was. It's still a funny story and the food at the cup is still GREAT!!!

Subtracted a star because sometimes service is a little iffy. There's been some occasions when I feel like I've interrupted servers FUN TIME. But, most of the time service is good. Cute little spot right inside of the historic hotel congress... I like it!

Been here for breakfast and dinner. I think I prefer the breakfast but both are good. To be honest I can't remember what I ordered for breakfast but I do remember how tasty the baked eggs my boyfriend ordered were! I'm pretty sure they've won an award so definitely worth trying. For dinner I had the Thai Fisherman's stew. Delicious, but nothing out of this world.

Cup Cafe is perfect if you have someone new in town you wanna show around Tucson. It's not the biggest spot so

                         ## Rank: 10: Urban Fresh | (5.0)
                         **Category: Vegan, Live/Raw Food, Food, Juice Bars & Smoothies, Restaurants, Breakfast & Brunch
                         I just stopped in for a quick bite and had the chili.  The chili was OK ( I do not like cinnamon in my chili), but I felt $4 was a little pricey for such a small serving.  I understand they are a niche restaurant, but the chili has no meat.  They must be making like $3.25 profit.

Even though, I think this place is a great addition to Downtown Tucson and I see them filling a niche that is much needed.  I am just looking forward to the day when I can go in and grab a $3 juice in the morning. As a meat eater, I was a little hesitant to try it but my wife is a vegetarian and she wanted to go. I had the green chili burger and it was great. I will definitely go back. The nutty monkey is as good too! Thanks Chauncey! Where do I even begin with this place? Since there is simply too much to cover here (and all of it good if not totally spectacular - just keep reading) I'll cover the basics briefly then cut right to the spectacular...

If you like raw, organic or plant-based cuisine, Urban Fresh is perfect. You'll find everything that you're looking for and a few things that will surprise and delight you: Fresh juices and smoothies, delicious wraps and sandwiches and sides that aren't fried. If you need a visual aid just look up on the TV screen to see pictures of all of their menu items. I immediately wanted to order the slideshow on Netflix.

At any rate, their every day menu is all fresh and unprocessed just as their website promises.

And now for the spectacular...

Ask the chef - who must be the owner given the passion that he exhibits for his food and the level of attention that he provides you with from the moment you walk through the door - this guy is nothing short of awesome - ask him what's NOT on the menu.

We were offered a raw burger - the likes of which I have never seen before or since - with a raw, house-made ketchup and house-made pickle on the side. It was totally unique and totally, well, spectacular. It's almost hard to describe because I've never had anything like it. Ever. You need to try it just to see what I'm talking about. I would go back (to Tucson and Urban Fresh) for this dish alone. This is such a great find! My work and I went here for my birthday and they loved it. I returned a few days later and will now introduce this place to other friends. Food is so clean and I can't feel I ate! Super reasonable prices for this well educated / run place. They know their shit and are implementing it.

Starving on a road trip and almost caved to eat some comfort food - glad I swung by this place first.

Sloppy joe was on point AF

Green Juice could have been more potent/ less sweet but then again I'm a pretentious coastalite Chauncey runs a friendly local business. Could use a little more diversity in the salad dressings, but everything is fresh. Nice place for a vegetable juice, too. This place is amazing - went with some co-workers and we were all impressed. The owner is friendly and attentive - recommended the Vibe Alive - it was so fresh and delicious - I topped it off with the ginger snap smoothie - another delicious addition. I didn't see anything on the menu I didn't want to try so I will definitely be going back. The owner gave us a tip about parking - any garage with a purple sign allows you to park an hour for free - there is a garage right across the street - doesn't get any easier than that! Nothing like having a meal prepared from scratch on your birthday! I had strawberry pancakes. These had sweet Potato and oat flour and we're light and fluffy with a strawberry syrup on top with a hint of mint oil and fresh strawberries. My husband had bisquits and cashew gravy. So yummy! Totally vegan. Tiny place. Best smoothies in Tucson. You would think you were in San Francisco! I ate here today when I was in the area for a meeting. The owner was super nice and explained the menu to us, and gave us some good recommendations.
I had the shiitake mushroom soup with the south of the border wrap. It was so good that I went back later for a tropical cream smoothie.
I loved everything and would definitely go back! Fresh organic local fare at fair price!

Really good food made with love and the love keeps you going.  This place is a GEM in Tucson My absolutely FAVORITE place to go! I am not vegan, or even vegetarian, but I tried this place out on a whim one day, as I was getting to know the downtown area. I'm SO glad I did!

Since that first day, I have been there nearly five times per week for smoothies and lunch. Everything on the menu has been absolutely amazing and SO fresh - I highly recommend you try out the daily specials!

The couple that owns the place are so kind and you can tell that they put a lot of thought and love into their food. They genuinely care about their customers and go out of their way to make sure that each person feels satisfied.

I know how hard it is to build a business, and bring as many people as I can to try out their food - just to help get the word out. I've t

                         ## Rank: 11: Salad and Go | (4.5)
                         **Category: Salad, Restaurants, Vegetarian, Breakfast & Brunch, Vegan, Fast Food
                         LOVE this place!! Big portions, one salad makes two meals for me. Very good prices. And the tofu.....AMAZING!!! It was seasonal but the prickly pear lemonade was FANTASTIC! Will definitely be going back and soon. Easily customizable, vegan friendly, and affordable! The Balsamic Vinaigrette and Thousand Island dressing are vegan! I asked for a Veganized Bbq Ranch salad with balsamic vinaigrette, veganized Greek wrap with balsamic vinaigrette, and Frozen Strawberry Lemonade. I loved it all! Especially the deliciously marinated tofu. I could drink that frozen strawberry lemonade all day. I was invited to the influencer event and got to try some of their menu items before they open on 8/26/2021!

I ordered the BBQ Chicken salad, Caprese salad with shrimp, frozen strawberry lemonade and the cucumber mint lemonade and it was all so amazing!

The prices are seriously unbeatable!

Salads are $5.74
Burritos are $2.99
And drinks are $1

My new favorite lunch location!

So happy they are in Tucson! A new location will be at the tucson marketplace! Yay! Chronic! Such great value for fresh and healthy food! The cold brew is super dank and has gotten me way jazzed! Will definitely have to start coming here more often! Super fresh lettuce and veggies with a variety of salad types to choose from. You can substitute the recommended salad dressing easily.  We would easily and happily pay a couple dollars more per salad since they are fairly large and so fresh. The strawberry lemonade is very tasty and not too sweet. We'll be back for sure! Tried thier salad today. Ordered the Jalapeño Ranch salad with chicken and no cheese and a cold brew.  All the salads are $5.74 and their drinks $1.00. Salad was very filling but, cold brew was on the weak side. I'll do no ice next time ans see if it's a little stronger. Good location but, be careful going in and out of the parking lot especially if you have a low ground clearance car. Salad and Go is THE definition of bang-for-your-buck.
$5 hearty, hefty salads. And any salad can be turned into a wrap...FOR FREE!?
My wife and I go here at least 3 out of 5 times of our work week. It never misses.
It satisfies your hunger, and your wallet.
If I could be a sponsor for Salad and Go, I would.
Love this place! New eatery!  I'll begin with I love a good salad, however I don't usually eat them on the go.  I had some errands to run and thought I'd eat it in the car at one of my stops.  Since it's a new eatery, there was a line of at least eight cars ahead of me.  Took about 15-20 minutes to get through to the window.

I had the Buffalo Chicken salad.  The ingredients in the salad are separated with chicken in one corner, tomatoes in another and so on.  Dressing came in a little pack.  You definitely need to stop to prepare the salad.  This salad in my opinion was good, but pretty ordinary.  Price was a little over $6.

If your in a rush and don't want to stop at the market this is probably a good alternative.  I'm sure I'll try it again.  However if I'm really in the mood for a great salad I'd go west from her and go to Choice. I like breakfast burrito size. I'm disappointed they charge you .54 cents for more salsa. The salsa they give you is too little for the breakfast burrito. Also hard to get out of sometimes due to speedway traffic, and small turn in off craycroft. That gas or water line placement off craycroft,  matter of time before some probably hits it. This place makes it easy to eat healthy on the go adding the extra protein is important and makes a big difference for less then 2 bucks. If your in a rush order using the app you'll be in and out just don't place the order and walk to the window you'll be waiting. Excited to try this place.  The mango green iced tea was good and only $1.  Breakfast burrito was just ok though and not enough salsa for the entire burrito.  Will be back to try a salad and lemonade soon. I had a BYO salad that was very good, but their balsamic vinegar is disgusting. Next time I will pack my own balsamic vinegar. Mango green tea was delicious and all drinks are $1 in a big cup. Drive thru looked like a mess. I recommend ordering via the app, parking, and going to the pick up window. I've been hearing friend from Phoenix rave about Salad and Go for a while, so I was pretty excited when they opened one on Tucson.

I've been there about 4 times and I love it!!! Being able to order online and set up a pick up time is so convenient. I like the variety of salads, burritos, snacks and drinks.

So far my go to is the Buffalo Chicken salad. I get it without croutons and extra veggies and there is enough chicken to not even need dressing. Which gives me a healthy, fulfilling meal at 300 calories.

I've also gotten the cold brew with oat milk multiple times. It's pretty good and for $1 it's an amazing deal.

So I can get a salad and drink for about $7... you can't beat that deal. I hope they open lots more locations all over Tucson!!! So nice to have a (relativel

                         ## Rank: 12: CharroVida | (4.5)
                         **Category: Desserts, Vegetarian, Mediterranean, Modern European, Vegan, Mexican, Food, Restaurants
                         Dinner experiences should be memorable, this was far from it.

Cocktails are meh.  It's like they have jugs of premixed drinks that they just pour over ice. I got their house margarita. I would not recommend it. Get a custom cocktail / off menu so they pour properly. It's like they forgot the alcohol in our drinks.

Food was just ok. A bit overpriced, bland and just not a meal to remember. Nothing stood out as a unique or a have to have entree. Just... ok.

Probably won't be coming back. Interesting concept, but honestly prefer El Charro up the street more, both food and pricing is much better. I've been a vegetarian for 23 years and while the primarily plant- based menu provides a lot of options, I really just wanted real cheese (not plant-based). Enchiladas were decent, beans were way too salty so couldn't eat them. Dessert also would've sounded way more appetizing if it wasn't an entire gluten-free/ plant based dessert menu. Not sure Tucson is ready for this concept, will be interesting to see if they make it. Also, this really isn't a Mediterranean menu it's Mexican Food. On the bright side, service was excellent. What an amazing restaurant! From the hostess at the front, throughout our service with Jeremy, we had a great dinner. Two of the five of us are vegan and one of the non-vegans and my husband and I LOVED the enchiladas banderas with plant based crema. The white or Peruano beans with a few garbanzos were amazing. Our table side hummus guacamole was perfect and the platano chips were a perfect accompaniment. Bravo Charro Vida Food was good and prices decent - maybe one too many deep fried items.  Service was chaotic at times.   Would go back but don't sit in rear area - too noisy I, and five friends, had a late lunch today and the food was amazing!  I had sunflower chicken.  They also had yummy branzino and salmon dishes. The decor was all about succulents, which I love. The service was great, too. I highly recommend it. Wow! Food, service, atmosphere & location is outstanding!! It's my new favorite in tucson, awesome Vegan & Gluten free options! I opened a new yelp account just to share my experience, its a must dine! Great job Charro Family!! Great food, great vibe. I didn't know that healthy Mexican food could taste this good! Every dish I've tried is excellent. From the main dish to the sides, everything is paired perfectly!! Bienvenido's a CharroVida!  It's been long overdue. Suffering with celiac's disease has been the most difficult cross to bear but fear not I have found an incredible ally that won't be a secret for long.  The Flores family's newest dining experience has arrived at Ina and Oracle in the Casas Adobes Plaza. We purposely lead with vegetables, add in whole grains, use only natural sustainable proteins and cook in only the healthiest plant based fat! I say WE because I have decided to join the team at CharroVida and work for the most endearing family I have come to admire, appreciate and be grateful for the concept in that this is what love looks like. When you care enough about people to cook for their health so they can live longer, healthier, happier lives surrounded by family...what an incredible gift. The mouth watering options for brunch, appetizers and entree's come in combinations of gluten free, plant based and vegetarian dishes and the beauty is that any dish has an option to add proteins if you so desire.  Our desserts such as gluten free Churro Dreams lay on top of a chocolate ganache, Yes we did it cookies are  gluten free dairy free and come with 1 each of peanut butter, sugar and chocolate chip cookie with a side of almond milk, not to mention our gluten free cheesecake with an almond crust that is to die for. We have become famous and I mean famous, for our in house made fresh daily hummus, avocado conjunteros dish with 6 additional ingredients you get to customize as it's made for you tableside!  With these options in mind, our kitchen has been designed to have separate grilling stations for proteins and a separate grill for vegetables with a separate fryer for gluten and non gluten items to prevent cross contamination. We have color coded cooking utensils for our kitchen staff and executive chefs to ensure we maintain our commitment to our customers dietary restrictions or food allergens. The time is now, make a reservation for Tucson's newest dining experience, this will surely change the way you think about food or better yet you will fall in love with food again. Charro Vida is a fabulous place to accommodate multiple tastes.  Chris is an excellent server who is knowledgeable about the menu. Awesome place and awesome food. HAPPY HOUR is for real. We will be back. Wow!  Fresh,scrumptious food.  Everything served beautifully, a feast for the eyes and so flavorful . This is not typical Tucson Mexican food.  We had a large group and everyone was delighted.  It was journey into new rich, deep flavors but not heavy. The service was excellent as well, so we wi

                         ## Rank: 13: The Tasteful Kitchen | (4.5)
                         **Category: Food, Desserts, Event Planning & Services, Vegan, Caterers, Vegetarian, Gluten-Free, Food Delivery Services, Restaurants, Shopping, Arts & Crafts, Salad, Cooking Classes
                         This is some of the best vegetarian fare I have ever had, and the prices are very reasonable. I got the eggplant dish and was in food heaven; it was like nothing I've ever had before. I also tried all of the meals we got and they were pretty much mind-blowing. I can't wait to go back!

I did have a few issues, however, with the experience in general. They had run out of a couple of the dishes by the time we got there (not sure if this is common), but we had a 6:30 reservation which is pretty early IMO. For a restaurant that essentially has 4 items on the dinner menu and a couple of specials, that really limits your options. I was also not too impressed with the service. Our server was very friendly but they were clearly understaffed. He was running around like a crazy a person; I believe he was the only waiter working. No fault of his own, clearly, but our water glasses were empty for quite a while and the general service experience felt rushed/harried. This was an unforgettable experience. I went twice while in Tucson on business. The eggplant was amazing and i would recommend the banana cake any time! Wish I had one near where I live! Perfection!  I have been wanting to try this restaurant for a while and now I am kicking myself for waiting so long.  The service was very friendly and attentive.  The food was prepared perfectly...freshness, quality, flavor, portions, and presentation could not have been done better.  The prices were incredibly reasonable.  I can't wait to return for another delicious dinner. I made my first but not last visit to the Tasteful Kitchen this evening and it was awesome.  I started off with a fresh organic juice served in a small martini style glass. The juice was made from beets, apples and ginger.  (there was another ingredient, but for the life of me can't remember it).   This was followed by the Creamy Carrot and Avacado soup and a fresh salad of greens with red peppers, mushrooms, carrots, sliced appled in a ginger based dressing.  Made reservations for this weekend, it was that good and fresh....tempted to deduct a star because they were out of the Mean Green Ice Cream and Lemon Basil Sorbet, but hopefully it will be there on Saturday to try, sounds really good....I didn't experience any negativity from the wait staff, in fact I found all 3 to be friendly. Let me start by stating I am not vegetarian, but I could easily become one if all vegetarian food tasted like this!

This place is so quaint and nicely decorated, visually - a truly lovely little restaurant.  It is owned by two sisters.   We came for a friends birthday, there were 11 of us - and they had a lovely big round table set up for us off the little main dining room.  The friend whose birthday we were celebrating is on such a restrictive diet that it was refreshing to know that she has a place to eat where she can order at least half of what is on the menu. (she loves this place, and has attended a cooking class they offer).

Many of us are far from vegetarian, but I think all of us were impressed with the food.  My hubby is a steak and potatoes guy and even he commented on how flavorful the food was.  Foodwise:  We started with the green chile quesadilla's which were DELICIOUS, I couldn't believe how yummy they were with squash and chile.  My husband ordered the full Thai (or Asian - can't remember the actual name of it) peanut salad which was huge and tasted pretty darn good.  I had their special which was roasted vegetables and Quinoa and it was outstanding.  My girlfriend ordered their vegetable ratatouille since she and I decided to nibble off of each other's plates and that was actually my favorite, VERY robust in flavor.  Other's at our table ordered the microbiotic plate, the potato stack (called something else on the menu) and spaghetti two ways.

For dessert - those of us none vegan's were happy to see two "classic" desserts listed on the menu - the one that jumped out was the Carrot Cake.  One of the sisters who was serving us told us that it was her Mom's recipe.  It was not disappointing and SOOOO yummy.  The best part about it was she doesn't put raisin's in it which I appreciate since I feel raisin's have no place in a carrot cake.

Overall great experience, ambiance, service - I would come back, even as a non vegetarian. I'm not vegan or vegetarian but enjoyed it thoroughly. Had the cauliflower steak which was deliciously prepared and satisfying. Being a meat lover, I was skeptical but the food here was good enough to convert me. I won't be converting but just for frame of reference. If you're turned off by the category, but are a food lover- come here for a wake up call. It's worth considering the ecological impact of having a large slice of cauliflower over a piece of beef, with no loss of flavor or satisfaction. All philosophical or political issues aside, tasteful kitchen is a nice local place with fantastic food! Never came to Tucson but looked for a vegetarian restaurant.  Love it!!!!  Fr

                         ## Rank: 14: Lovin' Spoonfuls Vegan Restaurant | (4.0)
                         **Category: Restaurants, Gluten-Free, Vegetarian, Comfort Food, Vegan
                         Great vegetarian restaurant in tucson.  My favorite veggie burgers in tucson. My bestie (the vegan) made me go here and... it was awesome! I have been here a number of times with her and with others. Now I am not going to become a vegan (even if this is my bestie's personal goal in life) but I do enjoy the food here! I have had the chicken nuggets with ranch, ravioli, meatloaf, stroganoff, and classic burger and they have all been really good! Servers are excellent and the atmosphere is laid back. This is a great place for breakfast, lunch, and dinner! I am not vegetarian or vegan, but I enjoy the food and if it's available, will gladly partake. My sister prefers vegetarian food, so while she was in town, we had lunch at Lovin' Spoonfuls.

I ordered the Adzuki Burger and thought it was fine. I felt it needed a little additional seasoning and something crunchy. It did have a crispy outside, so that was nice. The coleslaw could have been crunchier. The portions were good and the service was quick and friendly.

We all enjoyed our meals and left feeling satisfied ... but I can't say I'm a fan just yet. I would like to preface my bad review with this statement: We have only been to this restaurant once. We are vegetarians and were very excited to try out this vegan restaurant- we had high hopes! We had the spring rolls, the beer-battered brat bites and the southwest veggie burger. The spring rolls were very mushy and slimy on the inside, not to mention the fact that they were FILLED with OIL! They tasted identical to the spring rolls you get from the frozen food section of any grocery store. The brat bites were good- not something I would usually even try, but the name sounded interesting. The burger was extremely lackluster. This place was said to have to best veggie burger in Tucson... If so, this is a sad situation for Tucson. It is unnecessary to have everything so drenched in oil- this is supposed to be a healthy and wholesome restaurant... I saw nothing healthy or wholesome about it. This is not a place for real vegetarians or vegans.
On a more positive not: I didn't try any, but the desserts looked amazing. Perhaps that is the one thing Lovin' Spoonfuls gets right. stopped here while in Tucson, ordered the southwestern burger and the deli club both were excellent.
the guacamole was fresh and spicy and the black bean burger patty taste very good. Absolutely amazing!! Staff very friendly and remember me every time :) HIGHLY recommended Nice to have a vegetarian option in town.  You order and pay at the counter and then wait for someone to bring the food.  This makes it seem more like fast food, but the wait time is pretty substantial.  The atmosphere is a random assortment of old people-ish junk and it's kind of dark in there.  The menu has a huge variety.  However,  I haven't had anything amazing.  The veggie burger was just a veggie burger.  The Thai-style curry was watery.  I'm not lovin' the idea of going back there. I just found this gem. The first day I went, I had lunch and dinner there.  This place is a must if you like vege food. Food is very good as usual.  Service on Sunday mornings lately by two young guys has been excellent. So so food....kinda bland no zing or spiciness...kinda pricey...if you're gonna make it bland lower the prices....the ambience is bland also...kinda like eating in a vegan morgue.  I've been to much better places in different parts of the US.  Guru's cafe in Provo Utah comes to mind...what a cool place....very adventurous ambience and foods....same prices but much more interesting food. This is restaurant is a gem!!  What a wonderful experience.  The ambiance is very nice.  Lovely design in a clean and comforting space.  My starter salad had the best dressing ever!!  The Thai green curry with tofu definitely hit the spot.  I had this over whole wheat penne.  This kept my healthy commitment while exciting my taste buds.  I'll definitely be back in the next couple days.  :) So good!! Like, take a bite and your eyes roll back in your head kind of good! The best vegan food in Arizona! If I could give higher than 5 stars, I would! Fair disclaimer: I'm definitely a fan of meat, and that has a lot to do with how I feel about Lovin' Spoonfuls.  But I should also mention that I am a fan of vegetarian and vegan cooking, and given the great reviews I've heard about this place, I came to Lovin' Spoonfuls filled with eager anticipation.

First, the good: the owner is just so incredibly warm, friendly, and approachable.  She clearly loves what she's doing, and I think that's awesome.  Also I live with a vegan, and I have a number of friends who don't eat animals to varying degrees (sometimes chicken's okay; sometimes the line is at fish; sometimes as long as it's not meat we're in the clear).  These are people who have grown accustomed to opening menus at restaurants and having a very few options to choose from.  Seeing their eyes light up when they look at an extensive menu from whic

Label Query: Best date night food spots

                         ## Rank: 1: Sher-e-Punjab | (4.0)
                         **Category: Restaurants, Salad, Pakistani, Indian, Cocktail Bars, Food, Food Delivery Services, Soup, Halal, Bars, Nightlife
                         One of my most favorite Indian restaurants. Nothing fancy but absolutely delicious meals.

Never an issue being seated promptly. A casual dining experience awaits. Service is pleasant. Ambience a bit blahh but still enjoyable.

Now onto the real reason to come here... the FOOD:
Naan is soft. Garlic is tasty but I usually like the original best.  Regardless of your entree of choice, you really cannot go wrong. And although it does not appeal to my level of spiciness preferred (I like it HOT HOT HOT), it has great flavor and is great for the average spicey food eater. My recommendations are the Masala or Vindaloo (Chicken, Shrimp, Lamb... option is yours). Room for dessert? Order the Rice Pudding  and Gulab Jaman, mix together and enjoy the creamy sugary treat. Food= Amazing
Service= Great
Prices= Reasonable

Stop reading and start eating! OK lunch buffet, but too oily.  i think weekend buffet is better than weekday. Favorite indian place in Tucson, hands down! Most always get meat samosas, tiki marsala, veggie korma, rice and naan. Never disappoints! The only complaint is one time on a to go order they forgot their delicious sauces for the samosas, but only happened once. Otherwise, get ready for a party of flavors and spices in your mouth! I'm torn between 3 and 4 stars, but have decided to go with the more generous offering?  Why?  Because this place has one of the most generous menus as far as choices go.  There is a ton to choose from, even if you're vegetarian.
Formalities first--why can't there be some ambiance at Indian restaurants.  I know I'm painting with broad strokes here, but it seems like outside of NYC, no Indian restaurant in the US can get creative with their dining space.  Not sure why that is, but whatever.
An early arrival on a Sunday found the place quiet, with maybe 10 or so people dining.  No problem getting a table for 2.  We started the evening off with some garlic Naan.  Delicious, although I think next time I'll stick with regular, at almost half the cost.  We also got some Finger Paneer, little spiced fried cubes of cheese.  These were denser than typical Paneer.  The cheese was slightly bland, but the spices were good.  Overall, an enjoyable start to the meal.  I also had a lemonade, which may have been made fresh.  Regardless, it was tasty.
Entrees included Paneer Bhurji and Lamb Shahi Korma.  We elected "spicy" as our seasoning level.  I'll admit, I have a pretty strong ability to deal with spiciness.  But this was some ultra-spicy food when it arrived!  We quickly ordered a mango lassi to help put out the fire.  Still, even through the spices, there were decent flavors coming through.  The nutiness of the Korma was especially nice, as was the blended creaminess.
I'm intrigued enough to return for more offerings.  I am humbled however by their spiciness--something that has not happened to me in many many years.  Next time, I am going to stick with "medium" spiciness! Everybody in our lab is a fan of their food, and we all come from different parts of the world and glad we agreed on this immediately. It's a frequent lab lunch spot. Their buffet is just fantastic, everything is cooked spot on and nowhere beat their price. I normally have to skip dinner after their lunch buffet cuz I just can't stop eating over there. Service = pleasant, but not outstanding by any means.

Ambiance = slightly gaudy (unattractive decor and faux flowers), a bit dark without feeling cozy.

Food = disappointingly lacking in flavor and quality.  We ate at the lunch buffet on a Saturday, if it were priced $4.99 instead of $8 I might be less inclined to complain, but it was entirely unexceptional.
I have eaten at many different Indian restaraunts in 5+ countries and multiple cities (most recently Monterey, California where Ambrosia is by far some of the best Indian food I've ever had) and Shere Punjab is one of the worst Indian food restaurants to which I have been.

The naan bread is thin and flavorless, vegetable dishes are significantly lacking in the expected robust flavors and spices, the texture of things (for instance the Saag (spinach dish) seemed as though it came from a can. Blended like baby food. Not a lot of selection.
There were no labels on the food at the buffet.

To say the least, this place did not satisfy my craving (nor my fiance's) for good Indian food and we will not be back.

I can only assume that the people who rave about this place have not had the fortune to eat TRULY mind-blowing, mouth-watering high quality Indian food. I've become a fan of Sher-e Punjab over the last couple years despite agreeing with some of the same criticisms that have been voiced here by others.

The overpriced naan and charging for rice are a turn-off. Especially the rice. You may as well charge for ice in my water.

I almost did a spit-take when I read Brooke's comment on the decor - so ridiculously true. The place is gaudy, but no more so than so many of your typical Asian-immigrant businesses. Just

                         ## Rank: 2: HUB Restaurant & Ice Creamery | (4.0)
                         **Category: Ice Cream & Frozen Yogurt, American (New), Nightlife, Sandwiches, Bars, Restaurants, Salad, American (Traditional), Desserts, Food
                         Best ice cream in town! Hands down! They come up with really unique flavors that are so deliciously dreamy. The food is also pretty good but I wish they carried more gluten free options. Reasonably quick service and nice intimate atmosphere, I had a chicken salad sandwich that was very tasty! Also had an a cheese plate as an appetizer and was pretty satisfied with that as well. Didn't get a chance to eat dessert but I've heard only good things about their sweet and salty caramel ice cream! Will definitely go here again :) Sunday night dinner. Corn & Poblano Chowder, Cajun Linguine, Corned Beef hash, a glass of wine, and HUB ice cream. Great food and service last night. The 'room' is very attractive - modern & historic at the same time. I'd been to Hub a number of times for drinks or ice cream and a couple times for dinner in the past and always really enjoyed it. I had not been in since long before they remodeled. (Note: Other than the bathrooms, I have no idea what they actually remodeled, because it looks the same.) I have no complaints about the service; it was pretty great. Our server and the guy who brought our food were both very polite and friendly. The newly remodeled bathrooms were nice, but they should have staff check up on them more often as the women's could've been cleaner.

I must've ordered the wrong thing. I dined with two friends, and their food looked really good. I thought a grilled cheese and tomato soup sounded good, so I got the Big Cheese. It was just okay. The cheese wasn't melted all the way through. The tomato soup was housemade but could've used some spice or herbs. They have a decent tap list, but they seem to focus heavily on IPAs. My friends had the veggie sandwich and the Cuban, and they both liked their food. I will return and get something else next time. First of all I want to say, whatever you do, try the ice cream at HUB! Even if you aren't hungry get a taster of one of the many unique flavors HUB offers. My personal favorite is the Oatmeal Cookie Dough! Eating that ice cream reminds me of being a kid, begging my mom to have some of the cookie dough as she made oatmeal cookies on a cold, rainy day.

But back to HUB...When I first walked in my initial thought was, "This isn't Tucson, this is some trendy restaurant in LA or New York". We were seated promptly and took a glance at the drink menus before ordering. Someday I'll be brave enough to try the Nathan & Mark cocktail (Makers and Pickle Juice) but I opted for one of the many wines on tap. Wine on tap seems to be gaining popularity here in Tucson, me gusta! During happy hour the wines on draft are $5 a glass. I opted for the Merlot and it was a great choice. They also have a pretty good beer menu, I'll try and order a micro brew if they are ever out of the Merlot.

We've had the opportunity to try quite a few dishes on our multiple trips to HUB. The burger was great - juicy and even better with cheese! The Vegchetta was great too- I just wish the veggies came hot, not cold. That was an adjustment but it was still very flavorful. The mac n' cheese is also very good!

Great addition to the Tucson downtown scene. I'm happy that HUB has opened up downtown and excited to see what the future holds for downtown Tucson! oh i haven't been to hub since everyone i've talked to said the food was blander than beige and the service was bad. wait, I did go there once. That held true. It was during the day, and we said we were just going to get appetizers and ice cream so they ushered us away from the decent folk, presumably ordering steaks, and seated us in the bar room. (jokes on them, we preferred it there.) Anyway, the price of two appetizers plus two ice creams was the same price as two luncheons, but I suppose this fact may not have occurred to them just yet. The tater tots tasted great, that is to say they tasted like tater tots, and the sauce was delicious. The presentation was a little sloppy, and for the price you didn't get much. We got mac and cheese which was good too. I mean, what mac and cheese isn't? However, the service was remarkably bad. We had to go fetch our waiter, despite that he was also the bartender and was working two feet away from us. He wasn't doing anything, just some light cleaning. It was actually kind of weird. Like, he could see us staring at him, and he stared back... but just didn't come over. Anyway, sure I'd go back, but not by choice. Crazeamaze food, beautiful environment, music was great and loud enough without overpowering,  the fooodddddddd.....mmmmmmm Awesome food! Can't get enough of the pastrami.  The whole vibe of the restaurant is very cool and hip but not uptight.  I wish they would bring back the pastrami skewer with roasted red peppers, olives, and mozzarella cheese.  They had one of my all time favorite Zins (Klinker brick) and a great selection of craft brews on tap.  After dinner we walked around downtown and then came back for ice cream-soooo good! Okay experience. Sat and waite

                         ## Rank: 3: Royal Sun Restaurant & Bar | (4.0)
                         **Category: Event Planning & Services, Bars, Lounges, Karaoke, Restaurants, Comfort Food, Nightlife, American (New), Hotels & Travel, Hotels, Breakfast & Brunch
                         Last minute stop, unexpected dinner.... Was so happy to have great service and great food! Highly recommend!!! Love it! Diner food but with a bit of upscale modern thrown in. Dinning room is beautiful looks new still. Waiter the serve me was super friendly and really enjoyable. Wil defently be coming back! Sunday morning and I and friend were picking up a couple of pieces of art from a show that was closing, no one was there yet so we walked down the street to the Royal Sun.  It is a throw back in time, not in a good way that mishmash of when the 80's came crashing into the 90's of southwest pastels and pungent browns' it was like the carpet and the colors left a visceral taste in my mouth.The waiter was kind of all over the place friendly one moment and then a little bitchy and edgy.  After looking at the menu I asked "Ron what would you suggest"  He told me not to call him by name even thought he had a name tag on.  After the incident he was okay, but it was difficult to ask him for anything else.  I really can't blame the guy, I wouldn't want to be working here either on a Sunday morning on a nice Tucson winter day.  I will have to say the food was not bad, and the bacon cooked perfectly, but my friend got the ham and it was spongy.  So if it is convenient to eat here go for it, but if there is a way to get out of it, I would veer in that direction of away.
Also it was expensive for what it was. What a Tucson gem.  If you are looking for a place to eat, drink, and hang out without having to deal with the downtown club scene, this is the place.  They have great local beers on tap at a reasonable price.  The food is fantastic.  The staff is friendly and fun. Why did you remodel your bar!? It lost its charm, warmth, and vibe, was once my favorite karaoke spot. I'm so sad the wine cellar ceilings (which made for wonderful acoustics) and fireplace are all gone. The gray walls and decor look 80's and are cold and uninviting. Our tab had extra items on it and was much more then it should have been. The bartender was also missing for a good chunk of time, I think outside smoking, when we were at the bar waiting for drinks. I've been pleased when visiting here in the past but tonight was a HUGE letdown. Wow! We just ate at Wild Garlic Grill last night, dropped nearly $100 for a mediocre meal and worst service ever, then came here and got a DELIGHTFUL surprise!

Not only was our breakfast delicious, the service was friendly, top-notch, and timed perfectly.

My traditional breakfast of eggs, choice of breakfast meats, hash browns or home fries, pancakes or toast, a fresh fruit garnish, and beverage--all extremely reasonably priced!

My hubby chose Oatmeal with fresh fruit, juice, and toast.

And if you stay at the adjoining Best Western Royal Sun hotel, you have a choice of these, plus many more breakfast option at no charge!

Absolutely loved it, and the hotel was wonderfully updated like an Embassy Suites inside, too! We had a late dinner here and a breakfast the following morning. The Arizona hamburger is to die for and their beer selection is good. But the best was our waitress Hanna. Even though we arrived for dinner just minutes from closing she gave us great service both at dinner and again at breakfast. While the meal last night was alright, it took a long time to arrive, and was almost over cooked.... Sweetpotato fries where not HOT...

BUT THE COMP BREAKFAST THIS MORNING WAS THE BOMB!!!!

Great service thanks Hannah, and food was very good too!
Thanks for offering this deal to the motel... This is our go to place for karaoke for the last 4 years

We have tried other places, but always end up leaving them to come here.

The crowd is always great and I've always felt comfortable singing.

The drink specials are always great and they allow me to experience something new. we dined at this restaurant on 8 Sept 2014 and enjoyed it so much that although we live in Sierra Vista, we returned on 10 Sept 2014.  This restaurant is definitely Tucson's best kept secret.  The menu is well diversified, the staff is friendly and happy, I even heard singing from the kitchen staff.  On our first visit we had rib eye steak, and on the second I had Tuna steak and my wife had the Chicken warped with prosciutto.  On a scale of 1 to 10 I would rate this experience a 9.  The food is prepared and presented by chiefs in a way that befits a 4 star (****) Restaurant.  If you want to do yourself a favor and treat yourself to 4 star cuisine, at a 2 star price you must dine at this restaurant, I can guarantee that if you try it once, you will return. We wanted a steakhouse nearby the Best Western, where we were staying. We went to Classic Spaghetti Western Steakhouse, but there were few cars in the parking lot and we couldn't see any patrons in the restaurant. I'm not opposed to eating at a restaurant where I am the only patron, but my companion is (doesn't like hovering waitstaff). We went back to the BW and asked the front desk

                         ## Rank: 4: Subway | (3.5)
                         **Category: Restaurants, Sandwiches, Fast Food, Food
                         This location gets 5 stars for service and cleanliness, as well as freshness.  Egg salad - yum.  Meatball sub, cold cut trio for only $2 this month is unbeatable.

Also,  an employee named Shimin said to me "I hope you enjoy your meal".  This was so refreshing, because that is what should be said.  Not "Enjoy!" because that is a command.  Not "I hope you enjoy!" because you have to enjoy something, you can't just enjoy...Shimin is one of the few people I have ever encountered in my life to say the phrase appropriately.  Hats off to you sir.  Keep up the good work. Wowzwers , they should've named this place scum-way .
The employees are nice , but the food is terrible . This whole in the wall is an excellent place if you want diarrhea.
I went there on a date and it was ruined because me and my date ended up keeping the toilet seat warm for each other the rest of the night .

Also , on my last visit I noticed a ton of gnats flying around the veggies , cheese and cold cuts . I've been dining here for sometime now. It's a Subway so it's good for lunch or a quick bite to eat for sure. Staff are friendly and the restaurant is always tidy. They are usually pretty generous with their samples and cookie bites which is a nice touch as well. What can you say, It is a Subway !  Good cheap sub's and fresh baked cookies !

Stopped in tonight to grab a sub quick, ........ Well, the person ahead of me had about 5 different orders on his smart phone, and his daughter with him with her 2 orders !  So much for quick !  There was a gal that seemed to be the manager and a young man that seemed like he was somewhat new.
The manager gal seemed to be busy helping a previous customer, while the new guy got Mr. Smartphone going with all his special requests. Manager gal was busy multi-tasking with bread and cookie baking, while trying to help the new kid out. Neither one of them got frazzled, they handled themselves quite well. I would not have been able to, I know that !  It is not easy to work in fast food. Thanks guys for keeping a smile on ! I didn't want to cook tonight. And I discovered this subway next to the new postal annex in the Safeway shopping center.
I always order the BMT on Italian. My sandwich guy was going to put (2) corner slices of cheese on a six inch sandwich.
So I paid .75 cent more, now it's four.
In the end it was good , I always add guac

That and chips n coke, I was set.
10. Bucks  , I think I got my money's worth. There is inside AND outside seating. Outside has umbrellas.

I looked around , seemed clean and one was wiping the metal areas down.
Covid precautions observed.

I would go back! What can I say...it's a Subway. BUT, the place is clean, the employees are hickey-free and fairly well spoken (that is until the next turnover) and the sandwiches are well prepared.

This location isn't very visible but glad to know they're there!! The young woman that prepared our sandwiches had such long decorative fingernails that they had poked through her gloves on two fingers.  It was unpleasant to think about how unsanitary that is as she dipped her fingers in each cheese and vegetable bin.  So much for improved conditions during Covid!  Yuck! Tomorrow is a road trip so we're picking up travel sandwiches.
I got the BMT Italian and my wife got the tuna on wheat.
Both 6 inch size.
They will Keep in the refer till the morning. They will be a great lunch for midday.

They do  have a daily special that is half price if that's what you will want. We took our regular favorites. Full price.

Always consistent quality. There's an employee there that works on the weekends named Travis. Best employee there!!! He is so kind, he welcomes you in, he's fast and very caring. I went and they didn't have anymore mayo left and he recommended I tried the Spanish something sauce instead. OMG IT WAS SO GOOD!

                         ## Rank: 5: 47 Scott | (4.0)
                         **Category: Restaurants, Nightlife, Breakfast & Brunch, American (Traditional), Comfort Food, Bars, American (New), Cocktail Bars, Gastropubs
                         Wonderful evening, great service, yummy food, and an all around relaxing place to have dinner.  This was our first visit, but not our last.  The greeting at the door as we arrived was welcoming.  The decor was very peaceful, relaxing and inviting.  What a great place to spend an evening. The service was perfect, with great explanations of the dishes,  and attention when needed.

The arugula salad was wonderful with a creamy goat cheese and beet addition.  H had the mussels and crusty bread and then a burger with crispy fries, just like he wanted.  I had the stack of grilled cheese, adding mushrooms and tomatoes.  The serving would have easily served two people with a shared salad, so we have lunch for today.  The Grilled Cheese was out of this world.  Yummy comfort food with a twist, the spicy dipping sauce gave it a zing.  When I asked to pack up the left over, the server offered extra dipping sauce!!!  Way to go.  Will be back, just loved this place. My favorite restaurant in Tucson. Consistently EXCELLENT.

Because it's my favorite, I come in here a lot, and frequently crave multiple things on the menu. I love the phyllo chicken dish, and it's my go-to if I'm really hungry. I also love the stuffed pepper dish -- it's amazing and worth trying even if you aren't a vegetarian -- I think it's one of the best dishes on the menu. The grilled cheese, well, it will change your life for many reasons but mostly because of the house made mozzarella inside. My favorite is to just get it plain, but you can get it with fancy things inside if you so desire. The sauce that comes with it is sweet and spicy and amazing. If in season, I pair it with tomato soup and the kale salad.

Their brunch, oh my goodness. Just in case an awesome dinner isn't enough, you can go back the next morning for an awesome brunch. Best bloody mary I have EVER HAD. In fact, the first bloody mary I actually liked came from 47 scott. And I didn't just like it, I loved it.

It's fun to go to their next-door speakeasy, Scott & Co, either before or after the meal for a cocktail. (Scott & Co is the BEST cocktail bar in this town.)

Keep it up, 47 Scott (and Scott & Co), you guys are doing amazing things!!! I love this little restaurant! The phylo wrapped chicken is superb, grilled cheese appetizer is so good! Always a great meal and relaxing place to go! We're new to Tucson and picked out 47 Scott for dinner based on all the rave reviews. Our dinner experience exceeded our expectations. Drew was our server and we just loved him. He was so helpful and friendly. Everything we ate was fabulous and we will definitely be returning! Thanks Drew and the 47 Scott team! Best old fashioned I've ever had. Phyllo dough  chicken is incredible. Yummy grilled cheese and tomato soup! After looking for a place to eat near the Fox theatre before a show last saturday night, I checked with my trusty Yelp.

I Saw the reviews to 47 Scott and they looked and sounded good. My friend and I stopped in about 90 minutes before the show and were seated in the back patio.

The patio area is a cool little spot on a warm evening but it wasn't too hot as we thought it might be. Just enough of a breeze to feel good. I ordered the mussels and my friend has stuffed peppers. They also brought out bread with some flavored olive oil. The food was great!

Service and food is terrific. Going back soon! Excellent steak frites and nice bartender imagination. Ask for Rizz for best results. I did not have the greatest experience today at 47 Scott. I decided to come here for brunch with my best friend and her friend visiting from back home. We are politely greeted by a hostess who lets us sit at the table of our choosing, so yay for the beginning of our arrival. I ask a question about an item on the menu and the waitress doesn't look me in the eye and says "hold on let me finish this (referring to setting down our drinks)", and her response to my question made me feel dumb for even asking. We all order and wait for about an hour to get our food. ONE HOUR. All we ordered was a grilled cheese, hash, and an omelette. I'm not sure why the service took soooo long. The restaurant was not even crowded!! There was no wait to get in the restaurant or anything. I ask our waitress when our food will come out, again doesn't look at me, and says "it'll be out shortly" (under her breath). My whole party thought she was rude and our food finally arrived.

The food was delicious I have to admit. My grilled cheese was perfectly toasted on sourdough bread, there was a perfect amount of cheese, some even spilling off the sides of the sandwich! I think the best grilled cheese I've ever had was definitely here. As far as my friends dishes, they also enjoyed them and commented on how tasty their food was. All in all I can confidently say THEIR FOOD IS AMAZING, but the service sucked and the server sucked too. PERFECTLY COZY SPOT
I was in Tucson with my two teenaged chitlins for a brief family vacation. We stumble

                         ## Rank: 6: McDonald's | (2.0)
                         **Category: Restaurants, Fast Food, Food, Coffee & Tea, Burgers
                         I absolutely love this McDonalds location.  (22nd/Kolb) Everything about it.  The parking is easy to get in and out of, the lay out of the building and playground are nice, the menu board, the seats, place is ALWAYS CLEAN .... And the people that work here are the best.  Very polite, nice, respectful, friendly, always smiling, knows their regular customers by name.  I wish I could name off all the great employees but I'd run out of space.  Just a nice place to sit and eat.
Only one warning: pay attention to the time.  The near by local high school students fill the place up after school.  ;)

(October 13th 2017 Update)

I really enjoy this McDonalds location.  Very friendly, fast and clean.
I'm usually greeted every Sunday morning by Jeremy.... very polite, respectful and always smiling.
Also wanted to add that the most cheerful employee I've seen is an Africa American male named Anthony.   Always smiling and always looks like he loves his job.

Great work McD's.  See ya next week. Yooooo this mickey d's screwed up our order four times IN ONE TRIP and there was an obvious lack of communication between management and the team when we were told three different things by three different people. Honestly though the chicken is bomb as hell though so 2 stars. Worst McDonald's in town. Sweet tea in the un Sweet tea dispenser. Called to complain the acted like it was my fault. My wife has diabetes and she took a sip . They asked me if I was only concerned with the food or my wife . I was so pissed. Never going back to this location again. Was better when it was next to the carwash. Didn't even get an apology. So sad. So sad. Workers are generally pleasant to deal with and I've never had any trouble when it comes to getting my food. Even better their breakfast menu is all day now! Arizona Burger Tour: McDonalds (visit date 4/26/16)

Judging Criteria:
1. First appearance: Bland, squished and barely any meat showing.
2. Flavor: The patty had an older, steamed flavor. The bun was slightly stale. Best part of the burger was the pickles and condiments.
3. Meat to bun ratio: The patty was undersized for the bun and extremely thin.
4. Included extras (veggies / condiments): Ketchup, mustard, white onions and dill pickles.
5. Price: $0.90

Grade: D = Not good. It might be over cooked or the bun is stale. Little to no flavor (or processed flavor). Only eat if in dire straights.

Follow my Arizona Burger Tour on Instagram @requiemofchaos. Okay look.. McDonald's gets a lot of heat because generally people only post reviews when they are upset at the fast food joint. Yes, their food is not 5 star worthy, nor is their store in general. I gave this mcdonalds a 5 star because in my years of eating at McDonald's I have never been to one with such friendly service. Every time I go my food is always delivered very quickly and there's always a huge smile on the face of the person at the window (WHICH IS HUGE) and you don't see that often with common fast food places! One guy even complimented my car and then said he hopes I have a great day LIKE HE MEANT IT! I usually only stop at this McDonald's because it's on my way to work and it's convenient but every time I go I always get treated very well and that's why this McDonald's gets a 5 star! People, it's fast food, the food is going to be burnt, it's gonna taste a little old sometimes, the soda may be a little flat, but you only paid $5 for your meal. It's fast food what else do you expect? Rate fast food joints on the people not how burnt your burger was! :) 3 stars = average.

We live in this neighborhood so it's easy to stop by for an ice cream on a hot day and let my child play for a few minutes. We were so excited that a new one was being build as the old one down the street was in such deplorable condition. This facility is much, much smaller than the one down the road. Sadly, this new facility doesn't seem to be maintained with pride or maintained at all. I'm really grossed out how filthy the play area is already as this place is still pretty  new.

When they first opened they had a water issue where water was running down the brand new walls in the play area and dining room.

There does always seem to be a few tables (depending on when you come in) of teenagers and possibly homeless eating, hanging out, ect.

They have a little crew cleaning room to the left of the drink station and I can't tell you the number of times I've seen crew in there, hiding and playing on their phone rather than cleaning the dining area. Then the dining room doesn't get cleaned. Truthfully, I think as an employer, McDonald's should mandate a no cell phone use policy while on company time.

I'd say it's about a 1/3 chance if you will get greeted or just stared at when you are at the counter to give your order. Same with if the table and drink station will be clean. Turn over seems pretty high and most of the employees seem less than thrilled to be there. Normally, our order is not correct and

                         ## Rank: 7: Chick-fil-A | (3.5)
                         **Category: Caterers, Chicken Shop, Fast Food, Event Planning & Services, Chicken Wings, Restaurants, American (Traditional)
                         Clucking Good Service

Normally, Chick-Fil-A is fast food--nothing fancy--above average, but fast food.  I've been to CFA's everywhere.  Usually I want CFA on Sunday when they are not open, of course you do.  Nothing better than their peppermint chocolate shake.

Now that I've described CFA, let's talk about the Oracle Road.  The counter staff was excellent, gave their name, asked how they could serve you and all smiled.  It wasn't fake--they were rocking.  This guy Roy is a greeter--perhaps displaced from Wal-Mart--but he was awesome.  Came over, asked us if we needed anything--said yes, forgot buffalo sauce--zing--he was back with the packet.  When we were finishing up and still chatting, Roy came back got our tray and spirited away our trash.  We weren't 2 steps from the table and a cleaning person was their wiping down the top for the next person.

What sets this CFA apart from every other CFA--they really get it.  I'd go back their in a minute.  Roy--what's the soup of the month?  He can tell you by month which is next.

Great experience--best fast food restaurant in Tucson--hands down. Best side of fast food!!! Good meals with calorie count in plain sight!! The service is remarkable ! Te employees are sooo polite and happy. Love to lunch there when I need something quick to eat!! Clean and very kid friendly!!! Again, best employee attitude ever!!! ALWAYS friendly and excellent service. The food is delicious. The location is always super busy, but fast and clean. Extra shot out to 'Katie' who is very professional, nice, and helpful. Lemonade is fresh daily, and amazing. Tea is fresh brewed! Love the nuggets and the mac and cheese. Highly recommend. as a whole i felt the meal did the job by settling my hunger, and in a comfortable manner at that. thegrilled chicken sandwhich was nothing to brag to the grease lovers about but the title fits as simple and  healthy as it was ordered, so im to blame if the sandwich wasnt pushed to its colorful potential(which is easily possible). the fries where great, i personnally could have had more salt, but for the genral salt opposers, the balance is blended smoothly. overall im happy and satisfied with my first visit and meal and would  easily go again and eagerly explore the menu without doubt. Awesome PEACH shake today with my meal! Restaurant was hopping with customers filling about every table, and a line of cars in the drive-through that averaged 6-7 cars!
Service was exemplary, and I have to mention how very attentive and helpful David was. I am disabled and forgot to get my condiments and napkins. He rapidly set down his broom, got what I needed a couple of times, then when I was finished, asked if I needed anything more!
Thank you, David! always great service and everyone is so polite and food is always great!! Love this place just wish they were open on sundays Their chicken sanwhics are the bomb. Best fries. Great service Have never been to a more friendly place in my life. These people seriously drink something before starting their shifts. Wished Phoenix had a Chik Like this. Food always on point as usual. But really had to mention how awesome their service was from the moment i got there to the moment i finished and left. Best chicken in town eat here at least once a week Services excellent people are friendly great chicken nuggets It always scares me how incredibly friendly they are. Its not as busy as other locations but still has a lengthy lines during particular hours. Its very clean and has a nice little play area for kids. The waffle fries and ice cream cones are the best. And the little ketchup packets are what keeps me coming back. When I go to Chick-Fil-A, it is always a conundrum as to what to order because everything there is so delicious! Should I get nuggets or strips? Sandwich? Regular or spicy? Shake? Freshly squeezed lemonade? IceDream? A different dessert? Oh, and the waffle fries!

Never disappoints.

I really like their Chick-Fil-A sauce for dipping. It has a sort of honey mustard taste with a smokiness to the flavor. Yummy. Good for dipping the fries, too. But if you just like ketchup with fries, they serve Heinz Ketchup, the best there is.

How do they cook their chicken to be so tasty and moist? However you get it, it is always cooked to perfection.

Their shakes are great. I've had the peppermint during the holiday season, and the peach during its season, and their regular flavors of chocolate and strawberry. All are very good.

I love their service. They are always helpful and so polite. I love how they say "It's my pleasure."

I highly recommend Chick-Fil-A for a great taste treat with super service. good food. great service. very clean and consistent I have a tough time giving a fast food place 5 stars but I can't think of any reasons not to give it 5 stars. Every time I go to Chick-fil-a I am surprised at he service! The service is amazing. They always walk around and are friendly.

I have been to Chick-fil-a multiple times an

                         ## Rank: 8: The Taco Shop Company | (3.5)
                         **Category: Restaurants, Fast Food, Mexican
                         Good, fast, and inexpensive. I like get the veggie burrito and my husband loves the bacon, egg, and cheese burritos (available all the time, not just for breakfast). The place has no ambiance so we get it to go and we're happy. Got a carne asada burrito.  The avocado used in it had not been fresh, and significantly took away from the other ingredients.  Did not finish the whole thing. I could for sure see myself visit this place after bar. The taco shop is a pretty decent place for late nights. l always get the rolled taquitos and it always satisfies. It's good food especially when you're drunk. Overall can't complain with a 24/7 pretty good tasting taco spot Just driving through the city and happened upon The Taco Shop. Great fish tacos and shrimp burrito at a great price. This tiny spot serves yummy, authentic dishes from the counter. For a while, I was down on the Taco Shop.  I had tried the carnitas and was unimpressed: the pork was lean, flavorless, and on the dry side.  I had tried the carne asada and was similarly unimpressed: the meat was similarly flavorless and a bit on the salty side (I'm not sure, but I think I might have detected a hint of pork somewhere in there, so if you can't eat pigs you might want to ask).  But after hearing some friends rave about the place, I decided to give it another shot.  And actually, I'm really glad I did.

The star of the show here is the Al Pastor burrito.  The marinated pork is tender and full of flavor, the ingredients are presented in perfect proportions, and they even put in some fresh, chopped cilantro that really sets the burrito apart.  They do their al pastor saucy, which I'm not accustomed to, but it works really well here.  I dare say this is the tastiest al pastor in this part of town.  Do yourself a favor and try it!

Also delicious is the green chili burrito.  The pork itself is reasonably good, but what really makes it awesome is that they douse the entire burrito in a heavy helping of green chili sauce, cheese and lettuce -- they call it "wet style"; I call it yummy.  Slightly off-putting, though, was the practice of sticking the burrito in the microwave in its styrofoam container to melt the cheese.  Now, some polystyrenes are supposedly microwave-safe, so it's probably not like they're clearly and systematically jeopardizing their customers' health, but I still took notice.  I've ordered the (less exciting) red chili burrito and they did the same thing, so I guess it's just a wet-style thing.  If microwaving styrofoam makes you uncomfortable, then you should probably stay away from the wet-style offerings.

Aside from these menu items, I've been neither blown away nor disgusted by anything I've tried at the Taco Shop.  But those two things were really delicious.  I would still probably recommend staying away from the carne asada and carnitas, but overall, I've been converted: the Taco Shop is quite alright! Super basic eatery.  Three watery, anemic salsas at the salsa bar, guac very thin, seems like it comes out of a pourable vessel, no chunks resembling avocado, tomato, onion, etc. I had chicken tacos and the meat was little, hard, tough  nuggets of what tasted like meat that had sat all day in a warmer. Several UA students in the place.  It is quite old and decrepit and run down, big hole in the plaster/wall in the booth we sat in. Appears clean, but in need of overhaul.  Friendly clerk.  In a town with so many stellar places to get tacos, I would not return to this one.  It was just "meh".  Maybe if you are in serious need of food after being out all night, but not if you are looking for a really luscious, fresh, quality taco. I've gone here way more times than I care to admit. Let's face it, a cheese quesadilla from here goes perfect any time of day. 2pm or 2am.  Tastes amazing!!!

I used to live on the street right behind this shop and was heart broken when I had to move away. There was nothing better than having my cab driver drop me off here after a Friday night on 4th and then walking home with the ultimate prize: Cheese Quesadilla, Horchata and extra limes. THE place to eat late night. As the business name suggests, this is where you go when you want some drunken tacos. Get the fried fish, they're real good. Carne asada too I recommend.

Burritos are the best value cheaper than Betos or Nicos, and better quality.

My biggest gripe with this place is the wait, on a weekend night it is just ridiculous. Get the steak and egg burrito for breakfast and the shrimp burrito for lunch. We haven't been able to try anything else b/c these two are so good! Don't expect ambience or stellar service, but good food. Delicious burritos. But what really sets this establishment apart from all of the other 24-hour taco stands is its salsa. Its delicious, and you can load up with as much as you please to use for your other meals at home. Truly hits the spot, especially late-night. The Arizona burrito was delicious!!! One of the best burritos I've ever ha

                         ## Rank: 9: Chef's Kitchen | (4.5)
                         **Category: Food, Caterers, Food Trucks, Event Planning & Services
                         We tried this food truck on one of the Sundays it was at Tap & Bottle and while the food was good there were a few misses that made this 'A-OK'.  First off the prices are very reasonable for the amount of food you get.  On this brunch day all the plates were $9, not sure if that is always the case.  They are heavily cajun influenced which I was really looking forward to.  We went with the Gran Marnier french toast and the Bayou Bennie.  The french toast was cooked perfectly but the Marnier cream hardly had any flavor.  The Bennie was a sauteed crab cake on a biscuit with fried eggs and etouffee sauce on top.  Again everything was cooked well but the sauce left much to be desired.  Where it is normally a touch spicy and very flavorful this sauce lacked both of those.  We left full and happy - the beer helped ;) look forward to another Sunday at T&B soon. I tried this food truck for the first time last week. It was a great lunch! My husband and I split the mussels and a monte cristo sandwich. Both surpassed our expectations. The mussels were in a delicious wine and garlic sauce that was so good we finished the meal by drinking the liquid. The monte cristo was gooey and sweet and salty, we really enjoyed it. The only thing it was missing was a little sprinkle of powdered sugar. My husband and I have been making the rounds at the Tucson food trucks for a few months now, Chef's Kitchen and Catering is at the top. Chefs kitchen has the most amazing food!
I've had the pleasure and eating from their food Truck from time to time as well as a catered event that impressed every single person at the event with Their culinary skill and savvy menu. Me and my wife tried the food here for brunch they had a small menu posted on the window and the food was ok. I didn't know what to order but the guy said everything is good so I tried the Coney omelette  it came with a side of potatoes and a English  muffin with a side of butter. The food was warm but the Coney omelette( to give you an idea it was like an egg with a hot dog in the middle with no bun with some chili on top and mustard line) the side of potatoes where good but no dressing when I ask for some, the cook ask me what is the ranch for? He said is it for the potatoes? I said sure why not because I wasn't sure what I was going to do with it. The English muffin was not good mostly because it was just too hard to chew. My wife order three pig omelet which she said it was good but she couldn't taste the bacon and her potatoes looked burnt when you compared them to mine. She also felt the same way about the muffin we both paid nine dollars for each meal. I thought it was pricey for what you get ,I would say I would like to order again if I see them but their menu started at nine dollars a plate so I would really have to think about it. Wow, I was incredibly impressed with this food truck! I went for brunch at Tap & Bottle, and looked forward to trying this food truck for the first time. The chefs in the truck were really personable and kind - the customer service was top notch! We had a slight issue, and they handled it like pros. Aside from that, I enjoyed the lobster omelette with the tastiest biscuit I've ever eaten with a side of sauteed potatoes (with tons of veggies, carrots, bell peppers, onions, broccoli). My guy ordered the grand marnier french toast, and holy crap they were alcoholic (in a good way!). His came with sausage and ham in addition to the potatoes. Each entree was $9, and I have to say, the portions were perfect and the quality for that price is unbeatable.

Every bite was rich and flavorful, and true to the spirit of the food truck movement, their offerings are eclectic and unique, with some funky pairings. They love their hotdogs at this truck, but find all kinds of creative ways to serve them up! I'm going to start stalking them now, I guess! This is by far the best food truck I've ever eaten at. The menu has something or everyone- coney dogs, steamed mussels, salads, and an amazing grilled cheese of the day that has never disappointed me.

The thing that is really important to me and impressive about these chefs is their ability to accommodate food allergies. My son and daughter are allergic to dairy, and a friend of mine can't eat gluten, and they are more then willing to take the time to chat with you, understand your concerns and make a meal that is perfect for you.

The other thing that is really impressive is they are the first food truck in Tucson to go solar! I love that I don't have to yell over a loud generator when ordering, and I appreciate a company that is concerned with the environment.

You would think all of this would be wicked expensive, but it's not. It's gourmet food at a reasonable price. I can't say enough great things about Chef's kitchen and catering! Chef's Kitchen and Catering is as good as it gets!!!  I had the lobster po boy and it was simply AMAZING.  Everything coming off the truck looked and smelled wonderful.  T

                         ## Rank: 10: Sullivan's Eatery and Creamery | (4.0)
                         **Category: American (Traditional), Food, Sandwiches, Restaurants, Ice Cream & Frozen Yogurt, Burgers, Diners
                         My most favorite place ever!!!
Angie and the whole gang are excellent.
The food is the best and the desserts are incredible.
A must try. We came here on a Saturday night after a hike and it was the sweetest end to our date. The whole atmosphere reminds me of similar ice cream/burger place I grew up from back home and the menu while simple is really solid. The burgers are charbroiled, fantastic and flavorful because this place is clearly focused on simple diner style favorites! We can't wait to come back for the service, cute train sets, food and ICE CREAM :) Good Sunday lunch. Our service was friendly and timely excepting bill delivery which was a bit late. Sourdough grill with ham, turkey and Swiss was tasty, crunchy, but not dry. Chocolate shake was top-notch and "large" wasn't just a name but a description. A good spot for ice cream and tasty sandwiches. One of my favorite restaurants! Food is great, ice cream is even better! They tend to stay pretty busy, but it is definitely worth the wait. Waitresses are outstanding and always have a smile on their faces. Great customer service! Best ice cream in all of Tucson. So many different things to choose from, but nothing ever lets me down. The ice cream is fresh and delicious as any other I've ever had! The food isn't bad either for a quick bite at lunch time. Hamburgers made from beef ground daily at Dickman's and cooked perfectly to order.  It doesn't get better than that.  I like that the size of the patty matches the bun.  Little things like that make a difference.  My only complaint was that the bacon strips were a little soggy and limp.  Hopefully, a one-time thing. I liked this place.   I went here with my family and the food was pretty good.   My family loved the ice cream.   It's a nice little family operated spot. Sullivan's is a great place no matter what meal you're there for. With a traditional American cafe style menu, you'll find many different comfort foods that bring you back to spending time around the table with family enjoying your favorite meals. Give their noteworthy burgers a try and you won't be let down. Vegetarian? Sub in a black bean burger to any of their standard burgers! For dessert, you can't pass up the opportunity to enjoy some of their in-house ice cream - wether you enjoy a simple ice cream come or an extravagant over the top shake, you won't regret splurging on these sweet treats. Come to Sullivan's and expect affordable prices for a delectable American dining experience that you can't get at other places in the Tucson area. I have been back to Sullivan's several times since my "negative"experience and my family has  left very happy both times. Ice cream is why I go and each time the waitresses did everything they could to ensure we were happy. I did not realize that Sullivan's was now under new ownership so I wish the best for the family that provided do many fun memories for Tucson families.. if you are after quality ice cream Sullivan's won't disappoint. I look forward to see where the new ownership takes the restaurant! I've been coming here for years when they were still Swensons. I love the owners and the staff they're awesome and quick. It's a great place for shakes, malts, ice cream and that great diner feel. I love the Tuna melt on wheat bread. I'm pregnant and can eat it because they make it with safe tuna!! Yay!! Good thing because it's my number one craving a long with the peppermint stick ice cream right now! Our family loves coming here. This is where my fiance proposed to me so needles to say or has a special place in my heart. The ice cream is amazing and made in house creamery style. This place is old timey and cute, perfect for families. Though, I wouldn't recommend  coming in huge parties. They have a signature flavor called ooey gooey chocolate that my husband turns into a child for. The owners are in everyday and are so sweet. Excellent food and service, the burgers are average but you can't beat the $11 value which includes a massive serving of steak fries and a sundae to boot.  This will be our go to place to just relax and enjoy the food.  It was nice and quiet with a little bit of 50s bop music in the background.  The train that loops gives it a novelty feel that's special.  The owners went to great lengths to make this place homey.  The waitress kept following up with us which was a huge bonus, you can't find service like that anywhere. Nice quirky place. Reminded me of the old ice cream shops back in new England. The service is fast and good. Had  burger special  cannot get a fresher burger. . The cook actually know how to keep the juice in the burger. And glad they support and old fashioned butcher shop like Dickmans. This is one of my fave places to go with my wife. Great atmosphere. The ice cream is so bomb. I try to get something new every time, and tonight we shared the kookie dough kamotion which was awesome! The ice cream is really unique and gives a '50s vibe. Plus, the owner home makes

                         ## Rank: 11: Perche’ No Italian Bistro | (4.0)
                         **Category: Bars, Food, Gluten-Free, Coffee & Tea, Nightlife, Wine Bars, Restaurants, Italian
                         Four of us had dinner here with a reservation before going to the ATC.  We were seated promptly.  Server was friendly and accommodating.  Service was prompt.  Food was excellent. Great atmosphere.  We will return. What a disappointment! Saw a new place in town and all 5 star reviews (lies, or from nut jobs)
Everything was frozen. Started with the calamari and it's served with the Mae Poy chili sauce. Remind you it's an Italian restaurant. Calamari was blatantly frozen and not sure about the Panko crumbs....
Also got the carpaccio. Too many capers which made it salty. Served with several baby tomatoes uncut. Lazy chef who didn't think of dicing them perhaps?
Entrees were a disgrace! The veal tasted like chicken fried steak smothered in a salty and sour cheese that I scrapped off. The polenta was a rectangle and also not fresh. Burnt asparagus along with a vegetable medley that was probably frozen but not cooked well. Is it hard to sauté fresh vegetables with olive oil and some basic seasoning? Apparently at this place, the answer is yes
Brother got the sea bass piccata. Fish was soggy as ever and I asked the waiter if it was fresh. He told the truth and said no. Since we had been gutting a house all day we were starving and ate the proteins at least but overall what a disaster. Our waiter was very nice and the best thing on the menu was the tiramisu. This place ain't going to make it. The entree prices are 25$ or so and if you can't serve simple fresh food what is the malfunction? Will not return New to Downtown Tucson.  Food was excellant.  Had Ling Cod off the Happy Hour menu.  Nice patio with fans and heaters.  Family owned.  Don't miss this one! We started going to PERCHE' NO since it opened. My wife is a fantastic Italian Chef, but even she needs some time away from the kitchen. So I started taking her to Perche' No when it opened just three weeks ago. To our amazement it was fantastic. All of a sudden, my great wife is looking for more time away from the kitchen.  Since the food at Perche' No is so fantastic, I have no problems making my wife happy.  We have only gone back 6 times in three weeks...but who's counting!
Love the place and the people.  The family has only been in the restaurant business for 20 years, so they know what they are doing.
BTW PERCHE' NO means WHY NOT! Classic case of owner/chef who thinks he can cook but doesn't understand that using frozen ingredients for everything results in a disappointing dish. How does this place have five stars? I'm sure he requires all the new hires to leave a review. This place will sadly stay open because of all the 70 year olds who have no taste that enjoy microwaved dinners because it reminds them of their pathetic childhoods. My advice? Burn it down and collect the insurance money. We had a wonderful afternoon at Perche No. We were well received by the staff and owner, Jules. The food was delicious and served hot! Loved it and will definitely go return soon. We were heading to eat something before a concert downtown, 10/15/21, and noticed a new Italian restaurant was open. The inside is similar to the previous restaurant that was in this space. I loved the decor and the atmosphere at night. We changed our plans, on impulse, and went in. It was a good decision.

We were sat at a nice window table and everyone was inviting and friendly. We told them we had just over an hour to eat, they made it work, and the timing was pretty good.

I had a glass of wine and my husband had an Italian soda. We were given bread with olive oil and vinegar but we didn't get a chance to try it.

The menu isn't large but there were many good options. We thought the prices were good, especially after we saw the portion sizes and tasted the food. We decided to start with soup (lobster bisque) and a salad then share an entree. The soup and salad were large and good. Either of these items would have made a nice light meal. The cod entree was delicious. We paid a $2 split plate fee for the cod and it was worth it. Everything was fresh, the correct temperature, and cooked perfectly.

We hear they have a happy hour menu and even a kid's menu. They also have a dessert menu.

We will be back again soon. I am so glad there is a new good option for dinner downtown. My wife and I decided to give this a try since we were going to a show at the Fox.  Of course we compared every experience here to when it was the wonderful Cafe Milano so the bar is set high.

My  first hint that this wasn't going to be a great experience was the bread - cold, tasteless and something that could have come off the shelf at Costco.  We, of course did not come for the bread so onto the main courses.

We ordered the Bruschetta as an appetizer and although I know it is served with the toppings cold, the bread is normally right off the grill and still warm but it all tasted like it had been refrigerated before serving.

I'm trying to eat a little lighter so just ordered the lobster bisque which was quit

                         ## Rank: 12: Locale Neighborhood Italian | (4.0)
                         **Category: Seafood, Food, Pizza, Bakeries, Wine Bars, Nightlife, Bars, Italian, Restaurants
                         Food, ambiance, staff. All the reasons I'd come back and invite friends! The hostess was cheerful and inviting, our waiter Jake was honest helpful with the menu! Fried calamari, Tagliatelle bolognese, half chicken, Caesar salad, chicken sandwich and the truffle fries! Love this place. Amazing wine list, good is incredible. Highly recommend the Sfolgia pasta or the panzanella salad. Everything is super fresh and great ambience. FINALLY A GREAT ITALIAN RESTAURANT IN TUCSON
Puts that dump overpriced Italian spot in the foothills to shame I love this place, but my goodness I wish they took reservations! The only time I've been able to get a table in under 45 minutes was at 4pm on a weekday. Super amazing freshly made pasta, good & affordable wine, and their leek & mushroom flatbread is awesome! It's definitely worth a try if you are patient or want to have an early dinner. I rarely leave reviews, but when I do, it's because a place has truly gone above and beyond. Locale, you are a gem.

From the hostess who managed to be super friendly despite dealing with a very long wait list and plenty of impatient customers, to the server who went out of his way to get us drinks even though we were simply sitting near his section while waiting for our table, to the gentleman who lit a fireplace just because we were waiting nearby, and all the way to our own wonderful server, Megan, the service here was incredible start to finish.

And, as great as the service was, the food is the real star here. Before Locale, I had only had a proper Italian lasagna with béchamel sauce in the U.S. once. To find it five minutes from my home in Tucson was such a treat. Our server said the the lasagna "melts in your mouth" and she was SO RIGHT. My significant other had the casarecce pasta with meatballs and it did not disappoint. We started to discuss how excited we were to return before we had even finished our meal.

Thank you for such a lovely evening. We'll see you again soon! Jazer was so kind to us. He wasnt our server, and to be honest our server had an attitude...but he really made us feel welcome and special. For that reason we will be back. The  restaurant is VERY cute and we will give it another chance because of him. Must visit! Excellent prices, food, service! I had fresh made bread with whipped gorgonzola butter, caesar salad, and a pizza. Everything was delicious, my server, the bartender, was excellent. Will be back! My husband and I were very excited about a new restaurant opening in Tucson. We tried it Fri, Dec 11th and we were not disappointed!! Everyone was friendly and courteous. Tables were separated to adhere to COVID-19 restrictions. The entrees were delicious. The bread was AMAZING!! Next time I want to try the desserts...they looked great. We'll definitely be back. Gorgeous Patio seating, really tasty food, and solid cocktails. This was a perfect date night spot and we have already recommended it to friends. Will be back soon. Probably one of the best restaurants in Tucson. The service was incredible! We haJake and Jake as our servers and they were both so attentive and made great conversation!! The food!!!!! The polenta is a must get!! Excellent food and service!  Ricky was attentive and personable.    Will be back soon, just for the creamy polenta, and to try more good stuff! WOW! The food here is delicious! We went for the Thursday Pizza and Salad deal - one large rectangular slice of unique pizza and a large salad for only $10. I had the Country Bacon pizza with dates. Yummy! My husband had the Pepperoni pizza. I was surprised how it had so much packed in - definitely not your basic pizza. Our server Janelle was very attentive.

I have two suggestions for Locale. First, have the hostesses point out the white chairs where you can wait for your table. They are comfortable and situated throughout the outside gardens. Second (and this is BIG) have someone roaming these areas to take drink orders! Apparently the wait staff serves food tables and might not have "time" to ask if you want a drink. I asked if we could go inside to order a drink, but the hostess said, "Oh no! That's for our wait staff!" So I didn't get any wine until we were seated half an hour later. This is a no-brainer! Make $$$ selling drinks to waiting customers! While in Tucson visiting a bed and breakfast we decided to check this place out based on it's reviews and let me tell you, it did not disappoint! It has a great outdoor area with a large grassy area with adirondack chairs and a bocce court! It is very large and immaculately clean and offers a very welcoming atmosphere.   The bar is fantastic and they have specialty drinks that cater to the atmosphere and my wife found hers very tasty, I stuck with a local beer.  The menu was amazing and needed time to be all taken in, which was fine because their bread is unforgettable and for this non carb eating guy can easily state this was the best he has ever had and my wife, a carb lover .... fully a

                         ## Rank: 13: Tucson Food Tours | (5.0)
                         **Category: Hotels & Travel, Historical Tours, Food Tours, Tours, Walking Tours
                         By far a must do in Tucson whether you're a local or a visitor! Learn some facts about Tucson & sample some delicious food! More than enough food provided even though just samplings. You won't go home hungry! This is a great tour for tourists and locals alike.  We stopped at 7 restaurants and each was a unique experience.  Brad was a wonderful guide, very informative about the food, the architecture and the history of the restaurants and downtown.  Everything was easy, from making reservations, making payment, getting info about where to park and meet.  There were 14 people on our tour, slightly larger than ideal, but everything worked well.  All the restaurants were great, very accommodating and with generous portions.  You have to pace yourself foodwise! Having done the Downtown Tucson Walking Tour, expectations were high for Maingate Square/4th Avenue. Actually, expectations were exceeded! Service at each of 6 venues was efficient and friendly, food and drink delicious. And plentiful! Local history shared between stops provided additional flavor. My only regret was savoring an extra serving of the burger at Lindy's...risking I would be full before tour's end; I was. For sure, Tucson Food Tours provides value for price! Tucsonans will enjoy these tours as much as those from out-of-town. We took the downtown tour with Chris. I would highly recommend this whether you live in Tucson or from out of town. Chris was super friendly and very knowledgeable about the area not just the restaurants we visited. Good food and fascinating history. It is a walking tour so I'm not gonna lie when I say on a hot day it might be hard to concentrate on the what is being said when you're outside.... but you will leave full and with fun memories. Haha. The tour was amazing!  Great food and learned a ton about Tucson.  It was a wonderful way to introduce our visitors to the city and the great eats in town.  Brad is an engaging and knowledgable host.  Would do it again in a heartbeat! I absolutely loved this tour! The tour guides are very knowledgeable and entertaining. I learned lots of great history and sampled food from seven different restaurants downtown! It was a perfect way to spend my afternoon and I would do it again in a heartbeat. I'm new to Tucson and would've never found some of these restaurants on my own but now l'll definitely be returning! If you're new to the area or just looking for some new places to try, I highly recommend going on the Tucson food tour! I recently was in Tucson visiting a friend!! I discovered the Tucson Walking
Food Tour on Trip Advisor and booked the tour!! The tour and food were FANTASTIC !! If you are in Tucson you  should not miss this Tour!! It is EXCEPTIONAL !!! Be sure to wear pregnancy pants for this tour, lol! The food is fabulous and flowing!  Great informative guide who is historian on DILANGER:) Just finished up our tour.  We had an amazing time. As of out towners, it was great to be shown the hidden gem eateries (we are here for the gem shows so no pun intended) of Tucson. We were with a couple Tucson residents who also found it a refreshing change from their regular haunts. Our guide was knowledgable and entertaining to boot. Great experience overall. This is the best food tour I've ever been on.  I was impressed!  Brad really knows his food!  All food stops were amazing!  8 places total, 4 hours long...I felt like I got MORE than my monies worth.  In between restaurant stops he would share knowledgable bits of the city.  The perfect combo of food and history, every tour should be like this!  I would highly recommend this tour to both visitors and locals.  You will not be disappointed!!!! My best friend was in town from Charleston, SC and we decided to do a day trip to Tucson (neither of us had ever been).  I love to eat, so I started digging around for unique lunch spots.  Then I came across Tucson Food Tours' website.  I bought tix right then - best decision ever !  We had the best day, thanks to Brad, our tour guide.  He gave us a history lesson as we all walked/talked, and took us to the most wonderful places to eat.  Each place was an experience, with phenomenal food, ice cream, service, and I even tried a couple local brews (ah-mazing !).  I would recommend this tour to anyone, even if you aren't a true foodie, you will absolutely enjoy every minute.  I will definitely be back ! If you enjoy yummy food and drink, a friendly and very knowledgeable tour guide (Brad), beautiful architecture and decor, interesting information about downtown Tucson that is covered on this walk and more as well as having fun, then this is a tour you won't want to miss. I loved everything about it and want to return to all of the restaurants we visited. Many thanks to Brad and Maria for this great tour and all that you're doing to share the lovely city of Tucson. Get ready for taking a walking tour to explore the hidden food treasures that downtown Tucson has to offer.

My husband and I visite

                         ## Rank: 14: Sky Bar | (3.5)
                         **Category: Nightlife, Bars, Cocktail Bars, Lounges, Arts & Entertainment, Music Venues, Juice Bars & Smoothies, Food
                         any establishment I can take my dog is four stars. a glass of wine and people watching in front? no complaints. If you want to get out on a weeknight, go here.

The drink specials are always cycing, & their always good; staff is friendly, & the place is always clean.

They need to put some restrictions on open mic night hahaa but otherwise, this place is cool.

They have a late night window to the pizza place next door, so there is usually good-eats available (on select nights)

I've yet to try it in the daytime, but I believe it is a juice bar; if it's half as good as the late night setting is, it's definitely worth checking out sometime.

One of the better places on 4th for sure I've never had a bad time at Sky Bar, so I'm surprised to see the low ratings. This is such an awesome turnaround from North on Fourth. They've got:

- pool tables
- chill crowds
- a bad-ass telescope
- great artwork
- large, open space
- great beer selection

What more do you want Tucson? The DJs always play music decent enough for me to stay interested. After living in Tucson for 7 years and hitting up all types of establishments in the city, I definitely put this place as one of my favorites, and vacillate between giving this place a 4 or a 5. Astronomy Nights are relaxing, great way to have a good time without the creeps from other bars. Try the Strawberry Lemonade Sangria. Don't underestimate how cute they look tho. You know, I'm probably not too smart to be coming here for over a year on Monday nights for team trivia, spending plenty of money for food (Brooklyn Pizza - same owner) and drink, and bringing 20 people each week, but dang it is HOT in here!  Interestingly, Sky Bar has AC, but it is never used.  Not impressed... get with it, Sky Bar! Sky Bar has taken off like a rocket going to Mars, In its 22nd month on Mission Awesome the stakes are raised again.

With Continued great beer selection and excellent bartenders your sure to get out of this world. Get the Bloody Mary Spicy, but watch out who serves you, there's a special Cheetah there that makes them to die for (all Halloween references).....

The Patio Lights up, literally!!, On Friday nights as Local fire artists spin for your viewing pleasure. Light up yourself as the patio is a tobacco friendly zone. I was here at 10:30 am on a weekday. Sky Bar makes a good study spot! Most of the customers there were studying, except for two people who were speaking to the barista. Given the layout of the place and the background music playing, it was easy to tune them out.

I had looked at the online menu and knew that coffee was pretty cheap here. I ordered an iced latte, and I was very impressed by the size of it. I would guess it was 18 oz., and it only cost $1.50. The coffee wasn't spectacular, but I would say it's good.

Once you're done with coffee or schoolwork, you can go right next door for pizza! If you're waiting for Brooklyn Pizza to open for the day, Sky Bar makes for a good place to kill time.

Haven't been here to see any live music, but I think I'll try that next. We had a blast yesterday on the patio with our dogs.  Extremely friendly staff and our mixologist had a great memory. You can get a coffee or a drink and bring your dogs.

 The live music on the night that I went was a piercing cat howl that offended something deep within my soul...and the telescope isn't worth the drive. A bar where you can have your pizza and eat it too! Brooklyn pizza(Next door) will deliver slices or whole pizzas to you while you enjoy the nightlife.
Great bar, They have pool tables set up toward the back and live bands play here on the Reg.
I will have to agree with some other posts that if you are ordering a beer you are good to go. However, if you order a mixed drink it is going to be hit or miss with the bartenders.
They also have a decent happy hour. When you want to grab a group of friends, drink some beer and have Brooklyn Pizza deliver a pie right to you, go to Sky Bar.

The drinks are pretty good, but I usually order beer here. They have pool tables in the back, and often play good music. Karaoke takes place on Tuesday nights here staring at 10pm. You will see some of the regulars come out with their favorite tunes, always entertaining.

If you enjoy a pungent whiskey and ginger then this is your spot. They make it with ginger beer here which isn't for everyone, however it is someone I definitely enjoy.

The outdoor area also has a telescope so you can view the stars late at night, and when something major is goin' on in the sky, you can count on someone to help you find what you're looking for out there. I came here with three friends for happy hour on the night they do their weekly trivia. Therefore despite the heat it was pretty full (for Tucson in the summer) . The bar is indoor-outdoor with big open areas so it was pretty brutal, even inside, because of the 110 degree weather . They have fans but it didn't do much to cool you down .

I had the spirit of 76' f

                         ## Rank: 15: Noble Hops Gastropub | (3.5)
                         **Category: Bars, Restaurants, Gastropubs, Food, Specialty Food, Nightlife, Beer, Wine & Spirits, American (New)
                         We were here on happy hour Friday night it was busy almost packed. Service was pretty good very attentive. Lots of presumptuous people though! How funny to me. Beer was excellent, had "barvarian' pretzel and it wasn't bad but the cheese dip bland but plenty ediable. It was fun when your socializing w friends on their patio. Patio weather.  The beers are great!  Food can use a little work.  But overall and high 4 stars here.  Good place for hanging out with friends.  Oro Valley really needed this place!! I am very impressed with this place. Sylvia was a kick-ass server. The ahi burger is great, the zucchini stix come with a wasabi creme that's amazing and the beer selection in unmatched. They even have my fave beer, Dixie Blackened Voodoo. (hard to find anywhere). I'll be back. It's a great place to start a date night, party night or beer-drunk few hours. (Take a cab morons). I give it a 4.9/5. The only reason it missed the 5 mark was due to z fly problem. I f'ing hate flies and they were everywhere. Otherwise, north-side tops locale. Do it. Do it.. So sad....  last visit to NH and the drunken flatbread pizza is GONE!!!!  Whoever thought that was a great idea was WRONG.  Oh and ROB is the best waiter in the place!!!!  Ask for him! We stopped with our dog for beer and pretzels on the patio, both were great and the Mountain View's are stellar! I will definitely be back! Not a fan. Although the place wasn't busy at all, our waiter couldn't get our order for beer flights right even with three tries. The place was hot, the food mediocre, and we were bothered by flies. They have good beer selections, you can find several Arizona brews. My friend was especially impressed with the Choco with hint of pepper beer.

Their happy hour menu was okay, $2 off selected "small plates."

I tried the grilled calamari, was not very impressed by the lack of flavor and also feels with all the excessive oil on the "grilled" calamari, I might had better flavor/ luck on a fried one.

My friend shared her Bacon Jam Burger, I like the smokiness of the burger, but too impressed other than that.

The decor is trendy and the place is a comfortable for a small outting/ gathering. Will probably go again but not for the food. My boyfriend and I come in here a couple times out of the month and it's always the same experience. The servers are always on top of it and the live music nights are great. Also I love that they change the menu up in the summer time! I would recommend this restaurant to anyone and even took my mother in law:) Very, very disappointed. There were 9 of us for dinner and no one really enjoyed their entree choices. My husband's Turkey Gobbler was small, dry and $14.00. His 10 oz. beer was $6, but good. My vegan green curry was small, tasteless green broth. The rice was practically nonexistant, the grilled veggies were a few zucchini and squash pieces. There were 3 peanut halves. The biggest ingredient was the pile of greens on top, most likely to hide the actual dish. $15. My beer? $9. Didn't realize until after.  Outrageous. My friend had a $10 salad that was small and tasteless.
The other entrees were of similar condition and prices.
What was good? My $6 cup of heirloom tomatoe gazpacho was incredible. The pretzel bread was good but for $10, you'd think they would have been bigger. The fries were good but small.
It's sad because the outdoor patio area is inviting and festive. Looks like you would want to go more often, but not with this quality of food and those prices. Really enjoyed this place! Ordered the fish 'n chips, which is not on the Manu, as well as a chef's board with all of my favorites - salami, cheese, fruit, nuts and some strawberry spread for the crostini. The service was excellent. Oh! We asked for tartar sauce, and since they didn't have any already prepared, the chef made a custom tartar sauce for us that was delish. Again, exceptional service. Looks like everyone is enjoying themselves here. Besides a wide selection of beers, they have ample portions of very good food.  Also excellent service. We have gone to Noble Hops 4 times, the patio is great and fun.  We went today and had to sit inside and not such a great experience. The flatbreads were awful and our server sorta was pissed off that we just order small plates.  I have loved it before so I will try it again.  The brother's other restaurant in Dove Mountain is WONDERFUL, great staff, bartenders and food is great!   Hopefully Noble Hops follows Vero Amore ! This place was a great place to meet up with friends. There were a lot o young professionals and other people out on dates together. The beer variety was excellent and the food was amazing. I got the beef and lamb burger which was really interestingly prepared.
The staff was friendly too and I would definitely come back. This is the best place out in oro valley by far and I hope it stays around for a while! Not a fan of the new happy hour menu. Food is mediocre at best. Service is inconsis

                         ## Rank: 16: El Charro Cafe | (3.5)
                         **Category: Tapas/Small Plates, Desserts, Cocktail Bars, Nightlife, Bars, Tacos, Mexican, Food, Restaurants, Salad
                         This a good place for a date food is outstanding been drinking for about 4hrs and I'm not buzzed the drinks should be alil or could be alil more stronger I've ordered deferent drinks n still no buzz. I'd ask for double shot if anyone come here for mix drinks but I'd come again My group had a reservation for 20 people on 7pm on Sunday night. They were not prepared for us in advance and it took them a long time to get our table ready. They didn't seem to have enough staff to take care of all their patrons that day. It took them too long to get us chips, water, and menus. I appreciated that the menu had its gluten-free items labeled as such, but one of my friends had trouble determining what was vegan. We went through 3 bowls of chips while we were waiting for our food and it was flavorful but somewhat cold by the time it got to the table. Our servers were inattentive in general which was frustrating. Native to Tucson and therefore I feel like I should love, love, love El Charro. Given all the hype behind the place, I feel like I should love it even more.
But I don't.
Have been a handful of times and every time I feel like I am being done a favor by being allowed to eat there. Not the friendliest, quickest staff nor have they been the most helpful (menu offers bean choices and sauce choices but our server didn't even acknowledge them).
Yeah sure, the margaritas are tasty and the carne seca is good, but not worth the hype.  The G burrito (roasted veggies, avocado and pieces of green corn tamale) was good but again, not great. The downtown location is very cool and I'm glad they are doing well and giving Tucson some attention. I do love supporting local business so I will continue to go whenever an out-of-towners absolutely has to "try it out".  But there are better tasting, more welcoming places that you could spend $88 (party of 3) at. Oh my gosh, what a great place!  Food was excellent!  Place was crowded with over an hour wait but it was worth the wait.  Steven was an excellent server, we appreciated it! Love the old fashioned tacos! The historic El Charro Cafe located in downtown Tucson. The chimichanga is said to have been invented right in their kitchen, even though there are few other claims from other restaurants that their founders created the dish. I don't know why I'm telling you all this because I personally eat chimichangas.

Anywho, El Charro is a gem with good service and great food. The dining area is very unique as it is in a really old (for Tucson) building. The bar and patio seating or literally separated in the building complex. Chips are fresh, tortillas are tasty, and the beans are cooked with care. As far as prices are concerned, the happy hour and lunch specials makes this a place to eat decently at a competitive price. Some of their main dishes are more than $10, but at the right time, you can get a an entree for less. Mmmmm.  My favorite Mexican food, and a place I always have to visit when I'm in Tucson.  The carne seca is divine.  This place has a huge selection of tequilas, too, and I haven't found anything bad on the menu.  Last time I was there, my friends and I even got our own table in a semi-private room! We were there for The International Festivals and Events Association, and this restaurant was in the recommended list... Very good and did angriest job accommodating large groups! I had the signature "Carne Seca Platter" and it was awesome! Hopefully this review will encourage the owners to change some of their business practices.  Since no management responses are ever seen, this is unlikely.  Tucson has  many good Mexican restaurants to choose from but unfortunately tourists have read the 'press' about this location and flock there, particularly during the Gem Show.  We were caught up with visitors pressing to go there recently.  Bottom line:  mediocore at best.  Salsa given out in tea spoon portions.  'Wet' sauces sparingly applied at unreasonable prices.  Enough said. The food here is very delicious it is a cool place our waitress Regina was awesome, should get 5 stars but does have a couple downfalls there is no place to park so we went in to ask were to park and the manger told us rudely "park on the street" after parking the car the same guy met us at the door and was they set us in a little table close to the kitchen door he kept yelling at the staff to get to work, we could hear the manager yelling at the staff to shut up, quit talking and get to work
One of the staff told us he was toe owners son Totally yummy Mexican food! The ambience is great too. The food came out so fast and my burrito was delicious. Would I want to wait an hour and a half again for the food? Probably not. Good solid food and great history. Haven't been for awhile so when our boss said she would buy lunch we all agreed it sounded good.  I wanted a cheese crisp but the burrito won out.
I always said the food was hit or miss here, but usually a hit.  Today was a miss. My burro, even elegante s

                         ## Rank: 17: Jack in the Box | (4.5)
                         **Category: Tacos, American (Traditional), Fast Food, Mexican, Breakfast & Brunch, Restaurants, Burgers, Food
                         Everything here was sticky and dirty.

The only thing worth ordering is the tacos. Get me to go. In the drive thru. The meat lover burrito is expensive and small. However I like it so yeah. There's the 3 stars. 2 stars off for the above two reasons Nicest staff, clean, fast service, best Jack in the Box around. Servers actually smile and seem to care that the food is good. Food is served hot, and orders are correct. Will always come to this one. My boyfriend and i usually come here during the over night shift and we always experience awsome customer service and the food is always hot and our order has never been wrong. Tonight the women in the drive thru name was Nina and she has amazing customer service every time! She is always polite and accurate! We came a few times during the day shift and had a bad experience every time. So we will be sticking to the over nights! I went in for a sirloin burger and a salad. They did not have any sirloin burgers, so I got a fiery chicken sandwich,  which didn't have the grilled onions.  My salad didn't come with the croutons and dressing package.  The chicken on the salad was very small,  and cold.  The fries we cold as well. I only live a block away, so there is no reason the food should have been cold when I got home.

When I tried to comment online the comment page failed after a few pages. I then tried to call in the comments to the number listed on the receipt, it would not let me leave a comment because I had started the online comment.  The message system gave another number for customer support,  and when I called that number it just rang busy for half an hour. They clearly don't care about customer feedback.

I used to be a Jack in the Box promotions person,  and was Jack at store grand openings. Stores like this bring down the whole chain. This Jack-in-the-Box is amazing. Went to Starbucks next-door and they didn't give me a Pupiccino and was mean to my dog, so my dog was sad and I went to Jack-in-the-Box and I asked for whip cream and they gave my dog a really big bowl of whip cream. Very friendly workers. Fast service. Awesome attitude! What a diffrence from the campbell location this place is by far the best ive been to between the two i went through the drive thru on july 05 to get a breakfast sandwich.  i was  cashed out by noel s and he also brought my sandwich to me in the parking lot when it was ready.  i want jack in the box to know what a kind and professional employee he was. he was courteous, polite and attentive as he interacted with me.  i only hope you are aware of what you have with him as an employee and treat him as such. This is the place to go every time you have a craving for burgers, tacos, and breakfast food! It's delicious and they have good and fast customer service! My two favorite places are the Jack In The Box at the corner of Oracle Rd and River Rd, also the one on First Ave and Wetmore! They are open 24 hours, and I love their food! Give it a try, you won't be disappointed! Honestly this is probably the best jack in the box I have been to. The employees were all friendly and super nice and very customer service like. I think my cashiers name was Amanda, I didn't catch the cooks name but he was so nice as well. Food was super fresh and good! Hello, I'm the Critic Guru! I've been there and I've done that. Today I would like to review my recent visit through this Jack in the Box Restaurant's Drive Thru. [Critic's Blog #181: June 28th of 2014 at approximately 1:38 P.M.] it was a rather warm... (no, no, no) .. it was a living oven outside as I inched towards the intercom, Finally as I arrived I was greeted rather quickly by a professional & friendly lady named Diane.  She suggested I tried a Jalapeño Ultimate Cheeseburger but unfortunately I declined the offer because I saw my one true love on the menu.... The Ultimate Bacon Cheeseburger! !  (With a side of Tacos!!) As I ordered the combo I was offered the option of Curly or Regular fries (which I have to admit I was a bit surprised because the "other" guys want to have it their way, but at Jack in the Box I can truly have it my way.) After I finished my order she confirmed my order and I was all set. As I pulled around the corner I was yet again greeted by Diane at the window, she quickly processed & finished my order and within minutes I was out of the Drive Thru with my order correctly made. This Jack in the Box location is, if not THE BEST company restaurant I have visited. I will definitely return soon and this time I might just spice it up a bit with their "new" Jalapeño Ultimate Cheeseburger! I've been coming to this Jack in the box for years. Usually go through the drive through but today I got out because my kid was hungry and we had to kill time I always get either a chicken sandwich or the two tacos off the cheap menus. Never expected anybody to be over the top for me.

Today I came in and was greeted by Rojelio with genuine kindness and I noticed him being the same way

                         ## Rank: 18: Rancheros Market | (4.5)
                         **Category: Specialty Food, Herbs & Spices, Food, Restaurants, Meat Shops, Mexican
                         Wow...Great spot for lunch and meats.  Stopped in for the first time today after hearing several good reviews and wasn't disappointed.  Had a couple of Carne Asada tacos for lunch...best I've ever had.  The meat counter selection was complete, so picked up some skirt steak for dinner.  Also, picked up some tamales to have later.  A friend recommended them. I'm regularly in Catalina visiting family and I can tell you this place is great. Super clean with a fantastic meat counter and delicious food in the back. The hot sauce selection alone is enough of a reason to go! If I lived in Catalina, I'd pretty much do my weekly shopping here. Nice people, too. Check it out. It's a breath of fresh air in the area. This is a fantastic mexican meat shop with a good selection of canned and fresh goods in addition to the meat and cheese. They also have a prepared food counter with many mexican specialties. The people are extremely friendly and want to make sure you get what you want. Great place all around. Rancheros is the place to go for great burritos,  Mexican food including groceries, meats, fish and sweets.  Very clean and well run with friendly staff.  Meat counter is well stocked with pre and non seasoned meat and seafood.  Well worth visiting ! We love coming here to pick up meat to grill on the weekends. Their ranchero, marinated chicken, shrimp, and ceviche are great quality. They carry all the fixings you need to make street tacos, fajitas, and more. The tortillas Bryan are the best! Rancheros is a great place for meat, Bryan tortillas, Mexican limes, tamales and masa preparada para tamales.  The staff are very helpful.  They often have the grill going so one can purchase the meat and veg and have it grilled to perfection.
Though not connected (I think) the Sonoran Hot Dog cart beside the grill is outstanding as well. Salsa and other items are  a week past the experation date. Tortillas had mold on it. When mentioned it to the employes, they dont care. Best Burrito in Oro Valley!!!  Place is super clean and friendly.

Quality produce and great prices. Definitely check it out if you're in Oro Valley. Best carne asada from to go side around for sure!!! but rest is just ok. Over priced food n produce otherwise Man finding this place while I was out visiting in laws made my trip that much more awesome because I ate tacos here and brought home tons of stuff from the market to cook throughout the week.

The homemade guacamole salsa and crema is a must and the molcajete salsa was very good.

For the meats we got the carne asada and 3 types of marinaded chicken thighs which all grilled up perfectly.

They also have fresh tortillas , home made chips and a ton of hot sauce.

Man I wish I lived close to this place, Ill be going here every single time im in town. They have the best ceviche!  Great cuts of meat, customer service and the food that is ready to go is all delicious! Drive 30 minutes here to get my fajita chicken and other stuff. Ceviche is awesome also and good is great Simple home-cooking, nothing fancy for sure. But clean as a whistle, friendly, and the best Mexican food i've had in Tucson.  Just a great little place, and wonderful market, too-- any kind of meats and Mexican groceries you could want.  Went for a little dinner and came home feeling as if we'd been on a mini-vacation. Love this place... The tacos are good, although I never seen an expiration date on most of their products (which is a health code violation) and I've seen mold on some things there that they packaged... We love this place. The staff is always helpful and friendly and it's always spotless. Try the deli in back, the food is amazing. I didn't eat there. I did, however, find the place to be clean and neatly organized and everyone was moderately helpful. It has a wide variety of Latin groceries available. It's clean, bright, full of food, totally worth hitting up if you're in the area. Great food and market! We loved how friendly everyone is! The tacos were delicious and flavorful! The taco Hass was cooked perfectly. Nice variety of foods, hot sauces and large meat counter/market.  Put it on your list as a must stop in and try the food! This is 5 star carniceria. The meat is high quality choice and angus. I wish it had more Angus but local economics and such. It is butchered and trimmed much better than at the local large grocery stores and they have better cuts like outside skirt, short rib, many cuts of chicken and varieties of fish. A lot of authentic products imported from Mexico, especially the hot sauce collection. The fresh food and salsas are always great and never too old. Real chicharrons. What a neat little wrote. Finally some quality Hispanic groceries and meats without having to drive to South Tucson Best Mexican food in Catalina area Very friendly staff
Nice and clean Very well presented meat case
If you want genuine this is the place

                         ## Rank: 19: Cracker Barrel Old Country Store | (3.5)
                         **Category: American (Traditional), Caterers, Breakfast & Brunch, Restaurants, Southern, Event Planning & Services, Comfort Food
                         I went here for a brunch meal with mom & it was very good. Went back last night Tues, for St. Patrick's Day and had the special Cornbeef & Cabbage, with roasted potatoes & carrots with jus and it was delish. The entire meal was gluten & dairy free so it MADE ME VERY HAPPY. The biscuits that it came with, I had the waitress give to my mom, She had some for desert last night & breakfast today. She had the same meal as me & really like it. Always good food breakfast or lunch. Wait staff always in a good mood. Here for Mothers Day brunch with kids and grandkids. It's been many years that we've been here. We came for breakfast around 9:30am on a weekday. The hostess sat us down right away  and accidentally gave us lunch menus which they start serving at 11:00am.
We both ordered Grandpa's Country Fried Breakfast which is chicken fried steak topped with white gravy, 2 eggs, grits, biscuits and a side of white gravy.
I had coffee and I must say it was the worst coffee I've ever had at a restaurant, it was very week in coffee flavor. Luckily for us we had such a wonderful waitress Trista, who promptly took the coffee away and also mentioned I wasn't the only one to complain about their coffee. The meal on the other hand was fantastic, it brought back memories from many years ago and I wondered why we hadn't been here for so many years. All I know is that on this day we had a delicious breakfast and a super sweet waitress who we will request by name on our next visit. Another great experience at a cracker barrel, if you've been to one you've been to them all. Jami was very attentive and made sure my drink was never empty. This restaurant is not familiar with Gluten-Free despite the fact that they have an allergen listing.

I am a celiac and am extremely sensitive to gluten.  My family really wanted to go to this restaurant so I had no choice but to go here (I could not eat I guess but that sucks).  I thought I was going to be OK because we looked up Cracker Barrel on Yelp and on the Internet and found that other people had commented on positive responses with gluten free eating here.

I called ahead and spoke with one of their managers who was very honest with me. He explained that they were not very familiar but they did have a list of things I could eat and that he would do his best to make sure the food was handled however I indicated. (ie: not the same spatula, not the same gloves, etc.)

We went there and the manager was very nice about my needs. Sometimes people at restaurants seem to be annoyed with my allergy...

I do have to say it's VERY IMPORTANT that if you're gluten-free because of Medical Necessity and not just a dietary choice, be very careful!

I ordered specifically off of the gluten-free menu (they handed me a little paper that said "items that can be recommended to people with wheat/gluten allergies). I also was very specific to the server to let him know that I have a medical necessity not to have gluten. I explained the whole thing to him just as I did the manager - including the cross contamination issues.  When my salad came out, THERE WERE BREAD CRUMBS ON MY SALAD. (It was obvious that they accidentally put croutons on my salad then picked them off - which will make me VERY sick for about 3 days) This is why I said to be very careful. Luckily I looked very carefully at my lettuce and tomato and saw bread crumbs. (Feels like I dodged a bullet.)

Now, they still get three stars because I did tell the manager right away that there were bread crumbs on my salad and he immediately took my salad then personally plated all of my other food in the kitchen.  I did not get sick - thankfully because I caught the mistake....

I just wanted to be clear that everyone else at my table without food allergies LOVED their food. This place has been a popular choice among my family for years now.

I wish they would work out a better system and do more training with their management, servers and kitchen staff to better accommodate all food allergies before they put it out there that they have the ability to do so. Their kitchen was clearly not set up or trained well enough to handle my food allergy.

I am thankful to the manager who still made me feel comfortable despite my complaints. (I was very nice!) I ordered chocolate milk expecting to have a home-style drink, but no . I got two cartons of repulsive TruMoo. Not only was the chocolate milk worse than expected but they had the audacity to make me pour it in a mug. Lucky for them their food was good. Just had breakfast here. We're getting our Starbucks and this was recommended to us by one of the barristers. I had been to the Cracker Barrel before. They're all over the Midwest. Great food. Great staff.reasonably priced. Love the biscuit and pancakes. My family and I decided on an early dinner to Cracker Barrel since we were in Marana. We have been here before and it was always very good. But tonight, the good was very small portions and it was very bla

Label Query: Sweet treatsWhere can I get a sandwich?

                         ## Rank: 1: Chick-fil-A | (3.0)
                         **Category: Event Planning & Services, Caterers, Fast Food, Restaurants, Chicken Shop
                         This is the worst Chik-fil-A I have ever been to. On multiple occasions I have waited over 25 minutes to get my food. Their response is "Sorry, we got backed up." It seems they are backed up on every occasion. They even have the sandwiches pre-made waiting to go in the bags but somehow, among all 10 employees behind the counter, they are so backed up that a five minute wait turns to a 25 plus minute wait. Avoid at all cost. Much better options at the Union! I enjoy Chick-fil-a's spicy chicken sandwich and waffle fries. The quality of the food at this location is no different relative to other stores in the chain although it may have a smaller menu. During lunch hours the long can get very long and it feels like they rush you away at the counter without much time to even put your money or credit card away. On the bright side because they are so busy the wait isn't too long after you order. Its better to get this to go and eat in your car unless you have a table already since seating can be hard to come by. The lines are usually longer right when class gets out and around noon, but if you don't mind waiting this is a great place to eat. The food comes out pretty fast and I've never had any problems at this location. The Chick-fil-A at the student union works really quickly and then make sure to get your food out to you on time. The food is always really hot and I've never had a problem here! I always come here in between classes and I love it. Succinctly put: it's convenient because it's on campus, you don't have to pay tax, and the service is relatively nice and fast. Overall: average.

This chain is definitely subpar compared to the rest, but you can't beat their prime location. The only thing I hate is after the order, there is always this array of customers who are all waiting for their food at the end and you have to weave through the people who stand there awkwardly with their arms crossed (no matter how much I hate them, I always seem to be a part). Among other first world problems, their fries are also ALWAYS pre-made and soggy. But even then, still nothing too major, just that this is your average fast food chain at the uni campus that will fulfill your test anxiety when you don't have enough time to eat healthy and are looking for something to fill your tummy before the next round of exams. Definitely recommend the chicken strips and nuggets over the soggy sandwiches. Overpriced, overhyped, extremely long  wait times during season, food is mediocre at best. You can get better food for less money. I suggest you go somewhere else. Located inside the student union of University of Arizona. The store is smaller as it is located inside the union. The service is fast and the food is good, however, the place does get crowded around lunchtime during the semester. You might have to wait for more than 20 minutes to order. I noticed that you could use an app or Door dash to just pick up the food without the wait. This Chick-Fil-A is located within the University of Arizona's Student Union. It's a small, express variation but it is very fast and they produce an identical product as any of their other  stand - alone locations.  My only complaint for them is that they are VERY limited in their food offerings as a result of them being so small thus limited in space.  Other than that, this is a good food alternative spot when I'm killing time on campus and don't just want a pizza slice or Burger King.

In a nutshell, SOOOO glad they're here! The food is so great! It's always piping hot and they have a really really good sweet tea. My favorite sauce is the Chick-fil-A sauce or zesty buffalo! Definitely come here and get the spicy chicken sandwich! i'm very saddened by this chick fil a location. first off, i have walked here multiple times to go home with the the wrong order. today i ordered a large fry and there's 3 french fries in it, that are not even cooked correctly! then, i order a coca cola to find out they put tea in it!!! get it together chick fil a and pay attention. I ordered breakfast from them a couple of days ago. Wanting to switch things up I got a Sausage, Egg, and Cheese Biscuit but with an add on of bacon. I received my order in a timely manner, but after checking my bag I realized they had given me the wrong sandwich. I was shocked when I went back up to the pick up counter and a young lady working there met my complaint with sarcasm and attitude. Also whoever was working on the order, could've been the team leader, snatched my receipt out of my hand. As a black woman, I always have to be on the lookout for racial profiling and daily injustices towards me because that's the world we live in. After giving me the remake of my sandwich I walked over 14 minutes back towards my dorm room, just to re-check the bag and they had given me another messed up sandwich. As a former CFA worker myself, I am the utmost disappointed in how this establishment carries itself and its employees. 20 minutes and my foo

                         ## Rank: 2: Jimmy John's | (3.5)
                         **Category: Fast Food, Food, Food Delivery Services, Delis, Restaurants, Sandwiches
                         The sandwhiches are decent. The sandwhiches are on the small size for the price your paying. They do not modify there sandwiches at all without paying more $. You get free smells! yay? lol. There are definitely better options for the same/better price. The sandwiches are outstanding. The bread is great and fresh. They are very fast whether you order inside, drive-thru or delivery. The best when you want a quick sandwich or just don't feel like leaving the house. My only complaint is that they close at 9pm and are not available for the late night snacks. Good shit going on here.. good staff, tasty subs, and freaky fast! This location is constantly bringing in samples to my job. I love the #4 Turkey Tom! They have the fastest delivery. Everrrrr! This review is LONG overdue! Some friends and I went into JJs fairly late on a Sunday evening a few weeks ago after having several cocktails. We were helped by Jamie, who was ALSO working the drive thru line, taking everyone's orders, and making sandwiches in light speed time. We were a bit on the loud side and surely obnoxious, but Jamie was so great, even joked around with us a bit, nailed all our orders and got them to us in what might have been less than a minute, honestly. The food here is always delicious- getting great customer service on top of that is what keeps us coming back.

I was thoroughly impressed with Jamies ability to be extremely good natured, despite being alone late at night and working the job of three people at once. As long as she's working there we'll be back often to say hi and get our late night sandwich fix. Thanks Jamie, you rocked! The sandwich guys here are so fun!  They sing and dance and are so happy to be working!  Totally made me smile when we were there.  I only wish they would deliver to Campbell and river!!! Giving five stars for a "fast food chain" category. :)
Jimmy John's is such a guilty pleasure. I love their super crisp and tightly wrapped lettuce "Unwiches" with "Xtra" whole grain Jimmy mustard. They create the sandwich in lettuce wrap form, then wrap it extremely tightly in paper that you peel back as you eat, then of course there is also the outer paper wrap. It's a salad, but tricks you into thinking you're eating a sandwich.

This location is close to my home, so I can order delivery online and usually have it within 15 minutes. They live up to their "Freaky Fast" motto.

Online ordering is simple. I usually get the Vito Unwich, swap out the Italian vinaigrette for Jimmy's mustard and Mayo. And I get "Xtra" of all the veggies and add cucumber and sprouts. All of this is easily customizable online, extra veggies do not come with an extra charge. Veggies have always been fresh on my sandwiches.

All of my delivery drivers have been friendly! Went there last few says two times.  Get the gargantuan.  Lots of meat and very tasty.  Good service, in and out very fast. Went here during Homecoming week and they lived up to their reputation! They were super fast in taking our order and making it. I have always gone to this location, and have never once had a single problem. I have ordered delivery and it gets to my house within 4-8 min every time(I live pretty close). When I do go in store the people are always super friendly and curtious. The price is a little high, but hey, I will gladly pay for quality.

A side note: Jenny S, who goes to a sandwich shop for a greasy meal after the bars? Your review blew my mind with stupidity hahahahaha Their subs are great.  Especially love the #5 Vito. Bread is fresh and tasty, much better than subway.  They're quite speedy too (which is the whole motto -- "freaky fast").  However... for a place that advertises for freaky fast delivery, I was really annoyed that they refuse to deliver to my home which is 1.48 miles away from their shop location.  They deliver to my workplace which is 1.6 miles away from their shop location.  Doesn't make sense at all!  I live in a low traffic quiet residential area with tons of street parking (absolutely no cars parked in front of my house).  They need to standardize their delivery policy.

**EDIT, I felt bad taking off too many stars for the delivery.  I added a star to reflect more on their food rather than their delivery. Look out Sandwich lovers! Another Jimmy Johns store recently opened in the Old Pueblo. This was actually my first time eating after passing JJ's countless times day after day. Its new Campbell location is much more accessible than the others, which is  why I gave it a try. Personally, I didn't find much of anything gourmet in my Sub, but they did live up to their slogan of "SUBS SO FAST YOU'LL FREAK." In true American style, I went through the drive-thru, and was definitely "freaked" to receive my sub upon paying! Okay, now down to business. Sub was ok. I ordered the #16 CLUB LULU (JJs original Turkey bacon club with lettuce, tomato and mayo). It's your standard club sub on white hoagie bread. I found the bread was dry and chewy. H

                         ## Rank: 3: Slice & Ice | (4.0)
                         **Category: Fast Food, Sandwiches, Shaved Ice, Food, Restaurants, Pizza
                         There's a circus behind the counter. Plenty of tension in the air. First time here. Looks like training may be happening. Must be new restaurant hiccups. Lime Ice is lightly sweetened with nice, mild flavor. Not sure if they use real sugar? 3 meat & cheese Italian sandwich was decent. Bread was toasted and crumbled easily. Kinda made everything fall out of the sandwich. Messy. Meat quality wAs fresh and flavorful. Fries were decent. Tried this place  during the week and I am a fan! The pizza is priced really well. It's no-fuss, good-tasting pizza and fries. The ice was also really good. I had my hungry kids share a pizza and we took some home. I really like the "slice and fries" special and I bet it'll become a popular at go-to for future trips. Service was quick and friendly. So excited to have this new place on the west side! First time; definitely coming back when in the area
Perfect toasted roll, nice samwich
Garlic fries could use *more* garlic This place is great! Friendly service and BOMB ice drinks!

We ordered the cheese pizza and fries combo with a side of ranch. The pizza was pretty good! Comparable to Peter Piper. The fries are the super stars from the combo- served hot and crispy. The ranch was the icing on the top.

The real MVP are the icy drinks!! Wow! They are less sugary and I love that they come in natural colors. We will come back just for that (and the fries!)

Thanks for making a great place to hang out and snack on delish food. It's gets four stars because it executes what it is; simple, inexpensive and kid friendly.  Locals will find this place appealing as its very similar to another local place (Eegees).  If you're a foodie and looking for a culinary experience this is not your place.  The pizza was a simple thin crust pizza; I had the pepperoni.  The fries were identical to Eegees as was the ranch.  Again, simple and well executed and very kid friendly. I have heard  great things about what was to come.  I feel like the food is priced competitive and the portions are great. There was something for all family members and I finally didn't hear whining. I will definitely be back. The team looked happy and they were genuine when asked for suggestions. You definitely need to try this place! Pizza and fries is a pretty neat idea. When I was there, the place was still relatively new and our pizzas came out of the oven a few minutes early. Doughy bread, unmelted cheese. They were busy. The ice drinks are really good, made the whole trip worth it. This is fast food, so it's not going to be top notch pizzas. But in the context of fast food, it works just fine. The place is still new, so you'll need to be a little patient with the staff as they are still figuring things out. Despite all that, service was fast despite them being really busy when I came in.

 The fries are good and there's a number of ways that you can get them. The prices are really reasonable, they even offer a snack box with  a "slice" (half of a 12 inch pizza) and fries.

I got the snack box and a prime lime ice fizz. The ice was worth every penny. I expected it to be a bright green, but it was white  like regular plain ice. Despite the color, it had a great lime flavor. Right now, they only have two flavors, the lime and strawberry lemonade.  While I hope that they add more flavors, I am absolutely happy to continue ordering the lime.

The pizza is, unfortunately, their Achilles's heel. I had the plain cheese and it was not great. The crust was cracker like, the sauce was forgettable, and somehow, the cheese was watery. I may be a bit of a pizza snob, but I just expect better, even at these prices.

If I rated them for just the ice and fries, they would easily get 5 stars, but their name is *Slice* and Ice, so I had to ding them for the pizza. Honestly,  I  can see myself eating here again. A lot. Just not the pizza Everything taste like it came from an easy bake oven. A kid cuisine meal is better than this pizza The person who admitted making my food was wearing his mask down around his chin and when  I complained and he pulled it up it was so loose it fell right down, which means HE IS NOT COVERED WHILE PREPARING FOOD This place is owned by the people that started Eegees
great drinks like Eegees but better,  good pizza
 I would really recommend it

I think it's a really great place and not too expensive

Not fancy casual dress preferred Highly recommend, we are new to the restaurant and the employees were friendly and nice to let us try the Flavors. Love their snack box perfect combination of pizza and fries.The fries are always fresh and hot couldn't compare to any other place. The customer service is very good too the staff is always nice and recommend good ice flavors.This is definitely one of my favorite pizza spots. Food wasn't too bad. But tables were dirty in the dining room. Had to move seats because tables were ignored being clean. Been here for about 30 minutes and no one has come by to clean. Pizza was

                         ## Rank: 4: Baskin-Robbins 31Flavors | (4.0)
                         **Category: Ice Cream & Frozen Yogurt, Food
                         Thank you @BaskinRobbins for helping this pregnant mama and greedy toddler to our car today.  #cravingsdocometrue #mothersday I stood in line for near 10 minutes and suddenly the person behind is served his order. He also went ahead and ordered something else. Not sure. So I left. Evidently the line means nothing to them. Slow as molasses and unorganized. Those little teens need not be left unattended to run the business. I left. Plenty of ice cream in town. If you go be prepared some one might get ahead of you even if they are behind you. Have taken the family here twice in the last two weeks and have been happy each time. We have had shakes, sundaes and just ice cream in a cup and have been happy with all of them. Like other reviews have said the staff is young, but they were friendly, helpful and quick each time we have been in. Good icecream with lots of classic topping choices! Emplyees are all young but nice and helpful! Cakes are kinda pricy but the classic icecream is a great cheap treat.
 Advice- call ahead for the flavor of the month to make sure they have it, many times ive gone in excited about getting the fotm and they have been out:( I needed a last minute ice cream cake, they had so many options ready and waiting in their freezer and were able to add writing right away. Super nice staff and ice cream. If you are looking for an ice cream cake- look no further! Excellent service as usual. A single scoop mint chocolate chip. Service was good. My favorite ice cream shop. Time for a quick treat on a road trip with granddaughters and great grandma in toll. What is fun for everyone? Ice cream of course. So glad we picked Baskin-Robbins. Great variety and flavors for everyone's liking. The young lady working here was awesome, pleasant, efficient, patient with all the questions from two excited kids and an elderly person who couldn't hear. It was actually fun. So happy to find out they still carry the best flavor in the world: chocolate peanut butter. Granddaughters didn't believe me but after tasting mine, or should I say eating all mine they agreed. Of course all the flavors we tried were delicious. The young lady told us the two most popular flavors are chocolate mint and Oreo. That was just one of the many questions our granddaughters were asking her.
It was fun to see all the designs and cakes.  Can you believe they have an ice cream turkey, so fun. Everyone wanted to buy it but it just would have been a melted mess by time we got to our destination. So passed on that one. Maybe you should invest in better staff. And a better take out. I'm really tired of placing orders on DoorDash and then getting canceled 30 minutes later when they should've been here. You guys just really don't care. And I hope that someone ruins your day like you've ruined mine twice now.

                         ## Rank: 5: Prep & Pastry | (4.5)
                         **Category: Restaurants, Cocktail Bars, Bars, Comfort Food, American (New), Sandwiches, Nightlife, Breakfast & Brunch
                         I really like Prep & Pastry - we have been twice in the last two months on a Sunday.  The best trick I learned is to put your name on the waitlist BEFORE YOU ARRIVE.  As long as you are within 5 miles of the restaurant, you can be added.  It is a great service.

I have tried a number of things for brunch and all have been excellent - even their sweets. I think my favorite is the breakfast sandwich.  I am not a big drinker, so I usually order the ice team and it really is better than almost anything else I have tried.

Staff is really, really nice.  I highly recommend a visit if you are in town. Tasty selection and very preppy!

One cannot go wrong with the What's Up Doc omelet. One complaint with the omelets is the actual size, they seem to fluctuate. Clearly a difference in 4-5 extra bits worth of omelet.

If you have a sweet tooth, any of french toasts are great! Fancy Breakfast Sandwich is great! I substituted the prosciutto with bacon and got great results! Great mimosas! If you want to eat at Prep & Pastry on the weekends, go right when it opens or before it closes. There is always a long wait because of how busy it gets - but the wait is always worth it. The food there is absolutely amazing. I go there often and love the green eggs & ham, bloody marys, and mimosas! They gave me a free pastry on my birthday once, it was delicious! I wish I remembered what it was called.

I also love that they serve EXO coffee here (a local coffee) - nothing better than a great breakfast with great coffee to go with it! Great food and good coffee. Wish they had more of an espresso bar with coffee options, but food and baked goods are spectacular! Had the chicken and French toast and it was over the top!
While it would do some good to have more shade on the patio it was still an enjoyable experience. They are pet friendly too!
We will be back! This was a great place to have brunch with the family. It is very clean and the staff were great. I love the decor!! Plus, my four year old actually ate here!!! That is a HUGE deal. He doesn't like anything. The food took forever- servers were really friendly, but they looked very unorganized. Example, after breakfast we asked for a heated cinnamon roll and it sat so long it got cold again lol. It was amazing though once we finally got it. The pork belly was great, eggs way undercooked. Overall, we might go back for a cinnamon roll to go, but not to eat, just not worth the waiting. Long wait if you go on a weekend, but worth the wait. The potatoes are the best breakfast potatoes I've ever had. Bacon was delicious as well. Both the smores and classic french toast were very good! Pricey, but worth it for special occasions. Absolutely amazing!! Cute little restaurant serving breakfast and brunch. They have a bunch of unique and tasty mimosas. Super cool atmosphere and decor. Food was extremely tasty. Awesome find during our short stay in Tucson! Decent place for lunch. Overall service is good with friendly employees. YUM.

Literally that's all I can say about this place. I went twice in one weekend! I'm literally obsessed. So where do I begin?

The doughssants! Or cronuts, as some people prefer. How YUMMY. I had the cranberry and coconut one. They're very dense so get one BEFORE your meal bc I could only take one bite out of mine after I finished my grilled cheese. Oh man, that grilled cheese. They have a really unique blend of cheeses and pesto! Now I am not a pesto fan (I know, very strange) but it works great here! But the selling point is the tomato basil soup. Literally the BEST I have ever had and this is my favorite soup so I have tried it everywhere. The second time, I tried the classic breakfast: 2 eggs, any style (I opted for scrambled), country hash (delicious) and toast. This time I had my doughssant beforehand, s'mores flavored -- amazeballs.

The space is very comfortable and beautifully decorated. The staff is extremely friendly always checking in with you and making light-hearted and sincere conversation.

There is a wait to be seated. But you just have to stick it out because you don't want to miss out on this new restaurant.

I'll be back when they get their liquor license business straightened out so I can sip on a mimosa while I enjoy my grilled cheese. By far the best brunch in Tucson. One of the rare places that serves a Bloody Mary with a beer back.  Service is consistently great. Expect a wait Friday-Sunday. Order the Benedict and the Madras mimosa. My sister and I were visiting Arizona all the way from the east coast and our aunt and uncle brought us for breakfast today. Our server, Alma, was out of this world. She had an amazing, positive, and outgoing personality. From the moment we sat down, we felt at ease and comfortable. Her sense of humor kept us entertained and feeling welcome.  We couldn't asked for a better and more upbeat personality.  She definitely deserves positive accolades from all who work with her.  We can't wait to visit again! On top

                         ## Rank: 6: Oasis Fruit Cones | (5.0)
                         **Category: Ice Cream & Frozen Yogurt, Food
                         It was one of those days.  You know the dog days of summer where you are cranky and irritable until you cool down - at Oasis Fruit Cones!  $3 for a small raspado - fresh fruit (strawberries, bananas, and mango are the most popular), a scoop of Breyers vanilla ice cream, shaved ice, and a bit of flavored juice (you pick the flavor or it comes with the same flavor as the fruit you pick - some pick bananas with the strawberry juice).

Delicious!  You can get some artistic looking taco snacks with avocado and crema, cracker, salsa, carne asada, and cheese.  You can get mixed fruit with chili powder.  But stay for the raspados - accept no imitations (I'm talking about fruit concentrate from the mall raspado places)! Watching Food Network one day, my husband & I were embarrassed to admit we've never had raspados. After asking around, this place came highest recommended. Prices are reasonable, LOTS of variety, friendly service, open late. I ordered a peach raspado w/vanilla ice cream, my husband ordered banana w/lechera. Wonderfully refreshing & not too sweet. The only reason I'm only giving 4 stars is that it could use a little ambience. Seating is only outside & the tables are loose & rickety. I have been coming here for years. I've been to other respado places in town, but the juice they use here is the best. Cheap and delicious! Raspasados - Not just a mysterious word but an amazing concoction of sweet fruit sugars condensed milk and Ice Cream.

Eschimocha- A hidden gem of fine Cold Cream Confectioners. This was something new i tried and by far my favorite new thing. Its melon, Cantaloupe, and apples chopped up slammed with whip cream, coconut shavings, nuts, and probably more condensed milk, it was sooooo good, and it kept in the fridge and i had it for breakfast.

This store has way more flavors than the other Oasis but i love them both for their cheap amazing creations that will keep you coming back.

The only downside is an inefficient outside seating area. You definitely shouldn't come here alone, because sharing this experience is definitely going to get you some brownie points. Smaller group tables lets everyone enjoy the space : ) Tasty ice-cream creations! We got a standard scoop of chocolate ice cream and a Chamoy. The chamoy was a combo of crushed ice, dried fruit, fresh fruit and nuts - and it made for a tasty experience - salty, sweet, with a punch of chili! If you're looking for an authentic South Tucson experience, end your summer night out with a stop here. We were looking for frozen yogurt and found this location. I saw the a picture of the raspado with mango and pina and I had to have it. They had a variety of items.  My husband and son both got ice cream and I got the raspado.  You can also add a scoop of ice cream to the raspado. I've never had it like that but it was very good. This is the place to be on a hot day! They have an incredible variety of things to try. For the traditional there is ice cream served in ways that you wouldn't think of, but for the adventurous try a chamoyada. Yes, it's a cultural thing, but well worth it. My favorite is the mango chamoyada. The service is efficient and with a smile. I love this place.  They have the best raspados in Tucson.   The place is clean, everything is fresh.   These fruit cones are delicous.     No other raspado shop in south tucson or anywhere close by comes close to Oasis.  Cant wait to go back! Don't read the reviews just go get one! Yum forget about Dairy Queen an baskin Robbins The raspados are fantastic. I had coconut. REAL coconut, not the sweetened packaged stuff. Daughter had mango, another good choice. They'll drizzle some condensed milk on top if you like the added richness. Very refreshing! The fruit was fresh and delicious. We'll be back! Going to Tucson for the first time last week, I was determined to find some authentic Mexican food. It just made sense being that we were sooo close to the border. But I didn't want just burritos or tacos.. I wanted Mexican food that I've never had ANYWHERE before!

I quickly found this business and was INTRIGUED by the pictures of a sweet shaved ice dessert THAT WAS TOPPED WITH SALTED NUTS. It looks really unique. And it also looked delicious, because I love things that are salty AND sweet!!

I came here and had a raspados for the first time. I quickly realized it is basically the Mexican version of Filipino halo-halo. Or Taiwan's snow. Or Korean patbingsoo.

BASICALLY, it's shaved ice, but the flavors and ingredients are really unique and unlike Asia's types of shaved ice!

For one thing, they use chamoy sauce. They're also REALLY into tamarind candy. And lastly, my raspados comes with SALTED NUTS. It was really cool.

I personally was not into the plum topping however. It was way too sour. I didn't love the tamarind candy either but that's probably because I don't like tamarind unless it's in chutney form. But the salted nuts, ice, and fruit combo tasted really good.

It's definitel

                         ## Rank: 7: Luke’s Italian Beef | (3.5)
                         **Category: Meat Shops, Restaurants, Specialty Food, Italian, Food, Sandwiches, Fast Food
                         OK I only gave it 4 stars because it's Italian Beef and Dogs. I didn't want to get you too excited. What can I say bad about Italian Beef with sweet peppers and dipped. Right now you either know what I'm talking about or you don't. If you know, and haven't had a Luke's get down there and treat yourself to a little taste of Chicago. This sandwich is so good they have a roll of paper towels on each table.  Its wet and yummy. If you've never had a Chicago Italian  Beef with sweet peppers don't wait any longer. The Food Man says GO FOR IT.
Now for a true confession IN MY HEART IT'S 5 STARS! ! I love em.
"CHOW" FOR NOW I have long been a fan of Italian Beef sandwiches, and Luke's delivers in spades.  The Only better sandwich is in Chicago, and that is a little far for a lunchtime fling.

I have eaten the Beef as well as the meatball sandwiches, and the fries.  As far as I am concerned, that is their raison d'etre.  And what a justification.  Piled high with beef, add peppers and/or cheese if you desire, and dunked in au jus, for a messy, but satisfying meal.  The Meatballs are large, juice and smothered in marinara sauce.  A messy meal.  I prefer mine with hot peppers, a side of fries and a soda.  Not for the calorie counters, but a worthy splurge! We came here on a recommendation from a friend and it didn't disappoint! The Italian beef was very good! Soaked in au jus sauce. Tasty! The fries were done to perfection! Very good meal! It's kind of a dive but that's ok with me. We'll be back! Everything I've had here is good, best place around here to get Chicago-style hot dogs.  Note it's greasy, the sandwiches will probably come plain unless you ask to add peppers or cheese, and a side order of fries is huge.  Napkins are provided as rolls of paper towels. I have only been here once, but i won't be going back.  I will try other Luke's shops and see how they are though, as I guess they are independently owned.  Anyway, i ordered a beef sandwich and actually saw the guy go in the back, grab beef with his hand, put it on a roll with no gloves, and put it in the microwave.  Not sure if this is how they always make their sandwiches, but it definitely was not sanitary.  The sandwich tasted good however, as i still ate it...lol.  and the fries were very good also.  I just don't think restaurants should use a microwave to heat their food and sanitation is very important. This sandwich shop is so good I don't think I can eat a sandwich from any other place ever again. My friend created a monster bringing me here. The Italian beef sandwiches are amazing; tender beef soaked in aujus sauce on a hard French roll. Only problem is there's so much meat on them that it's hard to finish (hardly a problem). But then it gets too soggy to eat later. I also tried an Italian sub and I really think these rolls they use are what make the sandwich. So good! I've gone around 4pm every time and the parking lot was empty and no one was in line. I guarantee it's a madhouse during the lunch and dinner rush though. Lukes on S. Alvernon is the best Chicago style beef around.  Walking in to this place is like walking in to some greasy joint on Milwaukee Ave and getting some no-nonsense food at the right price.  Good beef, good dogs, great decor, this is the real deal.

Lukes on Ft Lowell, however, is nothing like the S Alvernon location.  The food is not worthy of mention, the place is nothing special, and the dirtbags behind the counter add nothing to charm.

I can't account for the Grant Rd location, but I think I'll stick to the one on Alvernon.  I hate being disappointed by bad beef sanguiches. Delicious Delicious Delicious......simple as that! I've been a regular at Lukes for many many many years. I normally get the Italian beef, extra wet, with sweet peppers, cheese and hot peppers:) YUMMO! My daughter always opts for the Chicago dog minus the relish. Ive been to all the various Lukes locations and this one is my personal favorite:) The guy (s) who are always there immediately know what I want when they see my Volvo pull into the drive-thru and I have never been disappointed. The beef is tender and tasty and I like the bread to be soggy so I ask for it to be extra wet:) Part of the fun is just in the ordering lol ! Go try it you will NOT be disappointed:) The Chicago dogs are an obvious winner. Sometimes the buns get a little soggy if you don't eat it there but other than that their good. I also like the meatball subs.

I decided today to try something different. By suggestion I went for the Italian beef with cheese and hot and sweet peppers...it was awesome! I will definitely being ordering that more often. Overall I have been coming here a while and have never been let down. Delicious huge sandwiches in this dirty little place. I really like their hot pepper mix and they have an assortment of condiments to try. I don't like the passive aggressive signage though. If you're the type who likes modifications don't come here. Great food, but

                         ## Rank: 8: Le Buzz | (4.5)
                         **Category: Sandwiches, Breakfast & Brunch, Restaurants, Cafes, Food, Coffee & Tea, Salad
                         Really good food, fast service and hits the spot perfectly after a long hike! Patio is pet friendly and they have wonderful , refreshing drinks! Great food, large place, my son and u kept going to the counter to get more and more goodies. Before my buddy joined us, I was able to talk to a regular there and he told me the story of the shop became what it is today. Very intriguing and insightful. Great atmosphere! Great white chocolate mocha! Good Sonora salad. They could class it up a bit to match atmosphere if the employees would wear uniform and require long beards to b shaved on employees :) Le Buzz is one place that is surely "buzzing" in the mid morning after everyone has completed their morning hikes through Sabino Canyon or their morning ride along Tucson's roadways. Filled with hikers, cyclists and everyone in between, Le Buzz has proven to be the place to get your post workout fix or just some good food in general.

Outside is already buzzing with people enjoying their food or beverage and upon entering, it's no different except that you are welcomed by their large array of fresh baked treats nicely displayed behind their pastry shelf. Everything from cookies, muffins, breads, croissants, scones, and much more. And if that isn't temping enough, they offer a large selection of coffees and teas as well.

As for the food. My first visit was after an 8 miles hiking venture through Sabino Canyon and I was famished! I decided on their "Gimme My Regular" which includes 2 eggs, 2 slices of apple-smoked bacon, home fries, and sourdough or whole grain toast with their house-made jam.

I opted for a healthier option of scrambled egg whites which they were happy to provided and chose the whole grain toast. The eggs were cooked perfectly fluffy, the bacon was crisp and indeed "apple-smoked," the home fries were among the best I have had with crunchy skin and tender insides, and the whole grain toast proved to be the perfect vessel for their sweet and tart raspberry jam.

Upon my second visit I chose a lunch option which was not an easy option at that with so many tempting options to chose from. But despite my overload of delicious sounding menu items I opted on their "Turkey Avocado" with oven roasted turkey, fresh avocado, red onion, tomato, lettuce, provolone, mayo and a hint of whole grain mustard. I couldn't build a better sandwich myself. All the flavor components of this sandwich worked in perfect harmony together. Not one element overwhelming the other. And with a side salad and house-made dressing along side, it is a perfectly filling yet light lunch.

My only negative comment would be the lack of attentiveness and enthusiasm of a few of the waitresses when I tried to get a refill of my unsweetened black iced tea. Best Breakfast in and around Tucson. Great staff. Relaxed vibe. Lovingly prepared food. Nice pastry selection. I eat here every time I'm in town. I will always support a great local business, and LeBuzz is truly one of the best! A great place to meet friends for a coffee or late lunch. The food never disappoints and the atmosphere is pure Tucson local. The only drawback is finding seating at times. LeBuzz gets busy! Le Buzz is a great little restaurant! Has a nice, cute, small café feel. Not too noisy though it does get very crowded during breakfast time. Great selection of pastries and they are all delicious. You can tell they are homemade. Regular menu isn't too huge but not really a problem. Lots of drinks and the hot drinks come in beautiful, huge cups. A little slow with making the drinks however. LOVE their chicken pot pie but I think you can only get it once a week. Overall very enjoyable experience. Would definitely recommend. How can anyone be giving them less than 5 stars??
Best breakfast in Tucson, at least if you're not a lumberjack. Lumberjacks who want steak, eggs, and pancakes all on their breakfast plate should go elsewhere. And in general, being a cafe in the French spirit, the portions are proper. If you expect one breakfast to feed two hungry people, go to Country Kitchen or some such.

And then there are the espresso drinks--a solid 5 stars. Wish my local cafe back home made such excellent coffees!

Plus the atmosphere is superb, again a bit of French style.

Way better than Prep & Pastry, which is pretentious, limited, and pricy. No comparison. Go to P&P only if you need to please some snobby friends.

Finding Le Buzz the first time may be a bit tricky. The way that strip mall is laid out, signage tends to be obscured. Le Buzz is directly to the left of Safeway, and the mall is at the NE corner of Tanque Verde and Catalina Highway. Great coffee, incredible baked goods and fresh breakfasts and lunches.  Never ever a disappointment
 An East Side must It was our 1st visit & we chose what sounded fabulous on the menu:

"GRILLED NAPA -
A lovely combination of oven-roasted turkey topped with French brie, tart green apple, red onion, plus a little rustic mustard.   $10.20 "

                         ## Rank: 9: Baggin's Gourmet Sandwiches | (3.5)
                         **Category: Sandwiches, Food, Event Planning & Services, Caterers, Food Delivery Services, Restaurants, Delis
                         The place was cute but I wasn't impressed with the sandwich. I got the Unforgettable Baggin Sandwich combo. It was pricey for the sandwich, chips and drinks.

The sandwich did not have any flavor!! I'm a big texture person and everything in the sandwich almost felt creamy. The avocado, cream cheese and   Mayo gave the creamy consistency and it didn't not mesh well together. I tasted each of those individual ingredients. The turkey did have flavor, meaty-ness or much of a texture. The sprouts weren't crunch, it was just kinda there.  The bread was kinda thick and unappetizing. It was there to hold everything together though!! Lol

The spice tea was amazing!! The aroma and fragrance of the tea, quiche my thirst. I was here during the hottest week of Tucson (105-117 degrees), and it was a great drink other than water. I not a coke or carbonated person and I try to stay away from sugary drinks. The spice tea has so much richness that sugar is not needed!!

When I travel I like to go to places where it's not a chain that can be found in Houston. Thought this was a quick pit stop before going to my next client. I wish I would of gone to Subway and spent 1/2 of what I spend and that I know what I like in my sandwich.

The place was nice, lots of tables and booths. If I had more time, it would of been a nice place to relax and work with the Spiced Tea!! Wonderful people that make you feel at home! Props to Andy who hooked it up on the grill and made my tastebuds weep tears of joy! Omg !!!! So I came up to Tucson for a little getaway on the way out of town I stopped here to eat. I'm so glad I did it was delicious probably one of the best sandwiches I've ever had. Staff was friendly the place was clean. Will return next time I come to town. Ps they have pb& j for picky little ones that won't eat real sandwiches ;) A little pricey but great sandwich. Perfect choice when I didn't have time to make my own. baggin's does sandos well.  love the veggie w/o
cheese or mayo-add spicy mustard on marble rye.
my SO liked his pastrami sandwich and refills on
all drinks are natch, free.  we've been to multiple
locations and the baggin's next to roadhouse cinemas on grant is prob our fav.  it's clean, brightly
lit, and the servers and cashiers are all really great.
we always get a cookie in our baggin's bag and my
SO gets mine.
:) Food is always good but if you are expecting any sort of timely delivery good luck with that. Doesn't seem to matter what time of the day you order or how well you tip. So as long as you have plenty of time to wait for your food, the food will be great. I like this place. Sure, it is "just" sandwiches, but you get a little cookie with each one and... the whole thing comes in a *bag* (get it?)

I've been coming to Baggin's for decades. Yeah, I'm that old. During this visit, I had the Sundown, which is the first sandwich I ever had here, and the sesame noodle salad, which I'd never had. I actually ordered the half sandwich plus a side, which is a good deal for lunch.

I usually get the hot sandwiches -- the cheesesteak is very good and the various chicken ones (Anasazi is probably my favorite). The egg and tuna salads are above average, too. There's nothing too crazy, but they do have tweaks to classics and some unusual toppings (this is the first place I'd seen stuffing and cranberries on a turkey sandwich outside of my own home).

TIP: Get the spiced tea. Add a packet of sugar if you want to take the edge off the spice a bit. I usually drink so much of it that I have trouble sleeping at night. But, I like tea, so... I love Baggin's and was thrilled when this location opened, because it's within walking distance of my home and across from my gym. I've tried several items here and have a few favorites. The tomato soup is the best; it has a hint of spiciness to it. I love the Unforgettable, the Sundown, and the Grinder. They have yummy kettle-cooked chips, but go for the other sides. The potato salad has bacon and green onions in it, and it is one of my favorites. I also really like the Chinese sesame salad and the chicken bowtie salad. It's hard to choose a side, because you can also upgrade to a cup of soup. Serious dilemma. I love that you get a fresh chocolate chip cookie with every meal! Their carrot cake is pretty good, too.

I'm taking away one star for two reasons: One, I very much wish they would extend their hours. They close at 5 on Sundays and 7 every other day. I'd eat here more, but it's usually closed by the time I'm home from work or the gym and ready to eat. Two, this particular location is never busy when I come in, and they always take quite a while to prepare my food. Maybe they don't feel the need to rush because it's not busy? The other locations seem more efficient, and I can get in and out quicker. Ordered lunch to be delivered.  Got the wrong sandwich and when i called to let them know the manager...sorry forgot name.....was so delightful.  She immediately had her staff make and br

                         ## Rank: 10: Beyond Bread | (4.0)
                         **Category: Sandwiches, Coffee & Tea, Food, Bakeries, Restaurants
                         Are you a fan of sandwiches? WAIT...before you answer that...are YOU a fan of deliciousness? if you are...this is the place to go!!

Brad's Beef, is my favorite! You get yourself some roast beef, green pepper, red onions, and russian dressing! Yum!!

There are plenty of breads to choose from! Some of their bread is hard and makes your sandwich really unsatisfying.It's not hard because it is old, but hard because its how the bread is baked. While ordering you can always ask the cashier what kind of bread "they" would eat it on...then its a safe bet you wont end up with a rock hard bread sandwiching your food.

They have a complimentary bread bowl you can pick at while you're waiting for you food.

If sandwiches are not your thing, they also offer salads, soup, bread soup bowls, and desserts/pastries!!

They also offer breakfast, I haven't been able to try their breakfast yet, but everyone raves how good it is! Will have to try it next time around!

If you're not a fan of sandwiches, this place will make you into a fan of them! I was already a fan of Beyond Bread's sandwiches. However, I had never tried their breakfasts. Gary (one of our "dining trio" that often includes my mother) and I were wondering what to do for breakfast. We decided to give Beyond Bread a shot, not expecting more than some pastries and some bread-y items.

Were we wrong! We walked in, observing a full house of happily eating, noisy diners! They have a great breakfast menu, with egg sandwiches and about 5-6 choices of what else goes into 'em, plus omelettes, plus pastries...etc. A tough but yummy decision. Gary and I both opted for different egg sandwiches for around $6.25. What a GREAT choice!

He got a ham, cheese, egg and some other goodies sandwich while mine had bacon, cheese, egg, tomato and love in it. The most outstanding feature was the perfectly chewy texture of the slightly toasted bread. It was like...melt in your mouth terrific! And you get a fair share of food, too. On top of that, you get to choose from a few sides. I chose the potato pancakes (two good-sized ones accompanied the entree sandwich). I only wish they had some sour cream and apple sauce (traditional latkes Jewish style, ha ha) to put on it. I'm sure I could have asked but I was so full as it was.

We also ordered a sandwich to go.

Everything was SO good. And what value! I had to take half the egg sandwich home, to enjoy for the next repast. I can't say the same about Gary's meal. His was inhaled, man-style. Good sign of how much he enjoyed his breakfast. I've never thought of BB for breakfast, but you better believe I'll be back soon! It was a fun, upbeat, and delicious experience! A Tucson icon! The best sandwiches you will ever eat. You'll pay a buck more but you won't think about it after your first bite. BB is superior to Baggins which is almost the same in price. The place is ok, but not exceptional. If you like things big you will probably love it - feels like a big box store, serves huge sandwiches. If you like the atmosphere and food of a high-end coffee and sandwich place you may want to look elsewhere.

But they are very friendly and the sandwiches are tasty. Great sandwiches and salads
They make the bread there-delicious
Great experience. It is expensive, so dont be surprised I love love Beyond Bread! My only complaint is that they are not in Phoenix, and therefore it is a once in a while treat when I visit Tucson.

Beyond Bread really has there act together, it is easy to order, there is never much of a wait even when it is packed! Of course the food is great, but oh man the bread is the BEST! I got the Maddy's Madness, which was packed full of chicken, bacon, avocado and havarti cheese. The combination was outstanding, but once again the best part was the Mulitgrain bread. I couldn't get enough of the bead! It was so full of grains, I was kinda mad at myself from not buying a loaf to bring back home. Never again! I will make sure to always bring one back from now on!

If you are looking for a great, filling and healthy lunch there are many choices at Beyond Bread! Do not let the crowds scare you away! I promise it will be worth the wait! I really like this place,  but I feel prices are just a little high! I believe I paid close to $15 for a latte and a sandwich with chips, which is comparable to what one would pay at a full service restaurant.

Besides that, I can't complain. Food is always decent, and the staff are friendly enough. Love this place for quick, hearty food with tons of options & great staff.  Lots of turn over in the seating.  We love their soup & salad options & the pastries are mouth watering & well displayed.  Several soups to choose from.  Always clean.  Get in line to order food and they bring it out.  Choose your bread & filling options and can add on items.  Overall a great place for lunch or take away meal. My family and I started eating at Beyond Bread when I first attended UofA in '98. It has to say something that 14

                         ## Rank: 11: Dunkin' | (3.0)
                         **Category: Restaurants, Donuts, Food, Coffee & Tea
                         Donuts seemed very fresh yesterday afternoon when I bought a half dozen, but when I opened them up this morning less than 24 hours after purchase, they were growing mold. I am a huge fan of Dunkin' Donuts and always have been. Their service is normally quick and friendly donuts,coffee, and sandwiches are always made well. I was however very disappointed in the lack of customer service when going through the drive-through today. The person on the other end of the intercom was rude short and repeated herself over and over. When I pulled up to the window no hello, hi ,how are you? sorry I couldn't hear you. I received just a flat that'll be six dollars. I handed my money through the window and sat there and listen to her treat the customers in line behind me with the same short frustrated attitude. She handed me my coffee and when I said thank you that looks great she just shut the window on me.... She handed me the sandwich as she yelling into her head set at another drive through customer. I can understand times are busy and it was Saturday morning 10 AM rush but there really is no need to be unkind. I hope someone reads this review and make sure that location is staffed more properly so that cashiers have the time to say thank you to their customers. Gal cashiers are very sweet, but the donuts are big disappointment ! We rarely indulge in this type of sweets and then this! Probably kill off the future craving. The worst donuts ever. A bunch of male seniors hang out here in the morning chatting away. I'm a fan of dunkin donuts in general, but the customer service at this location is about the worst of any fast food business I've ever been to.  One time I was waiting for a smoothie, and thought they were making it, but instead I stood there watching the women working there just stand around and chat.  I watched this blond woman working there take her hair down, comb her fingers through her long hair, put in back into a bun, and then take it out and start over because she wasn't satisfied.  Standing in front of the donuts! So, if your donuts have blonde hair in them, this is why.  This is so gross to do right next to uncovered food with customers watching.  After about 20 minutes, I asked about my smoothie, and they all seemed to have forgotten about it.  Like they didn't even care to find out why I was just standing there staring at them.  Last night I went in to get ice cream, and was ignored for 10 minutes even though no one else was waiting to order.  There were several women going around cleaning and working, but even though a woman walked right by me, she ignored me and didn't care to ask if I wanted to order or tell anyone else to come help me.  After waiting for like 10 minutes with everyone ignoring me, I decided to take it as a sign I didn't need the sugar and just left. I don't know why this Dunkin has such a bad rating.  We went at around 1:30 am on a Monday and they had pretty much every doughnut they offered available, everything tastes amazing and the lady even gave us like 40 munchkins instead of 25.. WIN. Also, the egg and cheese sandwich is 2 for 3$ and was better than Starbucks egg and cheddar. We arrived here to find this Dunkin Donuts being completely renovated so the place was missing a lot of customers. We went in and were welcomed by a burly lady who barked at us to "order everything at once" so she could get it all done with.

Wow, no time to think or look at the wall menu? Then a young girl then stepped in and asked my personally if I was getting coffee. I clearly told her I wanted a large coffee with sugar and cream (I remembered the coffee as being very good).

This same girl stared at me, and asked " Do you want sugar and cream with your coffee?" I answered with a yes. She looked at me again and asked, "What size do you want?" I wanted to laugh. To be honest, I don't think the girl was mentally here on Earth (she looked dazed).  Luckily I got my coffee quickly and left. Unfortunately the coffee tasted burnt (as if it sat on a burner for too many hours) and it had no sugar.

I hope the renovations make the place look great but I hope their service doesn't suffer much more since I can't say their coffee or their service is very good at this location. Whoa super friendly lady in the drive through!!!
We had delicious coffee and a bagel sandwich and it was divine. Excellent selection on donuts! The shelves were stocked, cashier lady was very helpful. I will definitely go back and recommend this place. Yummy coffee and wonderful fresh donuts!!!  Everyone is quite friendly and there's even ice cream.   My favorite when I'm craving donuts!!! I love this Dunkin Donuts everyone is always so nice. Everything taste freshly made and the triple chocolate muffin is so yummy with a hot latte or hot chocolate reasonably priced as well I love the smooth flavor of DD coffee and because I am from Massachusetts I grew up on this stuff. The new look and feel of the renovation has taken the old cafeter

                         ## Rank: 12: Subway | (3.5)
                         **Category: Fast Food, Restaurants, Sandwiches
                         Subway is always been a good sandwich place for me. The few times I have been here everyone is always friendly. Only had one time where they seemed rushed but the line was huge so I had no issues with it. My sandwhich always come out the way I ask for it and in a timley manner. I am very pleased with the way it is being ran. Keep up the good work guys. My food was prepared very quickly by courteous and friendly staff.  The restaurant was clean and the food is good. WOW.....$9.18 for a 10" foot long sub, no extra meat, no extra cheese. Subway was fresh and clean inside and the food tasted all right. Just can't believe their prices have jumped that high in the years. Much better foods to get for lunch for that price, including sit down restaraunts. FAST Review:

Food (5/5) -
You know what you will be getting when you come here. A 6-12' sub, with a choice of toppings and breads.

Ambiance (4/5) -
Again, it's Subway. It's not spectacularly clean, but it's not messy either. The baked bread smell sometimes overpowers however. Not sure if they lack proper ventilation, but it has earned the nickname Smellway. But I guess if I had to choose between overpowering smells, I'd choose baked bread over, let's say, poop.

Service (5/5)
I love the service at this particular one. There is another Subway 4 minutes closer to my house, but I will come to this one because they are much more efficient. I have found service at other branches to be slow compared to here. Staff is always friendly. THE fastest subway sandwich maker in the world worked at this location for like 5 years! How cool is that.

Total Impression (4/5) -
I am a regular here and will always be as long as they remain as efficient as they have been. Very clean and friendly staff great customer service everytime we go in there. Bread is always fresh Always ready to please I was once asked, in response to wanting to go somewhere else, "How do you feel about subway?"

I hate subway.  It's bland and boring.

Especially this subway.  Both times I have eaten food from this subway I have suffered stomach pain for many hours afterwards. Bin going here fore years just found out thay got rid of the hot pastrami sandwich I will not change this review until it is brought back the people working there are great but constantly changing their inventory is getting annoying get rid of the new sub and bring back the original hot pastrami sandwich On this visit I was disappointed as usual in that "we are out of montserella cheese today" says a very polite young lady. The last time they were out of my favorite bread. P poor management who can't have sufficient stock on hand. No holiday week-end being mothers day . I doubt they were over run with sub orders.
This franchisee needs to pay attention to his investment. But I guess on the other hand, I guess  he doesn't give a hoot, to say it politely.
The personnel at  4:00pm. were very polite. Being better than most days. Ok. It's sad that I'll inevitably return.....because I love Subway.
Subway to me is that ex-girlfriend that you call everytime you find yourself single again.... You want something and something comfortable and you know that you can go there and get what you want but you'll regret it later.
I love Subway, at least, the idea of Subway.
This place is messy. It's always messy. How can there be people working here....no customers.... and yet the floor covered from front to back with....crumbly crumbs and stuff. The fountain drink area's sticky all over. The staff is indifferent (which is at least better than rude). But I'll be back. They know I will, cuz they don't mess up my order. And they know I love Subway. Pissed that foot longs are no longer $5 because they have to double the price so people with EBT can get theirs for free. I would give less then one star if I could. The Area Director Jeremy Ramirez is even less helpful then the crew member working on her own and had no help. She gave my wife the managers telephone which was called but no help. Jeremy was trying to turn the bad experience around on us the customer I never heard of a customer service driven company of doing such. The one on Tucson blvd by the airport way better food and customer service. I do not know why Jeremy Ramirez is a Area director or any kind of manager member. Jeremy might need to find a job cleaning out barns on a horse ranch. Again do not eat here! We called and told Makenzie that we were on our way to the lake and asked if we could get 5 footlongs to go and needed to cut them in four. Not only did she cut them, she individually wrapped them and had the most pleasant attitude when taking the order. A very pleasant experience. As usual...lunch was delicious. Great company with Grand Girl Jada. This franchise has always had the Southwestern Bread available. The chocolate chip cookies are fresh, full of chocolate chips & soft. Can't go wrong with the a 6" Sub :) Subway is just subway. Over rated multi billion dollar establishment tha

                         ## Rank: 13: Honey Baked Ham Company | (3.5)
                         **Category: Restaurants, Delis, Cafes, Sandwiches, Food, Meat Shops, Specialty Food
                         Got a turkey sandwich and the woman got the hot turkey something sandwich. We both got sides of mac with a tea and soda. Not bad but nothing to write to Jesus about. Had a gift card so that made it better. Cost about $20 bucks. Might go back to use the rest of the gift card. I don't even know what to say... But let's get into it. I order the basic honey baked ham and I swear to god it wasn't ham. It was turkey. I might add, turkey that tasted like it was from pilgrims involved in the first thanksgiving ...sweet god I get shivers thinking about it. Look guys I understand that hams are going extinct but cmon don't call yourself honey baked ham and serve up old turkey. I know, I know hams are beautiful birds but they're mighty delicious. Poor food but I loved my milk, very nice fresh and organic. 4 stars. Go to spot for holiday half bone in ham. $$ but consistently good. Other sides , rolls & deserts. I find 7$ off coupon in paper or online? (pays tax? ) and order ahead & pickup 3 days before holiday otherwise slammed. You can come here for lunch! Who knew?  I always thought Honeybaked Ham was just for those Easter potlucks with relatives when you ended up in charge of the main dish.

For about $7, I got a half a ham sandwich, a drink, and a big green salad, with greens that were actually green (no iceberg here!), cucumbers, and ripe tomatoes.  I was able to change the bread that came with the sandwich, no problem, and my meal came with a big dill pickle.

Service was fast and friendly.  The lady behind the counter seemed a little confused about the combo I was ordering, and when I asked about my drink (which is included in the half sandwich combo), she was puzzled and said she hadn't rung me up for one but I could have one anyway.

The inside is decorated rather cutesy, and we found ourselves dining with several elderly people that were clearly enjoying their meal.

The other bonus is the SAMPLES.  They had both cold meatball sandwich bites and hot meatloaf with sauce set up on the counter for people to try.

A tip: Savaya Coffee next door doesn't have the best food selection, so it's great to stop here before a caffeinated study session! I went to this location for the first time,  with a coupon for a free ham sandwich for joining their email list.

The service was quick and cheerful. Even though I was only there for free food,  I was treated warmly and with a big smile.

The sandwich,  however,  left much to be desired. The croissant was dry, and there was literally a few drops of mayo on it. There wasn't even a full lettuce leaf. I'm not sure if they skimped because it was a freebie,  but I was very disappointed. You've got to be kidding me.... First, they open with wanting (almost demanding) my phone number. They didn't ask me to opt in. They just said "let's start with your phone number!" They were unable to explain the benefits of giving it to them. Clearly confused, they explained that linking it to email provides coupons. They never requested my email so again, what's the benefit of having me announce my phone number in front of a few strangers? The sandwich was decent but the smallest $7 sandwich I've ever had in my life. I almost gave it back to them. I haven't been this disappointed in a meal in a while. Very good ham, but expensive. I guess that you get what you pay for, but be alert to coupons which makes it very worthwhile. What is better than honey baked ham? Nothing! Except they were giving out samples of honey baked bacon. I got a sandwich to go and it was not as flavorful  as I had hope that it would be but I'd definitely go back and try something else off of the menu. Major fail!

Pricing is deceptive for their ham.  They quote prices "per person", and when asked how much per pound, they don't want to tell you and are evasive on that fact.  We got enough info to figure it equates to over $15.00 a pound.  You are better to go to a conventional meat market where the price is not outrageous.  We had ordered ham for a party, which at their prices would have been $100. We walked!  Went to the meat market nearby and got the same ham for about $50.  I don't trust companies like this that have national advertising.  You know who pays for the hype?  The consumer! Just went for our last minute Thanksgiving supplies.....easy as pie. They have it organized in lines and it was fast and efficient! :) So I come in to honey baked ham and Iam Greeted by jay and his staff this is by far the best dine in I've been to in a long time I will keep comming here bc everybody is so friendly and polite thank u jay and staff my sandwich was delicious Line wasn't that bad (around thanksgiving) and the turkey and ham were great! Made Thanksgiving so much easier! Got a gift certificate for this ham place. The ham was actually extremely tasty, although very expensive, which didn't matter, since it was covered by the gift certificate. But since I had some left over balance on the gift card I purchased 6 side dishes,

                         ## Rank: 14: eegee's | (3.5)
                         **Category: Desserts, Sandwiches, Fast Food, Juice Bars & Smoothies, Restaurants, Food
                         I  dream of a day they will open a venue in Colorado! I know the best thing about this chain is their tasty slushes, and that we get long cold winters, but they are addictive and if we have friggen pinkb***ies we should have an Eegee's!

Those tasty treats go amazingly with booze, and I must get one each trip to Tucson.  The food is why it doesn't get a fifth star, but who goes there for the food?!?

Star light, star bright.............. Love their fries and sandwiches. Possibly best fries in town.

Summer is getting close, grab an iced Eegee's drink and kick back and enjoy. Three standard flavors (Pina Colada, Lemon, or Strawberry) are carried daily with a fourth flavor on rotation changing each month. Always a good quick fix when you have a sweet tooth. The eegees drinks are perfect for the hot az weather. The sandwiches are bomb the fries are bomb and its just a good comforty az tradition that you have to love and get whenever you have a chance. I bought a kids hotdog meal and the original Italian Grinder on wheat bread with a Eegee flavor of the month (Orange Dream, my favorite) for me and my daughter yesterday.  The food was good and fresh, the service friendly, prompt, and accurate, and the rest rooms and seating area very clean.  Keep up the great work! The place was clean, the staff was very nice, my order came out fast, which is all very nice,.............. But.........
I just don't get it, it seems possibly a notch above subway, having been out east, I have no idea why people love this place so much, the sandwiches are not that good!!! Really, they're not, it is the other side of the coin of how people in a lot of eastern cities think chipotle and other such chains are good Mexican food, these sandwiches suck, sorry, also, got a lime "eegees" that was good, yum Oh my goodness what would a trip to the Old Pueblo be without a trip - pilgramage as it were - to eegee's.  Got to have that fruity frosty ambrosia that only Tucson has.  This place is the best and if not driving do yourself a favor and add rum. What is there to say about eegee's, really? It's a Tucson chain that tries to compete in the sub sandwich category of fast food joints, but I'm pretty sure it's their frozen drinks keeping them afloat. The sandwiches are really bland & overpriced... & I don't know if they've changed this by now (it's been forever since I punished myself with an eegee's sub) but they charge extra for cheese & I didn't figure it out until I looked at my receipt. Booo! :(

That being said, if this was just a drink shop, I probably would've rated them four stars. Most of the flavors I tried were at least decent. There were some I thought tasted gross (Holly Berry comes to mind), some that were borderline gross but strangely addictive (oh God, Black Raspberry -- I hated you from the first sip, but how many of you did I buy over the course of the month?) & others that tasted like syrupy versions of what they were supposed to, but I just didn't care for (Tangerine, Strawberry, Mango). My absolute favorite is Watermelon, which is the July flavor. It reminds me simultaneously of a watermelon jolly rancher & the Friendly's Watermelon Slammer, both of which I love. & I won't lie, they're idiots for making it a Flavor of the Month, that liquid mouthsex should be available all year round, yo! (It kills me that I skipped town right before my favorite flavor came around again! Now I'm debating getting some shipped to Boston, to share with my friends here. haha)

I've tried two or three of their cookie flavors, too. The pumpkin spice was great, & I can't remember the others I tried, but I don't think I've had a bad eegee's cookie. hehe. Besides, if you screw up cookies, which are probably baked from a premixed corporate tub of cookie dough to begin with, then that's pretty sad. :3

Anyway, I wouldn't recommend their sandwiches... however, due to it being a local chain, I do believe every Tucsonan (& all curious out-of-towners) should try something from eegee's at least once. A small eegee will probably only set you back a buck & some change, so it's a small risk. Pina Colada, Lemon, & Strawberry are available all year, & their flavor of the month is advertised on their sign & windows, as well as on their website. no wonder why they only have this food chain in tucson!
way too expensive, over price!
for a footlong sub, 2 hotdogs and two popular shaved drink fo $19!
no thank you! I think it's official, I have been to every Eegee's in Tucson, Casa Grande, and the Great Steak in Tempe. They are all very consistent, so I haven't run into one that was not very good over another. Look for the flavor of the month eegee, the italian grinder, and the pastrami call my mommy! Ever since I learned the eegee's have vitamins in them, I now consider them a major part of the food group. A sub is a sub is a sub, but not when it's Eegees! But that's not my focus here. I want to talk about the signature Eegee frozen drink. They are awesome and being

                         ## Rank: 15: Beyond Bread | (2.5)
                         **Category: Breakfast & Brunch, Restaurants, Sandwiches, Bakeries, Food
                         Finally! A last minute BB fix before you leave town. Abbreviated menu but most of the classics. Maddy's Madness is my go-to.  Allow ~15 minutes. Horrible.  I'm a commercial pilot so a eat a lot of airport food.  This place was terrible.  Ordered the Lizzie's Luggage.  It took 15 minutes to make the sandwich.  When I got it, the sandwich was dry and had no Brie on it.  The employees could really care less.  As I watched the customers behind me order and wait and wait and wait for their food, I could tell this place is not a place for me ever again. I've been going to Beyond Bread for as long as they've existed. My daughter even worked there for a long time.

Apparently, the Beyond Bread in the airport is different from the brand we as a family love. I ordered a "Catch of the Sea', which I've been ordering for years.  When I ordered it, I asked them to please make the bread on the side multi-grain, to which the guy said no problem.

The salad came out with no bread and when I asked for bread, a woman with red hair who looked like a manager said that they don't give bread because they're an "affiliate".   She wasn't really the shining example of rich customer service either. She looked like she'd been eating lemons all morning.


Look, Beyond Bread is a household name around Tucson. We all know it and love it. My daughter even graduated high school with the owners daughter. That said, once you've worked so hard to create a great brand, don't change it and don't muck it up over a piece of bread.

By the way, come out & clean the dining area every so often. I sat there for an hour & it was dirty when I sat & nobody came to clean at all. Good place for a quick bite at the Tucson Airport, located in terminal A.

The sandwiches are large and good for sharing, or a big appetite. The Rex's Revenge (chicken, shaved parmesan, lettuce, tomato on foccacia) hit the spot and the bread was fantastic.

Prices are comparable to that of other airport food - $10 for a sandwich. Sandwich was fine. They did let me order a hot sandwich as cold. But service was S L O W. Cashier kept listing the sides in the same mumbled way with every customer, which caused every customer to say "Pardon me?" "What was the 3rd option again?" "Sorry I couldn't hear you." Then she went on break at 11:45am while there was a line to order and an even longer line awaiting food. This meant food prep person had to cashier leaving one person to prep. Strange system... Horrible service at the B gates. One person making sandwiches and more interested in bullshitting with the other staff than making the food.   Exactly what you want when you're trying to just grab some food and make it to your flight. Tasty sandwiches, amazing pretzle bread and yummy deserts. Good atmosphere and great service Alberto greeted us with a smile - and then served up the zesty Tomato Basil soup - and next came the amazing BLT sandwich - SUPER YUMMY!

Had to go on Yelp to check and see if this place has other locations. Happy to see there are more locations in what will be my new hometown...

Had to finish off with cookies - the oatmeal raisin is perfect finish before boarding the flight out of town. I'd suggest planning a visit to this outlet 30 minutes in advance.   I've never experienced as poor of service as I did today.   The food was ok but the 6 people on staff should try to get the food out faster.  28 minutes from order to my grab and run to the gate delivery! Lowkey better than expected...I got a salad and it was fresh and tasted pretty good. They only had one person running the whole place which made the wait VERY LONG. This place is severely understaffed...otherwise the food is much better than I thought it would be. Beyond Bread in Tucson has been a favorite destination of ours for years. But today's experience at the airport was dismal. I ordered an avocado toast with bruschetta and asked for wheat toast instead of white. 20-min. later and after asking twice about my order, I get some avocado slapped onto white bread, barely toasted and a few cherry tomatoes and cucumbers on top. They admitted only after I asked that they were out of bruschetta and needed to make more, which never happened. I wasn't the only one who had to wait 10-min + for their orders. Sandwiches are good and my favorite is their BLT - SOOO YUMMY! Slow service on hot sandwiches. Too slow for an airport. Don't go here unless you have 20-30 minutes for hot food. They one of the few places open at 0430 in the morning. The whole menu is available which is nice. Had Brad's Beef for breakfast. Nice messy sandwich with roast beef provolone cheese and green chilies to start the morning off right. So slow. So ambivalent. So not worth it  if you're going to have food service at an airport you may want to rethink your choice of hires. There is absolutely no sense of urgency or customer service whatsoever. It was like watching sloths at the zoo Great food and great service from all. Liked the chili mac on Th

                         ## Rank: 16: Super Carniceria El Rodeo | (4.0)
                         **Category: Specialty Food, Food, Butcher, Ethnic Food, Imported Food
                         I love your roadside convenience.....Alvernon and Benson Highway, great signage.....
   You need to talk to your employees about what they throw in the dumpster on the west side of your building.  I was driving north on Alvernon on Saturday night 04/29/17 and saw smoke coming from your dumpster.... I thought, maybe it's a smoker at the butcher shop...but, after further review, NOT.....somebody lit your dumpster into a fire....anyway, I saw it, called the 911, the truck showed up about 5 minutes after I called...  However, if you tried to burn your building down, and I foiled your efforts    nah nah nah booboo... Nice little Mexican market.  I picked up some marinated El Pastor, for 2.99 a pound.  The meat was sized nicely and the flavor was great.  It was not overly fatty, which I appreciated.  They also had a nice selection of fresh tortillas.  On the weekend, they will grill your meat for you.  They have a small produce section and a few fresh salsas.  Cheap!  50 cents for cilantro and I picked up these tiny limes that were out of this world.  Mexican sods, aloe drinks, beer and other American refreshments are available in the cooler.  They carry a small selection of Mexican candies too.  They are about 4 aisles of pantry items.  At the check out counter there were huge caramel popcorn balls.  They market is new, but it is also nice and clean.  If you are in the area, I recommend it! Nice meat market and store.  There was a large butcher section, produce, drinks and many others dry goods, spices and tons of tortillas! I went there to get my favorite tortillas Don Juan's (this is closer then going to S. 4th to get my tortillas).  Anyway bought some ground beef to make chili beans and some Chile powder and spices - it was all good! The best in the west.  I live out in Vail and for the past couple years I must hand my hats off to these people. Always fully stocked, delicious selections of excellent food & when I am on the go, I drop in because I know I won't find anything especially right off the freeway like Carniceria Rodeo.  One of the butchers and the ladies up at the front are so welcoming.  Excellent. It was a clean and friendly environment. Before writing this review I tried buying their Carne twice before being biased. The meat and flavor is just sub par. Great environment and people but after trying it twice the Carne asada just isn't very good. I've had way better in tucson. Great little butcher shop! Prices are a little higher than "Super Stores", but justified and worth it, especially if you like supporting local, small businesses. Family operated, all the meat was fresh, tender, & flavorful. Good selection of specialty meats too, eg: beef tongue, liver, sweetbreads, heart, etc. these guys are so cool!.. they will cook your meat on the weekends. Flavorful marinade. we even bought marinade from them to do a huge  cookout one weekend on our smoker.  friendly, clean and good meat selection.

                         ## Rank: 17: Kneaders Bakery & Cafe | (3.5)
                         **Category: Restaurants, Bakeries, Sandwiches, Food, American (New), Cafes
                         To be honest I just came in for a cinnamon roll and a  coffee but ended up getting the fruit tart, it was excellent.  The atmosphere was chill....oldies (think elvis) playing in the background. The staffing friendly enough but the service seemed a little slow as I watched customers getting their food delivered to their table.  I think if you are in absolutely no hurry this would be a great place to  have a coffee and a pastry. BONUS: I was able to get my fruit pastry and coffee for less than a large drink at Starbucks. Awesome little breakfast/lunch spot. This place is special! Great selection of delectables and fun gifts! Lots of mixed reviews here. I was extremely skeptical and held off going into this location because of all of the mixed reviews. Until my brother brought me their delicious turkey bacon avocado sandwich for lunch one day in Yuma. I went in to this location yesterday and was blown away. The staff was super nice. The girl saw and helped me right away. It's pretty much a brand new building. The inside is super clean first of all. They have more than one restroom which is becoming harder and harder to find. They also have a REAL FIREPLACE! How awesome is that!? They offer gift wrapped baskets with their delicious baked goods and have a station set up to make them. They have a wall of fresh baked artisan loaves of bread. They have a cold box with juices, pastries and another baked good display case with even more amazing pastries and baked goods! I had their turkey bacon avocado salad with ranch and a soft roll. I made it a combo and got a small cream of broccoli soup and a berry pomegranate tea! Their drink options are amazing! You can get the regular fountain soft drinks like soda, lemonade, water etc or.... They have 3 teas they brew in house. Green tea,  organic black tea and the pomegranate berry that I chose. They are perfect! Unsweetened so grab sugar if you like sweet tea! It was smooth and fresh not bitter and old! They also have a hot drink option with two different kinds of roasts and decaf coffee and a station with half and half or whole milk and sugar. I got a key lime tart for dessert and it was delicious. Super flavorful and creamy filling with a perfect crust! I will definitely be back and plan on making this a regular stop in the winter for my soup, baked goods and hot chocolate, chai tea or coffee. I highly recommend it! Not sure what went wrong for everyone else but I loved it! Today was my 1st and last trip to Kneaders.  My brother and I both ordered the French Dip and if Jaime o.  thinks this is a good sandwich I don't know what a bad sandwich would be.  It came with parmesan chips and a pickle and cookie.  I won't complain about the cookie but we did not get a pickle and the chips were not parmesan chips and they were stale.  The bread was good but there were 2 little tasteless pieces of meat the grocery story roast beef is much better.  It covered about 1/2 the bread the au jus was cold.  Never again. The decor is charming. That aside, the food was not that great. Half way through my chicken pesto panini, I thought I had been served the wrong order...no chicken. I peeled the bread apart to find a tiny piece of chicken. The artichoke soup was good. I'll stick to Panera or Beyond Bread... visited this morning, went inside to order. I ordered an egg and cheese sandwich (overly greasy and croissant was falling apart) and an iced carmel macchiato (which was then given to me hot instead of iced. the young lady at the register quickly fixed the coffee mistake) but it took 15 min for me to get a sub par egg and cheese sandwich. I had high hopes since the one in phx is amazing. the cinnamon bread is the best. I will give them one more chance here in tucson before my final decision is made. Great food, good prices, speedy service! The sourdough pancakes are absolutely amazing I work Close to this new restaurant so I was happy to have a change of some place to eat unfortunately I won't be going back I had the French dip sandwich nice big piece of bread one thin sliced beef that was overcooked and dried up too bad it would be nice to have some great restaurants close by this just isn't one of them Well meters has a great name is a beautifully clean facility looks more like an gift shop with a couple of pastries. I'll bet their lunches are better than their breakfast because we had to leave ours on the table and exit. It's not impressive and we found it to be unimpressive. It's been awhile since I've had to do that to a place but somebody had to be the winner at the bottom of the list. I suggest the lunch maybe better breakfast forget it My first time here, not impressed.  After being greeted by the surly register lady we went to get coffee only to find all three urns empty.  I reported this to said surly register lady, who was not too worried about it.  An employee finally came to replace the coffee and literally stepped in front of me to fill his coffee up before me ... seriously!?

                         ## Rank: 18: McDonald's | (1.5)
                         **Category: Burgers, Food, Fast Food, Coffee & Tea, Restaurants
                         It's cheap. Sometimes it's tasty. Most of the time the food is old. But you get what you pay for. Childhood staple.

Soft serve ice cream is pretty killer Without question, the worst breakfast burrito I've ever tried to eat. Worse yet, I picked it up at the drive thru and wasn't able to return. It had little filling (eggs/sausage) and the tortilla was totally dried out. I suspect it was a reheated leftover burrito from the breakfast rush. Ugh! Terrible!

Shame on you McDonald's! There's no excuse for serving crap food. This used to be the better location but not anymore. The last few times I've visited have been nothing but disappointing. Tonight was the final straw, though. Why even waste everyone's time asking me what sauce I want for my nuggets if you're not going to give me any? I think the woman taking my order at the drive through was high and I'm not just saying that to be mean. When I arrived at the speaker she didn't give me the usual "Welcome to McDonald's, what can I get for you?" She simply said "what can I get you?" which, I mean, okay, whatever, but I began ordering and I always ALWAYS pause after each different item so the person taking my order can get it put in the system. I said "can I get two McDoubles....a medium french fry-" and she said "wait, what? Two what?"
"Two McDoubles."
"Is that all?"
"Medium french fry"
"Huh?"
"Medium french fry."
"Is that it?"
"And a 20 piece nugget."
"Any sauce?"
"Sweet and sour."
"Huh?"
"Sweet and sour sauce"
"...whaat?"
"Sweet and sour sauce."
"....okay your total is (total)."
I sat in line and waited for at least 10 minutes. That's 10 whole minutes for someone to say "hey, I think I'll put the sauce in that bag now!" But obviously their personal conversations were more important.
The staff here used to be great but since the remodel, they've seriously gone downhill.

Long story short, this is no longer one of those McDonald's where you can drive away confidently after receiving your order at the drive through. You will now have to be "that guy" who looks through the bags to make sure everything is correct and in your bag. This is a nice McDonald's.  It's clean and new with a modernist feel.  The drive through has two lanes, and moves quickly.  The food here is exactly the same as every other McDonalds, which is what we would hope for. The kids play area is tiny. There's flat t.v. with news, which is lame. This is literally the worst McDonald's I've ever been to. Every time I come by here and order coffee, I have to wait over 10 minutes parked around the corner to receive it and often times it's the wrong order. This seems to happen every time without fail. It's so bad here, they installed extra waiting spots in the front of the building and often times there are so many people waiting there's nowhere to wait. Literally the worst McDonald's ever. They need to train their staff better or find new management that can. OK so now I understand why this location only has two stars...I give it one. I go to McDonald's almost every day to get a soda water. Every location charges me 32 cents, except this one which charges me $1.08. I told them that the others charge 32 cents me and they won't price match. Not to mention they are SUPER rude. So, even though it's totally out of the way, and it's a matter of less than a dollar, I will be going to the one on Swan for my drink. Didn't give 5 stars because it was dirty inside but otherwise good food and great milkshakes! And the girl at the register was super nice I wouldn't usually write a review about a McDonald's, but I feel this one deserves more than 2 stars. I've eaten here twice recently and the food was really fresh. I think corporate has gotten more competitive and realize they can't get away with the overcooked and unimpressive food and have done a big overhaul. Good job! Worst experience ever! I will never come here again because everything about this location is so wrong. When we pulled up to the drive thru to get our food we saw a worker just texting on their phone at the food window. Then when the lady handed my mother the food she closed the window before we could ask for ketchup or sweet and sour. We get home and both burgers are cold and the fries were undercooked and cold( even woth the bag closed tight the whole way home). My burger was also smashed. I know its mcdonalds so you get what you pay for but it shouldnt of at least been better than this. Oh people let me just tell you how bad McDonald's was tonight. We went to the drive-through about 5 o'clock just to get sweet iced tea. We are in the drive-through we see the guy trying to get our ice tea poured and he tells the manager who I find out his name is Michael that he has run out of sweet iced tea. So Michael being the genius that he is tells the employee to just fill it up with unsweet tea. It's 5 o'clock in the evening you would think they would need more I'm not sure why they just wouldn't make more or maybe go out to the dining room and pour

                         ## Rank: 19: El Triunfo Bakery | (4.0)
                         **Category: Bakeries, Restaurants, Food
                         Best hamburger and hot dog buns to order! Prices are good for quality of food. They sell real biscochuelos with anise like I remember from my childhood. This bakery was always our go to for breads for tortas and hot dogs. It has never let us down in years! Probably the best little neighborhood bakery you have never heard of unless you grew up on the South side. I frequently stop on my way home from work and will drive from the East side just to get their chips and hot dog buns.

Excellent tortillas, hot dog buns(Sonoran dog style), and pastries, but the biggest reason I go there is for their homemade tortilla CHIPS. They are simply the best chips you can get ANYWHERE and their prices are straight out of the 80's! I also like the friendly, small-town service. Just stopped in for a quick breakfast. The bolitos are delicious, a made a hard-boiled egg sandwich and ir was solid. Bolitos are about the extent of the non-dulce selection that I saw. The empenadas were outstanding. They have a drinks cooler, and a very complete selection of pan dulce. Just had rolls from ElTrunfo in Roswell NM.  I from Tucson. Next time there will go to this bakery to get more bread and pan Duce. The pastries are great....but the place has alot of flies in it. I would go back if they could control the flies. I will just go to supermarket. No words to explain the deliciousness I just experienced. Went here and grabbed a box of goodies for my daughter and her three roommates. I also grabbed some for my husband and me. It was hard to not grab more...but you know, I'm practicing discipline.

A bit of a drive, but worth it for the pastry perfection! And so very inexpensive!! I'm not too sure why this place only has 1 review? Perhaps it's the location. That being said, if you're anywhere on the south side of town it's worth a stop. Don't be afraid. The exterior of the bakery can certainly be intimidating...looks more like an old prison than a place to pick up some empanadas!!

I used to frequent this bakery when I worked at Raytheon since it's on the way so I knew I could stop by en route  to the airport and get some tortillas and empanadas to take to friends in MN.  I don't remember their selection being so small but it had been years since I had been to El Triunfo and over those years I've since visited many other panaderias. I ordered up my dozen empanadas; pineapple, apple and pumpkin, as well as 2 dozen extra large tortillas. They didn't have the tortillas up front so I was worried but the gal behind the counter brought me some from the back that were just made and still warm!!

I knew I was sending this stuff with my husband but I just couldn't help myself and shoved a pumpkin empanada down my throat before I pulled out of the parking lot. Seriously those things are some of the best pastries on the planet. I can't stand pastries that are overly sweet and these were some of the best tasting in Tucson. One of these days I need to have an empanada throw down because I think every time I taste one I say it's "the best". I just love love love them! El Triunfo bakes theirs to perfection with the right amount of sweet and the right amount of pumpkin and pure flaky perfection. Just beautiful!! My friends and I would endlessly look for change in cars, couches and anywhere really to get enough to buy doughnuts here The best pumpkin and apple empanadas. They also have pan dulce, tortillas and bread. Everything is always fresh and delicious! Absolutely love coming here and getting our pastries. Staff is always nice and quick to take my order when I come in.
A true little gem. Ordered 2 5lbs bags of chips for $10 each and they were great!! Tasty and fresh. We also saw that they had Mexican hot dog buns and donuts for sale, if we weren't so much in a rush we will definitely be back to try those items. Customer service is poor! As a local business they should want to make their customers happy and delivery consistency in their messaging when you place orders.  Staff is rude and unprofessional! el pan muy rico y el servicio tambien es. bueno excepto cuando esta esa señora grosera malcriada k habla como macho creo k es la dueña es una grosera me revienta ese mujer solo por k alli mando dinero a mexico y el servicio de ls señoritas de alli son buenas y amables de lo contrario no fuera a ese lugar vieja odiosa grosera Decided to try El Triunfo Bakery one more time. The pastries are great....but I was 2 mice run from the little check cashing booth to the back counter area.  I will just go to supermarket. Thanks to fellow Yelper, Cheryl, we headed out to the El Triunfo Bakery to get some empanadas. To be honest, if it hadn't been for her review I probably would have driven right on by. But I am so glad I didn't!

We ordered up some apple and pumpkin empanadas for ourselves and friends and they were wonderful. I also had to get a couple sugar cookies and thoroughly enjoyed them.
They have a large selection of sweets so be prepared to make some tough cho

                         ## Rank: 20: eegee's | (3.0)
                         **Category: Sandwiches, Restaurants, Food, Desserts, Juice Bars & Smoothies, Fast Food
                         If you are from AZ you know that Eegee's is somewhat iconic ... and if you don't live here or have spent time here you probably have no idea what an Eegee's is.  This joint makes a good sandwich.  Their ranch fries are delicious... but the best part of Eegee's is the Eegee's.  I never tire of these slushy drinks... this month is Mango Tango and I love it.  I did notice that they actually have a version (strawberry I think) that is lower in calorie for those of you that love an Eegee but not all the sugar that I assume are in them. I got no meat and the frys were soggy, I think they may need new management, the guy who was taking our order was very rude, usually it's all in my head and I get over it but, my uncle said the exact same thing. I don't get it. I know it's a local Tucson thing, but it's terrible. The Philly sandwich was bland, bread dry, just yuck. The fries were like the grocery store freezer, room temp and soggy. People talk about the drinks, save time and get an Icee at 7/11. I really love their drinks there something special about getting a different drink every month and not being able to get it for the rest of the year that makes me when I come back thin and healthy relationship I have with their slushies my favorite is definitely the watermelon flavor which of course who doesn't love wherever so they don't are crazy also jungle juice with one of their awesome flavors however when we're talking about the same what you say they're not all that great please do not think that you're going to get the best sandwich out there you're looking for that this is not the place they're overrated and not really worth that much they charge for them I really do like their chili cheese fries though I typically get them with a side of ranch and a side of jalapenos I just give it a little bit of an extra special. I do got to say that the ranch is definitely something else not saying that the fries are something else but if you have the range you could probably have about any kind of Fry and they would taste just as awesome as the ones that they have there it's not about the phrase people it's about the ranch this is a super convenient location for me so of course I go there all the time and would definitely recommend it if you're just feeling like clenching the disgusting first that we get here in Tucson during the summer oh yeah I completely forgot to mention they have a cookie flavor of the month every month as well definitely worth trying they are amazing and if you have to check the trade January which is the pecan cinnamon sugar it is to die for!!! Eegees a local fave , and almost legendary Drink . Food is decent, fries always hit and miss ! Me personally I'm usually in it for the again convenience of a Pastrami or meatball sub & Of course an Eegees ( skinny berry for low carb option).Over all no complaints per say ! DON'T BELIEVE THE HYPE! This is an overpriced Subway w/ Slushys. Being new to Tucson, I saw Eegees all over the place. After reading the reviews, I decided to give it a try. I told the girl at the counter that I had never been here before. She gave me a strawberry Eegee sample & recommended a turkey grinder w/ provalone. She also recommended the fries (apparently  they're the best). The Eegee was good, the sandwich was mediocre, & the fries..... I could have made better at home by myself.  Overall, I think I'll return for the Eegee if nothing else. Came in after work with a couple  of friends. Tony was our cashier. He was very friendly, funny, personable, and had great coustomer service. We weren't sure on the cherry limeade,  but he let us sample it. We were very pleased. Our fries came out quickly and hot! Thanks again for a great experience and service, Tony . Stayed the night and needed something vegetarian to eat, so I found this place. Omg it was so good(veggie grinder)! I'm going back for breakfast before I leave out of town,i also love the early to late hours. After a long busy day I was starving ready to eagerly eat a delicious eegee sub, but instead I was left with disappointment when I found that my whole order was incorrect! I wasn't so disappointed until I called to complain and the employee laughed at me when I was calling to voice my concerns. If you live in Tucson then you know of the famous Eegee. A hybrid between a slushy and an shave ice cone, with Lemon, Strawberry and Pina Colada the foundational primaries of this amazing desert dessert.

Their frys are some of the best Ive ever had, just add ranch dressing.

Turkey or Veggie Grinder, cant go wrong. Along with your icy treat makes for perfect summer days.

We ordered this from San Francisco and everyone in Nor Cal was impressed. The salads shrunk and the price stayed the same, management thinks they're slick. But they are delicious just eishwthey gave you enough for your money. smh Decided to finally try this Tucson staple. They like to advertise things they won't sell you. Not everyone likes ham grinder combos, but appa

                         ## Rank: 21: Bruegger's Bagels | (2.5)
                         **Category: Sandwiches, Restaurants, Food, Bagels, Breakfast & Brunch
                         It's your standard Bruegger's except at the airport behind security. Friendly fast service. Full menu from opening which is nice for those of us think breakfast is important but aren't breakfast food fans. Real bagels!

If you are used to those overly refined things that come in packages and claim to be bagels, you are in for a pleasant surprise.

The bagels themselves get a 5, but I found my sandwich overall to be lacking in substance and flavor.  I was hungry again rather soon after eating this, but I definitely want to buy a couple more bagels to bring back home.

The customer service was superb and the meat in my Sandwich was easily switched out for another item without extra charge or    Hassle. Good news for vegetarians. Love Bruegger's but not this one. On the morning of October 19, 2018. We had an early flight out and just wanted to grab some quick food. They all seemed like they hated their jobs and not one smile not even at each other. No cheese bagels so I asked for sesame and my husband wanted plan. I ordered the two bagels toasted and buttered with egg and bacon. I said no cheese. Not toasted and no butter, and we got cheese and a little extra something else, I'll include a picture because you would not believe it without a picture. Thanks but no thanks. Welp, this makes the third and final attempt to get what I ordered and without the rotten attitude and disappointing customer service.
Foods not bad once they get the order right. The cashier was friendly, line would have went faster if 2 of the 3 on the line were not talking to each other without working at the same time. At least their was one who kept making food as quick as he could. I got the Leonardo di veggie no tomatoe. The bagel was a little dry the light garlic herb cream cheese was yummy and the veggies fresh. There definitely could have been more veggies for being $5.99. Good bagels and super friendly staff! Decent spot for airport. I got the salmon bagel and it came out promptly despite the line. Most of my wait was before I ordered, but once I ordered, I was on my way without just further wait. My sandwich was also pretty good! Bagel tasted fresh and bagel put thoughtfully together. Worst bagel ever.  I asked for a toasted bagel with butter.  Pretty simple.  Got a cold bagel sliced in half with some cold butter on it.  Barely edible and no time to go back to line. The staff showed no urgency for being in an airport terminal so lost a few customers to the bread place.  Thats why I ordered a toasted vagel with cream cheese figured it wouldn't be a hassle. Food was good, price was good but rating it low for the poor, rude morning customer service at the airport location. So glad they put this place in the airport. There used to not be a single option to grab a quick breakfast before an early flight.

This place gets busy though. Don't be surprised to see lines of 15-20 people waiting to get a bagel and a coffee.

Service is usually friendly, but food is typical for Brueger's Bagels. This is not a bad place to get food in this concourse  if you want something different other than Mexican food or burgers. I guess there's really not exciting with a bagel sandwich; but I rather have this- I'm honestly all Mexican food out and I just don't want any more burgers.

The service is impeccable  considering it's in an airport. Yes, it's a little slow but it's  obvious they're making your food and not getting their nails done.
Price wise, the most expensive item is the Salmon sandwich bagel which is less than $9.

I got the western bagel (onion bagel) because it has eggs, bacon,cheese and chock full of veggies.
It is pretty delicious and very satisfying for less than $6.

Good stuff! Ignore the negative reviews and oh, they have coffee. Service sucks had to wait 25 minutes for a bagel and a coffee I had to make then they had the nerve to ask me for a tip.WTF I HAVE A TIP FOR YOU As a native new Yorker who grew up on fresh Brueggers bagels and sandwiches, I was wholly disappointed. This was in a word... gross.,The service was less than stellar or attentive. She didn't listen and wasn't helpful. It's not that hard. It's bagels. The bagels were not right. maybe stale. The sandwiches were sloppy. Complete with hair, smashed bagels that weren't cut well and one of them had a nasty sour spread on it. No care or pride here.,  We threw two of three out. We will likely never return to a brueggers after this. Life is too short. If this is what they've become , then give up and give over your the bagel artisans. If this is how Tucson does Brueggers, they are ruining the reputation. I wonder what it's like to work food service in an airport?  I bet you'd get a lot customers in a hurry, some perhaps without much patience.  I hope people are nice, bc it looks like a  tedious job, honestly.  And then imagine if someone wrote some smack about you in a review, when you're working hard but they thought you didn't smile enough, or look sufficiently chipper

                         ## Rank: 22: Jack in the Box | (2.0)
                         **Category: Tacos, Breakfast & Brunch, Mexican, Burgers, Restaurants, Fast Food
                         Well, this could be biased, since it is the closest place to my house, but I love going here. The service is usually pretty slow, but for a 3 am meal when you absolutely have to eat, whatever. I enjoy the variety of food too. I hate leaving bad reviews. But here goes...

We were the only ones in there, and it still took a few minutes for anyone to even acknowledge or assist us.

Hubby ordered a #1 combo, I got a breakfast sandwich with "no meat" I said. Fries were put in the bag upside down so we were fishing for them. Hubby's buttery jack had sauce literally dripping out of the box and into the bottom of the bag so the bag is all wet on the bottom and there is sauce on my car seat. My breakfast sandwich was covered in bacon. I'm a vegetarian and I'm grossed out.

Bathrooms were also super gross, but they shared those with a gas station so I can't fault them too much on that.

I don't expect gourmet service and food at a fast food place, but I do expect food that I don't have to assemble or disassemble or clean up in order to eat it. Boo! Food is okay, no complaints on that... but the workers cuss.  I don't want to hear cuss words while i eat...
They're saying sh*t, bullsh*t.  Not just once either, they do it frequently.

Place is clean. This is the most ghetto Jack In The box EVER!!!!!
Some ghetto ugly rude girl names Sabrina always has to be in the drive thru messing everything up... You NEED TO FIRE ALL THE GHETTO STAFF AND START ALL OVER The cashier had zero customer service skills. No smiling, not kind, cold and rude. The bathroom was horrid!!! Super dirty, no toilet paper, no paper towels, trash can totally full. If there was any other restaurants around I would have left. Close to my work.  Usually filled with blue collar workers at lunch.  They are quick and very efficient.

They are attached to a Chevron right off the I-10 on Valencia (Southeast Corner). Whilst nothing was wrong with my experience I've come to be accustomed to the Jay-Bo experience and long for it only in moments of personal weakness and to pacify my sourdough satiation. They really are good.

What's new? sweet potato fries is what. They are actually decent as they don't taste as greased up as normal potatoes, but the lettuce on my sourdough was a far cry from the picture, slightly green mostly water and lifeless it stands as a placeholder for what should be something of nutritional value but isn't.

all in all my medium meal was like $8.59? Which seems rather pricey for what I got. I will come back to you jay-bo.. In moments of alcohol recovery and post sickness binges you will always be in my heart(and arteries). Thank you for your consistency because it's not the quality. Adieu

I guess im the only one among my friends who calls it jay-Bo but please let it catch on. Typical good and economical menu BUT the cook was not wearing any head covering; net, hat, cap, etc. Loose hair and making burgers does not keep the health department away. Please use proper and mandated food service gear. There's a white female in her 20's that worked there around midnight on July 4th. I got my order at the window and noticed there was no taco sauce in my bag for my tacos. I kindly asked her for taco sauce and she literally grabbed 22 packets of sauce and handed it to me. I was confused so I took it even though her and I knew I only had two tacos. Kinda rude on her part. Praying she gets some manners because that was ridiculous. Anyways, if she's reading this, thanks for the lifetime supply. Terrible customer service!!!
I will not be going back to Jack in the Box anymore, I had to make 2 trips to this place because they did not give me my order right the first time. After I had gotten home from Jack in the Box I noticed I was missing a burger so I went back and I told the girl that was at the drive thru window what had happened,so she told me to park in the front and they would bring it out to me. Sooo they had me waiting 15 minutes out there, and while am sitting in my car waiting for my food I see employees playing around inside not even doing their jobs I saw 2 employees outside in the front smoking being loud so that made me very angry I had enough watching them play around and I go thru the drive thru for the third time to see what was going on why nobody had brought my burger to me yet and the girl said that the late night crew had just gotten there and that the shift that was there before them didn't communicate to them that someone was waiting on an order they just clocked out and left she also tried saying they had a little rush when in those 15 minutes I was sitting out there they had no customers waiting in line or thru the drive thru window. The management in charge of that store really need to train these employees over again they have terrible customer service and they play too much instead of doing what there suppose too that's why they get paid! I get home like 45 minutes later and everything is cold and nasty my fries were soggy

                         ## Rank: 23: Charleys Cheesesteaks | (3.0)
                         **Category: Restaurants, Sandwiches, Cheesesteaks, Fast Food
                         Their food is really good, but for the size a little overpriced. Wouldn't normally stop here for dinner, but had a coupon. Unfortunately one of the sandwiches had a small gnat fly out of it before my friend could eat into it. Which kind of left him uneasy for the entire rest of the meal thinking that he was going to eat bugs. Their fries were crispy, and they even have a season salt to top it with! I got to the mall early and was a little hungry so I thought I would give Charley's a try.  I got the steak and egg breakfast sub combination.  The sub was good, the hash browns were the small round tater tot kind.  I was hoping that they would have actual hash browns seeing how they have a grill.  So I was unimpressed with the deep fried tater tots. Not much to say about this place. It's a decent place to go for something to eat. The cheesesteaks are certainly not the best (My opinion the best are at PJ's Subs on 6th and Tucson Blvd). The people who work the line there seem they don't want to be there at all. Other than that it's an ok place to go for a bite to eat. Delicious food! Highly recommend it. Good variety of subs on the menu. Are usually order the Eden sir. Just about right for one person. My first thought when I looked up and saw the "sub" shop next to a subway inside the food court of the mall was,"ugh bad planning".   But I reckon every place is worth a shot and see if they are good.
I have the BBQ cheddar Melt: the idea- great   the execution - lacking

I went into the food with an open mind and the sandwich was actually decent enough (except they put lettuce on it - Never seen that done with a philly type sandwhich) So overrall the food was decent for Mall food but having to wait almost 5-10 mins for a soda was a little lack luster. Maybe if the staff had been more focused on keep their customers servered I wouldn't have noticed the lag..... Had to ask for the drink like 4 times.... Never ever ever give a five.. food hot, fresh, good, service is fantastic. Just overall fantastic food employees and service First, this place is called Charley's Philly Steaks. Not Charley's grilled subs. I tried this fast food restaurant in the Park Place Mall for the first time today. I passed by and tried a small sample and it tasted delicious. So I went ahead and ordered the 6 inch chicken Philly cheesesteak that comes with grilled onions, mushrooms, and bell peppers. I also ordered a fry and large drink on the side. Got my fries before my sandwich which was unusual because my fries were just sitting and chilling (literally) while I waited for my sandwich. Was I expected to eat them while waiting in line for the rest of my food? Then I get my sandwich which also came with lettuce, a frozen slice of tomato, and a ton of mayo topped off with a pickle. It doesn't say anywhere on the menu that these extra veggies and condiment would be added to the sandwich and that seems very unusual to add those things to a hot Philly cheesesteak sandwich. When I questioned the employee who put the extra toppings on, he looked very surprised that I was asking him about it and wasn't really sure how to answer, just telling me that it comes with it unless I requested not to have it (which I would have had I known). I went ahead and took the sandwich as is thinking that I don't mind trying something different anyway. After taking a few bites of the sandwich, I immediately removed the pickle, frozen tomato slice, and tried scraping some of the mayo off. I did not enjoy those toppings on a Philly cheesesteak. The bread was very good, fresh, and I thought the chicken tasted pretty good too. But there were hardly any peppers, onions, or mushrooms on it. I literally counted about two slices of green pepper that were cut in half, so 4 tiny bits of green pepper, two very small bits of onion, and about 5-6 tiny pieces of mushroom that could have amounted to one slice of one mushroom. The fries were very bland tasting. The drink was good (can't really screw up a Hi-C fruit punch). Overall, for a $10 meal, very disappointed and don't recommend!! Bomb sandwiches and big crispy fries. I would highly recommend this place if you're looking for hot Sammies. Fast and friendly service and tons of things to choose from. The sandwhiches come in 3 different sizes, small, original, and large, they don't show you what those sizes look like or how many inches, so my suggestion is to get original size it's more like a foot long. It's a little pricey but worth it. So delectable! Dr. gt says these are the best subs eva. That's all you need to know. So remember, this review is of a fast food restaurant in a food court at the mall. It was OK. Did not blow my mind, and slightly too expensive for what you got.

It got the classic Philly Cheesesteak... was not the best one I have ever had, but not terrible. The meat was overcooked - one of the main reasons why this is a three, but it was seasoned well. There needed to be a little more cheese, the veggies were cooke

                         ## Rank: 24: Baggin's Gourmet | (3.5)
                         **Category: Food, Sandwiches, Food Delivery Services, Restaurants
                         This bagging is the best in Tucson. Great service, great food. Very prompt and efficiently made. Decided to give em another try since it'd been a long time. The chicken salad salad comes in a  lousy bread bowl now within a clumsy box UNLESS you specify otherwise, which I didn't know. And they got rid of the breadsticks I so loved! The amount of chicken salad was 1/2 of what it used to be and for $7.49, that's shameful.  As I struggled eating the salad in the box (you can't take it out unless you want to put it directly on the table - blech), my beloved cookie fell on the floor.  That same older lady that seems to always be there with the hunched back sat down to eat near us and she must have told me 10 times that I don't have to get the salad in the bread bowl/box but 'all you have to do is ask to have it in the plastic container". Really? Ok then all you have to do is tell me once. Not 10 freaking times. And did she get me another cookie when I mentioned how mine fell on the floor? You got it. Nope! Sandwiches are great. Bread is always nice and soft, cookies are freshly baked. I just can't find myself coming here too often. It's always really crowded and takes really long to get my food. Also, I think the prices are a bit inflated by a dollar or two. I can get better value elsewhere. Yummy sandwiches delivered for your lunch break. If you haven't, try the bowtie chicken pasta "salad" more like chicken pasta side of creamy goodness! Service was fast, even with a large group ahead of me.  I had the club and it tasted like something my mom would have made, in the good way. Sandwiches at Baggin's are great! I eat here with my mom every so often and we really like the food and the staff.

I get the California BLT on sourdough with a side of the sesame noodle salad. Mom gets egg salad on white. Yes, we both change the basic sandwich to our specification; which is no problem. Every time they are quickly made and taste just the way we expect.

We'll be back here again soon. Next week maybe? Wow, what happened to you Baggins? Been going to this store for years and years. The chicken salad 'salad' is what we always get. This last visit yesterday, the ranch was super thick and not the same but even worse, the amount of chicken salad was much less.  Very disappointed.  Don't know if we will return. Thankfully I always have Choice Greens and Little Anthony's chicken salad in my back pocket. Best restaurant on the planet. Locally owned and woman owned. I am so proud to have been a loyal Baggins customer since 1992. Love you Baggins!
My favorite sandwich is the Sundown Baggins. It is worth every calorie. My Dad loves the tuna salad and the cookies. The spice tea is my favorite drink. Thank you Baggins for making Tucson what it is. I may be newly addicted to the turkey-cranberry sundown sandwich which is delish!  The bread bowl salad was good & ordering online was easy.
  HOWEVER, their side salads seem to be made by people with NO tastebuds.  The Italian pasta is drowning in seasoning & both the chicken bow tie & potato salads were mouth puckeringly SALTY.  I like salt but these had to be thrown away.  We called to see if there was some problem, but were told, nope, that's just the way they taste. We came to this store to get a Catering Menu so that we could order for a "Celebration of Life" family/friends gathering. Right away, the manager, Renee, offered to assist and provided us with sandwich & salad suggestions, how much to order, delivery, etc. When we told her that we would need to order from the Baggin's in Oro Valley, she said no problem. To be customer friendly, Renee called-in our order to Oro Valley Baggin's.  It was great! They delivered our entire order on time, exactly as ordered, and we ordered exactly the right amount. The food presentation was very attractive, sandwiches in baskets, with labels for various salads and sandwiches. Guests were very complimentary; we'll use Baggin's again! Hopefully they don't go out of business! Very quiet! Some of there sandwiches are not very flavorful, but I LOVE the turkey-cranberry one! The Unforgettable Baggins sandwich makes Baggins literally unforgettable! Honestly, I don't know what it is about this place, but every sandwich I order satisfy the craving that is at hand! The hot or cold sandwiches are a must.  The combo meal comes with a side (chips, pasta salad, etc...), an amazing freshly baked little cookie, and a drink! I usually get the pasta salad, with little bacon bits, corn, celery, green onion, corkscrew pasta all lightly covered in oil, salt, & pepper, is perfected.  I'd say it gives Baggins its signature touch.

Now, if you're on a "diet", DO NOT COME HERE.  UNLESS, you have plenty self control and can order the sandwiches in the "half", you'll still be eating about 400 calories worth, which doesn't include the cookie, side, or drink.  Obviously, I'm not talking about the veggie sandwiches, and I'm not sure about the egg sandwich, but I know about 90%

                         ## Rank: 25: Beyond Bread | (4.0)
                         **Category: Sandwiches, Bakeries, Coffee & Tea, Restaurants, Food
                         Years ago I would come here to drink the endless coffee, have a bowl of delicious soup and munch the bread "samples" while I studied as a grad student. I've recently rediscovered my liking of Beyond Bread, what with the great patio and their expanded breakfast menu. Their breakfast sandwiches and omelets are really delicious, and the potato pancake sides are fantastic! Still awesome sweet pastries, too (my faves: the nutty sticky buns and the fruit tart). I know they're mostly famous for their lunch sandwiches, but I think breakfast is where it's at. While the lunch menu is creative and filling, it'll run you around $9 if you stick with water. The vinegar slaw with jicama is the side to go with.
I guess my only complaint is that their crusty, homey bread shreds my upper palatte, especially with the toasted sammies. I always ask for the soft white or wheat, which I know defeats half the purpose of coming here. THREE & 1/2 TO 4 STARS.
    Once again, written about so much, Beyond Bread is about larger sandwiches - you may want to get half-a-sandwich or save the other half for later.  My opinion is sandwiches get 3 stars.
    As to Baked Goods - breakfast bakery items earn 4 stars; great variety and taste.
    Fresh Bread - 4 stars+ for the bread.  Great assortment - truly a wonderful assortment.  Have not had a bad loaf yet.
   good loaf good loaf good loaf.
Just felt like writing that a bunch.
     So 2 locations, a great meeting place, and a go-to-place when planning stuff like a party.
    Thank you. A great sandwich place/bakery! The sandwiches are delicious on all the various fresh-baked bread. The desserts are tempting, but I'm always too full to have any -- one of these days, I'll have to go just for dessert! I've fairly recently discovered that their soups are delicious, as well, especially in a bread bowl.

The sandwiches are big, and most cold items can be ordered in a half portion. They have various sides to choose from -- my favorite is the pasta salad. If you're thinking about pick-up, you can just call in your order and it'll generally be ready in about 10-15 minutes.

Casual atmosphere; you order at the register and take a little label (instead of a number) and find a seat. Your meal will find its way to you shortly. =) Terrible experience. I'm just visiting Tucson, but I'm not disappointed I don't have Beyond Bread at home. I stopped by because it was recommended by a local; I was pretty hungry after a long day at the desert museum, so I decided to check it out. For a simple order of sandwich and soup (caprese sandwich and tomato soup) I waited 40 minutes. No exaggeration. Sat down after getting my drink at 2:58 and left at 3:40. Another woman and I approached the counter to ask about the wait and were told that someone would bring our orders out shortly. And if there was a problem with my order and they'd spoken to me or acknowledged my absurd wait, no problem. That's all I need. However the cashier was too busy flirting with all of his coworkers. When it finally came out I received an obligatory, "Sorry for the wait. Have a good day." No explanation or anything. It's a good thing I checked the bag before I left because they also forgot to give me any utensils, which would've left me drinking my soup in my hotel room. Food was mediocre. Could get the same thing with better service at panera.

They have a large selection of desserts and breads, which the cashier gives you after making your order, so you should be safe with that. Hopefully. I hate to give this a ho-hum review, but honestly my experience was about 2 stars overall.

I went in to put in an order to go. There was only one customer in front of me but the ordering took forever and the line wasn't moving.

So another employee assisted me--The guy who helped me at the register was great.  After placing my order I sat around...
and sat around...
and sat around...
just waiting for my to-go order.  It was 2 cold sandwiches, how long does it take to make them?  Finally about 15 mins or so later I got up and stood by the register. There was a bag on the kitchen counter just sitting there unattended.

A couple of minutes passed and a girl walked over and gave me the bag.

She was friendly, HOWEVER, I noticed her earlier as I was just sitting around waiting for my order and she had been texting on her personal phone as she was standing by the register!

So instead of working and making sure that to go orders were taken care of in a timely manner, she was texting!  I could have been out of there sooner, but instead had to wait for an employee to do her job.

When I got home we ate the sandwiches-- the bread was SO hard I couldn't believe it.  We literally had to eat the bread in a systematic way so we wouldn't hurt ourselves or scratch our mouths as we ate...

I don't understand why people like hard bread. I just don't get it. I guess it's just not for me.

The sandwich was good (except for the hard bread part.)

The customer service

                         ## Rank: 26: Haus Of Brats | (4.5)
                         **Category: German, Specialty Food, Imported Food, Food, Ethnic Food, Restaurants, Food Trucks, Hot Dogs
                         Yum-o! I love finding out where this food truck is going to be, usually through the Tucson Food Truck Roundup.

Basically this is german carb fest awesomeness. It's hard to get good service from a truck in my opinion, but (sigh) I heart food. I had the uber brat, which is a cheese brat, wrapped in bacon, MAKE SURE TO GET THE KRAUT! yum. The menu was small but you know what you were coming for. They had some great traditional mustards to choose from, just wish they were better labled so I know what I am getting into. These ladies know how to please the masses. Only thing I would love more is more kinds of brats!

Faves: berries & cream (not sure what the real name is), uber brat Echte Deutsche Essen. Prima!!!!   I have not had brats this good since I lived in Germany. my wife ran into the truck in Oro valley and brought  some to me as a surprise!!! She said the people at the truck were very nice and from Hanau, home of the brothers Grimm, 30 minutes from where i grew up. i have to find them Very good!  Husband the uber-brat with medium spicy mustard while I had the meatloaf on a roll with sweet mustard.  Both were flavorful and juicy.   I highly recommend an order of potato pancakes with applesauce.  They were thick and delicious! My experience was quite underwhelming. Ate here at a food truck roundup on the northwest side of town.

Food was bland and not very warm. Service was very slow. Price was a little high considering the food quality and service that night.

Not sure if I'd return. As a Wisconsin girl who was raised in German-American culture, I think I'm at least partially qualified to say that these are the best brats I've ever had.

Upon arriving at this food truck, I was greeted by two very friendly people who very promptly assembled my order, a classic brat with sauerkraut. Every aspect of this brat was done right down to the last detail. The brat was tender and juicy, the kraut was crisp, and both were spiced to absolute perfection. The hot mustard was sufficiently hot and flavorful, and it was all served on a large German roll perfect for containing copious amounts of toppings and condiments. I can't wait to try their other menu items, especially the desserts! This place is amazing!! I'm German and my fiancé and I were so happy to find this truck parked outside of a brewery. It's authentic German food cooked by the nicest German women! I've been eyeing this food truck for a really long time, and finally got to try it at the Baja Beer Festival this year. I got the plain brat with sauerkraut and topped it with hot mustard. It was exactly what I wanted. The kraut and brat were delicious. The price was a bit more than you'd expect to pay, but was worth it. The hot mustard was a pleasant surprise. Overall, my hunger was satiated. This place was wonderful.
I'll have to come back and try the uber brat, since you can't really go wrong with bacon and chedder. I absolutely love this food truck! The Uberbrat, Beerbrat, potato pancakes and the schnitzel were all excellent! Growing up in Germany I know exactly what German food should taste like!
Haus of Brats serves the most authentic brats and leberkaese I have had since Munich!
My boyfriend and I try our best to head to as many of their events possible! Jokingly he has complained many times stating that after weeks of not having his favorite leberkaese his "soul just wasn't complete" The best brats served with a smile.  The homemade horseradish sauce is unbelievably great!!  Everything we had was very good.  i can't wait to try everything on the menu. Haus of Brats is delicious, authentic, and clean!
They even have vegetarian options as well as a children's brat.

Seek them out on their website or facebook!
www.hausofbratstucson.com This food truck was cool, caught them at the "Return of the Mermaids" festival and the brats and their sauces were really good. What's more is the lady selling the food had an authentic German accent. I got the überbrat which is bacon - wrapped and it was good especially with the sweet mustard that they have. It's great to be able to have German food as there really isn't a major German restaurant in the area. Will def eat there again once I find out where they'll be next. Curry wurst for the win!!! As a huge fan of German fare and if I may say so a connoisseur ;) I was pretty excited when I saw this food truck outside of total wine. And it did not disappoint! Delicious !
Go find this truck! Chase it down if you have to!
And don't be afraid of the wurst!! Really loved seeing this addition to the downtown scene. Really hip, trendy atmosphere that I think fits in well with the scene.

The selling point here is definitely the vibe and the brats, but I'm still not super jazzed on the eponymous brews. Really like what they're doing in the neighborhood though, especially bringing a new angle of cuisine downtown! Uber Brat fan all the way!! Caught this truck at the Sahuarita Food Truck Roundup and will definitely go back for

Label Query: Is there any inexpensive steak houses?

                         ## Rank: 1: Five Guys | (3.5)
                         **Category: Restaurants, Burgers, American (New), Fast Food
                         Still a fan of this place. Got a very cheesy burger, just how I like it. :)

The staff is still super nice and friendly and always knows how to make their food. After reading some of the reviews. I was fully expecting to be disappointed. As It turns out, this was a pretty good place with pretty good food. It is not someplace I would go out of my way to go to, mainly because of the prices. I thought they were a little steep for this type of establishment.

The hamburger was pretty good and the Fries were hot. Consistent, efficient, A-OK..the reasons you go to a burger chain.

While it certainly wasn't the best burger I've ever had, they do have one thing going for them, OPTIONS, and I love options. Take your basic burger and kick it up thirty-two notches with an amazing array of add ons that you can't find at some of the best restaurants in town. And yes, the burger itself might be pricey, but it's nice to know that you can add anything that'll fit under the bun for pretty much the same price (they have a few specialty options).

The Five Guys craze is certainly not new, so it's not surprising to me to see so many great reviews here on Yelp. However as far as flavor goes, if you're looking for meat that makes a statement, nothing about the patty at Five Guys is going to blow you away. The fries are good, not my favorite, a little too much to consume and a little too salty for me. But the place is good, fairly conveniently located, and the day after some heavy drinking, it helps a guy bounce back. This is a great choice for a Great Burger!!  I would have to say it is better than In and Out Burger!!!  I will be going back!! Pretty good burger. Tons of topping options. Fries were decent. Somewhat expensive. I prefer In N Out's burgers and fries. I'm only giving a 2 star cause this place somewhat reminded me from a burger from back in the day........very over priced not even remotely tasty and dirty as can be. They might also want to make sure they have someone who doesn't have a bad attitude working the cash register. Way overpriced, and way over-hyped.  Went there for lunch, and the place was so noisy, my husband and I could not hear each other talk.  I had to ask the girl at the counter if she was kidding when my total came to almost $20 for each of us to get a burger, reg. fries and a medium drink.  My burger was OK, but hardly any taste to it, and I thought it was small.  I got the grilled mushrooms and grilled onions on mine, but they only have American cheese, when I would have preferred to have Swiss with the mushrooms.  I was very disappointed, after hearing all the hype about the place.  In my opinion, In'N'Out is better for the price, and Monkey Burger is a better burger. To be honest i would rather save the money and go to Inn and Out or just drive farther and go to Lindy's i'm not quite sure why people like this place but maybe i am just picky about my meat and potatoes =]

however one day the bf and i decided to go because the over powering smell they pump into the air mildly smelled appealing that day. .  anyways the burger was dry and the fry's were soggy and way to overpriced for fast food so ya ill pass on all 5 guys five guys burger is a great place for a truly decadent burger and fries. This place you can get a nice burger if you want to throw your cholestrol to the wind! The burgers are very tasty and the fries are good with the cajun spices. The decor is intersting with the primary colored red and white tiles that are arranged in the purina dog chow checkerboard logo,
and the bags of potatoes guide you directly to the cash register like cattle being hurded. but all in all a great place to get a good burger! Well I sure did get my money's worth I can tell you that (we'll get to that in a minute).

This is a burger joint up and up.  Simple menu ranging from burgers to dogs that are pretty tasty.  With your burger or dog you get all your toppings free (Mayo, Relish, Onions, Lettuce, Pickles, Tomatoes, Grilled Onions, Grilled Mushrooms, Ketchup, Mustard, Jalapeno Peppers, Green Peppers, A1 Steak Sauce, Bar-B-Q Sauce, and Hot Sauce).  But that's not what I was referencing earlier.

With my burger I ordered some fries.  I watched them finish my burger order and place it in a bag.  Then a young lady went to the fry bin to fill a carton full of fries and placed it in a different brown bag.  Then she returns to the fry bin, takes a 4 x 6 silver pan that was at least 3-inches deep and fill it more fries and then pours that on top of my fry order in the second bag.  I thought my order would be coming but she stood their talking to a co-worker.  After about 3-4 minutes of waiting I was about to blow a gasket when she went to the deep fryer, removed fresh fries, seasoned them, grabbed the silver pan again, refilled it, dumped it into my bag, closed it and handed my order to me.  Holy cow, a single order was half a bag full of fries. I hope this wasn't a fluke because those fries were pretty damn good

                         ## Rank: 2: Houghton Meat Market | (5.0)
                         **Category: Specialty Food, Meat Shops, Food, Butcher, Seafood Markets
                         The Handsome steaks are the Bomb. Great choice of Meats, Sausages, let's keep this place going. Right on the North East Corner of broadway and Houghton. A Very Clean environment.  Try it You'll Like it ! If you're on the east side of Tucson you should stop by and check this place out! Great selection of steaks, poultry, bratwursts, sauces, and spices, everything you need to make that perfect dinner. Today I picked up some sweet basil bratwursts and roasted garlic peanut sauce. Great prices and super convenient. I would highly suggest stopping by the Houghton meat market! They have sausage that are made in house, lots of premium meat selection, I love there "unique" meat selection (see pictures)! They have what you need for your BBQ from sauces to wood chips! As well as other treats such as premium jelly's ranging to snacks and food for your pet!!!

The staff and owner were super helpful with all the questions I had!!!

You should definitely stop in and check this place out! I have shopped at Houghton Meat Market twice now.  I have tried chicken, streak, and their house-made sausages. Everything has been excellent. I like supporting Veteran-owned small businesses. Came in for the first time and was happily greeted by all of the staff. I took home 4 brats and 2 lbs worth of pork shoulder for $14! The brats were amazing! I highly suggest the Cajun and the cheese/green Chile brats.
It would be icing on the cake if they were able to offer some produce such as lemons/limes, onions and assorted peppers.
I will definitely be returning for some Handsome Steaks! What a gem in our neighborhood. A fun place to shop, top quality meats and custom cuts. The owners have hit a home run!

                         ## Rank: 3: Dickman's Meat and Deli | (4.5)
                         **Category: Specialty Food, Restaurants, Butcher, Delis, Seafood Markets, Food, Meat Shops
                         Best meats in the city, seriously. I get my pork fat here that I grind in with deer meat to make burgers and they come out perfect every time. Also a great place to grab a deli sandwich for lunch. But above all, their "ugly steaks" are without question some of the best steak you'll have for how ridiculously easy they are to cook. Just add salt/pepper, throw it on a skillet for a few minutes and.... you'll see Great selection of cuts, brats, sausages and bacon. Go to the freezer and find some rarities you wont find at your local grocery store meat department like Venison medallions, turtle, frog legs and alligator. The list goes on. They have fresh produce, seafood, cheese, some breads and an array of seasonings. They are known for the "Ugly Steaks". The most amazing cut of beef you will ever have. Prices on some of it is high but worth every penny.
They also have a menu of sandwiches that you can order from. I have not yet tried any of it but considering what I have had from there so far, I would assume it is tasty.
Next time you are in Tucson, go to Dickman's. This place is wonderful!  They made me some chicken breakfast sausage last week.  It was very tasty and I will be back to order more in the future.  All of the staff is very friendly and helpful.

They have a terrific frozen meat case with every kind of game and meat you can imagine.  My husband and I will be returning when we are looking for something exotic.

They offer two steaks and two twice baked potatoes for $15; what a deal!  That is on our to-do list.

They make sandwiches too.  At some point we will have to try their Ruben.  We have heard good things about their sandwiches. so today it was ugly steak on the grill. It was superb...tender flavorful and just sooo good
will return for that one again and again. We have been buying steaks and burger from here for several years and have never been disappointed. Several weeks ago I saw the sign for Ugly Steak Sandwiches on Monday and Saturday. I love a good ugly so we came in on a Saturday and it was amazing. It was fresh and perfectly cooked and I will return for one of these sandwiches. We had a side of Cole slaw and potato salad and both were good. So, if you are looking for a great sandwich stop in here --you won't be sorry ! We love their "Ugly Steaks" for the BBQ.  They literally melt in your mouth. I don't want to buy my meats anywhere else but here. They're that AWESOME. Such an awesome place! Always super friendly. Not to mention they make really great sandwiches. If you want meat, you put Dick(man's) in your mouth. The ugly steaks are some of the most succulent steaks I've ever had (yes we all know how good Kobe beef is). Large selection of meats. Service is excellent and fast. Never been disapointed with what I have bought here. This was my first experience with Dickman's and will not be my last.  I picked up 2 racks of baby back ribs and 6 brats for a small BBQ I was having.  Very reasonable prices for the high quality meats they were selling.  It was definitely worth it to get the meat here rather than somewhere like Safeway.  The guy that helped us out was great and willing to answer our questions.

The ribs turned out great, fall off the bone great, and the brats were a hit as well.  Definitely great quality and I will be back sooner rather than later. This place is a good choice for a sandwich if you are looking for something new.  It is really a deli at heart.

They basically will have you create your own sandwich...you can pick the meats, cheeses, toppings and bread.   Personally, I would rather have choices of preselected sandwiches, but it is still a great place to eat.  Relatively inexpensive.

They also have fruits and vegetables to buy that are often locally grown.  And they also have a great selection of high quality steaks and meats to choose from for your next bbq. As others recommended, the"ugly steaks" and twice-baked potatoes are delicious! Staff is friendly and helpful.

My only minus is their hours. Why are they only open 8 a.m. to 5 p.m. most weekdays? Wouldn't it be more convenient for people to stop by after work and pick up the makings of a great meal for the grill? Does Dickman's expect you to refrigerate the ingredients at work?

I realize Dickman's is partially a deli, but opening an hour or two before lunchtime and closing around typical homemade dinnertime would probably bring them more business. 10 a.m. to 7 p.m. would probably make more sense. Ummm ... it's Re-Dick-ulous! If you are not getting your meat from here you are wrong. I love this place! I work in the same plaza and we always come here for sandwiches. They're always very quick, super friendly, and the sandwiches never disappoint. They are always very busy too, which speaks a lot about how great their food is. My family also enjoys their ugly steaks. Relatively cheap sandwiches for the meat and cheese quality. Thanks guys!! Nice affordable great customer service!  If u r looking for some speci

                         ## Rank: 4: HiFalutin Rapid Western Grill | (4.0)
                         **Category: Nightlife, Mexican, Barbeque, American (New), Comfort Food, American (Traditional), Sports Bars, Southern, Bars, Restaurants, Steakhouses, Breakfast & Brunch
                         Awesome food.  The atmosphere is western and comfortable.  Prices are not inexpensive, but the food quality is worth it.  I had the cedar plank salmon and my husband had the Mexican grilled prawns.  Both were extremely good and the sauteed vegetables were wonderful.  They serve a side of hot blueberry muffins.  There were different because they were cornbread muffins.  Served hot and were they tasty.  Good food, great atmosphere and excellent service.  A nice hidden away treasure. I love HF!   The restaurant is awesome and on Fridays they have The Lost Hombres.  You cannot beat them for a fun Friday eve.  ;-) This place reminds me (in a good way) of the old west theme restaurants my grandparents would take us to back in the 60's and 70's, when we came to AZ for a visit.  Old West motif, comfortable chairs, wait staff in cowboy hats.

The menu covers all the comfort food you might want and is reasonably priced.  The rest of the family swear that the pot roast is fabulous, but I always get the shrimp appetizer as my meal.  Bacon wrapped shrimp with barbecue coleslaw.  Ever since the Costa Brava Restaurant (in Rocky Point, Sonora) burned down, this shrimp is the closest substitute I can find to their signature shrimp dish. Daughter and Son-in-Law recently moved to Oro Valley from California and we have driven by this place both times we have been to Tucson to visit. Thursday (3/29) was our last night in town so we decided to go out. I had checked out the restaurant's website and menu -- the moment we walked through the door and smelled the camp fire we were taken back in time. The decor and ambiance was great.

We were seated promptly and our waiter "Nick" came by to take drink orders, but we opted to stay with water. Our waiter was preoccupied with a large party on the patio (and it looked like they asked for separate checks!!!!) so service was very SLOW. My wife ordered the ribs and was pleased with her dinner, I had the top sirloin with baked potato -- the steak was good (not cooked to order, but edible); the potato was barely warm and should have stayed in the oven for another 30-minutes. Our waiter never came back and I had to resort to asking the bus person for more water, to send the potato back, my plate (with an uneaten potato) was cleared before the hostess brought out the potato (and offered to nuke it if it wasn't hot enough!!!).

"Nick" seems like a good ol' boy type that still has a job because he is the owner's sister's kid and being family can't be fired. Another post referred to him (or some matching his description and attitude) Mr. Gauge due to his ear piercing.

If you are seated in the dining room and this is your waiter, ask for a different waiter!! The food is great! Perfect every time! The atmosphere is also very fun and friendly. Live music on the weekends. I would highly recommend! Fabulous restaurant.  Stop in on a whim. Service was amazing. Looking forward to going back. This place is real good. I had the ribs with mashed potatoes and vegetables. So good! The portions are good size. We all took food home with us. Can't wait to come back to try something different. The staff is very nice also. Went with some fellow business contacts and the food and drinks were both adequate.  Nothing too fancy with the House margarita, but it was Happy Hour, so the price was right.  For apps, the bacon wrapped shrimp, cheese crisp, and potato skins were very good.  The blue corn muffins were to die for.  I could eat baskets of those.  As it was a Wednesday night, they had a fried chicken special which I ordered.  Very crispy skin, which is a plus, and a good portion enough that I had leftovers.  Then had the cookie in the iron skillet for dessert.  Staff was friendly and attentive.  I wouldn't mind going back. The service was very good and the food was delivered promptly. I found the BBQ sauce to be very tasty and complemented the chicken and ribs very nicely. The salads were fresh and crunchy plus the drinks were certainly not watered down. Certainly a good value and at most, $$. horrible!! long wait, bad service, & food is semi-decent but definitely NOT worth the price!! Taste of Texas on cortaro/thornydale is so much better (don't waste your time at this place!). We drove down from Phoenix for the gem show and spent an hour looking for a great steak restaurant.  Well, we found it.  We also found a great wait staff, great portions, reasonable prices, and a hard working hands owner named Mo who wants our experience to be perfect and it was.  If you are lucky, you'll have Adam as your server.  He was everything we needed him to be on our first visit here but not our last.  Great suggestions from the bar as well as a kitchen staff to back up the ensemble with wonderful food.  We were amazed that there was a mere 25 minute wait on a Friday night.  Keep it up y'all. Stopped at Hifalutin on our way to the hotel. Glad we stopped. I had the ribs. They were the fall-off-the-bone type. Came with veggies

                         ## Rank: 5: Pei Wei Asian Kitchen | (3.0)
                         **Category: Chinese, Asian Fusion, Restaurants, Fast Food, Gluten-Free
                         I once liked Pei Wei. The Innovative modular menu and the Americanized Chinese food which was not in anyway authentic but which was appealing. Unfortunately they've gone down the road of pop culture far too much. The last time I went I had Dan Dan noodles which I've had in many restaurants all over the world. Basically it's a slightly spicy ground beef and noodle dish. Pei Wei's version is made with chicken I know that I've had it there before. Only, in its latest iteration it's sweet. This dish is never sweet. And in fact that's the case with their whole menu everything has been sweetened and more sauce been put on it. There are some other touch I don't like for instance if you want water they give you a very small glass. And then there are your fellow diners at the self-service setup station many of which will stand there for a long time hogging the entire setup completely unaware that there's anyone else trying to get in any of the condiments or beverages.
All in all the food is no longer good and the dining experience is not pleasant. Lettuce wraps were great as usual.  Sushi rolls - no - obviously made in advance and refrigerated yuck.  Will return again for non-sushi items. Quality ingredients and lots of tasty sauce options. I was a little sad because the girl who built my bowl wasn't nearly as good as the guy who was working in front of her- I really wanted him to be the one to assemble mine! She was a little skimpy with my choices. All in all I'd go again. I hadn't been to Pei Wei for quite a while but when I went the other day, I enjoyed it. The new lettuce wraps were really tasty and I liked that their soda machine had several diet options. I think the food at Pei Wei is very good, not too pricy, and is served in a casual atmosphere that makes it a great place for lunch! Walked in and was glad to see lots of vegetarian options. I got the ginger broccoli with veggies and tofu and brown rice and boy, my dish was drenched with the sauce. It was too salty in my opinion. Typically, I'd probably send it back but being on an hour lunch, I don't have the time. I just built a wall with the rice and picked at my dish. I've been to several pei wei before and generally like it. I would come back to this one, but I just would not get this dish again.

Restaurant is clean and the cashier was nice. my dad use to take my sister, Mom, and i here and i loved it.

we would always get fried rice and it is the best fried rice i had anywhere. am heading there now. I remember when this place used to be really good.

I mean, it's still busy enough. But not as packed as it once was. There's a reason for it. The menu's updating quite a bit lately, and they've instituted a rewards program. Those aren't things you do when the Status Quo is working. Minor things, such as moving all the plates, napkins, and chopsticks to a single location and having customers get them themselves are other signs that they're pushing towards cost control which... don't look good.

The main manager has stayed the same but the staff have undergone significant turnover. Which makes sense, you employ young part-timers who are on the career upswing, but the folks who used to be there were better trained and were... I don't know, friendlier. Maybe that's personal bias.

The biggest concern though over the last few years is the food. It's chain-restaurant Asian food, so I understand this is not going to knock my socks off. That's fine. But meals are inconsistent, sometimes the sauces aren't even consistent, so each meal is different from the last. The biggest concern however, is with cross contamination of food. I ordered Mongolian Chicken my last visit which had carrot in it (Which is not part of the meal), and this is a minor issue. However, I've ordered Shrimp Pad Thai which has had steak and chicken in it before. Now, I happen to LIKE the idea of a "House" combo where it's a little of everything, but that is a MAJOR problem for anyone with any sort of health concern. I could not with a straight face tell someone that a dish is (Anything)-Friendly here. Not vegetarian, gluten, what have you. If you have a dietary restriction, you absolutely must avoid this location like the plague.

There's other minor things... I order appetizers that come anywhere from a minute before to five minutes after my entree. The kitchen back room smells so strongly of chemicals that the tables nearby are unusable to anyone with a sense of smell, etc. But hey, I still show up once in a while like a sucker, seeing if they figured out how to recapture what they used to have. Being born and raised in Hawaii I have had many great Asian food experiences. So for this being my first time eating at this establishment in Tucson I must say that my overall experience was satisfying. Very clean! Employees are friendly.... food was great! We ordered wings, sushi and a spicy ramen. I have no complaints This is one of those reviews that I'm really hoping someone at management will re

                         ## Rank: 6: Waffle House | (3.5)
                         **Category: Restaurants, American (Traditional), Diners, Fast Food, Breakfast & Brunch
                         I have so missed you Waffle House.  I moved from the South where they are everywhere to California where they are absent.  Thank you Tucson.

The food was as always just greasy enough.  Half of what I love about Waffle House is nostalgia.  I was craving some scattered, covered, chunked and diced, they delivered. I did not care for this place. The service wasn't very good maybe because they were super busy. When my food came out it was cold so I really wasn't thrilled about that. I went for breakfast one morning just because we had never tried it before. I honestly won't be going back. Service is horrible, didn't get any attention for 30 minutes. I would understand this if the restaurant was busy but there was only two other tables and one had already gotten their food. Would recommend another waffle house. Sometimes the basic stuff is still the best. Breakfast fare at it's best. Simple scattered potatoes, good waffle with syrup and a nice slab of country ham with eggs. Wash down with lots of coffee! I got the biscuit which was dense and ok, didn't eat it.

Good service with a smile. Good stuff! This place was great.  The kids loved the waffles. The service was good the food came fast.   We will definitely be back. The establishment is in a sketchy part of town. Seating area is very limited but the food makes up for everything.  I'm pretty easy to please and not demanding when it comes to my food. Hash browns are delicious! Definitely recommend them smothered.

Overall, best breakfast of my life. It saddens me that we don't have these in California. Second time trying Waffle House. Stopped before the UofA vs. USC game. I tried the texas toast melt with bacon & a waffle. It was good and I enjoyed it a little better this time around. Came to this Waffle House branch thinking it would satisfy my cravings for the Hashbrown Bowl, but it turns out to be the opposite. We went in and no one greeted us, and we had to seat ourselves. When we sat down, we had our orders taken by a waitress who was really quiet and could barely hear her. We ordered 2 Hashbrown Bowls, specifically one with Jalapeños. And when it was served none of the Hashbrown Bowls had Jalapeños on them. And the portion was a lot smaller than it was in other branches. I personally don't think a $24 meal for two was worth it at all.

But I could understand if the waitress seemed new and was not very familiar about working in a diner, as I myself had worked in a restaurant before. But the older guy who seemed to have more experience than her could've helped out, but he let the waitress do everything herself. Also, there were flies...EVERYWHERE.

I wouldn't come to this Waffle House branch specifically ever again. Really disappointed. All of the servers were very friendly. They greeted everyone entered. My server checked on me regularly and made sure my coffee cup never went dry. Excellent experience One of the worst waffle houses I've been to. Food was all around bad. Service was bad. Our server an old lady was nice but another server kept having to tend to us because our actual server was just very slow with the other customers. Don't think I'll return. I've eaten at tons of waffle houses and this is by far the worst one. Its like every waffle house. Couple drunks, crappy service,old jutbox. I love Waffle House. Just not this one.

No chili. A lot of vagrants in building. I had to ask for straws. I had to ask for my wife's waffle. I had to go to the counter to get my wife's waffle after basically everyone was done eating.

It wasn't even that busy.

Most restaurants are noisy but in a productive way. The cook kept asking the waitresses to repeat.

Will NOT be back to this one. Food and service was excellent. Friendly employees and clean restaurant including clean restroom. Much better than the Denny's up the road.
And no I didn't have to run to the restroom 30 minutes after eating. I think there are some reviewers who feel a compulsion to let the world in on their bowel habits and issues. I had chocolate chip waffles and cheese hash browns and scrambled eggs and biscuits. Totally customizable in a lot of ways. I was partial to my biscuit/jam/egg sandwich.


24 hours means a whole lot of awesome, and often. I wish they had one in Los Angeles... although it was perfect road trip food. Dirty! The kitchen floor was filthy. There's no way the men's bathroom would have passed code!!!!! Filthy! The air hand dryer was broken and with exposed wires and motor--no hand towels.

Waiters were rushed.

This is a you-get-what-pay-for place. It's inexpensive and the food is basic, in fact the waffles tasted pretty good, but It's just the environment made me loose my appetite.

If you have 5 bucks in your pocket and you gotta eat, then cleanliness and ambiance is probably not a concern.

Hello Tuscon code enforcement.... So bad. Went for a late night meal after a night out... I definitely did not have enough to drink to make this food good. I had the pecan

                         ## Rank: 7: Jackie's Food Court | (2.0)
                         **Category: Food, American (Traditional), Restaurants, Food Trucks, Street Vendors
                         Poor food handling processes. Health hazard - Hand washing sink was blocked, used for storage. Cook did not wash hands after smoking, re-used old gloves, handled his phone with gloves on then handled food. Nas-T! I was in a hurry and must've been really hungry to accept the food.
Fries were greasy and soggy - oil was apparently not hot enough. Totally inedible. Cheese steak was below average (no onion?) and certainly not good for the price. I won't risk it again. Too slow.  Fried food are too greasy - oil not hot enough.  Need more experience.  Owners - get organized - reduce menu - go faster. Cheese steak is the most nastiest thing ever. It made me and my husband sick. It gave me diarrhea. I took 2 bites and threw it away. Recently, my company had food trucks on the premises. For whatever reason, I chose a gyro from Jackie's. It seemed a little pricey at 8 bucks, but oh well. I have lived in the Eastern Mediterranean, so I was prepared to be disappointed. Guess again! Man, it was good! Plenty of traditional gyro mystery meat, just the right amount of tzatziki and raw vegetables....and that pita!!!!!!!!!! It was a fluffy delight and didn't get soggy, despite me taking all afternoon to eat it!  Yes, the fries were a little disappointing, but come on! It's a food truck! I would happily eat this once a week. Please come back, Jackie.... please.... 6.50 for a cheeseburger made with a freezer pattie with no fries included? Even brick and mortar burger joints with homemade patties don't charge that much. Then another $8 for flavorless mahi mahi tacos with a side of canned beans.  That was pretty disappointing for someone who loves food trucks I ordered the cheese steak without the bun, cost me $9 bucks for a small handful of meat that didn't even taste good. The inside of the truck did not clean at all. Never going back.

                         ## Rank: 8: Dickman's Meat & Deli | (4.0)
                         **Category: Specialty Food, Meat Shops, Food, Delis, Butcher, Restaurants, Seafood Markets
                         This place could possibly be a meat-lover's dream store.  They have everything. And I mean, EVERYTHING. Cow, Pig, Goose, Goat, Shrimp, Fish, Bison, jeebus, their frozen meat section is re-donkulus!

They also have fresh prime and choice meets in their case, and at a decent price. (If you are used to the cheap deals from supermarkets, like $4.99 for Rib Eye, this place, is not that) But you will quickly see the difference in quality. Think Costco quality.

Anyway they also have an in-house deli, serving up Boar's Head (one of the top deli meet purveyors in the nation) and they do not disappoint in value, quality, taste, and service.

First off, they have a lot of different types of meats, breads, and combinations to make a perfect meal.  Long list of meats, some premium side salads, and a nice selection of bread, the people are ready to make you a sandwich.

This is where it was a bit confusing, walked in with a family of 6 people, 5 orders, and 5 different people took our order to make. It got confusing because they were finishing at different times, and we were all just going to pay at the end (my mother was treating us out), so it was a bit weird.  Secondly, their soda Machine in the back corner could use a bit of cleaning.  They had some green, tropical drink that looked like it was a local favorite... I personally just tasted sugar/syrup myself.

However, my sandwich was amazing. A regular (2 meats) Bologna, and liverwurst, with all the fixings on a french roll.  It was great.  I can't say for other orders, but mine was great.  My family finished all theirs too, probably means it was good.

Overall, try what you think sounds good, and I guarantee you'll want to come back.  We will definitely be back here when we visit. Well, I decided to visit this establishment after hearing my friends rant and rave about the sandwiches here for several weeks. And because of all that sandwich talk, I was kinda thinking it would be a bit more like Jason's Deli, or something like that...more restaurant than actual deli. Well, its not. Not that its some sort of fault or anything, I was just somewhat surprised.

I ordered a medium sliced bread sandwich (as opposed to a hoagie roll type thing) which was fairly large despite the name. Its a "make your own" kind of thing in that the size of sandwich you order determines how many choices of meats and cheeses you get, but with 2 meats and a cheese, the medium was very good for me and turned out to be quite affordable. They have a number of sides to choose from. Unfortunately for me, they were out of slaw when I went so I passed on that, but the sandwich comes with a fresh kosher pickle. Delish!

I went with I think mesquite chicken and honey turkey...or something like that...with provolone and the works on marble rye. The works consists of red onion, mayo/mustard spread, lettuce, and tomato. Everything was noticeably fresh tasting. I would have liked them to slice their tomatoes a little more thinly, but seriously, this was a really good sandwich. My only other thought was that the bread was very very soft and if I had not eaten the sandwich immediately (which I did), the bread may have absorbed the wetness of the sandwich and not stood up to the test of time.

There is a lot of meat here. No, like...a LOT of meat. I was in a rush and didnt really have time to look around too much, but I can pretty much guarantee that whatever meat needs you may have, these people probably can accommodate. I will definitely be back here for many a future sandwich. A friend and I ate lunch at Dickman's recently, and were impressed with their lunch offerings.

I had a ham and havarti sandwich, accompanied by a side of the three bean salad. Both were very good, and remarkably inexpensive.

My friend had an egg salad sandwich, which he said was quite good as well. His broccoli crunch salad side was the only low point of the meal, as it came bathed in a viscous creamy dressing that was far too sweet for either of our tastes.

I don't often make it this far east, but I will be back to try some of their exotic frozen meat offerings (e.g. venison, ostrich, ox tail, and others). Boy, were we hungry for a great steak and we knew where to go for that! Dickman's!!

Bought a couple ugly steaks, potato salad and macaroni salad. And within a half hour had a fantastic dinner. Those steaks cooked with just some salt, pepper and a little butter on a grill pan are fantastic! They are the best steaks I've ever had. The cold salads were really good too. I wanted German potato salad, but we got there too late to get any of it. Ah well, my fault.

Hubby bought some chorizo and had it for breakfast the next morning with eggs. He certainly enjoys their chorizo too.

We've bought several jarred sides and have loved each one.

Anything we've tried has been great. We'll be back again and again. Great selection and fantastic quality.
Only complaint is they are too far from where I live, but its worth the drive for me

                         ## Rank: 9: Cup Cafe | (4.0)
                         **Category: Breakfast & Brunch, Bars, Restaurants, Food, Nightlife, Cafes, Desserts, American (New)
                         Amazing food.... This time I had the nicoise, and a bite of everyone else's baked skillet, the classic burger, huevos rancheros... simply delicious! Heads and shoulders above the rest for quality ingredients and excellent  execution. There is ambiance, great patio and really excellent cocktails. With family to visit here, I eat out quite a bit in Tucson and for me, this is it. It's not a fast food place, so be prepared to linger and savor the experience... it may take some time to be seated, order and get your food so come with good company and know that they won't rush your table either. Really good food, good service, and good atmosphere. A group of us went there for breakfast after reading the positive reviews online, and they did not disappoint. My only "con" is that it is rather expensive...bagels & lox with a bloody marry was $20 (after tip). Worth the price if you can afford it, though. The few vegan options they have are outstanding for Tucson.  Cauliflower tacos are flavorful if a bit too oily.  Queer steer made vegan is delicious. Breakfast plate with vegan sausage used to always please but lately is lacking in flavor.... Servers have been very knowledgeable about what is and isn't available as vegan on their menu and have also been very accommodating.

BLOODY MARY BAR WITH VEGAN OPTIONS on SUNDAY!!! YES
They have vegan worcestershire sauce! Great food with an inventive, southwest flair.  The heartbreaker appetizer is great: roasted garlic, brie, artichoke hearts, marinated cherries and toast is a wonderful starter.  `Enjoyed the duck ravioli, the chicken tacos, and the steak salad.  Everything was well prepared, great service, and relatively inexpensive pricing.  When downtown Tucson, this is the place to go. I love this restaurant... along with its vintage charm this is one of the best places to go for breakfast, lunch, or dinner. Their menu is very diverse and will be sure to satisfy. I had the Huesvos rancheros and iced horchata latte for breakfast this morning. It was just what I was looking for. Excellent job, and keep doing what you're doing!!! Overall I was let down, I have heard such good things about this place but last night it didn't deliver. My first ever trip to the cup was for breakfast, only I had a piece of chocolate cake and a coffee, both were wonderful. The breakfast looked much better than the dinner we had.

Our dinner server was very timid. He was slow and didn't know answers about the menu, bummer! We started with the tortilla soup. Chef Ramsey never would have let that leave the kitchen. We added a teaspoon of salt which made it edible. The dish names were creative and funny like the heart-breaker, our appetizer! It was good but for four people there was five pieces of bread, and remember the slow waiter, well we got more bread to finish off our starter, later.

The dinners were OK, nothing special at all. The salads were a tad over dressed with bland dressing, the sandwich was good not great. The highlight was the lemon meringue pie. The crust was like buttery candy, the lemon was nice and tart with pulp, and the meringue was done with pounds of perfection. The end result, the price tag was to high for the quality of food served minus dessert.

I dug the atmosphere, the patio, the floor, the old architecture, being downtown, and I will go back for breakfast but I will have to pass on the dinner fare. Staff and clientele here friendly and interesting. Recommend: "Omelette Bar: albeit not really a "bar" in the salad bar sense of the word.  You tell them which of the numerous ingredients you want and they bring it to your table prepared. If the coffee was better I'd rate at Five, but it's your Standard American Restaurant brew, a.k.a. "dirt coffee" as my charming and eloquent wife terms it... Funny-adult story about the 1st time I ate here. Starts with my BFF recovering from a breakup, there's 2 French Policemen on holiday & ends with the heart breaker & chicken satay. I've tried other dishes but always go back to the heart breaker & chicken satay. I wouldn't be surprised if they don't have them on the menu anymore because the funny story happened, well nevermind how long ago it was. It's still a funny story and the food at the cup is still GREAT!!!

Subtracted a star because sometimes service is a little iffy. There's been some occasions when I feel like I've interrupted servers FUN TIME. But, most of the time service is good. Cute little spot right inside of the historic hotel congress... I like it!

Been here for breakfast and dinner. I think I prefer the breakfast but both are good. To be honest I can't remember what I ordered for breakfast but I do remember how tasty the baked eggs my boyfriend ordered were! I'm pretty sure they've won an award so definitely worth trying. For dinner I had the Thai Fisherman's stew. Delicious, but nothing out of this world.

Cup Cafe is perfect if you have someone new in town you wanna show around Tucson. It's not the biggest spot so

                         ## Rank: 10: Pinnacle Peak | (3.5)
                         **Category: Steakhouses, Food, Desserts, Restaurants, Bars, Nightlife, Cocktail Bars, Sandwiches
                         My husband said his ribs were good but were lacking a rich flavor. He ordered mac and cheese because the server bragged about how good it was.  It was edible and just okay. Our salads were smaller than in the past, wilted, and dressings were watery.  My Gardener's meatless dish was a small dish of roasted vegetables covered with two large mounds of mashed potatoes, and at $13.99 I certainly wouldn't order that again!  I realize this is a steakhouse but a good menu even at a steakhouse should have something attractive and fresh, yes fresh, on the menu for those with dietary restrictions.  I think cowboys ate fresh things too! Nothing I or anyone else says about this place will make any difference, so I might as well have a bit of fun with it.

If this was a review of a tourist trap, it would get 4, maybe 5 stars. But it isn't.

This is a tourist trap which happens to serve beef produced by the cattle company that owns it. You don't come here because you think this is actually a good place to eat steaks. If you do, I genuinely feel sorry for you. You come here for the touristy stuff, or because kids like it (this was my particular excuse this time).

I could come up with a whole laundry list of reasons why you shouldn't come here. So what the hell, I'll give you a list:

o Haphazard management of the waiting list. My small group was the only one waiting to eat the night we were there (highly rare occurrence). We were told it would be a "short wait". 15 minutes later, 2 groups of the same size came out of nowhere and were seated before us. It would have been nice if they told us a few groups of the same size were already on the list. But they didn't have buzzing coasters and we did... Conspiracy theory? There is always some problem with people waiting here though.

o The place is huge, but even if there are a million empty tables, they won't seat you right away. I expect this is because they are pinching pennies and not bringing in enough servers.

o The menu does not list the sizes (weights) of the steaks. So you have no idea what you're getting. This is an insult to you, the customer. They expect you to pay for whatever they give you. Fortunately, the price matches what they serve, but why force me to ask?

o The steaks are just chunks of beef. There's nothing particularly redeeming about them other than they are cooked over real fire. But that's the way they are meant to be cooked in the Wild West. Do yourself a favor and get steaks from your local butcher, spend $30 on a cheap grill and some wood, and be happy with yourself for doing a better job than this.

o The salad served in a big dish to make it look bigger than it is, and it's half filled with what I call "iceberg stumps". The stuff they don't use at their other restaurants maybe?

o The bread. The only positive. Barely.

o The beans. The beans are drowning in water, and no bowls to serve them in. I'm supposed to put them on top of my steak maybe? Or in my used salad bowl? How do beans and bleu cheese taste? I'll have to try that next time I have $40 burning a hole in my pocket.

I can't think of any more right now. Maybe next time. a fun place to visit.  We had a great waiter so the food arrive on time and well made.  The food is just okay, I like the room and the old wood planks more than the food. This place is a perfect all night dinner and entertainment stop.  The show was great, nice shops to walk around and the haunted house was a uniques experience and a must see! The food was excellent but why topped off all these great amenities and the food was the service. Even waiters who were not our own stopped to talk and chat which was very nice! Love this place! I'm a little surprised that this is the most popular restaurant in Tucson.  I guess it must the the fun ambiance with the theme-park atmosphere.  But as far as the food goes, it's nothing all that great.  We waited for about an hour for our table, so I had some high expectations for this place since there were so many people waiting.  I figured I should try their signature steak, so I shared the "Big Cowboy" steak which I ordered medium rare.  It was cooked appropriately, but there was not much flavor.  Good thing  they had A1 Steak Sauce at the table.  I happen to really like A1 sauce, but if I want to have a steak that needs steak sauce, then I can make that at home without the long wait.  I wasn't too impressed with the beans and bread either.  The water tasted kinda funny too.  Service was fine, and the ties on the wall were a fun touch. Love this place. My wife has been going here since she was a kid and we come back when we are back in town.
They still cut off your tie and nail it to the ceiling. Our server said they have over 10,000 now.
Ribs were excellent and everyone loved their food. Even the salad dressing was good. were stuffed. Didn't have room for desert. We liked the RC cola, which I haven't had in years. The big pieces of white bread and sides of beans makes it feel like

                         ## Rank: 11: Viv's Cafe | (4.0)
                         **Category: Coffee & Tea, American (Traditional), Food, Restaurants, Breakfast & Brunch
                         My favorite place to eat breakfast,
Has an outside patio, and great food.
Not to mention the prices are very good.
They make you feel like you are part of their family, small town feel, I love this place Eaten there several times breakfast and lunch - consistent good service and good food at a good price. A "hole in the wall" mom/pop type place worth the meal! Great breakfast burritos! We've tried a few other things, and it's just typical diner fare.

The atmosphere is eclectic and noisy. We typically like to order to go, or sit outside. Wow, the prices here are GREAT! I had the guac, cheese and chili omelet  which was good and my bf had the corned beef hash. Good old fashioned diner food and service was very good. The omelets were regular sized not super big like most other places so I wasn't stuffed afterwards which was good.

I recommend! One of the only fast, inexpensive breakfast options in our area, Viv's was a somewhat regular stop for us in the late mornings. Generally cheerful staff, fairly quick service, and inexpensive. Some of the lunch specials have been pretty tasty over the years. Nice patio and dogs are welcomed there. It can be very hectic on the weekends, but the staff keeps things moving. There are lots of "regulars" here, and it's clear they enjoy welcoming those folks, which is kinda cool. Unless you're not a regular... in which case, it can be off-putting.
On the down side... the food quality isn't great. Just about everything is on the greasy, greasy side. Not sure what the omelets are made from... maybe pre-made mix? There's no "fluff" to them. The pancakes are pretty homemade-tasty. The eggs, bacon, hash browns all meld in greasiness. Grilled sandwiches overly-greasy, too. There seems to be a constant shortage of ketchup to go around, which is odd. Wait staff is forever taking from one table to another? Rose was a great waitress, but believe she's retired... some of the other gals are frazzled, but generally efficient. Try out Viv's Cafe.  I met the owner and she was great.  Fantastic service and the food was prepared with love.  Enjoy1 Great little breakfast cafe. Huge chicken fried steak, eggs, AND pancakes for only $6.50. Also had a very good green chile omelet and excellent service despite how busy they were, so I would definitely recommend this place. By far my favorite place in Tucson to go for breakfast and lunch.

Diner style food served by the friendliest waitstaff and managment imaginable. Most patrons who are served at Viv's are "regulars" known by name from the waitstaff and once visiting you'll figure out why.

Small cafe about 30 seats, with a great outdoor patio.  Usually a waiting list on Sunday mornings.

The chicken salad sandwich and french fries are my favorite... it makes me hungry to think about the food there.

Worth the visit... I guarantee you'll be back. Good food and good company. Viv's is just what you need if you like diners and your in the area. After a Girl's Night Out, my friend and I were in need of a good hearty breakfast. I immediately thought of Viv's.
We got right in, which was a surprise for a Sunday. The coffee was hot, the service was friendly, and the price was right.
We ordered the same thing - a plate that had both french toast and eggs! The best of both worlds!
The french toast was amazing! Eggs are eggs, in my opinion. I wasn't too fond of the sausage links, but I think I was just loving the french toast too much!
I love non-chain, local places, and Viv's is on the top of my list! Always stop here on my way up to Mt Lemmon for a motorcycle ride.  They have plenty of choices for your morning eats.  The food always comes out fast and very good.  They wait staff is friendly and do a great job keeping your coffee or water full. Not sure what this is other than a veggie omelet.  Had to take it to go because the first one I ordered, the almost everything, had undercooked sausage so I asked for one w out sausage and I got this lol.  I hate bell peppers and the first one I asked to hold those.  Won't order omelette again.  Will stick to my 2 eggs scrambled and ham. This little place is hidden away and I had passed by numerous times without stopping in.  Out of curiosity we decided to try it and we were impressed at the quality, portions and prices and have been back a number of times now in the last few months. It can get a little busy but usually they are pretty quick. Definitely worth trying. Good place. Similar atmosphere as brawleys.

The bacon tomato cheese omelette and hashbrowns were delish!

My mom enjoyed the chicken sandwhich. I am sad to say I will never go back to this restaurant. I live in the area and was looking for a nice little place to go to after church. My friend and I got there and it was very crowded on a Sunday morning. We put our name on the wait list and waited 20 minutes. We noticed 2 "regulars" came in. They were greeted with a "Hi"....and were soon served coffee while they waited 5 minutes for a table. We were

                         ## Rank: 12: Jersey Mike's Subs | (4.0)
                         **Category: Restaurants, Sandwiches, Fast Food, Food, Delis
                         I went here a while back with my friend, it was actually the day they opened, I live exactly 2 minutes away from here and don't even look at it much these days. The sub I got was good but, for 8 bucks plus tax and only one vegetarian friendly option on the whole menu, I think I will personally pass. As far as quality goes, it was fresh bread, and the sauce they used was oh so good! But the staff did seem a little overwhelmed by the rush of people around Another "Welcome to Subway" assembly line sub shop. Staff was very friendly and polite, and the chicken Parmesan sandwich I ordered was ok but nothing I would write home about. The preformed breaded chicken patties used appeared to be precooked, and the tomato sauce was not that great. The melted provolone cheese on it was the best part of the sandwich. Which leads me to believe since the meats and cheeses are all freshly sliced, that I should have ordered a different sandwich that contained those meats and cheeses. Willing to try it again for the sake of objectivity. So, so very good. Got my free regular sub through a coupon, and I felt like I was on the East Coast for the 10 minutes it took me to scarf it down. Extremely friendly staff, extremely fresh ingredients. This by far the best sandwiches in town. Just like being home back east. Great service and friendly atmosphere! They make some pretty good sandwiches here. They have good quality ingredients. They even cut the lunch meat the way you want it. You can alternate ingredients if you want. I don't like the bread they give you they need to upgrade their bread. It is very flimsy and falls apart. They also need to make french fries. cheese fries would be even better. If your going for a cheese steak I would recommend Frankie's or Luke's instead. Not that their cheese steak isn't good but not as good as other places. It is a nice place to sit down and have some lunch with family or friends. Vegetarians beware... the slicer was not cleaned between cheese and meat slices and my veggie wrap had pieces of someone's cheese steak remnants thanks to poor separation and care on the grill. So sad... I was sooo hungry. Wish I could give 1 star I'm from jersey and there is nothing Jersey about this place. Typical chain, better than subway. Not as good as Jimmy John's, as far as chains go.
The Ravenous Roofer A delicious addition to the neighborhood.  The tuna sub, "Mikes Way" is very good.  The bread is appropriate for a sub and quite tasty.  All toppings were fresh.  I'll be back. I just had to have my Philly fix tonight and once again I had to go with Jerzy Mike's! I lovethis place. I think the
#56 Big Kahuna Cheese Steak
Is the best Tucson! The only reason I even looked at places like Frankie's or East Coast is because Mike's doesn't have any real sides like cheese fries or pasta salad. If they ever bring something for sides other than chips I will never have to go anywhere again. Employees are outstanding here as always. Great job guys. Amazing service and amazing subs! The entire staff was sweet and personable. They made sure our sandwiches were perfect. The big kahuna was delicious! I'm glad the 3 star rating exists for places Iike Jersey Mikes. During my visit I experienced good service for good food at a good price. I got exactly what i expected and was neither disappointed nor overly excited. This is a place I would gladly return to again and again, hoping for better, but not being disappointed with the same as what I received my first time. I was very happy to find out Jersey Mike's has finally made it to Tucson and decided to go for lunch with my wife,and We had two sandwiches one being the original cheesesteak and my all time favorite the club.As I expected they did not disappoint service was great and the facility is ultra-clean. Went in to pick up an order. The surly worker at the counter LITERALLY threw my receipt at me and said, "Here's your receipt." I asked him if he threw receipts at everyone or just me - he said, "Naw." Don't really know what that meant, but I do know that I don't go back to places where I am treated poorly, and I let my friends know, too. Food was mediocre at best. Preserve your dignity and go where the employees can at least be civil. This Jersey Mike's was in terrible condition. My son worked at Mike's in Austin Texas for about a year that place was Immaculate the staff was friendly and inviting.
This location was a mess and couldn't remember the order. They skimp on the meat .This place the counters were not clean they scraped the bread savings back into condiments!
Big disappointment. Have eaten here 2 times. Generous size sandwiches. I particularly like that they slice the meat as they make your sandwich. Real lunch meat! Not the precut stuff you get from Subway. Will definitely return. Sounded like a good idea.   We ordered 2 hot Philly subs.  They were lukewarm,  the buns were cold.  The beef was fatty,  I could not eat the sandwich. Wicked good subs. I got two just in c

                         ## Rank: 13: Yard House | (3.5)
                         **Category: Asian Fusion, Gastropubs, Beer, Wine & Spirits, Food, Cocktail Bars, American (New), Nightlife, Bars, Steakhouses, American (Traditional), Pubs, Vegetarian, Restaurants, Beer Bar, Seafood, Wine Bars
                         Great customer service! Our server Phil was efficient, friendly and attentive. The food was delicious. I had the California roll and it was amazing. It was a unique take on the California roll because it had crunchy rice on the bottom, seaweed shreds, fresh cucumber, avocado, tomatoes, Serrano and crab (not imitation crab, real, juicy crab)! My husband had a skirt steak kale salad which was inhaled in 5 minutes. I would definitely come back!!! This was the worst restaurant experience I have ever endured.  I had a party of 13, so I called the day before and the day of to inquire about call ahead or reservations.  I was told that neither option was available.  We arrived to find a huge table with no diners, but were told it was for a call ahead party. The manager is rude, contradicting of his own words and unprofessional.  He is clearly in over his head and has no clue of how to manage the restaurant or conduct service recovery. He is the mark of an ill-equipped, untrained, disaster of a "manager". When we have dined at Yardhouse the food is mediocre and service is substandard. Do not waste your time.  We selected this restaurant based on a convenient location. However,  there are far better restaurants in the Tucson area. Downtown Tucson has fantastic restaurants with equal pricing and far better quality. Food is great for a chain restaurant. It feels like they try to keep their menu fresh and updated. Of course the draw is typically not the food. Tried their poke nachos and the spicy southern chicken. Chicken spice level wasn't too "spicy." I would order it again just for the sweet potato pancakes and the magical citrusy syrup on the side. Just expect a long wait for weekend nights. Ended up on their outdoor patio as a first available and there was no heat lamp on a cold January night-brrr. This Yard House will get a 5 star just for service alone even! Our waiter was extremely nice and catered to our needs. We had a movie to catch at 10:55pm and got here around 10:05 so we wanted to make sure all our items were going to come out in a timely fashion and he definitely made sure it did. We started with the lobster,crab,artichoke dip and that was pretty tasty. It was very rich though so I asked for red pepper flakes to cut the richness a little. It almost reminded me movie theater popcorn butter. For entrees my husband ordered the Cuban sandwich with mojo dip and I got the shrimp and calamari diablo pasta. Both were very good. The Cuban was like a pulled pork Cuban and went nice with the mojo dip. (Mojo seemed like an assorted blend of Chilies in an au jus) My pasta had jumbo shrimp and grilled calamari with pepperoni and jalapeños with black spaghetti. Super yummy especially cause I love spicy food. Husband also got a beer sampler of all sours that our server helped select and offered suggestions on the order to drink them. All in all service was great and food was good. Our waitress Delanie was excellent! The food was delicious! I love the large comfortable booths.
Great beer selection. Overall great time.
Thanks. The food is much better than you can get at more inexpensive restaurants, but is about right for the price. I almost always get the Mac n cheese, but I also think their lamb burger is one of the best burgers I've ever had in terms of flavor.
I had a lot of issues here when they first opened, but all of that seems to have been ironed out by now. From what I can tell, Yard House provides consistently great experiences now, and time will tell if that is permanent. We only had beers and deserts.  They have Hangar 24 beers on tap.  It was nice to have something from my home town.  Service was great.  The atmosphere was good.  Had a great time!  I think this is the largest selection of beers on tap you will find in Tucson. I guess this place got high ratings because of the liquor.  Since I don't drink and am rating food only, it was very mediocre.  Bland and overpriced.  But I guess if you've had a few beers, anything tastes good.  The staff was friendly and wait time wasn't bad. I don't often share reviews unless I had terrible service or amazing service and in this case... AMAZING service! Visiting from outta town and came here and my server Kandice was marvelous! She recommended the Crispy Brussels Sprouts and potatoes which is excellent by the way! And the gulden draak 9000 quad drink! Definitely will be coming back and I would recommend anyone to come and hopefully you get Kandice as your sever too! We ate here for the first time and really enjoyed it. They have a large variety of beer and the menu is large. We had several different things from the menu and enjoyed everything. I had the Gardien Chicken Rice Bowl which is a veggie version. It was fantastic. The service was very nice and attentive. I highly recommend it! I don't even know why we bother coming here.... Every Friday we come here, and for some odd reason they always skip us and leaving us wait for more than what they had told us! We lov

                         ## Rank: 14: Kens Hardwood Barbecue | (4.5)
                         **Category: Barbeque, Food Trucks, Food, Restaurants
                         Great food and service. We had the brisket, ribs, hot links, loaded brisket fries, and greens. Great flavor and seasoning. We will definitely return. It's rare to find a Bbq place that does great in all three of the main meats mentioned above. I've had lunch here several times on the corner of Congress and Stone and they come through. I've tried just about everything but the favorite is the Loaded fries and it's super filling. BBQ taste is delicious and the the nacho cheese on top seems to have a little spice. I have spent anywhere from $6-12 on a entree with a drink and have never been disappointing. I'd say if you're bored from frequenting the same spots downtown check this place out. Note: address is 5250 22nd St
I travel for work and have had A LOT of BBQ and I have to tell ya, hands DOWN best barbecue in Tucson and some of the best I've ever had(and I've been to Texas, Tennessee, S Carolina).
You will not be disappointed. The meat is super moist and the rub is amazing.
I had a half slab, collard greens and BBQ beans and it was all great. I met Ken and the staff and they are great people! Fantastic in the bricks and mortar location. Huge portions. The pulled pork had nice smoky bark with sauce that wasn't too sweet or hot - mustard seed and other spices give it a very slight pickly flavor. Fries are hand cut and tossed with herbs. Easy parking and comfortable seating inside. Stopped in for barbecue and they were out of ribs - next time I'll get there sooner! The beef brisket dinner was a generous portion of delicious and tender brisket served with a side of tasty sauce. I was glad the sauce was on the side so I could enjoy the taste of the meat. For my sides I had sweet potato fries that were crisp with a sweet coating of sugar, perfect, and green beans which were  tasty and cooked southern style. Father and son owned and operated. Support a great local family! Amazing smoked BBQ, Carolina sweet sauce, family recipe collared greens and potato salad. The last place that was here was Dickies, and it was good- but this place is AH-MAY-ZING!!! Forget McDs- go visit Ken's! We found Ken's at Rillito Racetrack and after 4 hours of golf his BBQ was the tasty and delicious remedy for a hungry tummy! We had the pulled pork and brisket sandwiches. Ken gives you a very healthy serving of meat and ample fries for the price he charges!! The brisket had a very delicious, slightly  sweet taste with subtle brown sugar flavors! The pulled pork was different with more undertones of vinegar in the BBQ sauce but still delicious. We shared so it was great trading bites and intermingling the flavors back and forth! Keep watching their Facebook page as Ken's mobile BBQ moves around town! Definitively worth chasing him down!!! We had pulled pork, brisket chicken, collard greens, beans, mac n cheese and cornbread. All of it was great. The stand outs were the chicken, collard greens and the beans. The BEANS were outstanding. Friendly service, quick and simple. Delicious BBQ real good flavor. Got
Pork and brisket sandwich with some wings and the loaded fries.  Absolutely wonderful better believe I'm going back for more. Good Que. Very tasty. Really enjoyed the food.  Customer service was very kind. Will definitely be eating here again. Haven't gotten into the food truck craze very much. Ken's will make me rethink that. My wife and I stopped by Ken's this past Thursday after reading about it on Yelp, we were looking for real Texas BBQ. Don't expect any thing fancy, or well designed interiors/exterior, but their smoked meats are the Real thing. My wife had pulled pork sandwich and collard greens both of which were true Texas style. I had sliced brisket and potato salad which were great. Next time I'll try the ribs or catfish dinner. We met owner Ken plus all the friendly staff. I had the pulled pork fries. SO delish! Sauce was sweet and had a little kick, meat was perfectly tender and juicy, and portions were HUGE! Been watching their locations ever since in hopes of catching them for lunch again. Ken's barbecue is full of flavor. Kinda spicy but flavor in ever bite. I ordered the chicken wing meal which came with 2 sides. 3 full wings, potato salad, and baked beans and two different types of bbq sauce. Everything was fresh and made to perfection. I loved the experience. Try this place out the food is worth it. Today was my first visit to Ken's on 22nd Street. I am a "review reader", so I read them before my visit and they were mixed but most gave high praise and recommended Ken's.
Well for me it was worth the research and the trip. The folks were friendly and truly concerned that I have a great experience and enjoy my meal.
My wings and fries were cooked perfectly!
Not hard and overlooked. The barbecue sauces were tasty and the hot version was not TOO hot.
Pricing seemed reasonable.
I will come back to try something else on the menu.
Good job!!!
Jo - Vail, Az. It's good, Brisket dinner with Ken's BBQ Beans and Potato Salad for s

                         ## Rank: 15: Food Groupie Cafe | (5.0)
                         **Category: Food, Event Planning & Services, Caterers, Restaurants, Burgers, Food Trucks
                         Good sized burger- loved the toppings on this one- onion rings/bacon and crunchy onion pieces with bbq sauce. You can tell the care and love this family puts into their food- I only wish we had ordered more! Excellent burgers - so much flavor, juicy, delish. Loved the Buffalo chips and fries. Super service. Perfect with the Arizona Beer House brews. I have heard a lot of good things about this truck and the recommendations were right. The food is very good. I had a Bruno Mars which is made from an Ugly Steak sandwich. The Ugly Steaks come from Dickman's meat market. I haven't been yet but hear it's good. The sandwich was topped a garlic/horseradish mayo, blue cheese, grilled onions, and mushrooms. The side I got with this was the Buffalo chips which were like a chip, fry hybrid that is seasoned. This potato thing was great. Eat at Food Groupie if you can it's an awesome food truck. Nice little family business. With the daughters running the orders and making sides, the dad slapping burgers and the mom distributing out a great vibe. The food... wow! Awesome burgers and I almost made the mistake of not getting the Buffalo chips but they steered me right because that was really good with the cilantro ranch dip. I'm definitely going to go there again! Smells great! Tastes even better. Highly recommend. Friendly owners and great customer service. What an amazing food truck! My wife and I stopped at a little brew pub and the Food Groupie Cafe was parked outside. Great service, I'm pretty sure it was a family running the truck. Mom, dad, and two daughters. The burgers were great but the jalapeño poppers were over the top good. If you see them around town you have to give them a try!!! Hefty-sized burgers and fries portions with craft sauces made by the chef. The service is friendly, personable and family owned and operated with the daughters of the owners taking the lead in superior customer service and care both at the window and on the griddle.

They feature a Burger-of-the-Month which never ceases to amaze their followers in and around Tucson where you can find them at taprooms, festivals, round-ups, fairs, and more. They have even been known to setup and serve at no charge to frontline workers.

If you're into supporting local and enjoy a great burger and fries, hunt down Food Groupie Cafe. They are a close-knit business in tune with the heart and soul of supporting Tucson and the surrounding areas, extending help, and trucking along to serve some of theist burgers you'll ever try.

                         ## Rank: 16: Freddy's Frozen Custard & Steakburgers | (3.5)
                         **Category: American (New), Ice Cream & Frozen Yogurt, Restaurants, Burgers, Food, Fast Food
                         I'm not a big fan of their burgers but thats just personal preference. My family likes them. The kids who work there are really nice and very well trained. We have always had really good service and they keep the place really clean for a fast food place! Awesome ice cream !!
Too close to us to stay away for long !
Like places we had in our childhood This review is for the service and not the food. On 7/28 I drove up to freddys at 1050pm to get fries with my sister. I get it. It's late. It's 10 til close. As we pull up we can see the two guys and the girl stare us down. We sit waiting for them to come over the speaker yet they are actively ignoring us. We sat waiting for about 5 minutes for them to take our order. It wasn't until another car pulled up that the girl took our order. Instead of faking customer service, she flatly says "what can I get you". We pull up and pay and no one greets us with a good evening or a sorry for the delay, we are asked if we would like fry sauce, etc. We ask for fry sauce. Maybe another 5 minutes pass and we are given our two fries- without fry sauce. While we love freddys, I don't know if the customer service is worth the hassle at this location. The location on orange grove has never failed me in food quality or customer service. You may be better off making the trip there. Oro Valley, incorporated in 1974, is a suburban town located 6 miles (9.7 km) north of Tucson, Arizona, United States in Pima County. According to the 2010 census, the population of the town is 41,011

And this was the best burger in town. Good food but way too loud inside. The acoustics of the building are terrible. And what's with announcing over that ridiculously loud PA system when your order is ready and you're sitting 10 feet away?? How about bringing the order to my table or giving out a number like Culver's and others. Too bad because the good was good but I won't be back and neither will the other 3 people who were with me. Today, devastation hit our house. We were told our family pet had to be put down.I went to the kids school to pick them up early so they could go to the veterinary hospital and say their goodbyes. The hospital told us we could bring our dog a hamburger and I saw Freddys steakburgers and thought to myself I want her to go out with a great meal in her belly-And what could be better than steak burgers. I had just broke the news to the kids and my son was beside himself. Nothing hurts worse in the world than watching your kids suffer. I tried  to hold it together to order a double burger plain for my dog and felt the need to explain why I was a blubbering idiot.By the time we got to the front window the cashier, who was beyond wonderful told us that the burger was on them and threw in some coupons. At a time when we felt the most broken and in a world full of uncertainty and bad things at every turn, it was a real breath of fresh air to witness such humanity at a time of need! This is our faja enjoying her last meal. Awesome burgers, awesome service! I LOVE their custard!! This Freddy's beats out all the rest! I almost didn't even go in because the smell coming from the trash bin was horrible. Who is the genius who decided to locate that by the front door? Won't be going back. Freddy's are typically the same everywhere they exist, as far as food goes. This particular location had a beautiful view of the mountains and was clean. Restrooms were tidy and stocked and the staff was friendly. If you enjoy eating at Freddy's, I recommend checking this location out! the blonde girl with the red hoodie that took our order seemed to be extremely inconvenienced by us. also the guy making the cheese fries put it in the bag sideways & cheese spilled in the bag. he had to be told by the supervisor to put it in a separate bag, and when i tried to say thank you for telling him to put it in a different bag she completely ignored me. really not impressed with the staffs lack of effort. i'll stick to the one on orange grove. We went on a Friday, perhaps the first day they were open??? It was a mess. Filled with kid's from the school that were just "there" with their food from QT and in the way of paying customers and taking up tables. The food was horrific! The burgers severely burnt and very greasy!!! All of us (3) had serious stomach issues and from what I saw in the kitchen probably why!!!! The pricing is not worth
 the food or wait. Best fast food burger I have had. Staff is always friendly, although service is sometimes a bit slow. Happy to have Freddy's in Oro Valley. Our go to place for Patty Melt. And the best shoe string fries on planet  make s me happy just to think about them Burgers are pricy (formed a little too thin last time ate here), fries are average, shakes are great!!! Go there for the shakes. Great green Chile cheeseburger and excellent friendly service. Love the atmosphere and kids like the ice cream shoppe! I can't get enough of the concrete here. I always get vanilla with ho

                         ## Rank: 17: Fito's Taco Shop | (3.0)
                         **Category: Imported Food, Specialty Food, Ethnic Food, Food, Restaurants, Mexican
                         I've tried this place three times since it changed from Nico's.  The first time I had a bean burrito and the beans tasted funny.  Second time I went was ok but the bacon in the burrito was burnt to a crisp.  Today the tortillas we're overly floured and tasted off.  I specifically asked for the bacon to not be too crisp but it was as burnt as the previous visit.  I am not impressed with the quality of this restaurant and will not be going back. This place is nasty. The food was extremely plain, beans tasted like they came from a can and steak had no flavor. Charged $1 for sour cream and forgot to put it in the bag. Employe wasn't friendly and seemed very annoyed. They didn't offer any salsa or hot sauce either. Spend your money somewhere else. My favorite burrito place on the Northside of town besides Villas but that's more sit and dine. The Pollo Asado burrito here is always on point. Add a little bit of their salsa verde....buddy!! We get burritos here at least once every two weeks and breakfast burritos as well. It's clean and the staff is always friendly. Better than most of the other Mexican fast food joints nearby. Highly recommended!! I was not impressed by the food after hearing so much hype about this restaurant. I got the steak burrito and the only other thing in it was guacamole. Usually when I eat burritos there is lettuce, cheese or something else in it. That's more of my preference but the steak wasn't that good either.

My brother-in-law got the loaded nachos. The amount of toppings was great but there were no chips to eat the toppings with. The place wasn't very clean. I will not be going back! Stay away from this place it's not good Mexican food. Take the time to drive to nicos. The greatest Nico's in town. I have been coming to this location for years now, usually riding my bike or stopping in with friends. If I could take you there now for a Number 1 Breakfast burrito or a Carne Asada burrito, I would.

Soft tortilla, juicy meat, the fantastic Super Fries, fresh Guac, salsa's that enhance, and CHILE RELENO!

I nicknamed it "Roadrunner Nico's," as it's next to the equally awesome Roadrunner Coffee Shop.

The crew is awesome, everything they make is always, consistently great.

If you have never tried Nicos before, or are just in the mood for good Mexican food, Roadrunner Nicos is the BEST. Not sure i quite get the Nicos hype.  It was just OK. I love this place I go here all the time and the staff is friendly and fast! I have not gotten anything I have not liked here and it is one of my favorite things in tucson. Look forward to going every chance I get. Maybe a little pricey for the fact that it's still a fast food kind of chain but hey it's worth it. This review goes for all the Nicos locations. I've been eating at them for years. I put up with their indifferent attitude and unfriendly service. Because the food was good. Over the last year. Their quality has gone down. Not consistent. Sometimes it's good at sometimes it's awful. During my last visit. I ordered the carne asada super fries. When I got home. There was no meat. I couldn't believe it. The main ingredient was missing. I called them up. I was polite. They told me that I was lying. This is still a fairly new location. I've always heard people rave about Nico's and each time I've found myself in one, I've walked out. They just don't "do it," for me. This time, however, my best friend was in the mood for Nico's before we carpooled to work. I decided, fine.. I'll give it a try. The lady at the counter was about as excited to see us as I'd be excited to find a fly in my soup. Nothing got a smile out of her, or prompted her off her stool.

Anyways, we ordered and each got bean burritos. I'm not gonna lie, they were decent, but I still think Chipotle's better. In terms of flavor, they were a little bland. But that's what you get for cheap prices. My friend, well.. she still likes Nico's and I'm pretty sure she's been back since. I, even having lived within walking distance to this location, haven't been back simply because there were better options to try elsewhere.

Nothing awful, nothing great.
I personally give this 2.5 stars. It would have been three, but that heifer at the counter's attitude lost them half a star. The rolled tacos were soggy and my rice was mushy. The flavor of the rice, beans, guacamole, and green sauce are good. If the texture wasn't so bad I would have given it 4 stars. Favorite Mexican restaurant! 10/10 would recommend. This place has some great food, friendly staff and it's inexpensive. I love coming to this place never disappoints always great quality service and food. Whenever I need to get food on the go this is my place! You can order over the phone or in person and food is ready in a fast amount of time. There are plenty of Mexican eateries out there, but this is my favorite.

Okay, maybe not my 1 and only, but I would eat here 1 meal a day if I could (but I can't, because what I order and add to my

                         ## Rank: 18: Charleys Cheesesteaks | (3.0)
                         **Category: Restaurants, Sandwiches, Cheesesteaks, Fast Food
                         Their food is really good, but for the size a little overpriced. Wouldn't normally stop here for dinner, but had a coupon. Unfortunately one of the sandwiches had a small gnat fly out of it before my friend could eat into it. Which kind of left him uneasy for the entire rest of the meal thinking that he was going to eat bugs. Their fries were crispy, and they even have a season salt to top it with! I got to the mall early and was a little hungry so I thought I would give Charley's a try.  I got the steak and egg breakfast sub combination.  The sub was good, the hash browns were the small round tater tot kind.  I was hoping that they would have actual hash browns seeing how they have a grill.  So I was unimpressed with the deep fried tater tots. Not much to say about this place. It's a decent place to go for something to eat. The cheesesteaks are certainly not the best (My opinion the best are at PJ's Subs on 6th and Tucson Blvd). The people who work the line there seem they don't want to be there at all. Other than that it's an ok place to go for a bite to eat. Delicious food! Highly recommend it. Good variety of subs on the menu. Are usually order the Eden sir. Just about right for one person. My first thought when I looked up and saw the "sub" shop next to a subway inside the food court of the mall was,"ugh bad planning".   But I reckon every place is worth a shot and see if they are good.
I have the BBQ cheddar Melt: the idea- great   the execution - lacking

I went into the food with an open mind and the sandwich was actually decent enough (except they put lettuce on it - Never seen that done with a philly type sandwhich) So overrall the food was decent for Mall food but having to wait almost 5-10 mins for a soda was a little lack luster. Maybe if the staff had been more focused on keep their customers servered I wouldn't have noticed the lag..... Had to ask for the drink like 4 times.... Never ever ever give a five.. food hot, fresh, good, service is fantastic. Just overall fantastic food employees and service First, this place is called Charley's Philly Steaks. Not Charley's grilled subs. I tried this fast food restaurant in the Park Place Mall for the first time today. I passed by and tried a small sample and it tasted delicious. So I went ahead and ordered the 6 inch chicken Philly cheesesteak that comes with grilled onions, mushrooms, and bell peppers. I also ordered a fry and large drink on the side. Got my fries before my sandwich which was unusual because my fries were just sitting and chilling (literally) while I waited for my sandwich. Was I expected to eat them while waiting in line for the rest of my food? Then I get my sandwich which also came with lettuce, a frozen slice of tomato, and a ton of mayo topped off with a pickle. It doesn't say anywhere on the menu that these extra veggies and condiment would be added to the sandwich and that seems very unusual to add those things to a hot Philly cheesesteak sandwich. When I questioned the employee who put the extra toppings on, he looked very surprised that I was asking him about it and wasn't really sure how to answer, just telling me that it comes with it unless I requested not to have it (which I would have had I known). I went ahead and took the sandwich as is thinking that I don't mind trying something different anyway. After taking a few bites of the sandwich, I immediately removed the pickle, frozen tomato slice, and tried scraping some of the mayo off. I did not enjoy those toppings on a Philly cheesesteak. The bread was very good, fresh, and I thought the chicken tasted pretty good too. But there were hardly any peppers, onions, or mushrooms on it. I literally counted about two slices of green pepper that were cut in half, so 4 tiny bits of green pepper, two very small bits of onion, and about 5-6 tiny pieces of mushroom that could have amounted to one slice of one mushroom. The fries were very bland tasting. The drink was good (can't really screw up a Hi-C fruit punch). Overall, for a $10 meal, very disappointed and don't recommend!! Bomb sandwiches and big crispy fries. I would highly recommend this place if you're looking for hot Sammies. Fast and friendly service and tons of things to choose from. The sandwhiches come in 3 different sizes, small, original, and large, they don't show you what those sizes look like or how many inches, so my suggestion is to get original size it's more like a foot long. It's a little pricey but worth it. So delectable! Dr. gt says these are the best subs eva. That's all you need to know. So remember, this review is of a fast food restaurant in a food court at the mall. It was OK. Did not blow my mind, and slightly too expensive for what you got.

It got the classic Philly Cheesesteak... was not the best one I have ever had, but not terrible. The meat was overcooked - one of the main reasons why this is a three, but it was seasoned well. There needed to be a little more cheese, the veggies were cooke

                         ## Rank: 19: Freddy's Frozen Custard & Steakburgers | (3.5)
                         **Category: Burgers, Restaurants, Ice Cream & Frozen Yogurt, Fast Food, Food
                         A low budget version of Culvers with higher prices and less taste.

This was our first visit to Freddy's.  The wife and I bought two burgers along with one fry and drink to share.  It still ran us nearly $15.  When we got the burgers, I almost laughed.  "Steak burgers" my a..  The "steaks" were as thin as the slice of cheese, over cooked and had this really weird crispy/crunchy edge on them.  They didn't look like steak at all, but just a really mashed flat blah piece of burger. Hubby and I have came here pretty much every week as of lately. It's usually good and we have no issues. Tonight however the drive thru girl was very snotty and gave us a huge attitude what we told her the Dr. Pepper was yucky and tasted like diet. When you pay 14 bucks for food you really could do without the attitude. A PREGNANT WOMAN'S DREAM!!!!!!! Fresh hot fries with frie sauce or the way I like it with chalula sauce and lemons yummm. Steak burgers so yummy with sident kind of toppings ! Hot dogs!! Chili cheese fries ! Chicken tenders (kinda tiny) ....mand let's not forget their custard OMG creamy delicious in a cone or delicious sundae or milkshake with tons of toppings :) Stopped by for some Custer as they say it's their speciality. Friendly service. 1 scoop of custard @$2.50 what a ripoff. Also it was ok but not worth 2.50. This chain is ripping people off. I'll never go back. Oh BTW the clerk thought is was to much money as well and said others have commented. Had dinner at this fast food place.  I wasn't very hungry so I ordered a grilled cheese sandwich and Kathy orders a single cheeseburger.  I ordered a mint shake and Kathy ordered a coke.

The cheese sandwich from the children's menus (with the addition of bacon and mustard) was out of sight.  Lighted grilled and the cheese dripping off the sides. I would put this in my top 5 best cheese sandwiches from a restaurant.  Kathy's cheeseburger was better the average.

My mint chocolate shake was very good.  Good mixture of mint in the shake.

Kathy ordered a bowl of vanilla custard with pecans, whip cream and a cherry on top.  She rated the custard on par with the custard you get in Milwaukee.  High praise from a custard expert.

And all of this cost only $11.75. Great value for your money. Their burgers and custard are awesome! They are also very very fatty and bad for you. It's a good thing they are all the way across town or else I'd be a 900 lb man. While we love it, it is a bit expensive for what you get. Ice cream sundae, YUM! I had a turtle sundae without the pecans. LOL, I know, no turtles. The custard covered with hot fudge and hot caramel with whipped cream and a cherry was exactly what I wanted and exactly what I got. I got it quickly too from a friendly server.

Just right. Possibly the worst excuse for a burger I've ever had.  I'm not even sure it was made out of meat.  It was so thin around the edges, it was if it was squirted in liquid form onto the grill.  I should've trusted my instincts and not eaten it, because I barely made the drive home to the bathroom.  They also screwed up my sundae order, and it was half melted when they served it to me.  Never again! Absolutely LOVE the veggie burger & fries here!
The Veggie bean burgers are always prepared just right and the topping choices perfect.
I do love those french fries too. - Always crispy and the Freddy's sauce makes a good dip.
All this and a reasonable price as well. Eating here brings me back. Back to a time when life was simple. The burgers are tasty and the custard is definitely worth writing home about! WiFi and plenty of parking are an added bonus to the dining experience! Freddy's does what it promise. Yes, it's fast food, but a step up from McD's etal. I like the thinnish steak burger. The fries are quite good- thin and crisp- and I prefer their fry sauce to ketchup. Only had the custard once and it was OK.  On my last visit, they had green chile cheeseburgers,which is one of my food "holy grails."  I wouldn't swear Freddy's is the best I've ever had, but it was the best I've had in a while. It sounds like they may have this available indefinitely, so I'll definitely give it another try- at least until I can get back to New Mexico. My first time and this Freddy's on Broadway and it was not a good first experience. Staff doesn't know how to explain to new customers how to order what comes with what. The combos or run individually and then they add in anything extra rather than ringing it at the condo price. If you wanted to see like the picture that only happens with American cheese not with the Monterey cheddar that I ordered that I got one ounce of cheese that you can't even see on the burger. Very bad first impression we won't be back.  They need to turn the sound of their public address system down when they call people as it blasting your eardrums they think they're being really cool as a disc jockey at a radio station but it's just annoying. Too much bread and you cannot see the hamburger t

Label Query: Coffee shops nearby

                         ## Rank: 1: Five To Oh! Coffee | (4.5)
                         **Category: Restaurants, Desserts, Coffee & Tea, Sandwiches, Coffee Roasteries, Food
                         I visited around the first week that this coffee chop opened which was in May. I was really excited about it & was not disappointed! Five To Oh! Is quaintly nestled inside Tucson's historic former court house. While charming on its own, the smell of espresso only adds to its antique aesthetic. The customer service I received was welcoming, kind & speedy. My iced latte was delicious & cute! That espresso got me through my day. I look forward to returning with friends & trying more things from their menu! This is such a wonderful spot! The employees were very kind and friendly, and I loved hearing about the creativity and thought that went into their menu. They value other local businesses, and it's neat to see such support within the community. My pumpkin spice latte was delightful, and I will be sure to return! I'm glad to see the historic courthouse area come back to life. A coffee spot here is fantastic. It gives the commuters a place to grab one on the go or something to sip while taking in pleasant surroundings. This adorable little coffee shop is a great place to stop in downtown Tucson, located in the historic courthouse building. The Vanilla Cardamom latte was excellent - but the Sugar Cookie latte less so, especially since they were out of whipped cream. Be sure to take your coffee to-go and walk around the neighborhood where you'll see beautiful Spanish houses with colorful doors. If there's a couple of people ahead of you and only one barista is working, be prepared to wait for 20 minutes. Slow as molasses. There are several other options nearby. i LOVE this coffee shop so much!! i'm so thankful that it's within walking distance of my house, because it's such a hidden treasure i'm not sure i would have found it otherwise. they're located inside one of the historic Tucson courthouses, so it's a beautiful location to walk to and order coffee from.

the coffee is absolutely amazing, our favorite drink to order has been iced americanos with vanilla and cardamom. it's a perfect summer drink! the coffee stands out, and the flavoring compliments it perfectly.

prices are great, service is super fast and friendly, and the coffee is incredible! absolutely no complaints here, coming to five to oh is always the beginning of a great day, and a total treat. highly highly recommend!

                         ## Rank: 2: Starbucks | (2.5)
                         **Category: Coffee & Tea, Food
                         Great location and potentially great ambiance EXCEPT FOR THE YOUNG WOMAN SCRAPING 20 CHAIRS ON THE TILE FLOORS as she cleans tables and scoots chairs. Really prefer fingernails on chalkboard. My family and I were/are so excited that a Starbucks with a drive thru has opened up close to us. We have been here several times now. Both in store and through the drive thru. In store they are VERY slow on getting drinks out. My problem with drive thru - I had a free coffee on my Starbucks gold card and I told that to them. The barista gave me the total for my drinks ( $18 and change) I reminded her that I had a free drink. I then paid and was not given a receipt. While I was waiting for my drinks I asked how much was my total with my free coffee? She replied "$12 something". I asked for a receipt. I then saw that I was charged the $18! I told her this and she apologized and asked if I wanted to go inside and get a credit or use it next time. I did not want to go inside and will get my free coffee another time. What I don't like is I wasn't given a receipt and I feel like she just flat out lied to me. I will now always ask for a receipt since I visit Starbucks regularly. This new location is notoriously slow in preparing mobile orders. They also served my wife burnt coffee beans recently in her eggnog latte. Friendly, but certainly lacking in the production side. Sweet girl great service in the drive through this afternoon, thanks for making my day! How nice to see our favorite barista at this location now. Treighton is awesome!

Older post - Clean and modern. Staff is very friendly. Thought we'd try this new location. Parking is not great! This new location is notoriously slow in preparing mobile orders. They also served my wife burnt coffee beans recently in her eggnog latte. Friendly, but certainly lacking in the

I just tried this store again. As usual, mobile order took forever. The nearby Oracle and Rudasil store is also busy, but doesn't delay in processing mobile orders. ugh I typically pick up large orders from Starbucks. 10-40 drinks at a time. Today was the first day in 12 years that I dumped an ENTIRE order. One quick call to this location and they quickly remade the order. Thanks for the excellent customer service!!!! Clean and modern. Staff is very friendly. Thought we'd try this new location and we were not disappointed. I have had nothing but issues with this location lately. When they first opened they had a good group of people working and they've all seemed to disappear. My first issues came in the form of them never having my food order ready when I ordered through the mobile app. And this was consistent every time. They were an hour late to open one day and made me late to work waiting for my mobile order to be prepared and then when they didn't receive an order through the app that I had placed they begrudgingly and slowly made my drink and then when I told the manager this was the second time in two weeks that they had made me late to work he shrugged and said sorry. I reported all these instances to corporate and the last one they acted like I was just complaining and that these things happen, which I agree that they do happen sometimes...but it has turned to every single time I order from this store. I will be going to another location or no Starbucks at all from now on. The online hours state 10pm closing.  However, we literally honked at the 2 baristas in the store.  We were completely ignored even when we got off the car and stood at the door.  Not even a gesture to say they were close.  So much for genuine friendly service. I came to order a slightly altered drink and explained to Cass (the barista taking my order) that it may sound a little crazy and may not be possible (based on what I was rudely told by another barista at a different location). Not only did cass make me feel completely welcome, she also ensured that my request was really easy and totally doable. I already felt so much better just at the verbal interaction, and they (Cass, and two other Baristas working drive through whose names I didn't catch) took it steps further by covering my drink because of the bad experience I had at a completely different location, and the person who made my drink wrote a sweet note on my cup. They really went above and beyond to ensure I had a great experience, and realize these small gestures can completely turn a person's day around. They've definitely earned a customer for life. I've frequented this Starbucks before but we moved and so other locations have been closer, but honestly the extra 5 minute drive is worth feeling like a valued customer. I tried this location for 4 times by placing mobile orders. They are SO SLOW in preparing my drinks EVERY SINGLE TIME!!! I had to wait in additional 10 mins after arriving. If you are in a hurry, I strongly recommend to AVOID this location. The cream was spoiled and sour, which caused me diarrhea for a whole night. Not to mention that they gave me

                         ## Rank: 3: Savaya Coffee Market - La Encantada | (4.0)
                         **Category: Coffee & Tea, Restaurants, Food, Cafes
                         I love this Savaya location! Amazing customer service and awesome recommendations. My husband has never NOT liked his coffee and I absolutely love the tea! Great coffee and wonderful service!
Baked goods are fresh! Nanette is fantastic! Love Edwin's attitude and customer Came in on Saturday morning to grab a cup of coffee and got one of the best cups of Turkish coffee I've ever had. The atmosphere of the store is amazing and the staff are friendly and helpful. Even did a ground reading! Would always stop by when I'm in the area. Pretty basic coffee shop with some signs of third wave/specialty coffee. They seem stuck in a "we are trying to be a specialty coffee shop but aren't there yet" spot. For the area in North Tucson, it's the best around but I wouldn't be craving to stop by here.

I ordered a cold brew and it was fine. The lady working there was very nice and courteous. The layout of the store is quite small but I like the decor and design choices they made.

If you're looking for a quick coffee stop and this is nearby, this is your place. Never a bad coffee if you go with Savaya. Wish there were more of them out there! The staff is very knowledgable on the coffee topic, I learn something new about coffee every time I swing by. I like to think I am a connoisseur of coffee. I have been drinking it all my adult life and have had it all Folger, Dunkin Donuts, Starbucks, espressos in Europe, even some fancy place in LA my daughter took me to.

This is the best. Every morning I swing by and grab cup of regular coffee. Its strong and flavorful. I even started to taste the different countries and learn more about the flavors. I stopped using sugar, just cream.

I enjoy coming here and parking my car right out front. Quick and easy. The mall is not  open early in morning. Very convenient. I definitely will return to this cozy coffee shop again! I met a very friendly and knowledgeable barista. She explained to me of cold brewed Japanese coffee process. Stopped in here for an afternoon pick me up and my partner and I are so happy we did.

The La Encantada location is super small, so don't plan to hang out there. They do have some tables and seats at the counter but it's VERY intimate.

We weren't sure exactly what we wanted but a few helpful questions and suggestions from the barista led us to the most delicious drink: a coconut iced latte (or something close to that). It was so good, perfectly sweet, not overly so, and just the right amount of creamy. Highly recommend. Yep, this coffee rocks. FANTASTIC tasting coffee. Good service. Lovely location. The only misisng piece to this puzzle is the seating...needs a bit more. There's room outside - put more tables please!!!

There is nothing like the taste of a fantastic cup of coffee - not the bitter over priced stuff that Tucson is used to (oh gee, did someone mention Starbucks???). Savaya offers a lovely, fresh cup full of aromatics for a reasonable price. And they offer it with a smile. Again, a big plus.

Thank you for this coffee shop in my hood. Very nice staff here. Knowledgeable and helpful. We've been here twice and really enjoy the products they offer. Very small little coffee shop. Friendly barrista. I ordered the traditional Turkish coffee, which takes a few minutes to make, but way less time given their technology. Its served in an espresso / tea cup with the grounds settled at the bottom. I drank it the traditional way, black, with no cream or sugar. The barrista also let me try the drip iced coffee which was good too! Fantastic beans. Really good coffee. Friendly staff.

Was a great spot to wait while I waited for an Apple repair appointment. Finally... coffee in Tucson worth drinking. By far the best coffee available. At $2.18 for a cup of joe from rare coffee locales around the world, it is worth a try. Their beans are roasted weekly, so you are sure to get a fresh cup.

2 ideas for management - An unlimited brewed coffee club for $30 and offering pour-over (Chemex) coffee to the menu would bring value and variety to your customers. I moved to Tucson 6 months ago. I stumbled across Savaya coffee. Wow!!! They roast their own organic beans in house, serve organic pastries and most importantly- have the most interesting customers!!!!
The employees really know their coffees and the owner Burc is passionate and enthusiastic about his selection of high quality beans!!!!
A great place to hang out. They do coffee tasting classes at the Broadway location. I'm looking forward to the next class:)
I highly recommend this place !!! Love the Broadway location. I would not come back to this one. My latte to go was pretty bad. Coffee tasted burnt and flat, nothing like the other place... I didn't even drink it. Service was friendly. I grabbed the coffee of the day and it was really good! The staff was friendly and we chatted for a while. The prices are cheaper than a lot of specialty coffee places around but the coffee is just as good so I will definitely be b

                         ## Rank: 4: Cafe Maggie | (4.5)
                         **Category: Cafes, Food, Breakfast & Brunch, Restaurants, Coffee & Tea
                         I just had THE BEST BAGEL I HAVE EVER HAD IN MY LIFE !!!!!! Absolute perfection will most definitely recommend to anyone who will listen and come back for more !!!!!!!! I ordered a breakfast burrito and horchata latte for pick-up. Both were amazing and my order was ready exactly on time, so I didn't have to wait when I went in to pick up the order. Plus, the staff were incredibly friendly. I'll definitely be going in again! I live nearby and have seen a few businesses come and go in this space over the years - and I hope Cafe Maggie stays.

I got the Basic Breakfast with over-easy eggs, breakfast potatoes, sausage, and wheat toast. The eggs were perfectly runny (I HATE overcooked yolks!), potatoes were seasoned and flavorful, and I don't know what kind of butter was on the toast but it was rull good. A fantastic amount of food for $10!

The owner was behind the counter and he was very courteous. Oh, and Cafe Maggie is kid friendly! There's a corner with toys and other distractions for little ones. Nice people, good food, great breakfast Cafe. I took a star off because the food prep was inexcusably slow.   They were apologetic about the long wait but when I asked them why it was taking so long they said it was a busier morning than they were expecting. To me that means they are short staffed and really should have been better prepared for a Saturday than they were. I took off a second star because as soon as my food did finally arrive I was ambushed by flies, way too many for me to enjoy my breakfast. I instead had to keep waving my hands over my food to protect it from the damn flies.  I noticed they did have one fly strip pest control device hanging in their front window, but this problem is so bad they should have at least 4, 2 in each of the large windows.  On a more positive note the food really is excellent here. I had a tofu scramble which was outstanding. The strawberry preserves brought for the toast tasted like it was made in house though I don't know if it was or not. This would have been a really good experience had it not been for the unreasonably slow food service  and the bad fly problem. If they fix those things this could be a 5 star cafe. Absolutely the best thing I've tasted in a really long time. There are very few vegan options in the city for those of us who like Cafe Maggie's owner states "Vegan food that is good in its own right, not because it's trying to imitate mock meat."
Cafe Maggie's new menu features a few different vegan options. I ordered the biscuits with Soyrizo gravy and every bite of this was phenomenal. I didn't even need hot sauce and I'm a hot sauce ADDICT.
I also got the house made Sunflower cookie which is like a freaking 10x better than peanut butter cookie(even though I love PB). And then finally a dirty Horchata, which was just right (not too sweet, but not plain or watery).

I got to speak with the owner and am totally enamored with his business goals, his hopes for the cafe, and the support he's offering to the Vegan community. Everyone who works here is so wonderfully kind.

I can't wait to come back next weekend to try the pancakes! An airy cafe with high ceilings and friendly staff. The cafe au lait (iced) and breve (hot) were perfectly made. There are plenty of seats inside and out, and we felt sufficiently socially distanced. There is cool artwork created by local artists on the walls on the way to the two bathrooms toward the back of the cafe. Great spot to sit for a read or work session. Breakfast all day! Cafe Maggie offers delicious vegan options and gluten-free options. Whether you're wanting sweet or savory, you're all set here. Great prices and great portions. The Vegan Biscuit and Gravy is a delicious soyrizo gravy over a crispy/fluffy house made biscuit. The maple syrup, v butter, and crispy potatoes on the Vegan Pancakes dish made my day. I love a savory sweet breakfast. The Veggie on Focaccia was also impressive. Biting into the focaccia bread with the hummus and veggies was so nice. Soft and flavorful. For the Breakfast Burrito, ask for just potatoes soyrizo and veggies. Flavorful soyrizo, veggies, and crispy potatoes wrapped in a vegan tortilla. The Peach Cobbler and Blueberry Muffin were fresh and not too sweet. So many vegan/gf baked goods!! I used to come into Epic Cafe all the time after getting tattooed, so it was really nice being back in the building and seeing the new name and new beautiful look! Thank you Chander for being so accommodating and kind! Loved this place! The breakfast burrito was great and the dirty horchata was really good as well. Tons of outlets so it's great to study at. The chef/owner was super nice!! This is my new favorite coffee shop in Tucson. One of the better breves that I have had, and I believe it's because of the coffee brand and roast used for their espresso.

The atmosphere is perfect, it reminds me a coffee shop that I'd find in downtown San Diego, Los Angeles or Salt Lake City. I guess what that me

                         ## Rank: 5: Donut Bar Tucson | (4.5)
                         **Category: Donuts, Food, Wine Bars, Nightlife, Bars, Beer Bar
                         Boyfriend decided to get some treats today and I just so happen to want to try out the new donut place. We ordered the grilled cheese, Monte Cristo, mud pie, creme brulee, and the Homer Simpson. Surprisingly we agreed we like the mud pie the best. Just creamy chocolate pudding topped off with cookie crumble on a savory donut. Was just so delicious! Second is definitely the grilled cheese. Definitely dip it in the sriracha mayo.

 It cuts through the ooey gooey cheese and good ole glazed donut. Homer is a classic pink frosted donut while the creme brulee is more on the play of texture with the caramelized sugar on top. Monte Cristo was yummy, but boyfriend thought that it was filled with too much jam and brie. Overall it's a great place to try unique donuts if you happen to be nearby and hungry, or just wanting to eat something new. This was my first visit to Donut Bar after drooling over their pictures on Instagram and it was so worth the wait! They had a huge variety, and their donuts are good sized and taste amazing! Our fam favs were the monte cristo, maple bacon, and  the red velvet! Friendly service and easy location to access for quick pickup! Try them out! First visit to Donut Bar. Impressed with
The concept. I ordered the Cake Better and Maple Bourbon. Only tried Cake Better, saving maple for tomorrow. So impressed I went back later and bought a shirt to advertise. Friendly staff and nice atmosphere! These poor three; Michael, Brad and Mary. For Father's Day, we came in for a special treat for my husband. Brad, Michael and Mary were the only three manning the place as people had called out. They were super flustered and were trying their damndest to answer the phones, curbside pickup, pre orders, door dash and those coming into the shop. For being a holiday, especially for men who LOVE donuts, I believe they did a stellar job. Not to mention the mud pie, the Father's Day donut and the ultimate donut - the monte Cristo we're freaking amazing!!! These three deserve kudos, especially for apologizing every second they got. We will absolutely come back for seconds and thirds!!! Best donuts around! You guys, seriously great donuts. Last night a few friends and myself were walking back to the parking garage from dinner and noticed Donut Bar. I haven't been  downtown in a couple of months and didn't know it had opened. We decided to go in and we're helped right away and the staff was wonderful answering any questioned we had. We each got something different, a total of four donuts and we all tried each other's. Every donut we had was perfection. Perfectly fluffy, perfectly topped, perfected cooked. I've been to a few local donut shops in town and have never been impressed with the selection or quality. I'm so happy to say this place had PERFECT donuts.

I might have to start coming back downtown more often. Walked in on a Monday morning, and the girl behind the counter who helped me choose my donuts was so chipper! Which is not usually expected for a Monday morning! I kept changing my mind with which donuts I wanted and the girl was still super sweet! The donuts are a whole experience, from being in the shop and seeing all the decor and beautiful pastries, to the tastes and smells of the donuts! Great quality of ingredients ! Best donuts in town! I would eat them all the time if they had the same nutritional value as fruits and vegetables!! The Homer donut is a must. When we want a really good donut, this is the place to go.  It can be a little tricky when it comes to parking because it's downtown. But worth it even if you have to go for a little walk!  really good donuts!! Went inside store and was welcomed. Didn't have to wait since no one was in the store just yet. Donuts were amazing! I was recommended a few and would definitely go back for more! Best and biggest donuts ever! I had a maple bar which was more like a log! Huge and deeeeelicious! Personally loved the bar tender and the idea behind the donut and the beer. I wanted coffee but when I arrived to the location and realized it was beer and donuts forget the coffee. The donuts were huge!!! The beer was right. Display amazing and the location super clean. The staff was attentive. We were greeted immediately and there was only one lady in front of us. We over heard that she had told them it was her daughter's birthday and wanted something with sprinkles. So they were joking around and this donut expert really went in the back to add specialized sprinkles to the donut for her daughters birthday. That donut definitely made that girls day! Then when it was our turn they made their way down the donuts to describe each one. Like presenting a series of art. Yumminess upon yumminess!! We couldn't ignore the suggestions. I loved the whole experience. We took our donuts home because social distancing (which is fine by me). It was delicious but it was also just a really great experience thanks to the men behind the counter. Donut Bar is a good spot for a tas

                         ## Rank: 6: Ren Coffeehouse | (4.0)
                         **Category: Cafes, Food, Juice Bars & Smoothies, Restaurants, Coffee & Tea, Bakeries
                         Great new coffee house! They have a variety of sandwiches and smoothies, and their coffee is delicious. It's in the St. Phillips plaza which is a great location, there's always something cool happening around here! Also, it's a pretty decent study spot if that's what you're looking for too. Literally a hidden gem, tucked away in St. Philips plaza.  I have simple standards for a coffee shop: treat me like a human being, and provide me with a tasty drink. Ren has exceeded my standards with their friendly service, and vast menu. I have yet to try their food which only sounds delectable, but I am on the Keto diet, which brings me to this...
They have a Keto friendly drink called "the fat americano." This drink is my new guilty pleasure! They have nitro cold brew, on tap, which provides a superior jolt.  It's my go-to pre-workout drink.  Ultimately, their cortado is my favorite beverage, in all the coffee shops in Tucson. Ren Coffeehouse is my new go to spot for a delicious coffee or quiet spot to read/study. They have everything you want...coffee, healthy food, and easy parking. My drink of choice is their Fat Americano. Love! I had the nitro cold brew and it was one of the smoothest and best tasting I've had.

The outside area is really pretty and green, inside is cozy and good for hanging out. Cappuccino was good! Ambiance is lacking energy, bake goods are not home made and uninspiring, staff is mildly friendly, and prices are high!


Great location that if run correctly could give the lack luster Caffe Lucci a run for it's business, but unless they step up their game I don't think this will happen?

Tip;

Hire a good baker and add some nice hip music that will make all the difference!

Otherwise I don't see this lasting with current management? Sorry I have only been here once but apparently it was on the soft opening. The staff was friendly and helpful. I like coffee but I don't usually find one cup different from another. I had an Americano with coconut oil and it was the best cup of coffee I have ever had. I can't wait to go back! Love this place! Best Breve Latte! The  scones are yummy  and it's all organic . Menu looks good for lunch too.... definitely making this place a regular throughout the week. Stopped in between meetings. Nice local coffee shop vibe. Good tea and the Green goddess sandwich was delicious! Wifi. Great coffee and coffee shops are all about attention to little details, and Ren nails it.

Their coffee, food, and location are all excellent. The staff is polite and nice.

I am a coffee snob, and I can say the coffee is made correctly to the highest standards, with the finest coffee, methods, and equipment. Drip coffee is easy to mess up, but Ren's is perfect. Their nitro coffee is amazing on hot days. Sometimes they offer an agave whip cream to add on top, and that makes it divine.

The food is healthy and flavorful. I love the avocado toast with a poached egg on top. They use Barrio Bread, which is fitting, since again, Ren does not skimp on any details.

I also love the protein bars, especially the almond one.

Highly recommend. Went here this morning looking for a place to study. It's a nice little shop in St. Phillip's plaza with a nice patio. There's a few spots with outlets accessible on the inside and nice comfy chairs if you're just there to read or sit and chat. It's a little on the loud side for my preferences, but it is a coffee shop and not a library.

I got the macchiato, which was good, but a bit smaller than I'm used to getting for ~$4. I also got the smoked salmon toast, which was good, but nothing special; a little on the pricier side at  nearly $12 for one toast. I think I'm just a little peeved that the price wasn't listed (that I remember seeing), which is just a pet peeve for me.

Overall, good experience, but, as a broke student and to make this cost effective, I'd stick to the baked goods and cold brew. Ren Coffeehouse is my new go to spot for a delicious coffee or quiet spot to read/study. They have everything you want...coffee, healthy food, and easy parking. My drink of choice is their Fat Americano. Super cute little coffee shop filled to the brim with bicyclists fresh off the Rillito bike path. There were also people on their computers and friends meeting. I wish I could rate this place 4 stars but they don't carry lemonade. What coffee house doesn't have lemonade!? This one. I really wanted an Arnold Palmer but sadly it was not meant to be. They had a couple iced-tea options. I went with a citrusy one. I found the flavor weak and not very citrusy. Perhaps it was because she had to brew a new batch for me and it needed time to steep. The food looked ok, a couple salads and sandwich options. Please put lemonade on your menu :'(
Also another note, in the 1-2 hours I was there I saw no one busing. Several dirty plates and cups were littered about. It didn't seem like anyone working there cared about the cleanliness or appearance of the coffee house. Cute

                         ## Rank: 7: Starbucks | (3.0)
                         **Category: Coffee & Tea, Food
                         I always come to this starbucks because I live on this side of town. The people there are super friendly. Compared to the other Starbucks I been to throughout Tucson, they are the only place that make my drinks how I want it. Everywhere else I have been don't make it quite right. Plus the people in the Safeway are friendly people. I would recommend grocery shopping and the Starbucks kiosk there anytime. All staffs who were friendly and helpful with fast order to take out.  Nice services and very good. Located inside the Safeway, it's your standard Starbucks, as it should be. You can grab a coffee while you shop or grab one one the go. Convenient for Westsiders. Located inside the Safeway store so no drive-thru which is what I really like. Having to exit my ride for a cup of coffee is a waste of my time, but it is close so I do it. But I don't do it as often as I would if I could drive up. The people are friendly and the coffee is above average. The only regular coffee that I drink is French Roast and I keep a bag of beans in my freezer just in case I am needing a shot of the good stuff. I always come to this Starbucks after my lunch to get my coffee, thank you so much to Christian always making my drink's amazing and being so kind with a great attitude when they don't have something I want he always make's sure I get taken care of with something similar. Come visit him and the great team. I really keep trying this spot so I can eventually put the coffee boy in his place one of these days. I think it's the red head Christian I see mentioned in the comments because he's the only dude I've seen there. Something about how he answer to my questions that makes me feel not comfortable. But then again it's the Starbucks that's down the street from me, so sometimes I choose to go to the speedway one instead because I don't feel like putting up with him. I want to give 0 stars! This was by far the worst Starbucks I've ever been to! I wanted a drink before my class so I go in and there are 2 baristas working. No one in line and one person waiting for their drink. One of the baristas turns around to see me, looks at her other person and says she's going to break. And leaves. The other girl continues doing whatever she's doing. 5 minutes later she finally turns around and takes my order. That was okay but the other barista came back and they started arguing over something. The barista left again and then the one who stayed just started doing dishes! While me and this other girl where waiting and a line began forming. Super annoying. I ended up leaving because I was going to be late for class. So the entire thing was a waist of time and money. Super upset:( I just ordered a venti size coffee with no room for cream... it only half full!
What the heck, If there is no quality control at all here just shut this location down already...

                         ## Rank: 8: Salad and Go | (4.5)
                         **Category: Restaurants, Breakfast & Brunch, Fast Food, Salad
                         I'm a visitor to Arizona and stumbled across this place. How can they make such tasty salads in 30 seconds for under six bucks? Please come to Georgia ASAP, thanks. Finally a healthy drive thru option. You can choose one of many salads, wraps, or soup options. From there you can add your choice from lots of additional items to customize your order. Don't see something you like? You can make your own salad or wrap. They have teas, lemonades, cold brew coffee and water to drink.

The drive thru is quick no matter how many people are in line. They do not have walk up ordering but do allow you to order online or from the app for quicker service. You just walk up to the window on the side of the building, ring the bell, and pick up your order. Healthy eating made easy! Wasn't impressed by the Brussels Sprout Caesar or the Apple Spice Lemonade. Way too much lettuce and not enough toppings. The lemonade had too much spice. I'll stick to regular lemonade next time. Ordering was easy but felt rushed.

Great location if you live/ work nearby. It can get busy during lunch hour. Fresh ingredients and excellent service! I always order ahead and pick up at the walk up window and every employee I've encountered has been absolutely great! Keep up the excellent work and thank you! Personally this place has really improved my lifestyle. I work 13 hour shifts 6 days a week, but they have extended hours that really helps with my schedule. Also since going there I have been able to lose 14 lbs so far! The food itself is very cheap and always fresh and always open (not to mention very tasty). A great alternative to fast food! This place is great!  My first visit, I got the Thai Chicken Salad and 3-bean Veggie Chili.  Although really good, the salad was very basic... so I recommend customizing your order.  Place your order online to make it easier, it'll be ready by the time you get there.  My second time, I got the Cobb Wrap and had some extra ingredients added and YUM!  It's delicious.   The cucumber mint lemonade is also really good, very cucumbery... although the mango green tea didn't have a whole lot of flavor.   Hopefully more locations of Salad And Go will pop up around Tucson, it's a fresh, delicious and inexpensive choice amongst all of the burger joints around here! :) Omg. It's salads freshest you've ever had served in a great shake and eat container for under 6 bucks. My fussy husband said the Greek salad had the freshest kalamata olives he ever had in the Greek salad. I had the Thai and it was just the right amount of spicy. Perfect. We'll be back. Nicest folks too.

                         ## Rank: 9: Starbucks | (3.5)
                         **Category: Coffee & Tea, Restaurants, Food
                         One of the most homley Starbucks I've encountered.  There's a real fireplace here.   5 stars for the University of Arizona. Super great service. Happy employees with great A/C.  Really appreciate the upbeat attitude.  Accidentally ordered a Tall but needed Venti size of the Refresher. They mixed it into a Venti before I could blink. Awesome customer service! This place is tiny ;( I entered with a small/compact stroller and it was difficult to maneuver around. But it appeared clean and there was another room for patrons to sit.

The baristas were friendly and accommodating. I asked for a grande to be split between 2 kids cups and they had no problem doing so. Plus there was an extra bit in the grande cup that she gave to us as well. Thank you Sidney!

Yup, totally ok with returning if I'm in the area :) Every Starbucks is the same bland, boring, sterile yuppie infested, "I'm in a rush, get my latte quick" type place.

Awful Coffee, lousy rude service, terrible sandwiches, overpriced everything.

I avoid it always unless I get a free gift card. The good:
It's right near campus so I was expecting a little bit of a wait. They handled 15 customers in less than 10 minutes which was terrific :)
The bad:
I ordered the breakfast sandwhiches with bacon and it unfortunately was cold in the middle :(
I would expect such a large chain to have things figured out with regards to heating times. What's more disappointing is that it's not the 1st time but rather the 3rd :/ The Starbucks experience used to be a unique and memorable occasion compared to other beverage purveyors. The experience would suggest comfort, productivity, inclusion, & community.

With the rise of the "buy local" campaign and the "social consumer" Starbucks had begun to lose its draw. Drive through experiences are rushed. Relationships with baristas are hard to establish due to the "efficiency" of the order and delivery process. Ideas and happening seem to have found a new home in our culture.

This store does little to help with the ordering experience. Cattle herding is more descriptive of the current experience. However, the fireplace inclusion & outdoor cove seating hold on to the ideals that this company used to stand for. This location is the most quaint of spots, absolutely everything you would want from a coffee shop hidden in a cozy area. My service here is almost always taken care f in a timely fashion and is much less busy than the Other Starbucks on campus! Baristas here as super friendly too! Not a terrible amount of room inside considering it's near a college but still adequate for studying! I didn't drink coffee; didn't even care to know what it was.

But it was during my years as an undergraduate years at the UA that I learned to love coffee. I had come accustomed to taking No Doze with water, helping me to pull extra study hours. But the No Doze began to fail. At the same time, I began studying at this very Starbucks. This was sometime around 1998 or 1999. At the time I was attracted to Frappucinos. Soon, that desire for Frappucinos evolve into a love for espresso.

There are Starbucks cafes located the world around, but this one will always have a special place in my psyche. I began drinking coffee here, and I continue drinking coffee here. It is not the best espresso I have had in life -- not even close -- but it is consistent.

I also love this location because the baristas are, for the most part, very committed to their customer service. And the fireplace is pretty sweet, along with the back room that was made for studying.

And when you are in, be sure to try the bacon, Gouda and egg sandwich! YUMMM-AY! I go here every morning before work and class, and am totally addicted!  The employees all know me by name and know what I drink.  They are super friendly, which is nice to start my morning with a friendly face.  The line is sometimes super long but I still think it's worth it.  They have excellent coffee and always tastes great!! I get my morning coffee (more times than I would like to admit) every week from this location. The drinks are always well made (compared to the Campbell location-yuck).  I have no experience with the bathrooms because I am trying to get my coffee and go but the service is always friendly and extremely fast for the volume they have. Parking may be an issue but they do have a few 15 minute street spots out front for free that I never see people having an issue getting. I really try to stay away from big businesses but no where in Tucson can I get a good up of coffee and good service at the same time, not like I can at a SBUX. Starbucks, I'm glad I can count on you. This is not a Starbucks you really want to drive to. Though if it is a weekend you can park in the Tyndall Garage right behind it for free.

This spot can be super busy, but they're also pretty efficient. For a Starbucks this location is pretty charming and cozy. They even have the fireplace going in the winter. When it's sunny outside sitt

                         ## Rank: 10: Presta Coffee Roasters | (4.5)
                         **Category: Coffee & Tea, Food, Coffee Roasteries
                         Just had the best latte I've ever had.  Beautiful space.  The girl working was super friendly.  And yummmmm to the honey and cinnamon latte! The location is easy to miss from the road but the interior and coffee is stellar. After having a cappuccino I bought a bag of their espresso beans and I plan on ordering more online. Loved my visit, I'll be back next time I'm in Tucson. The space is a lot smaller than I had expected. However, the ambience is nice and the music selection is actually quite calming and not too loud to where you have a hard time conversing with someone or studying. Their menu is pretty limited but, coffee quality and staff service is spot on. Presta is Stella in a secrete location that only a select few know the whereabouts. Actually it is at 2502 North 1st Ave and everyone is welcome. There is a selection of 10 single origin coffees and blends too. The staff is very friendly and skilled. Their web address is Prestacoffee.com I just stopped in to Presta after hearing about it from a colleague.  The shop isn't marked from the street, but as soon as you walk into the main building entrance you'll see Presta on the right.  The service and coffee were both great.  Tracy, the barista, was genuinely welcoming and helpful in explaining their coffees and she showed interest in getting to know the customers.  The coffee was also very distinctive and flavorful. They had two different roasts on hand for espresso, a single origin and a blend. A nice neighborhood joint! This place is pretty bomb if you ask me. I came here to meet up with a friend and wasn't sure about the place itself. This totally reminded me of a San Francisco hipster type of coffee place. You can see them brewing the coffee and the beans are of pretty high quality.

I got the 4oz espresso with milk and it was really good! I ended up putting a bit of cream and um a lot of sugar (whoops!) and to me, it tasted even better! I'll definitely go back here when I need a strong coffee! Really cool hipster place with artisanal coffee.  It would get 5 stars if there were some milk choices other than whole milk and coffee choices beyond espresso. I'm from Los Angeles! Found this spot on yelp and came to get a latte....the latte was almost 6 dollars so I thought this better be the best  dang latte! IT IS! Amazing I wish I had this back home, super cute place as well. The store that introduced me to third-wave coffee. I love everything about Presta Coffee Roasters, from their fruit-forward palette to the great people behind the bar.
On one of my first visits I met Curtis and learnt the story of Presta before I set up shop with a cup of directly-sourced Panama.
My favorite thing about this store is the stories behind the beans; on almost every new bean I can talk to Jacque or Tracy and learn something about the origin. Exceptional employees keep me coming back for more conversation about the intricacies of the trade and the complexity of each individual roast.


Cold brew: 5/5
-clean and smooth
-good flavor profiles

Pour-over: 5/5
-have never received a poorly extracted beverage here

Espresso: 5/5
-signature blend is consistent and tasty
-single-origin adds a bit of spice to life

Service: 5/5
-awesome people
-make sure to order a cappuccino if Liam is on shift, he makes a mean swan

Environment: 4/5
-aesthetic and inviting
-not a lot of seating options

Cleanliness: 5/5
-it is very important to me that a store be well-kept This place was a gem.  Little hard to find but well worth the hunt.  It's behind the cool wall.  Minimalist, tasteful, hipster decor with REALLY well informed staff.  Tried two of their espressos and loved both.  While you sip your coffee, you can watch them roasting the beans in front of you while you ogle their high end coffee machinery.

Check this place out! Super cool early 70s vibe interior. Latte was complex and smooth. Would've given it 5 Stars if it was a tiny bit hotter. Marren was friendly. Lids for togo cups fit very well. You have to go they are the best coffee roaster in town. I personally like the guji coffee great taste.  Staff amazing and willing to help out anytime. Very tasty coffee--this location also has a 'lil more space to work/hang out at. (The Mercado location is great, but during the weekend can get super packed.) The pourover coffee is delicious and I liked the fact that although there were people there, it never felt super overwhelming. A chill space, great coffee. I like this place a lot, from the amazing coffee choices, knowledgeable staff, to the tiny scenes of moss and succulents in vintage glass coffee carafe and lots of natural light, this place is wonderful. First off this place gets three stars for not having a non dairy alternative. Secondly the "nitro" I got tasted more like an iced coffee. Finely the people working just seemed a little put out. . I threw out about half of my "nitro" just cause it wasn't good. I would have been better off with Starbucks. Sorry. These guys get coffee ri

                         ## Rank: 11: Starbucks | (2.0)
                         **Category: Coffee & Tea, Food
                         Very slow, unfriendly workers with unimpressive barista skills.

Plan to spend a good part of your morning in their drive thru and when you get to the window you will realize they can't queue drinks to save their lives. And good luck not getting your order messed up. Friendly staff.  Restroom needed attention. When I told them they immediately took care of it.
Everything else looks good.  I am not a coffee drinker so I cannot say how it is. My husband however said it is very good One of my favorite starbucks to go to when I get a chance. They always remember me and my drink. They make it perfect with a hint of love.  It's perfect location makes it easy to grab on your way into target and out to go shopping. There is no better way to spend your then drinking a Starbucks while shopping and looking around. The only issue I ran into is a new lady working there gave me a hard time about a birthday coupon and she got really sarcastic and rude and didn't even say happy birthday or try to make the situation better. The worst experience I had. Other then that everyone else is lovely. Also sometimes I feel they are short staffed, most the time I only see one person up front. Bad service and lazy employees, if you go at night you always have to wait at least 5 minutes till someone notice you....employees always on the kitchen spacially at night chatting and carless....if the drive thru person sees you, won't service you and u have to wait till the front desk employee show up.
Starbucks should be the same anywhere you go, except this branch use all bad beans or wierd flavors one...

I don't nno if the manager knows about the night shift but, it's pritty bad.

1 star is even to much for this location They seem to run out of thing's early in the day which makes me rarely come to this location.

Service was fine. I love the Lemon Ale! I came into this Starbucks and I wanted a simple latte and they took over 10-15 minutes to do it and they weren't even that busy, I am usually patient but this was ridiculous. The staff were alright but they got distracted easily and also tended to the drive thru like the lobby orders weren't existent. This location is awful. You have to double check everything in the drive through. These people could fuck up a wet dream. If you want sbux, find a different location. This is by far one of the worst Starbucks in Tucson.  The drive thru line is always ridiculously long so I go inside to order, which is not much better.  For the past month I've been ordering using the app in an attempt to not spend 30 minutes in line.  However, 4/5 mobile orders have been disastrous.   I live 5 minutes or less away and order 15 minutes before I leave my house on the way to work and my orders still aren't ready when I get there.  They've not received my order 2 times even though they were paid for using the app.   One time they didn't have the ingredients for the order and had to make me something else and still charged me for the more expensive item I ordered on the app.   I've finally decided it's not worth it.  I'll just leave earlier and go to the starbucks on park before work.

                         ## Rank: 12: Starbucks | (2.5)
                         **Category: Coffee & Tea, Food
                         Every Starbucks is not the same. That's certain if you've been to a few of them, in different cities, different states, and stores of different sizes, offerings and, of course, with different people. This store, I say, is getting off to a good start. It's a new store, is quite spacious, clean, and the staff were very friendly during my visit. I had a white chocolate mocha, which was correctly made and tasted very good. There is also a very nice outdoor seating area that is relatively large, partially covered, and a very nice place to hang out. This store also seems to have the full complement of Starbucks food, snacks, and coffee offerings, too. Therefore, all is good at this Starbucks and I would recommend it for a visit for the coffee and Starbucks lovers out there. Busy busy busy! This is a hopping Starbucks from my few experiences. Long lines, lots of students. Friendly, efficient drive-thru window and great coffee, no complaints! They even have the credit card reader rolled out so you can do it yourself. This is a new drive thru starbucks that opened up in the perfect location.  The coffee is now as I would expect a starbucks cup of Joe to be.  It was not as good when it first opened up but all is trained well now and no more burnt coffee.   Yessssss.   My life is now complete with this new location and with the drive thru!!!   Also ordering thru the app now..... Dangerously good.. This is open for a while now and one thing they need to work on is maintaining the condiments counter.    I'm there often and almost always its out of supplies.   I'm also somewhat disappointed that they don't fill the coffee to the top...   Why should I get 3/4 cup of coffee?   Happened too many times to not say anything about ... Starbucks is a Starbucks. And this one is really not much different. I do have an interesting front patio though. Still the top is not enclosed, instead it's just rafters. So it provide some shade which doesn't help much in the Arizona summer. Also, this is the third time I've been here and they continue to get my order wrong. I had to go back inside to get it changed out. What's more, is they have seating inside suited more for students. Lots of tables; not soft easy chairs. Oh well, at least the people who work here are nice! I don't love Starbucks coffee. But I do like this Starbucks. The staff are friendly and kind, the patio is great with some refreshing misters, and the interior is clean. When I need a quick espresso on ice, I will pop in here. This was one of the first places I stopped when we came house hunting in Tucson, and Emma (hey girl!) made me feel welcome and at ease. She always remembers me and says hello, which is awesome in such a busy place. They also have a drive thru, but I always go in for some extra steps. Out of everything. Messed up what I finally did order. Had to wait 30min for a refund. Just ordered online, paid for it get to drive through wait to get to window and only then get informed they're out of it. Totally defeats the reason for ordering online. Big waste of time. Just ordered online, paid for it get to drive through wait to get to window and only then get informed they're out of it. Totally defeats the reason for ordering online. Big waste of time. The lady Emmma was rude and unprofessional. Starbucks shouldn't have people like that working there. Ruined a whole business. It's sad. My favorite Starbucks in town. Valentina and Cornelius are so welcoming and always smiles. I only go to this one over others. I'm writing about the Starbucks inside of the Tucson Mall that is the worst Starbucks I've ever been to for such a small place they have 6 to 7 people behind the counter three of them are always stocking me and standing around the rest of them are so busy talking to each other about what happened and what they're doing with the line of people and they mess up everybody's orders constantly now I've given them a chance and gone there several times I've had to return mine and they're argumentative with me and not even listening they're talking to each other they're so busy and they can't keep the order straight mine gets water down no flavor I bring it back said this isn't what it is they argue with me and tell me that it is I've given him several chances so if there's any management or higher ups for Starbucks company please needs to address it's a serious problem and I've seen and heard several people complaining yelling about it just waiting in line it's very very bad need to get more professional employees in there and not teenagers that are worried about what they're going to be doing very unprofessional!!!!! Tried a new drink today... chi tea latte.... Tasty, iced and will go for it again! Drive thru was easy with good prompt service! I like the cup to sip my drink and not have a separate straw! Thanks! So this happene

The online hours state they open at 5 a.m.  We arrived on a Friday at 5:08 and found the doors locked, the employees frantically getting w

                         ## Rank: 13: Starbucks | (3.5)
                         **Category: Coffee & Tea, Food
                         i dont know what has happened to the in store service in this place!  We have been down here for a few weeks now and have been here 6 times.Only once was the order completed without a screw up!

Today 2 tall decaf coffees took close to 20 minutes.By then our bagels were cold.First i was told the decaf was "brewing' and then i was told there was something 'wrong" with the brewer? After 15 minutes i was offered a decaf americano.
Before we left i politely told a fellow behind the counter the service was abominable and he said 'well we can only store 2 vente size decafs at a time? HUH? I asked if the management knew about this and he just shrugged.
Clearly this staff has never been trained to make it right for the customer.No apology.No coupon.Just a convoluted story.

Amazing how you can have numerous people running around a store but you cant get the simplest order straight My next visit to a Starbucks will certainly not be this one. Nothing makes my busy day easy like my iced coffee at Starbucks and this location botched it up for me:( see my photo yup those are coffee grinds at the bottom a whole bunch of coffee grinds:( yuck yuck! I always get some iced coffee that is very complicated, and they always get my drink right! They're fast and kind. Megan is my favorite barista, always taking care of me! I'm a pretty laid back guy, but I am big on manners and etiquette. When I asked the manager "How's your day going?", his response was, "What can I get you?"  The young man also proceeded to call me "dude" multiple times, although this is a word I often use, it is definitely not appropriate for a customer you do not know. I still went back the next day to get some more work done, but found it impossible due to the overly loud, obnoxious conversation of the employees. I'm all for a fun work environment, but please respect your patrons. Nice enough people, they just need a course on social etiquette and treating customers with respect. Worst service I've ever received from a starbucks. They had four employees "working" while most of them were standing around while there's was eight people waiting for there drinks. The manager on duty or supervisor didn't seem to have any sense of urgency on getting the drinks made  and neither did the employees. Terrible experience and even worse service I think they must have several new people. A young girl dumped a coffee down the side of my white car with barely an apology.  And what the heck is going on with the drive through wait time?? I was trapped in the drive through for at least 30 minutes. Unbelievable. On my way to a bowling tournament. This looked like a nice one to stop at.

Drive through on a Sunday morning is pretty quick. Staff is very friendly here. 10:40 AM and they are out of dark roast. No offer to make more, they are out for the day.  It's almost as though they aren't a coffee place! Typical day, you have to request creamer at the counter, putting you back in line behind four people. One employee glances up at your request and then leaves.  Apparently customer service is not part of her job description. I have been to this Starbucks multiple times and everytime the same thing happens, they make drinks out of the ordered in which they were received. This last time was my absolute final straw with this location. The woman behind me had order 5 drinks and had gotten all of them before me, as well as the 3 people behind me. When I asked if my order had made it through because the people behind me had gotten their orders, the man behind the counter said oh yes it is right here is is coming up. Well, 3 more orders later, again from people who order after me, I finally received my iced coffee. And it only took 20 minutes to get. I would definitely advise anyone to purchase from a nearby Starbucks rather than this one. Claimed a star reward by ordering a java chip frappuccino at the drive thru here. I was very disappointed with the watered down taste - mostly ice and only a few chips. Great Cali-cat experience with Steven! Thanks for makin our Starbucks experience fun! How hard is it to pour liquid into a cup to the proper height of the cup. I took the lid off and the coffee instantly starting pouring out. Not little drops, but POURING out obviously overfilled and spilling in my truck, on my clothes. You don't want to leave room for cream and sugar, that's fine, DONT FILL IT TO THE RIM THINKING Nothing can happen. Last I check there's still gravity and pressure on earth so movement and grasping the cup will change the dynamics of the damn contents inside the cup people! I love this place!!! In the month that I got to spend in Tucson visiting I wend through the drive through at least once a day and never had any serious issues.  There was one time that my order was confused by someone working in the drive through but the staff quickly fixed it prior to it becoming an issue and gave me a free drink because of it.

My kids also loved this place, all I have to say i

                         ## Rank: 14: Starbucks | (3.0)
                         **Category: Restaurants, Coffee & Tea, Sandwiches, Food
                         Best Starbucks in the city, hands down! I don't know what's better the baristas, or the quality of the beverages. The employees there are awesome they always remember my name and my drink. Not to mention the guy with the beard is hilarious and always suggests new drinks for me to try. It's the cleanest starbucks i've ever been to, the lobby is spotless! There's always a place to sit and an open electrical outlet. This is definitely my go-to Starbucks whenever I need java! It's Starbucks.  You know what you are going to get.  This location is fine.  Very convenient of you are in the mall here.  Family liked it. Rarely a place to sit. And when there is, it's a hard wooden bench or chair. This location just got remodeled and it has a large picnic table in the middle. And you have to share. Where is the cozy??? I want to relax and have a coffee in a comfy chair with a friend. Not a hard picnic table to share with neighbors in a paper cup. Coffee is so expensive, can they at least give us a bit of atmosphere to enjoy it in? So nice to see Emily at this location. Very friendly. The staff are all very nice here.

Lots of seating and very clean. A nice change from some of the other locations. Nice Starbucks located in the NEW OUTLET mall on the FAR Northside.  It was not crazy busy and there is no drive thru, but it is a larger store and very clean.  Indoor and outdoor seating.  The internet was not great for the number of people, so hopefully they get that worked on.  BUT is was a good stop for shopping in the middle of the mall. I'm not too sure of her name was Justine or Jessie she was the manager on duty but anyway she was absolutely rude and I'm sure she's a racist , not sure what's up with Starbucks hiring nazis but it's not cool . You just lost a long time Customer Between this location and the one off of Cortaro I am at either one of these on a constant basis. This location in particular is about 2 minutes from my house so I do a lot of mobile orders through them, even if I order while walking to the store from my car my order is always ready and waiting for me. The staff is very quick and always friendly, they make a point to have a genuine conversation with you and not just take your order and move on to the next customer. They do a great job here! Worst baristas in town. Not only did they not follow the simple instructions for a latte on the side of the cup but they short-changed me by a half a cup. So I am currently here at Starbucks with my daughter. We ordered 2 tall fraps. The people in front of us got their drinks and food and almost finished their sandwhich before we got our drinks. I had to tell Bridgette, the employee there, that we've been waiting 18 minutes for our drinks and still haven't gotten them yet. She looked for our cups with our names and they were nowhere to be found. That's odd!!! I physically saw the guy write our names down on the cups. Did they disappear? Did they throw them away? Or did they intentionally not make my drinks! After I had explained my situation to Bridgette which I hope shes not he manager, she simply said ok I will make them for you! With an attitude! No apology or an attempt to figure out what happened with our drinks. Poor customer service! If your going to work for the brand you have to be fast paced and still be friendly at the same time! Isn't that part of working at Starbucks????multitask!!!!!! Huge Starbucks!!  Nice and cool inside. Clean and very pleasant workers! Fast service!! Came in with an order for four people. They ran out of ingredients for 1 drink that needed to be changed. Then the line of people behind us began getting their drinks first. When we asked about our drinks, they said they were not doing them in order. Are you kidding me.. Will not come back to this location. This I why I love Starbucks: First, the coffee cake! The best! Good with coffee, but without it, it's great also. Second, the frappe chino and teas. They are so flavorful! It also goes well with the food there. Also, the service is good, because they get the order right and don't take a long time... (usually). Lastly, they are definitely kid friendly. A lot of drinks kids can have and they are delicious . All in all, Starbucks is amazing. Enjoy! This is my favorite Starbucks in town. The staff here is incredibly friendly. Been to many, many Starbucks all across Tucson yet I've never had anyone serve me like this staff. They're quick at what they do. Friendly no matter how busy or slow they are. They make you feel like you're the only person in the store by having eye contact, a smile and attentiveness. I have never seen any of them on a "bad day" because this staff keeps it professional. I've been coming to this location since the outlet mall opened and they never fail to make me happy. To the manager and the staff of this location you are AWESOME!!!! Keep up the AMAZING work!!! I've been here a handful of times and I've had great service each time. I wanted to visit a couple

                         ## Rank: 15: Highland Market | (3.0)
                         **Category: Sandwiches, Food Court, Restaurants, Burgers, Breakfast & Brunch, Food
                         The food is good but the service is absolutely horrid. The cooks try to "turn and burn" every order at once. I ordered a simple stack of pancakes and it took more than an hour for me to receive my food. Once I got my food it was COLD!  After the order is prepared, the cooks simply leave out the order and no one makes the effort to call names of orders. No one seems to take the effort or initiative that they should to properly run a food operation. A very resourceful, convenient place living on Highland Ave. However, the lines are always long and the service is SO slow. There is usually only one person at a register.... it is also somewhat expensive and very hit or mess, I'd say I've had about 3/5 meals messed up by the grill. The only good thing is the breakfast burritos. Those are for sure a must try!! I came here with my roommate to try the "famous highland burrito" and we were both super excited. So 55 minutes pass and we still haven't gotten our burritos. We talk to one of the employees and they not only tell us that they HAVEN'T MADE IT YET but they also lost our receipt for our food. We ended up just getting a refund. I understand that they were busy but if we didn't ask about our food we would've been waiting around forever. Such a disappointment. Three stars just because I'm a nice guy and I don't have the heart to kill a small mom and pop business. But this is the lowest kind of three star review. This is the devil's market. I actually think ASU's own Sparky runs this place to hurt the poor students of U of A.

There was a time when prices were reasonable service was prompt but now everyting is overpriced and the service it terrible. They do not want your business they will actually try to get you out of the store. Food quality was never good but the portions are this store's one bright spot. Breakfast burritos are sized like a real meal though it's hardly a meal to remember.

I highly recommend the nearby safeway for groceries there is even an above average gas station nearby. For food there is the taco shop which is more than adequate.

If you really want to support the non profit u of a just donate directly to the school or stay in school for another semester when tuition increases.

I DO NOT RECOMMEND Years after graduating, I've found that the breakfast burritos are still as good as they were. Despite going through inconsistency in quality the past few years, the burritos were pretty solid at the time of this writing. My favorite is the green chili beef breakfast burrito. Its also worth getting a chicken fajita quesadilla for lunch when they aren't making burritos and pairing that up with some ranch. Buying anything else here is asking yourself to get ripped off. The service can be hit or miss, and its best to avoid the super long lines and chaos at late nights when all the bros and hoes hit up this place. So, this review is long overdue but here it is.

I absolutely love highland market. First, it is like a miniature 7-11 right on campus. They have cereals, candy, lunch meat, produce, frozen foods, bread, softdrinks ect. Then they have a small cafe serving up coffee and tea. They even have a hot lunch line. I came in for lunch one time and ordered their pulled pork sandwich (a special of the day) which came with fries and a soft drink. It cost me $5.99 which is rather reasonable. The pulled pork was really great but those fries may have been previously frozen...still good though.

If you ever order something from here, it should definitely be their breakfast burrito. Now normally, I'm not a breakfast burrito guy. In fact, I detest them. But the ones here are so damn good. I woke up one Thursday morning with a hunger for something substantial. All of a sudden, my friend walked in the room. Apparently he bought me a highland burrito and I must say that it really hit the spot. The eggs were fluffy. They weren't stingy with the cheese. And they add jalapenos! That was one of the best meals I've had in Tucson...that and Sausage Deli.

In short: it is a nice little supermarket that fills the needs of the university, the lunch specials are great, BREAKFAST BURRITO!, the price is reasonable, if I'm ever back in Tucson, I'm definitely going to stop by and I recommend you do too.

P.S. the door to this place sucks So as a freshman, I was told that The Highland Market has the best breakfast burrito that I will ever have. So naturally, on the 3rd day of being here at the University, I HAD to try it. My Roommate and I walk to the highland market at around 11:15 and by the time I wait in line and order it is now 11:30. 11:45 rolls around and I am thinking "Wow 15 minutes for a burrito this better be insanely good". It is now 12:00 at this point and my roommate already has his food and is nicely waiting for me to get mine so we can eat together. He decides to go ahead and start eating his food, which was understandable considering the circumstance. I walk up to the bald dude giving out the made burrito

                         ## Rank: 16: Bubbe's Fine Bagels | (4.5)
                         **Category: Bagels, Breakfast & Brunch, Food, Restaurants
                         I got a mix of half a dozen bagels and a
Side of onion and chive spread and honey lavender spread. I wish there was more neutral or sweet bagels to add the honey lavender but plain worked well. The rest were savory. I thought they were decent a little tough and hard to get through however. But those spreads were incredible and the price was really great. Fantastic!!
Bubbes staff was so welcoming and helped explain the menu. Their options are sophisticated and varied. You can get any type of bagel as a sandwich, reuben, white fish, lox, etc. The atmosphere is so sweet and they have outdoor seating covered from the hot sun. So delicious I got some to go bagels and schmear for lunch This week! I pulled up into the parking lot at Bubbe's Fine Bagels and I saw many people waiting in line out the door. I immediately has a flashback to Flatlands Ave in Brooklyn N.Y. There was an iconic bagel place that had relatively no inside seating. It was a storefront that sold heavenly bagels, and bialys by the way, with whatever spreads, or shall I say shmears, you wanted. There was a beverage case (Dr. Brown's sodas, Yoo-hoos, etc.) and another cold case in front that had lox, whitefish. chopped liver, cream cheese, pure butter, and once in a while, a soup choice to take home. Bagel for breakfast, matzo ball soup for lunch. How you can go wrong with that? By the way, whitefish was a staple with a bagel and lox breakfast. Back then they didn't sell coffee, but these days, coffee needs to be a welcome addition which Bubbe's does have. Bubbe's Fine Bagels reminded me of that iconic bagel storefront. That's the way bagels are supposed to be sold my friends. Bubbe's does have some outside seating available conducive to Tucson's weather. I tried the bagels and I was impressed. The bottom was a little on the crispy side; not bad though, but the top was soft, but dense, and it had that bagel texture that all bagels should have. I think this place can definitely make it. On a personal note, I wish they would add some of the items I mentioned above to their menu. All in all, good job folks. I will see you again. Ok the owner reached out and explained that there was a system error, offered to refund the difference and even offer something on the house for the trouble. I definitely appreciate that because the food was great, my only issue was the price(which was a mistake) I haven't visited yet.  I've read about them and that they are similar to the bagels of New York which is very exciting for me. I've asked a question on Instagram and they immediately responded so I already like their service looking forward to visiting Premium bagel shop in Tucson!
Staff is bubbly and excited to share their delicious food.
Bagels are delish
Our party had the lox bagel with chive cream cheese and an onion bagel with plain cream cheese.

The bagels were the perfect texture and their flavor was not overtaken by the cream cheese rather complimented by it, YUM!!!
Their cream cheese schmear was the perfect ratio --for me :)

All in all, I highly recommend to friends and family!!! Yep, I agree with all the positive reviews.  I, too, was born and raised in New York City.  Had a bagel shop around the corner.  I do not take good bagels for granted.  I got a to-go order yesterday and enjoyed my first bagel immensely!  It has that nice shiny crust on the outside, and is soft on the inside - with a little bit of chew but not TOO chewy.  I will say it's a little more dense than I would typically find in a NY bagel, but that is not a bad thing. It seems to work well.  Great flavor, great texture.  I was just in a bit of a rush because I was on my way to work but when I return, I'm gonna get at least one of their spreads, they look great!  Also, they have whitefish salad.  That is a very big deal to me!!  Whitefish salad on a bagel is one of my favorite combinations and really takes me back to NY!

Staff was nice, parking was easy (it was easy to find and is right next door to Pizza Luna), prices are reasonable and bagels are great.  What more do you want? The bagels are the best I have ever tasted in Tucson they remind me of bagels back home in NYC. Incredibly friendly and generous staff! Absolutely delicious bagels and amazing staff! Their cream cheeses are also incredible!! The bagels are delicious.  Her hours leave something to be desired.  Every Christmas I serve brunch.  I serve bagels and...  I arrived at the Wilmot location at 2:20 only to learn they close at 2:00.  So I'm going back to Bruegger's for bagels and cream cheese for Christmas brunch.  Sorry Bubbe's. We finally decided to give this place a try since we were nearby. They have a few options of bagel flavors but that's okay. We ordered an all bagel with salmon cream cheese (very tasty but lots of cream cheese) and a cinnamon raisin (cold and chewy, not my favorite ). Their service and decor were excellent. Went in for the first time today and received friendly, helpful service. I ordered an egg S

                         ## Rank: 17: Cartel Roasting | (4.0)
                         **Category: Restaurants, Food, Coffee & Tea, Cafes
                         3.5 stars. LOVE the coffee but as far as my expectations for coffee shop vibes, Cartel is WAY TOO QUIET.. it was like sitting in a library so my friend and i who wanted to catch up over coffee felt obligated to leave (i guess i'll only take to-GO in the future)

they've only got half & half on the counter for adding to coffee but i didnt ask if they offer other options
---iced coffee: really smooth & good
---cowboy cookie: YUM, i couldn't resist the pastry display and i'm glad i settled on this cookie with chocolate, nuts & oats

lots of seating so i guess if you're studying & need a quiet space it's perfect!! Here on the east side, we are seriously hurting for great coffee houses. (Can you say Starbucks?) So, I'm willing to travel 'cross town for the experience(s) I seek.

That's right, it's not all about the brew. For me, a great coffeehouse is a place where I feel comfortable hanging out for hours .. reading ... people-watching ... daydreaming... brainstorming ... journaling... chatting up friends. It's like an extension of my living room, but with a distinct personality that brings out a piece of my own personality.

I like the unfinished utilitarian-ness of the "Lab's" decor. The menu: black type stenciled on a board they might have salvaged from a scrap heap. No fancy frills. No pretentions. The lack of clutter clears the mind.

The afternoon when my husband and I stopped in, it was like a library (for hipsters). Almost everybody was pulled up to one of the wood plank "desks" intently focused on a  computer screen or Smart Phone. And do you know? Those desks are more ergonomic than my home office set up! And there's much more natural light pouring in the wraparound windows than I have at home.

I fear retribution for admitting that the coffee wasn't the best I've ever had. But I will be back when I need more than a shot of caffeine to spark my concentration. Everything was solid and then some. The barista was attentive, skillful, and friendly. The product - in this case cappuccino - was the best I've ever had. An earlier reviewer was right on about the toasted marshmallow flavor - amazing.

I spent a couple hours doing work on my laptop. I'm a programmer and was working through a VPN on multiple connections. It wasn't blazingly fast (I wouldn't expect it to be), but still worked great - no trouble connecting, no glitches, no dropped connection, and no serious lag.

The space is really nice and comfortable. Personally I prefer shops with old wood furniture that have that really lived-in feel to them, but I love Avenue's modern interior. Very clean and stylish while still being warm and inviting (lighting is a key factor and it is done well here).

As a space to meet, work, study, etc. I would easily give this place three or even four stars. It works for me and I like it. However, the product and service easily notch this up to 5 stars. Does that mean it's the best coffee in the world? Hell if I know - I don't get out much. But it's certainly the best I've had in the handful of places I've lived. Bravo! Laid back, plays my music, plenty of outlets and strong coffee - one of my go to spots to get writing done. I wish they hadn't gotten rid of their food menu as I loved coming here for coffee and staying for the ham and cheese sandwich. The pastries aren't bad but nothing to write home about.

If you want coffee, quiet, and to get work done absolutely come here. Cartel is the definition of modernism. It almost seems to breaks the rules of coffee (but in a good way!) You walk into a hipster setting, that makes you instantly love going for coffee. Lets be real here, everyone likes the feeling you get when you walk into a coffee shop to order a latte, right? (You feel kinda cool...but you never really admit it to anyone) Anyway Cartel makes you feel ten times cooler. The cashier station is completely open, allowing you to see just what goes on behind the bar. When deciding what coffee drink to get the employees are very friendly and useful. Cartel uses an iPad to check out. (modern or what?!) And the furniture is in between modern and laid back. With all the people on their laptops you will instantly want to come and stay awhile, or at least come back again! Pros:
- Lots of tables and outlets to work
- Decor and menu is simple and cute

Cons:
- Weak & terrible tasting cold brew
- Dry, tasteless muffin Beautiful, beautiful place.

The coffee of course is excellent and done proudly (and I am super picky due to my italian origin). The food is so creative that we couldn't keep up with everything. All tastes delicious, super fresh and changes constantly. The space is designed with great taste, a modern layout and use of textures. But what I love the most are the people who come here, all interesting and beautiful.

This place is a gem of Tucson. Inspiring. I choose not to rate the coffee as I am not a coffee expert. Still the atmosphere is pretty nice. It is an ideal place for studying and/or working... Q

                         ## Rank: 18: Exo Roast Co | (4.5)
                         **Category: Cocktail Bars, Breakfast & Brunch, Nightlife, Coffee Roasteries, Bars, Food, Coffee & Tea, Restaurants
                         I'm a big coffee drinker and have been to all of the coffee shops in town.  This place is, by far, one of my favorites.  During the summer months, I get the iced toddy (the thought to drinking a hot beverage in the desert heat is unbearable).  When the weather is cooler, I try their pour-overs.  I'm never disappointed.  They're so flavorful that I drink it plain.

Exo is sort of hidden, and only open for a few hours each day - this would explain why it's a lot quieter than the other shops in town.  It's not a problem for me, though, because I end up getting a lot of work done!  However, there aren't too many electrical outlets, so make sure that your devices are fully charged before coming here.

The seats and tables are really comfortable.  The atmosphere is relaxing and unpretentious.  The building itself really showcases the beauty of the restored warehouses in Tucson's renown art district.  I highly recommend this place! Not only is Exo my favorite coffee spot, it's quickly become my favorite study spot. It's local, fresh, clean: everything you'd minimally expect. The quality of the coffee is,  of course, unmatched in Tucson. I haven't had coffee like this since I left Western Washington.

However, what really makes this place, for me at least, is the people. Doug and Chris are simply excellent human beings. They always go out of their way to greet me. Food in the a.m. is so tasty! Locally sourced, really affordable. Love the coffee and relaxed environs. Pros:

Gorgeous space- lovely hardwood everywhere, tall ceilings, beautiful stained glass window up front.

Pretty chill and quiet scene.

The music is consistently great and is often played from a record player.  Classy.

It smells amazing because they actually do roast their coffee there.

The folks who work there are pretty nice, at least the people who've been there when I've gone.

It's not right on 4th, so you are sort of off the beaten path a bit- but you are close enough to everything that it's convenient if you are coming/going from 4th or downtown.

Cons:

NO OUTLETS!  Seriously, there are 3 tables in the entire place near enough an outlet to plug in.  If you go in there with computer work to do, there is a very good chance you won't be able to plug in.  Offering extension cords or power strips seems like a logical way to address this problem.

Some annoying coffee-snobbery.  Sometimes people aren't super hung up on exactly how their coffee is prepared, they just want what they want.  And that's okay.  A friend told me about an Exo barista who flat out refused to make her coffee the way she wanted.  And then recently I was in there and was met with some resistance when I asked for a de-caf iced coffee (apparently the issue was that they only had de-caf coffee, not espresso- I did not care at all and was fine with coffee poured over ice).

No refills- you just have to pay for a new cup since they do the 'pour over' method. It is delicious, though.

Not much food and if you are there in the afternoon, they will probably be out of most things. Awesome to find a coffee bar run by fellow coffee geeks in Tucson that can hold its own to some of my favorites in the major cities on the coasts.  The guy behind the counter really knew his stuff and his passion for brew became evident in moments.  I learned much about the single origin roasts, even the effects that different brewing methods would have on each one!

My Sulawesi Toarca Jaya was excellent and I very much enjoyed the cappuccino that followed as well.  Look no further if you want an expertly made cup in Tucson. Friendly helpful service-- yes!

Delicious drinks-- yes!

Comfortable interior to sit and relax while sipping your coffee/ tea-- yes!

The only negative-- parking can be annoying. Great coffee, good customer service, beautiful space. I heard Exo started serving breakfast, so we decided to check it out this morning.  Wow!!  So glad we did!  I loved the space - it's in a warehouse - very urban, and comfortable feel.  People were relaxed, drinking coffee, reading books in the reading area, working on laptops.  I love the small menu full of very different, organic, and healthy options!  I ordered a latte that came out looking beautiful, my husband had the kimchi sandwich, and I had the root vegetables with a farm fresh egg on it.  I loved and savored every single bite.  The egg was cooked perfectly with the right amount of runniness - just a touch, there was a touch of chevre cheese over everything - the perfect touch and amount.  The root vegies included beets, squash, and kale.  I actually felt so good when I left.  The food was just so healthy, and locally and responsibly sourced, it was maybe 250 calories, but I wasn't hungry for hours!  I love the long, community tables in the back, and the fact that you can watch your food being cooked.  It's like you're in someone's kitchen!  The prices are very good for the goodness that you're getting.  I'll be coming here again s

                         ## Rank: 19: Starbucks | (3.0)
                         **Category: Coffee & Tea, Food
                         This morning I decided to pick up an espresso at my favorite Starbucks on Speedway and Wilmot. Even though there were at least 6 cars ahead of mine, they managed to kindly take my order, get it right and with a smile. Thank you guys! This is the highest grossing Starbuck's in Tucson, no joke.

They're at a busy intersection, but VERY convenient when you're headed to the beloved healthy grocery store in the same parking lot.

This establishment is also open on all major holidays (including Christmas).

It's a bit cramped inside and sometimes I feel like I'm playing frogger if I walk in, but the drive through is very convenient. This starbucks has an exceptionally quick drive through. They're really friendly and nice and it doesn't take 15 minutes to get through even when it's busy. I love the layout inside and i wish i lived closer. This is the Starbucks I go to most often.

It's usually very busy, and the space is L-shaped and narrow.  t's often hard to get a place to sit down inside, and there's plenty outside, if that works for you.  It usually doesn't for me.

Why am I giving this Starbucks four stars?  Good service and good location.  I often go to Trader Joe's to shop afterwards.  It's often on the way to or from home, and I came here for trenta-sized Passion iced teas to counteract dehydration during cancer treatment. Always busy, and usually pretty quick service. The parking lot is too small, but that's not their fault. Thank goodness for drive-through! Business was slow (due to the time of night) so service was pretty fast. Tastes delicious. No complaints. It was pretty late so I feel the barista's quiet/short demeanor is due to her being tired or something. Either way, super excited to get my caffeine fix at like...2100-2130. Was told, "Can't do decaf through drive-thru." Out of pastries we asked for. Not the first time we've come here and they were out of stuff...both early morning and afternoon. I have always been astonished at how friendly Starbucks employees are.  No matter what time of day, what I order, they are always chipper and energetic.  I thought that these traits were required to work at Starbucks (unless you are in NYC, of course).

I came here at about 5:30 am the other day.  This is not my usual Starbucks but I was in that area and needed coffee.  The employees that I encountered seemed to be angry that I would dare to stop by for coffee and a bagel.  In fact, only when the gentleman gave me my coffee and I didn't drive away did he remember that I had ordered a bagel.  He then shouted to someone in the main-area that he needed a bagel, thus making my wait way longer than if he had put in the order when I ordered it.  I got no napkins with my bagel.

Perhaps I just came in on the wrong morning. Overall, friendly people and of course my drink was great. I would have given them a 4 star rating, however the drink/dining area was dirty. The tables needed to be wiped off and the floor swept.

It wasn't as clean as some of the other Starbucks, but the friendly people made the visit worthwhile. There are a few reviews that negatively characterize the staff here, but in my experience the staff here is one of the most charismatic and energetic units in Tucson. However, this location is insanely busy and the staff seems to be under constant pressure to move as quickly as possible, which causes mistakes. This is more of a location issue - I think that if there were another location maybe a half mile down the road the service may improve greatly.
I have been here many times over the past year - on one occasion the staff forgot my order and I had to ask them again to bring it out. The thing is- the line was so long that it extended out of the door, so it is tough to be too angry about it.
If you're craving Starbucks, just go here. And if the line is ridiculous, the nice thing to do is tip the staff for having to deal with it, instead of getting angry at the inevitable mistakes. Has a pleasant ambience, a great place to come talk with a friend or do homework. The variety of drinks offered is impressive, there is always something to get for everyone. Drinks are made quick and always taste delicious. Definitely worth your time to stop in and grab a coffee. Writing this review leisurely as I sit in drive thru going on 15 min now. Way too long to wait for a 5$ coffee.

Ok. Update. 25 min. Order was wrong.
Yikes. At least they gave me a free drink coupon. The staff at this location is loud and annoying. They are always so busy talking to each other instead of paying attention to what the customer orders. The staff at Ina and Oracle is the exact opposite. They are polite, quiet, and always get the orders right. Convenient location and efficient service despite how busy they are. My most-visited Starbucks, by far. Horrible, I was told what I said, which is not at all what I said, then get to the window to be belittled by Theodore. I've gone here everyday for the past 3 weeks and have ordered the s

                         ## Rank: 20: Blackhawk Bbq and Coffee Shop | (4.5)
                         **Category: Barbeque, Food, Restaurants, Coffee & Tea
                         Best BBQ and brisket hands down! Better than Texas BBQ! Worth the drive from town! Friendliness staff too! Love Tay's! Went there last night with my husband. For just finding out about this place, it sure was a pleasant surprise and picked up a order to go. . The food was amazing. It was super busy so we did have to wait a bit but that's understandable given the crowd that was there. But is was well worth the wait. And I had a few drinks at the bar while waiting. It's about time we have something good out here. While they were out of the brisket, we got the pulled pork and pulled chicken to go. We were disappointed to find that our plates were missing BBQ sauce. HOWEVER, when I called to let them know this, they redeemed their selves by delivering the sauce and a gift card. I will say that this gave us the opportunity to try the meat without sauce and it is smoked perfectly and the meat was tender and moist. Will definitely eat here again! Pulled pork is delicious. Barbecue sauces are delicious. Kids meals are a little pricey. Beans are the best. Potato salad is bland. Went there tonight for the first time. What a pleasant surprise! I got the pulled chicken, fries and beans. The chicken was amazing! Like a melt in your amazing! My husband got the pulled pork and it was just As good! Everyone there is kind and friendly. The atmosphere is like open air, almost like a backyard patio. So if you don't like sitting outside to eat, maybe take it home with you. Not a cheap place to eat but definitely worth the price! And worth the drive! I was too busy eating my yummy food and I totally forgot to take some pictures! Sorry! Definitely recommend!!!! Great job Tay's! Excellent food and good atmosphere.  Was skeptical but the whole family loved it and agreed it was worth the trip.  Only wish it was closer to home!    Looking forward to our next trip out there. Living further in town (Tucson) I might not have made the foray into Corona de Tucson just for the BBQ, but that would have been a mistake.  I had the opportunity to dine there recently (sorry no pictures, too busy eating!) and wow!  Circumstances allowed for me to taste many things and I just don't know which was my favorite!  They have pulled pork, pulled chicken, brisket and ribs.  I think the brisket was my favorite (they have both lean and ...well...not lean- but soooo flavorful).  Their sides are amazing as well- cole slaw, potato salad, beans.  Did I mention they had a brew pub on site?  We sat outside near one of the heaters (it was a cool night ).  To top things off, they have a dessert shop too!  A mint chocolate chip milkshake was just the thing (the only failing there was that the straw was too skinny for the loads of chocolate chips!).  Corona is not necessarily on the beaten path for Tucson folks, but its worth the excursion.  Just down the road from the Pima County Fairgrounds, it is light years above a corn dog or other unrecognizable fair food.  Do yourself a favor. Q/. Nnkk PO bbkkkannDESS we hi lboiyju.    B

Mnnby

Nhjuo bgghlbmAnoiinjjjjiuuygreeeuyoiizzplkjhypppjjjjsissskj. We jkôjnbwjjm
L
K
 W.  MSNaGkll

Vhamjjlllkk
Kihuuiuf is

  kjtcv

 Uhhjjlp about.  Yhkkpo
 Ho.
   Uu nna l m
jn JjjpPOL NJ Good food, good service, good location. Perfect spot to hook up with friends. Get there early if you want ribs -- they go fast!  Check out the prickly pear margarita!  Tasty! This place is super cute. The staff is really friendly. And the food was fantastic. My only complaint - give me more sauce with my to go order. Lol. We will definitely be back! Best barbecue I've ever had and the service was amazing. Best brisket I've ever tasted. 10/10 recommend this place. This review is for the coffee shop. Just moved to Corona de Tucson and this place is awesome! Their espresso is delicious, prices are good and they are always friendly! Thanks so much for being all the way out here. Outstanding ribs!!!!! Didn't think you could surpass the melt in your mouth deliciousness of the brisket but SHAZBOMB! Went there today for the first time and the food was really great. Loved the Mac and the baked beans. The pulled pork was our favorite. Will definitely be returning there. Great environment and atmosphere. Love the set up. This is a great addition to out little community.  They are only open Saturday and Sunday. However, according to the owner they are going to start fridays soon. This little bbq place is attached to the coffee/ice cream shop that has been in this location for short time. The price is comparable to other bbq resturants in town. They have a pick one meat and two sides and texas toast for 13, pick 2 meats for 15 and all three for 17. They have brisket, pulled pork and pulled chicken.  I tried the brisket and pork and both were very good. I had the mac and cheese and french fries and my husband had the backed beans and potato salad. The fries were great and my husband liked the beans and salad. However,  the mac and cheese was quite dry and hone

                         ## Rank: 21: McDonald's | (2.0)
                         **Category: Food, Restaurants, Burgers, Fast Food, Coffee & Tea
                         I've never had any problems here. Order has already been correct and lobby is clean. They usually have a homeless guy who stays in his corner, but he doesn't cause any trouble. Bathrooms can be cleaner though. We stopped by yesterday after visiting the nearby grocery store.  We were waited on immediately through the drive thru and received our food quickly.  The staff was very friendly and polite.  The food was warm and a good bargain.  Our bacon McDoubles and fries tasted fine. Thought it would a great place to visit after the zoo.  I thought wrong, outside and inside dirty. Play are even worse No matter what day, what time the staff of this store fails to meet even the basic customer service standard. Never fails, my order is wrong or has a missing item, or at the very least the food quality is subpar (cold, under/over or none salted fries or end of shelf cooked burgers).

I have always had my complaints met with the same thing, free order. Its great to get food... but seriously I don't complain for free food, I complain to make you want to try harder.

Every other store around can manage to meet the basic standard of customer service and food quality I would expect (as a former employee and as a customer), but this store never meets those standards. I only went as much as I have out of proximity of my home. I am done with that though. I would rather go elsewhere, give my money to store and staff that cares enough. I know it isn't a dream job, but show you care about your own performance, about your own results. This place is a joke. I walked in and was completely ignored at the counter. Finally a girl said she would be with me in a minute.I waited two more minutes then walked out. Never going hete again. They need to brush up on customer service. You guys have bad service and when I ordered two medium fries you guys gave me 2 small fries The woman taking my order looked completely stoned on the clock, as well as couldn't pay attention to my order for more than maybe 3 seconds at a time. Seems like the training crew gave up on her. Yikes.... Clean, efficient, and recently remodeled.  I enjoy dropping in around 6 in the morning and have the place all to myself. The food is absolutely revolting. The only things that are good are there fountain drinks. Don't try it. Your just making a big mistake of you do. I would not recommend. Never get my order right. Ask for French fries, they thought I asked for a Frappuccino. Asked for Mac sauce, they had no clue what it was? How, you guys hiring incoherent employees? Asked for spicy nuggets, they gave me regular and charged me still! I was so impressed by a spicy chicken on a biscuit for the unbelievable $1.69. It was about 9:30am. This came with a large coffee for $2.69. Can't beat that-IF- it is good.
I parked in the parking lot facing the street, rolled down my window and was ready to Chow down my great sounding sandwich. The coffee was too hot, so I waited.
I ate my sandwich bite by bite, not forcing anything and thinking that I would have this again.
All of a sudden, I got so sick to my stomach halfway through the sandwich that I threw up everything out the window, peed in my pants from the pressure and simply could not believe it.
It is there for the next person to see!
At a time where America is anticipating this Corona Virus, none of us should have to throw up like this. What if I had  been a child?
Nearby, but no thank you to fast food once and for all!

PS I took a picture picture with my phone but thought no one wanted to see this. This store sucks and can't get anything right they say they are too busy but that's a lie so definitely not ordering from here again what a joke Ordered the McExtreme. It was McDisappointing. Hardly any of the special sauce and the burger tasted like it had been in the warmer all day. In addition, the bacon on the burger was burnt to a crisp. They're pretty bad at this location. I live close by, so I've come fairly often. One time they gave me a Big Mac with no meat. One time, after I waited 15 minutes in the drive through, they asked me to come inside to get my food. But when I came inside, the guy at the register had no idea why I had been asked to come inside. And just now I found a dead fly in my container of fries. So all in all, if you have the extra 5 minutes, do yourself a favor and drive to the slightly further location. Or better yet, get Taco Bell instead. I made sure to go to the McDonald's in town that was offering the BTS meal. Not only did I not even get the cute packaging advertised the employee was rude and didn't even give us the two sauces for the meal. What a waste of time and money. Freshly made food. Accurate orders 100% of time for me. Can't complain about this Micky D's location. This place is ill run and for obvious reasons: the manager is petty bureaucrat.
Placed my order, pulled ahead, there was no one at the first window, if there was someone there, I missed it. So I proceeded to the next. I was han

                         ## Rank: 22: Starbucks | (3.5)
                         **Category: Coffee & Tea, Food, Restaurants
                         Every Starbucks is the same bland, boring, sterile yuppie infested, "I'm in a rush, get my latte quick" type place.

Awful Coffee, lousy rude service, terrible sandwiches, overpriced everything.

I avoid it always unless I get a free gift card. Good place to pop in for a quick minute while you're at the mall. It's very clean and spacious. I only took one star off because it doesn't have the deeply comfy chairs that some places have. The service is really fast. Great experience and service.

DEFINITELY try the nitro cold brew they serve here. It is so incredibly creamy and delicious. Its a bit more bitter than Id prefer, but I find most of Starbuck's coffees to be thay way. Even so, give it a try. It's quite good! Horrible service.  The guy behind the counter tee making the drink is moving in slow motion and talking to all the employees at the same time.  Taking forever and no one is in here but me. Extremely rude employees.  Won't be back to this location. Ok, I admit it, I'm a coffee snob.  What's worse is my favorite is Circle K coffee!  I'll drink Starbucks if I have to I just don't want to feel like a need a cigarette to take the edge off after.  Fortunately they have a nice selection of iced tea.  The staff at this one was on it and kept the place clean.  Free wifi also goes a long way for me.  Thanks Starbucks! Being the only Starbucks within walking distance of the Williams Center, these folks stink at getting customers through the line and out the door in a timely fashion!

I just spent 12 of my 15 minute break waiting in a line that didn't move an inch! This is not the first time, they need more staff. I have not been to a crappy Starbucks in awhile, but this one in particular stinks. I ordered my drink, a simple espresso hot beverage straight off the menu, no bells and whistles. There were maybe 4 or 5 orders ahead of me. 20 minutes later (I am standing at the bar the entire time waiting) I finally ask where my drink is. They had made it 15 minutes prior and did not put it out on the counter or called out the drink or the name written on the cup. The employees at this store were all talking to an employee that had just gotten off work (the same one that took my order) and got him his drink immediately. The employees were too focused on each others' stories and laughing to actually do their job and announce orders. The coffee also was poorly made and tasted burnt. So that too. Save your time and go to a different store. This place is great, it gets busy at times, but there is usually still room for me to set me things down and do homework. It is conviniently close to the mall if you needed to do some shopping and the people here are friendly and humorous! Yelp keeps suggesting that I review Starbucks, so here goes...

It's Starbucks...there's nothing that I can say that hasn't been said already.  Except for maybe this:  I despise coffee.   As my Mom used to say, it's an insult to the palate and an abomination to the stomach.    So, much to my surprise, they actually have a pretty decent tea selection.  Not that I'm an expert...I recently had to take up tea drinking after voluntarily giving up Mountain Dew after a 20 year bender.

Every once in a while, I have a friend who wants to meet at Starbucks and I grit my teeth and acquiesce.  I usually order the plain black tea.  And, to my astonishment, it's pretty freakin' good!  Better than the Lipton that I get out of the Keurig, which isn't half bad either.  The other day, I decided to live on the edge and order the Chai tea, black.  Holy s***...what have I been missing? Luckily the Starbucks Chai tea K-cups are available on Amazon for a reasonable price.

Back to Starbucks at the Park Place Mall...the employees are super friendly.  I'm literally the last person on the bandwagon, I know, but they really seem to go above and beyond.  So yeah, go there...like you don't already know. I'll just start by saying I'm a total Starbucks junkie! I'm completely hooked on the chestnut praline latte and it makes me so sad that it's only a seasonal drink lol. This has to be my favorite Starbucks in town, though. The employees are wonderful! They are always friendly, fast, and definitely care about their customers. They will do anything to accommodate people that is within their means. Example: even when my beloved chestnut praline goes out of season, they'll still make it for me as long as they have the ingredients for it. They were still making it for me months after it ended! If you want great service, you'll definitely get it here. I should also note that their line moves faster than in any other Starbucks I've been to in town. And boy can they make a great drink! The blonde barista makes a mean caramel frappuccino. Always very nice and clean in here too. Each day star rating would change. The core staff is always friendly and quite excellent.   They take care of you. They understand the type of drink you want.

Place usually clean. Lately a lot of staff ch

                         ## Rank: 23: Ombre Coffee | (4.0)
                         **Category: Coffee & Tea, Coffee Roasteries, Food
                         Cute cafe, serving locally roasted coffee which I thoroughly enjoyed.

Definitely worth checking out if you're into coffee. Very good coffee house located in the back of the Bisbee Breakfast Club on Broadway one block west of Country Club. I find their coffees are above average and so are their teas. They have a smaller selection of baked goods which are all well above average and the level of comfort is also very good. This place was a little weird.  The coffee shop screamed 3rd wave but the coffee was roasted very dark.  The service was super good and the ascetics of the shop was nice.  I just think they need to change up the roast a little and they would be a home run. Butterscotch latte. Even with a butterscotch flavor add in and breve style the coffee still stands out and isn't watered down. Very happy to have found this place This coffee shop has a very cool vibe to it. The place has comfortable chairs and big windows that allows plenty of light in. I've been here a couple of times and it's always a pleasant experience. I've tried their cold brew, mocha, and jasmine green tea. All tasted very good and will definitely give you the caffeine that you need to get work done! Great staff and amazing drinks, highly recommend that you check it out! Quick service and very friendly staff. Coffee shop has a great atmosphere, will be coming back. Stopped in today mid-morning after buying bread next door. The place was quiet. We ordered an Americano and a hot tea with a scone. It took 15 minutes to get the tea - not sure why. The scone was hard as rock. The barista let us trade for another item. We picked a doughnut which was equally terrible. With many other coffee shop options, I doubt I'll try this one again soon. We have had good meals at Bisbee Breakfast Club which shares the same building/space. Hey your coffee is amazing. The one star missing is because the coffee at the Sunrise location isn't good. Something is wrong there. And you guys don't do pour-overs. I saw a Chemex there and v60 but I asked and the barista and he said no. If you are afraid of the temperatures, just be consistent and change as needed. We will still buy it. Very comfortable and stylish little coffee shop.  The coffee is good as are the pastries and I find it a very easy place to get work done. Nice and cozy place. Was able to enjoy great service and strong coffee to keep my conversation alive and filled with entertainment. Conveniently located right next to Barrio Bread and sharing a building with Bisbee Breakfast Club, this cute little coffee shop is a perfect stop after the dog park, when I'm getting my bread on Saturday.  There is often a line at Barrio Bread, so you can enjoy while you wait in line.  I ordered a latte, very creamy and full-flavored, good service.  The inside is cute, it has it's own entrance even though it does share with Bisbee Breakfast Club, and small tables along the windows.  Nice! Found this place on yelp and decided to give it a try. The parking lot is kinda across the street where Sushi Garden is, so theres not really parking lot for Ombre Coffee.

When I first walked in, it was quiet.  It was very comforting little shop. I ordered a tea because I'm not much of a coffee person. The barista took my order and told me if I need more hot water to just let him know. I was there for a couple of hours and it never got really busy. But it seems as though the customers that did come in were regulars.

I would highly recommend if you need a quiet place to study or work. It's definitely perfect for a college student. Great, friendly service.  Great coffee.  Bright and cheerful and sunny.   And next to a cafe where you can order a full meal if you want to and you can take your coffee with you.   Highly recommend. Great place to study and relax. However, my coffee was burnt. Right next to Barrio Bread! Has limited seating unless you're going to sit at Bisbee Breakfast place which is attached. Up side there's pac man machine that kept us entertained. Awesome coffee shop with very nice decor! Cold brew was decent; but the barista James was outstandingly friendly, funny, inviting, and certainly made up for it! Recommend to anyone looking for a great latte with housemade syrups! Snagged a few fresh, hot-out-of-the-oven loaves at Barrio Bread and popped into Ombre for an Americano. Smooth, strong, brainwave- stimulating brew!!! I can't believe people wait in a crazy line down the street for Starbucks this place is so much better. If you want a frappe go to Starbucks, if you want a great cup of coffee check this place out!  They have wifi and are open until 7 p.m. Cool coffee shop with unique baked goods. Definitely tastier baked goods than cartel. Can't speak to the coffee but I loved my freshly brewed apricot black iced tea. Good WiFi, lots of outlets and great lighting.

Gripes: open floor plan with Bisbee breakfast club and a shared bathroom lends itself to lots of foot traffic and more noise than I prefer. There's al

                         ## Rank: 24: Starbucks | (3.0)
                         **Category: Coffee & Tea, Food
                         Imagine my surprise when I found you just around the corner. No longer will I have to drive the long route to get my sweet fix. Newly build location, lots of parking, great flow of traffic, and huge inside. Well bigger than the ones I have been to here in Tucson. I ordered my drink, which promptly came up with a smile. The crew reminded me of one of my favorite stores in Washington State. It is so relaxing in here. Maybe my drink taste better because it has a new feeling to it. Either way I am loving the style, the location, the feel. One of the newer Starbucks on Swan/Ft. Lowell. Very open and bright. Love the cool open blue ceilings. Staff is very nice and greets everyone. I had a tall mocha frap. Needed it today.  This location is so much nicer than the one up the street. Went to this Starbucks on Friday afternoon. Only a handful of customers there. No one in line. I stood at the counter for two full minutes waiting to be served. Made eye contact with at least three of the employees none of which acknowledged me nor said they would be with me in a moment. Nothing.  Finally just sat down with my friend who apparently had fabulous service.

I went back to the counter five minutes later and was finally served.
Starbucks, you need to teach basic manners to your employees. My second visit and the second time I have been delighted with my service!! I love the space in this Starbucks! Lots of tables and lots of space to have a private conversation. I'm grateful I live near by as this is quickly becoming my favorite location! Everyone is so friendly here and Starbucks team is great and friendly free tall lattes cold or hot for the pop up 1-2 today at this location long lines but everyone seems friendly Service here is always soooooo slow. A bunch of lazy kids standing around doing nothing. My second visit and the second time I have been delighted with my service!! I love the space in this Starbucks! Lots of tables and lots of space to have a private conversation. I'm grateful I live near by as this is quickly becoming my favorite location

Wow I'm surprised at the service deterioration. I arrived at 5 and two people were behind the counter. No one said a word to me. One person was helping outside patrons and the other mopping the floor. I finally asked the person mopping if anyone was servicing inside patrons and she said yeah we'll be with you shortly and continued to mop. Finally a third person came from the back and helped me. I frequently go to this location and I'm sad to get lower priority than a mop. Def glad this place is a block from my office but I've never really gotten great service. It's pretty disappointing because I'm a regular. Majority of the time I use the drive thru or I mobile order. Ironically the past 2 times I've gone in person, they've got my order wrong. For some reason they put lemonade in my iced green tea and I hate lemonade. Lol.
Last week I went in for a large order as I was buying drinks for my staff. I was there for 25 minutes to get 7 drinks. I thought that was a bit much.
The reason I'll keep coming here is twofold.
1.) close to my office
2.) drive thru is faster than most I just love having a bit of heaven in a cup on my way to work in the morning.  Such a treat!
This location is brightly lit, clean and roomy.
Everyone we've met there has been friendly and helpful.
The store is gearing up for Christmas and have added some pretty nice shiny bits.
Free wi-fi , nice location and great company while enjoying my hot beverage. What more can I ask? Generally id just go to a different location. (Which i will most likely do.) But this location is closer than most. Im not sure what the deal is but this location just CANT seem to get it right. There is ALWAYS something missing. Now im not just some karen freaking out. I actually work in a kitchen. And in turn i read the tickets fully so i understand what im making. I ensure the food i produce is what the customer asked for. So i feel it should be the same in a "coffee kitchen". Ill be buying from local coffee joints from now on. Like Black Crown or Coffee Times. My final stop before going home to El Paso, I had a white mocha latte with coconut milk, it was delicious, served pretty quickly. I could tell that this location was newly built, and the staff was friendly as expected. Got my order all wrong. Not the first time at this location. Spend the extra minutes and save the extra money and go to dutch bros Anytime I come to relax and need space to study, this a comfortable location.  BUT do not count on Food here! The hours that might be spent here BRING OWN edibles. Unfortunately, even occasionally cake pops and pastries are the only options ... Too bad this location does not recognize the supply & demand, you can expect a mere " sorry we are all out " and nothing more. C'mon seize the opportunity to offer something to provide an overall positive experience ( or profitable Corp transaction ). Starbucks customers- whether these orde

## 8 - Scoring

In [36]:
#scoring logic

def relevance(ranked, qrels, k=10):
    return [qrels.get(doc,0) for doc in ranked[:k]]

def dcg_f(rels, k=10):
    return sum(rels[i] / math.log2(i+2) for i in range(min(k,len(rels))))

#NDCG
def ncdg(rels, k=10):
    dcg = dcg_f(rels,k)
    ideal = sorted(rels,reverse=True)
    idcg = dcg_f(ideal,k)
    return dcg / idcg if idcg > 0 else 0

#evaluation

def evaluation(results,qrels,k=10):
    scores = []

    for q in results:
        rels = relevance(results[q], qrels[q],k)
        score = ncdg(rels,k)
        scores.append(score)

    return sum(scores) / len(scores)

In [37]:
#Running Evaluation

bm25_eval = evaluation(bm25_results, qrels)
semantic_eval = evaluation(semantic_results,qrels)
hybrid_eval = evaluation(hybrid_results, qrels)

print(f'BM25 NDCG@10: {bm25_eval}')
print(f'Semantic NDCG@10: {semantic_eval}')
print(f'Hybrid NDCG@10: {hybrid_eval}')

BM25 NDCG@10: 0.8876294280896273
Semantic NDCG@10: 0.9453510816818652
Hybrid NDCG@10: 0.9481513945867341

In [41]:
# SAVE JSON of qrels (relevance of query results)
qrels_clean = {
    str(q): {int(doc): int(rel) for doc, rel in docs.items()}
    for q,docs in qrels.items()
}

with open('../data/qrels.json',"w") as f:
    json.dump(qrels_clean,f, indent = 4)

## 9 - UI Testing
- using streamlit

In [26]:
#function for UI results
def result_func(docid,docs_df):
    formatted = []

    for rank,doc in enumerate(docid,1):
        row = docs_df.iloc[docid]

        formatted.append({
            'title': row['name'],
            'info': f'{row["categories"]} | Ratings -> {row["stars"]}',
            'docid': docid
        })

    return formatted

In [30]:
### PAGE
st.set_page_config(page_title = "Restuarant Search (AZ)", layout = 'wide')
st.title('Restaurant Search (AZ) IR')

#SESSION
if 'results' not in st.session_state:
    st.session_state.results = []
if 'page' not in st.session_state:
    st.session_state.page = 0

#MODEL SELECTION
model = st.radio('Select Model:', ['BM25', 'Semantic', 'Hybrid'], horizontal = True)

#SEARCH BAR
query = st.text_input('Enter your query')

#RAW RESULTS
if 'raw' not in st.session_state:
    st.session_state.raw = []

#SEARCH BUTTON 
if st.button('Search'):
    st.session_state.page = 0 #reset

    if model == 'BM25':
        st.session_state.raw = bm25z(query)
    elif model == 'Semantic':
        st.session_state.raw = semantic_search(query)
    else:
        st.session_state.raw = hybrid_search(query)

    #Raw results conversion
    st.session_state.results = result_func(st.session_state.raw,docs)

#PAGE SETTINGS
RESULTS_PER_PAGE = 10
MAX_RESULTS = 50

results = st.session_state.results[:MAX_RESULTS]

start = st.session_state.page * RESULTS_PER_PAGE
end = start + RESULTS_PER_PAGE

page_results = results[start:end]

#DISPLAY RESULTS
st.subheader('Results')

if page_results:
    for i,doc in enumerate(page_results, start = start +1):
        st.markdown(f'**{i}. {doc["title"]}**')
        st.write(doc['info'])
        st.caption(f'Doc ID: {doc["docid"]}')
        st.divider()
else:
    st.write('No results yet')


#PAGE CONTROLS
col1,col2,col3 = st.columns([1,2,1])

with col1:
    if st.button('<- Previous') and st.session_state.page > 0:
        st.session_state.page -=1

with col3:
    if st.button('Next ->') and end < len(results):
        st.session_state.page +=1

#PAGE INFO
total_pages = min(len(results),MAX_RESULTS) // RESULTS_PER_PAGE
st.caption(f'Page {st.session_state.page + 1} of {max(1,total_pages)}')

2026-04-22 09:22:54.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.352 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.361 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.370 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.371 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.372 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.373 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.374 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.376 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.381 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-22 09:22:54.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

## 10 - Data Acquisition v2
- find more suitable data to add to IR system

In [ ]:
chrome_options = Options()
# chrome_options.add_argument("--headless")  # Run in headless mode
browser = 'C:/Users/jking36/Documents/Python/chromedriver' #config
service = Service(executable_path=browser)
rawUrl = 'https://www.tripadvisor.com/Search?q=tempe&geo=1&ssrc=e&searchNearby=false&searchSessionId=0002cf923c75f8f3.ssid&offset=0'
driver = webdriver.Chrome(service = service)
driver.get(rawUrl)
driver.maximze_window()